### PR TITLE
Bitstream command line cleanup operation - huge running time and potentially missing a DB commit

### LINKED ISSUE #8649: Bitstream command line cleanup operation - huge running time and potentially missing a DB commit
**Describe the bug**
I am currently running the "dspace cleanup" operation in our test environments to delete about 275K bitstreams flagged as deleted in our DB and I am observing huge differences in behaviour in DSpace 7.4 compared to our current DSpace 5.10.
In fact, I have not managed to get the script to complete in DSpace 7. Command run is "dspace cleanup -l -v" (with allocate 5GB or RAM just in case)
- In our current DSpace 5.10 it has completed successfully in a couple of hours, and has only reported 12 errors out of more than 275K iterated items
- In our test DSpace 7.4 it's been running for days and has not yet completed. 

I have also noticed that there are no intermediate Committing to DB messages in the log files so this has prompted me to look at difference in the code in the cleanup method (BitstreamStorageServiceImpl.java). Could it be that a context.commit() statement is missing in that method within the commitCounter IF statement?

**To Reproduce**
1. In DSpace 7 run dspace cleanup -l -v

**Expected behavior**
The script completes in a couple of hours (for DBs with a large number of files to be deleted)

**Related work**
Link to any related tickets or PRs here.

### PR DESCRIPTION
**Pull request by amgciadev**
## References
* Fixes #8649 

## Description
Simple addition of a commit statement in the cleanup method.

## Instructions for Reviewers
List of changes in this PR:
* Added missing commit in cleanup method to commit changes to DB every 100 iterations

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 
Without this commit changes won't take effect until the whole process finishes.
## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

File: dspace-api/src/main/java/org/dspace/storage/bitstore/BitstreamStorageServiceImpl.java [hunk 1]
```diff
@@ -303,6 +303,10 @@ public void cleanup(boolean deleteDbRecords, boolean verbose) throws SQLExceptio
                 commitCounter++;
                 if (commitCounter % 100 == 0) {
                     context.dispatchEvents();
+                    // Commit actual changes to DB after dispatch events
+                    System.out.print("Committing changes to the database...");
```
Comment (tdonohue) [inline dspace-api/src/main/java/org/dspace/storage/bitstore/BitstreamStorageServiceImpl.java:307]: @amgciadev : I'd recommend changing the text here slightly so that it's not *identical* to the "System.out.print" which occurs below on line 315 when `context.complete()` is called.  That way, you can tell which commit is running based on the output.

Maybe changing the text here to be "Performing incremental commit to the database..."?

Beyond that, the rest of this PR looks good.

Comment (amgciadev) [reply dspace-api/src/main/java/org/dspace/storage/bitstore/BitstreamStorageServiceImpl.java]: Done @tdonohue

**Review by tdonohue — APPROVED** [review]
👍 Thanks @amgciadev ! Gave this a test locally on a database with >100 items to cleanup and can verify that this was triggered properly.  No issues found.
