### PR TITLE
fix: replace deprecated AntPathRequestMatcher with PathPatternRequestMatcher

### LINKED ISSUE #11634: Use of deprecated AntPathRequestMatcher in Spring Security configuration
While reviewing the security configuration in the DSpace codebase, I noticed that the class `org.springframework.security.web.util.matcher.AntPathRequestMatcher` is still being used in

- `StatelessLoginFilter`
- `WebSecurityConfiguration`

This class `AntPathRequestMatcher` has been marked as [**deprecated** in recent versions of Spring Security](https://docs.spring.io/spring-security/site/docs/6.5.5/api/org/springframework/security/web/util/matcher/AntPathRequestMatcher.html).

According to the Spring Security migration guidelines, `AntPathRequestMatcher` is scheduled for removal in a future release, and applications should migrate to alternatives depending on their setup.

### PR DESCRIPTION
**Pull request by soto-raul**
## References
* Fixes #11634 

## Description
This pull request handles the deprecation of `AntPathRequestMatcher` by replacing all its usages with the recommended [`PathPatternRequestMatcher`](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/web/servlet/util/matcher/PathPatternRequestMatcher.html). This migration in the Spring Security configuration ensures future compatibility without altering existing behavior.

## Instructions for Reviewers

List of changes in this PR:
* **Replaced Deprecated Class:** All usages of `AntPathRequestMatcher` have been replaced with the recommended `PathPatternRequestMatcher`.
* **Updated [`StatelessLoginFilter.java`](https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/security/StatelessLoginFilter.java):**
  * The filter's constructor now uses `PathPatternRequestMatcher` to define the URL and HTTP method it responds to.
* **Updated [WebSecurityConfiguration.java](https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/security/WebSecurityConfiguration.java):**
  * Modified the `requestMatchers()` call for the `/actuator/info` endpoint to use `PathPatternRequestMatcher`.
  * Updated the logout configuration such that `logoutRequestMatcher()` uses `PathPatternRequestMatcher` for the `/api/authn/logout` endpoint.

**No Functional Changes**: This is a pure migration. All existing automated tests pass; manual testing needed to confirm that the behavior (e.g. logout, etc) remains unchanged.

## Checklist

- [X] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [X] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [X] My PR **passes Checkstyle** validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [ ] My PR **includes Javadoc** for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [X] My PR **passes all tests and includes new/updated Unit or Integration Tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [X] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [ ] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [ ] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [X] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/security/WebSecurityConfiguration.java [hunk 1]
```diff
@@ -104,7 +104,8 @@ public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
         http.securityMatcher("/api/**", "/iiif/**", actuatorBasePath + "/**", "/signposting/**")
             .authorizeHttpRequests((requests) -> requests
                 // Ensure /actuator/info endpoint is restricted to admins
-                .requestMatchers(new AntPathRequestMatcher(actuatorBasePath + "/info", HttpMethod.GET.name()))
+                .requestMatchers(PathPatternRequestMatcher.withDefaults().matcher(HttpMethod.GET,
```
Comment (saschaszott) [inline dspace-server-webapp/src/main/java/org/dspace/app/rest/security/WebSecurityConfiguration.java]: Why not use the shorter variant `.requestMatchers(HttpMethod.GET, actuatorBasePath + "/info")` ?

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/security/WebSecurityConfiguration.java [hunk 2]
```diff
@@ -141,7 +142,8 @@ public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
                 // On logout, clear the "session" salt
                 .addLogoutHandler(customLogoutHandler)
                 // Configure the logout entry point & require POST
-                .logoutRequestMatcher(new AntPathRequestMatcher("/api/authn/logout", HttpMethod.POST.name()))
+                .logoutRequestMatcher(PathPatternRequestMatcher.withDefaults().matcher(HttpMethod.POST,
```
Comment (saschaszott) [inline dspace-server-webapp/src/main/java/org/dspace/app/rest/security/WebSecurityConfiguration.java]: Why not use the shorter variant `.logoutUrl("/api/authn/logout")` ?

If CSRF protection is enabled (default in DSpace REST), then the request must also be a POST. This means that by default POST "/logout" is required to trigger a log out.

**Review by saschaszott — CHANGES_REQUESTED** [review]

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/security/WebSecurityConfiguration.java (hunk 2 above)
Comment (soto-raul) [reply dspace-server-webapp/src/main/java/org/dspace/app/rest/security/WebSecurityConfiguration.java]: Thanks for the feedback! You're right, `PathPatternRequestMatcher` is a bit overkill in this case since the matching logic is not too complex and using the fluent API methods is more concise. I'll get working in these changes as soon as possible.

**Review by saschaszott — APPROVED** [review]
Thanks for your contribution, @soto-raul .

**Review by tdonohue — APPROVED** [review]
👍 Thanks @soto-raul !  Apologies it took a while to get to this, but the code looks good. I've also verified there's no change in behavior.

**Comment by soto-raul** [comment]
> 👍 Thanks @soto-raul ! Apologies it took a while to get to this, but the code looks good. I've also verified there's no change in behavior.

No worries 😁 I'm glad I could contribute to the project, thanks a lot!
