### PR TITLE
Fix for Delete items after copies have been requested

### LINKED ISSUE #8654: Requesting a copy causes item to be undeletable
**Describe the bug**
If we have an item with one or more Bitstreams that are under embargo for which an EPerson has done a "Request a Copy" call, that item will not be deletable as an entry is created in the RequestItem table which won't be deleted on item deletion, causing a Foreign Key Constraint exception to be thrown as can be seen hereunder
`org.hibernate.engine.jdbc.spi.SqlExceptionHelper @ ERROR: update or delete on table "item" violates foreign key constraint "requestitem_item_id_fkey" on table "reques
titem"
  Detail: Key (uuid)=(a1d0b513-749f-43cc-acbf-83eebf218b10) is still referenced from table "requestitem".`

**To Reproduce**
1. Create an Item in the Repository
2. Add a bitstream to this Item, making sure it's under embargo
3. As an anonymous user, request a copy of this bitstream
4. Try to delete this item as the admin user
5. Verify that the error is thrown & that the item is not deleted

**Expected behavior**
The item should be deleted

Atmire would like to claim the work to fix this & it should require 4 hours of dev work including a test

### PR DESCRIPTION
**Pull request by jensvannerum**
## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #8654

## Description
This fixed the issue referenced above by deleting the `RequestItem` objects related to the item being deleted first.
## Instructions for Reviewers
List of changes in this PR:
* a new `removeRequest` method in the itemService which is called when an item gets removed
* a new DAO method in `RequestItemDAO` to find objects from the DB based on the relevant Item
* a test was added to verify this works in the `ItemServiceTest` test class

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by pnbecker — APPROVED** [review]
Code looks good to me. Haven't tested it so.

File: dspace-api/src/main/java/org/dspace/content/ItemServiceImpl.java [hunk 1]
```diff
@@ -802,6 +808,15 @@ protected void rawDelete(Context context, Item item) throws AuthorizeException,
         itemDAO.delete(context, item);
     }
 
+    protected void removeRequest(Context context, Item item) throws SQLException {
+        Iterator<RequestItem> requestItems = requestItemService.findByItem(context, item);
+        while (requestItems.hasNext()) {
+            RequestItem requestItem = requestItems.next();
+            log.info("Remove Request Item: " + requestItem.getID());
```
Comment (tdonohue) [inline dspace-api/src/main/java/org/dspace/content/ItemServiceImpl.java:815]: @jensvannerum : Can we please remove this `log.info`?  This looks like it'd only be useful for debugging & isn't useful otherwise.

**Review by tdonohue — COMMENTED** [review]
@jensvannerum : Thanks ! I've verified this works.  So, I'm +1 to this as soon as the unnecessary `log.info` (see comment above) is removed.

**Comment by tdonohue** [comment]
@jensvannerum : Just a friendly reminder that I'd like to include this in 7.5 if possible... but it needs a single `log.info` statement removed, see comments above.  If you can find time to get this fixed, please ping me so that I can get this merged.

**Comment by Raf-atmire** [comment]
Hi @tdonohue just quickly jumping in here, I've removed the log info that you've referred to. Thank you for your review!

**Review by tdonohue — APPROVED** [review]
Thanks @jensvannerum and @Raf-atmire !  This looks good to me now (and I had previously tested that it works)
