### PR TITLE
Fix `/api/core/items` endpoint's `totalElements` count to avoid empty pages at end

### LINKED ISSUE #3317: REST api /api/core/item returns duplicates for small page sizes
**Describe the bug**
When calling /api/core/item and paging over results, duplicate items will be returned unless size>=100. I am looping over the results to build a map of items keyed by handle. For page sizes <100, some items will be duplicated and others will be missing. For larger page sizes, results are as expected.

On main:latest.

**To Reproduce**
1. Call /api/core/item?page=n&size=20, incrementing (n) until no more results found.
2. For each result, add to a map keyed by item[handle]
3. Check whether handle it already in the map: will find duplicates.
4. Adjust page size to 100, and there will be no duplicates.

**Expected behavior**
I am unsure why the page size should effect the results. I have tried reindexing but it did not change the result.

**Related work**
Link to any related tickets or PRs here.

### PR DESCRIPTION
**Pull request by tdonohue**
## References
* Discovered when analyzing #3317 (see [my comment on that ticket](https://github.com/DSpace/DSpace/issues/3317#issuecomment-878545926)).  _I believe it actually may fix that issue as well, but waiting on response from original reporter._

## Description
Currently, the `totalElements` property returned by `/api/core/items` includes WorkspaceItems, while the actual endpoint only returns archived Items. This can result in pagination working improperly, as the wrong number of pages is listed and last page(s) may be empty.

## Instructions for Reviewers
List of changes in this PR:
1. Prove the broken behavior by creating a WorkspaceItem in the `findAllWithPaginationTest()`. This is in the initial commit https://github.com/DSpace/DSpace/pull/3321/commits/b60b76d29e318ccea362a6c03471122cc6cce739 and results in an IT failure (as the value of `totalElements` will be incorrect, even though the WorkspaceItem is not returned from the endpoint).
2. Fixed the bug in the second commit https://github.com/DSpace/DSpace/pull/3321/commits/025c7a8c78a488df0ee300ed5e6cef0a6c472492

This should be easy to review using the tests.  It also can be easily proven locally by simply ensuring one or more Workspace or Workflow items exist.  This will result in incorrect pagination/total counts from the `/api/core/items` endpoint.

REST Contract PR: https://github.com/DSpace/RestContract/pull/166

### CODE REVIEW

**Comment by tdonohue** [comment]
@abollini : Assigning this to you for review, as it likely will be very quick for you to review.  If you agree with this fix, I can make a small update to the [RestContract](https://github.com/DSpace/RestContract/blob/main/items.md) to clarify that the `/api/core/items` endpoint only paginates through *archived* items at this time, and you must use other endpoints to discover non-archived items. (As a sidenote, we could choose to change this behavior at a later date, e.g. in 7.1.  However, at this point,  our tests in `ItemRestRepositoryIT` are all implying this endpoint should only paginate *archived* Items, so changing that current behavior would be a larger task.) 

That said, it's `medium priority` as this endpoint's pagination isn't used at all by our UI -- so this bug is only discoverable via using the REST API directly.

**Comment by tdonohue** [comment]
@abollini : As promised, I've created a REST Contract PR corresponding to this PR: https://github.com/DSpace/RestContract/pull/166

File: dspace-server-webapp/src/test/java/org/dspace/app/rest/ItemRestRepositoryIT.java [hunk 1]
```diff
@@ -197,6 +197,15 @@ public void findAllWithPaginationTest() throws Exception {
...
 
+        // Create a Workspace Item (which in turn creates an Item with "in_archive=false")
+        // This is only created to prove that WorkspaceItems are NOT counted/listed in this endpoint
+        WorkspaceItem workspaceItem = WorkspaceItemBuilder.createWorkspaceItem(context, col2)
+                .withTitle("In Progress Item")
+                .withIssueDate("2018-02-05")
+                .withAuthor("Doe, Jane").withAuthor("Smith, Jennifer")
+                .build();
+        Item itemInWorkspace = workspaceItem.getItem();
+
```
Comment (abollini) [inline dspace-server-webapp/src/test/java/org/dspace/app/rest/ItemRestRepositoryIT.java:208]: it would be more effective to create also a workflow item and a template item just to proof that nothing else is counted

**Review by abollini — APPROVED** [review]
@tdonohue changes look good to me. I will appreciate if you can extend the test as by my inline comment. Feel free to merge once done without further recheck

File: dspace-server-webapp/src/test/java/org/dspace/app/rest/ItemRestRepositoryIT.java (hunk 1 above)
Comment (tdonohue) [reply dspace-server-webapp/src/test/java/org/dspace/app/rest/ItemRestRepositoryIT.java:219]: done!  Added tests for those in the latest commit & definitely a good suggestion
