### PR TITLE
Escape HTML tags in hit highlights

### LINKED ISSUE #1495: HTML tags in administrative workflow view are being evaluated
**Describe the bug**
First of all, I am not sure whether this is really a bug or more like a feature. 
Since I came across this while doing some XSS attempts on  a local DSpace 7.1.1 setup, I entered some HTML/JS code in the resource submission form.
The sanitizer of Angular appears to detect my attempts and makes them safe. Still, in the administrative workflow the HTML tags are evaluated:

grafik

**To Reproduce**
Submit new resource, enter
``
in any of the text fields.
Hit deposit and check administrative worklow.

**Expected behavior**
HTML tags are stripped entirely or at least are not being evaluated as in the other views.

### PR DESCRIPTION
**Pull request by alexandrevryghem**
## References
* Fixes DSpace/dspace-angular#1495
* Requires DSpace/dspace-angular#4737

## Description
Enabled escaping of HTML tags in metadata before applying the hit highlight `<em>` tags. This ensures that highlights can still be rendered via Angular’s `innerHTML` safely, without introducing XSS vulnerabilities.

## Instructions for Reviewers
List of changes in this PR:
* Updated the `SolrServiceImpl` to escape all the metadata fields by default when retrieving the hit highlights

## Checklist
- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR **passes Checkstyle** validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR **includes Javadoc** for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR **passes all tests and includes new/updated Unit or Integration Tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

File: dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java [hunk 1]
```diff
@@ -900,8 +901,20 @@ protected SolrQuery resolveToSolrQuery(Context context, DiscoverQuery discoveryQ
         if (0 < discoveryQuery.getHitHighlightingFields().size()) {
             solrQuery.setHighlight(true);
             solrQuery.add(HighlightParams.USE_PHRASE_HIGHLIGHTER, Boolean.TRUE.toString());
+            boolean escapeHTML = configurationService.getBooleanProperty("discovery.highlights.escape-html");
```
Comment (tdonohue) [inline dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java]: Please set default to `true`.  For example:
`configurationService.getBooleanProperty("discovery.highlights.escape-html", true);`

File: dspace/config/modules/discovery.cfg [hunk 2]
```diff
@@ -57,3 +57,8 @@ discovery.removestale.attempts = 3
 
 # The field to use when filtering for geospatial metadata (boolean flag)
 discovery.filter.geospatial.field = dcterms.spatial
+
+# Set to true to escape HTML tags in hit highlight results
+discovery.highlights.escape-html = true
+# Set the fields that should not escape HTML tags in hit highlight results when discovery.highlights.escape-html is true
+discovery.highlights.html-allowed-fields =
```
Comment (tdonohue) [inline dspace/config/modules/discovery.cfg]: Can we provide an example in this comment description?  Can you provide a list of fields like `dc.description.abstract, dc.title`?  Or is the format different?

I'd also recommend commenting this out by default to clarify that it does *not* need to be set.

File: dspace/config/modules/discovery.cfg [hunk 3]
```diff
@@ -57,3 +57,8 @@ discovery.removestale.attempts = 3
 
 # The field to use when filtering for geospatial metadata (boolean flag)
 discovery.filter.geospatial.field = dcterms.spatial
+
+# Set to true to escape HTML tags in hit highlight results
+discovery.highlights.escape-html = true
```
Comment (tdonohue) [inline dspace/config/modules/discovery.cfg:62]: This should likely be commented out by default to clarify it's not required to be set.

**Review by tdonohue — COMMENTED** [review]
@alexandrevryghem : I gave this a quick code review.  I have a few inline comments.  I haven't had a chance to test this yet, but hope to do so soon.

File: dspace-server-webapp/src/test/java/org/dspace/app/rest/DiscoveryRestControllerIT.java [hunk 4]
```diff
@@ -6685,4 +6685,30 @@ public void discoverSearchObjectsNOTIFYOutgoingConfigurationTest() throws Except
             .andExpect(jsonPath("$._links.self.href", containsString("/api/discover/search/objects")));
     }
 
+    @Test
+    public void discoverSearchObjectsFirstEscapeHTMLTagsBeforeApplyingHitHighlights() throws Exception {
```
Comment (tdonohue) [inline dspace-server-webapp/src/test/java/org/dspace/app/rest/DiscoveryRestControllerIT.java:6711]: This test is good as it proves that by default HTML is being escaped.  But, we should also add two tests that prove the behavior of `discovery.highlights.escape-html=false` and adding a field to `discovery.highlights.html-allowed-fields`.  (I had to test both manually and they look to work, but we really should have an automated test as well.)

**Review by tdonohue — CHANGES_REQUESTED** [review]
@alexandrevryghem : Thanks for this PR.  I've tested this alongside https://github.com/DSpace/dspace-angular/pull/4737 and it seems to work well.

However, I'd appreciate it if we could add a few more ITs to verify the behavior of the new configs.  (I tested them manually and they appear to work as well, but ITs are always highly recommended to ensure continues to work as expected in the future).

Once the additional ITs are added, I'd be +1 this PR.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @alexandrevryghem !  This looks good to me now.  I retested it and it's still working well.

**Comment by tdonohue** [comment]
@alexandrevryghem : Unfortunately none of the backports worked on this PR.  Would you be able to create manual backport PRs that we can merge into 7.x, 8.x and 9.x?
