### PR TITLE
File downloads don't close inputstreams when cached fix

### LINKED ISSUE #8078: S3 connection leak
**Describe the bug**

DSpace can use S3 as a backend to store & retrieve files, but there is a leak somewhere in the BitstreamResource that doesn't always close connections. 
Every download opens up a connection to S3 & these aren't closed so after a certain amount of downloads the download AND upload just quit working because the S3 connections are up.

**To Reproduce**
1. Enable S3 on DSpace 7
2. Download different files & after a while the downloads won't work any more (they just time out)

**Expected behavior**
Connections to S3 should be properly closed.

### PR DESCRIPTION
**Pull request by KevinVdV**
## References
* Fixes #8078

## Description
We changed it so that the BitstreamResource doesn't open up an inputstream that would potentially not be closed IF the response was cached by spring.

## Instructions for Reviewers
The easiest way to test would be with an S3 assetstore, push a few files there & download them in quick succession. After a while the S3 connections will be used up & the file download won't work anymore.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [X] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [X] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [X] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [X] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [X] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Comment by tdonohue** [comment]
@abollini : Assigning this to you for review as you noted your team was interested in seeing this fixed immediately.  Feel free to delegate it to someone else as needed.

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/BitstreamRestController.java [hunk 1]
```diff
@@ -131,32 +133,37 @@ public ResponseEntity retrieve(@PathVariable UUID uuid, HttpServletResponse resp
...
-                    .withFileName(name)
-                    .withLength(bitstreamTuple.getRight())
-                    .withChecksum(bit.getChecksum())
-                    .withMimetype(mimetype)
-                    .with(request)
-                    .with(response);
+            HttpHeadersInitializer httpHeadersInitializer = new HttpHeadersInitializer()
+                .withBufferSize(BUFFER_SIZE)
+                .withFileName(name)
+                .withLength(bit.getSizeBytes())
```
Comment (abollini) [inline dspace-server-webapp/src/main/java/org/dspace/app/rest/BitstreamRestController.java:140]: the response size will be different from the bitstream size if the cover page is used

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/BitstreamRestController.java [hunk 2]
```diff
@@ -131,32 +133,37 @@ public ResponseEntity retrieve(@PathVariable UUID uuid, HttpServletResponse resp
...
+                .with(response);
 
             if (lastModified != null) {
                 httpHeadersInitializer.withLastModified(lastModified);
             }
 
             //Determine if we need to send the file as a download or if the browser can open it inline
             long dispositionThreshold = configurationService.getLongProperty("webui.content_disposition_threshold");
-            if (dispositionThreshold >= 0 && bitstreamTuple.getRight() > dispositionThreshold) {
+            if (dispositionThreshold >= 0 && bit.getSizeBytes() > dispositionThreshold) {
```
Comment (abollini) [inline dspace-server-webapp/src/main/java/org/dspace/app/rest/BitstreamRestController.java:152]: the bitstream size can only be used if the cover page is not used

**Review by abollini — CHANGES_REQUESTED** [review]
Thanks @KevinVdV for this PR. The code looks reasonable and should solves the connection leak but introduce an issue if the cover page feature is used (see inline comments).

Integration Test to demonstrate the bug and the solution would be appreciated as the bug is likely to occur in specific scenarios (i.e.LAST-MODIFIED header) and it is heavily influenced by the internal spring implementation. The BitstreamService can be proxied to track retrieval of inputstream and proper closure.

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/BitstreamRestController.java (hunk 1 above)
Comment (tdonohue) [reply dspace-server-webapp/src/main/java/org/dspace/app/rest/BitstreamRestController.java:140]: @KevinVdV : I think @abollini is correct in both his comments...these code changes need to be using your new `getCitedDocumentLength()` method whenever the cover page is enabled.  It looks like that may only require a minor refactor to your PR though... but, I'll wait to review/test this until that minor cleanup is complete.

**Comment by KevinVdV** [comment]
@abollini You are correct, there are issues with the coverpages & the size. I moved the determination of the size up in the code & used that variable whenever the size of the bitstream is needed.

@tdonohue @abollini mentioned that tests would be good to further prove that this works (and to demonstrate the bug), although I agree with him it won't be an easy IT to write. We can try to create tests for this, but how much budget can be allocated to this ?

**Comment by tdonohue** [comment]
@KevinVdV : I'd need an estimate for what an IT like that would require before approving it. If it's a couple hours, that's fine, but if you are talking a day or more, I think this PR is good enough as is. I'm not willing to delay 7.2 for this, and it sounds like we all agree that this needs fixing in 7.2.  So, in my opinion, @abollini 's request for an IT is optional...if it's possible to achieve easily in a 1/2 day or less, then do it. However if it's highly complex, then I suggest we move forward with this as is.

I'll also note this PR has a new LGTM comment above that points out it has a "useless null check". That should obviously be fixed.

**Comment by tdonohue** [comment]
@abollini : I'm asking you to re-review this, as it sounds like from talking with the Atmire team that an IT would be overly complex and likely would delay this past 7.2 (and all your other feedback looks to have been addressed).  So, I'd recommend we review this as-is for possible inclusion in 7.2...and we could always add an IT in 7.3 as needed.

File: dspace-api/src/main/java/org/dspace/disseminate/CitationDocumentServiceImpl.java [hunk 3]
```diff
@@ -297,8 +296,21 @@ public boolean canGenerateCitationVersion(Context context, Bitstream bitstream)
...
+        throws SQLException, AuthorizeException, IOException {
+        byte [] citedDocumentContent = getCitedDocumentContent(context, bitstream);
+        return new ByteArrayInputStream(citedDocumentContent);
+    }
+
+    @Override
+    public Long getCitedDocumentLength(Context context, Bitstream bitstream)
+        throws SQLException, AuthorizeException, IOException {
+        byte[] citedDocumentContent = getCitedDocumentContent(context, bitstream);
+        return Long.valueOf(citedDocumentContent.length);
```
Comment (abollini) [inline dspace-api/src/main/java/org/dspace/disseminate/CitationDocumentServiceImpl.java:309]: splitting this in two separate methods is inefficient as it means that the coverpage and the resulting file must be generated potentially two times. I recommend to keep the current service interface as is so that a single method provide both information. Eventually we can accept this code as a quick fix for the 7.2 and improve it later to avoid calling the method two times

**Review by abollini — CHANGES_REQUESTED** [review]
Hi @KevinVdV ,
the code works and I agree that IT can be added later as they are already missing as we are short of time. I would like to see the task to add ITs on our board for 7.3 with the same priority that we would assign to a bug.

That said, there is also a new issue with the updated code that I have highlighted inline. Also in this case if a proper refactoring is not feasible in time for 7.2 I would suggest to accept this code just restoring the service interface and using the appropriate side of the Pair in the two different call and leave the refactoring as part of the followup ticket together with the IT.

It is better to don't change the service interface back and forward as we have already noted that the current interface is the one that would offer the best performance

**Review by tdonohue — COMMENTED** [review]
@KevinVdV : Overall, the approach here looks fine to me, though I agree with @abollini that the refactoring in `CitationDocumentService` seems like it would negatively impact the performance (as you have generate the CitationDoc *twice*...once to get the actual content, and once just to get the length of the content).  Is it required in this PR? It seems like it might be secondary work that could be removed... 

If I'm not mistaken, the main fix here is in `BitstreamResource`, and that doesn't seem to require the CitationDocumentService refactoring (unless I'm overlooking something).

Could we consider keeping the `CitationDocumentService` as-is?  Or is it somehow part of the fix here?

Overall, I agree that I want to make sure to get this fix into 7.2.... but, it does look like the PR could be simplified to undo the `CitationDocumentService changes, and *still* fix the main bug.

**Comment by KevinVdV** [comment]
@abollini I agree with you that if we split it up into 2 methods the work might be forgotten, a single method probably works best here. I altered my PR & adjusted it.

@tdonohue I restored it currently but should be high up the list for 7.3 I believe as performance will suffer because of this change, creating the cited document twice will slow down downloads. Sadly with the way the code is structured now there is no other way to do this as we need the size but we MIGHT not need the actual inputstream of the file.

When refactoring the citation document for 7.3 we need to be careful that we don't reintroduce this bug again, so what I would suggest:
* First create IT's for both the Cited & regular downloads to prove that the issue is gone
* Refactor citation document creation & use the tests from above so we don't reintroduce this

Ps: Can somebody who actually has cited documents enabled do a quick test to make sure that the cited document download still works with this PR ?

**Review by abollini — APPROVED** [review]
the changes look good to me. Thanks @KevinVdV

**Review by tdonohue — APPROVED** [review]
👍 Thanks @KevinVdV ! It looks good to me as well. I also tested this with Citation Page enabled for PDFs and the download works fine (and the citation page is generated correctly).

I'll create a ticket for 7.3 for the next steps & link it up to this one. Then I'll merge this for 7.2

**Comment by tdonohue** [comment]
@KevinVdV and @abollini : I've created a follow-up ticket for 7.3.  https://github.com/DSpace/DSpace/issues/8140  If either of you would like to claim it immediately, let me know as I agree it'd be good to assign so that this area of the code can be cleaned up & verified with ITs.
