### PR TITLE
#8412 In Submission Form, list collections alphabetically

### LINKED ISSUE #8412: In Submission Form, list collections alphabetically
**Describe the bug**
In DSpace 6.3 XMLUI, in the submission form, e.g. https://demo.dspace.org/xmlui/submit, the collections are listed alphabetically starting with the top-level community.
DSpace6_submission_collection_list
In DSpace 7.3, in  the submission form, e.g.https://demo7.dspace.org/home, the collections are listed randomly. The community containing the collection is listed above it. 
DSpace7_submission_collection_list

**To Reproduce**
1. Do this
2. Then this...

**Expected behavior**
Please either list the top-level communities alphabetically, like DSpace 6, or list the containing communities alphabetically or list the collections alphabetically.

**Related work**
Link to any related tickets or PRs here.

### PR DESCRIPTION
**Pull request by arvoConsultores**
## References
* Fixes #8412 

## Description
Add alphabetical ordering to collections list at Submission Form.

## Instructions for Reviewers
Add alphabetical ordering to the collection list and retrieve methods used at submission. For consistency we add ordering to some other retrieve methods.
List of changes in this PR:
* findSubmitAuthorized
* findSubmitAuthorizedByCommunity
* findAdminAuthorized
* findSubmitAuthorizedByEntityType
* findSubmitAuthorizedByCommunityAndEntityType

To check you should go to the submission form, e.g.https://demo7.dspace.org/home, add one item, and the collections should be listed alphabeticaly.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [X] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [X] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [X] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [X] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [X] If my PR modifies the REST API, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.

### CODE REVIEW

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/CollectionRestRepository.java [hunk 1]
```diff
@@ -248,6 +253,7 @@ public Page<CollectionRest> findSubmitAuthorizedByEntityType(
             List<Collection> collections = cs.findCollectionsWithSubmit(query, context, null, entityTypeLabel,
                                               Math.toIntExact(pageable.getOffset()),
                                               Math.toIntExact(pageable.getPageSize()));
+            Collections.sort(collections,  new NameAscendingComparator());
```
Comment (tdonohue) [inline dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/CollectionRestRepository.java:256]: @arvoConsultores : Rather than re-ordering results from Solr, wouldn't it be better performance to do this sort as part of the Solr query itself?  It looks like the `findCollectionsWithSubmit()` method just builds a Solr query, and we might just add `discoverQuery.setSortField()` call somewhere around here: https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/content/CollectionServiceImpl.java#L1015

Overall, I'd recommend we consider doing this sort using Solr **if it's possible to do so**.  That'd also provide much faster performance than reordering the Collection List after the results have been returned.  The other advantage to this approach is that all features which use `findCollectionsWithSubmit()` will then have the same alphabetical ordering with fewer code changes.

Comment (aroman-arvo) [reply dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/CollectionRestRepository.java]: Changed ordering to solr.

File: dspace-api/src/main/java/org/dspace/content/service/DSpaceObjectService.java [hunk 2]
```diff
@@ -52,6 +52,10 @@
             = new MetadataFieldName(DC, "format");
     public static final MetadataFieldName MD_SOURCE
             = new MetadataFieldName(DC, "source");
+    /*
+     * Field used to sort community and collection lists at solr
+     */
+    public static final String COMMUNITIES_AND_COLLECTIONS_SORT_FIELD = "dc.title_sort";
```
Comment (tdonohue) [inline dspace-api/src/main/java/org/dspace/content/service/DSpaceObjectService.java:58]: Small thing, but this appears to only be used for *Collection* sorting at this time.  So, it's name is misleading, and it probably would be better added to `CollectionService`.

I'd recommend moving this to `CollectionService` and renaming to simply `CollectionService.COLLECTIONS_SORT_FIELD` (or possibly even `CollectionService.SOLR_SORT_FIELD`).

**Review by tdonohue — COMMENTED** [review]
@arvoConsultores and @aroman-arvo : Thanks! This looks much better and it's working well for me.

I just have one minor comment inline below.  I think the new SORT_FIELD constant should just be moved over to `CollectionService` as it only applies to Collections at this time.  This is a small bit of cleanup, but I think that'd make this new constant easier to understand.

Beyond that, I'm +1 this PR.  So, once that change is made, I'll run one last test and then get it merged. Thanks again!

**Comment by aroman-arvo** [comment]
Constant moved and renamed to SOLR_SORT_FIELD (as its into CollectionService "COLLECTIONS_" is redundant)

**Review by tdonohue — APPROVED** [review]
👍 Thanks @arvoConsultores and @aroman-arvo !  This all looks great to me now. I've retested today and verified it's still working well.  Merging immediately.
