### PR TITLE
Fix Creating Researcher Profile fails when Custom URLs are enabled.

### LINKED ISSUE #12280: Creating Researcher Profile fails when Custom URLs are enabled.
## Describe the bug
Users are unable to create a researcher profile. The creation flow does not complete successfully, there is internal server error. 

The request to the `profiles` endpoint upon clicking "Create new" returns a 500:
```
{
    "timestamp": "2026-04-09T18:26:20.636+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "message": "An exception has occurred",
    "path": "/server/api/eperson/profiles"
}
```
Observed on the Sandbox during 10.0 Testathon, related to T212. 

## To Reproduce
1. As a registered user, go to the Profile screen
2. Click on the "Create new" button in the "Researcher Profile" section
3. Observe the errors that appear

https://jam.dev/c/b8fab09c-6156-45e2-82b9-dcb5c5147e62

## Expected behavior
A new researcher profile is created successfully.

### PR DESCRIPTION
**Pull request by AdamF42**
## References
* Fixes #12280

## Description
When creating a researcher profile with Custom URLs enabled, the request fails with a 500 Internal Server Error. This occurs because the `replaceCustomUrl` method receives a detached Hibernate entity from event consumers, causing a "detached entity passed to persist" error when trying to add metadata.

## Instructions for Reviewers

List of changes in this PR:
* Modified `CustomUrlServiceImpl.replaceCustomUrl()` to evict the item from the Hibernate session and re-fetch it using `itemService.find()` to obtain a fully managed entity before performing metadata operations.
* Added test coverage in `ResearcherProfileRestRepositoryIT.java` to verify the profile creation works with Custom URLs enabled.

**Include guidance for how to test or review your PR:**
1. Enable Custom URLs in the [DSpace configuration](https://wiki.lyrasis.org/display/DSDOC10x/Custom+URL+for+Entities#CustomURLforEntities-CustomURLautogeneration)
2. As a registered user, navigate to the Profile screen
3. Click "Create new" in the Researcher Profile section
4. Verify the profile is created successfully without a 500 error

## Checklist
- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR **passes Checkstyle** validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR **includes Javadoc** for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR **passes all tests and includes new/updated Unit or Integration Tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

File: dspace-api/src/main/java/org/dspace/app/customurl/consumer/CustomUrlConsumer.java [hunk 1]
```diff
@@ -288,7 +288,18 @@ private String extractMetadataValue(Item item, String metadataFieldName) {
      */
     private void assignCustomUrlToItem(Context context, Item item, String customUrl) {
         log.info("Assigning custom URL '{}' to item {}", customUrl, item.getID());
-        customUrlService.replaceCustomUrl(context, item, customUrl);
+        // Evict and re-fetch the item to ensure a clean managed entity.
+        // During event dispatch the item may have detached associations
+        // that cause "detached entity passed to persist" errors.
+        try {
+            context.uncacheEntity(item);
+            Item managedItem = itemService.find(context, item.getID());
```
Comment (tdonohue) [inline dspace-api/src/main/java/org/dspace/app/customurl/consumer/CustomUrlConsumer.java:296]: @AdamF42 : Rather than completely uncaching the entity, couldn't we just use `context.reloadEntity()` here?

For example:
```
Item managedItem = context.reloadEntity(item);
```

I think that'd align better with other consumers that also use reloadEntity() when processing items (e.g. `MediaFilterServiceImpl`.

If I'm wrong and `contenxt.reloadEntity()` doesn't work for some reason, then I'm OK with this current code.  But, at a glance it just seems we shouldn't need to fully "uncache" it and find it again if we can just reload it into the Hibernate cache.

**Review by tdonohue — CHANGES_REQUESTED** [review]
@AdamF42 : I tested this today, and it works to fix the issue. However, I'm not sure about the implementation (see comment inline below).  I think we can simplify this by using `contenxt.reloadEntity()` (see my comment inline below).  However, let me know if you already tried this and found it to be problematic.

The rest of the code all looks good to me!

File: dspace-api/src/main/java/org/dspace/app/customurl/consumer/CustomUrlConsumer.java (hunk 1 above)
Comment (AdamF42) [reply dspace-api/src/main/java/org/dspace/app/customurl/consumer/CustomUrlConsumer.java]: @tdonohue thanks for the suggestion. I actually looked into `context.reloadEntity()`, but it doesn't solve the root cause here. The issue is that `reloadEntity()` fetches a fresh copy from the DB without evicting stale child entities (like MetadataValue) already in the Hibernate session.
The `uncacheEntity()` method ensures those children are evicted before the `find()` call. I'm open to moving this logic into `ResearcherProfileServiceImpl.reloadItem()` instead so we can fix it at the source.

Comment (tdonohue) [reply dspace-api/src/main/java/org/dspace/app/customurl/consumer/CustomUrlConsumer.java]: @AdamF42 : Thanks for the further details. That makes more sense now.  Yes, I think it'd be better to move this logic into `ResearcherProfileServiceImpl.reloadItem()` with a comment that explains why it's necessary.  That seems like the best approach to me.

Comment (AdamF42) [reply dspace-api/src/main/java/org/dspace/app/customurl/consumer/CustomUrlConsumer.java]: @tdonohue thanks for the feedback. I took a look at moving the logic into `ResearcherProfileServiceImpl.reloadItem()`, but unfortunately, it didn't work as expected.

I also explored a few other workarounds to keep the logic into `ResearcherProfileServiceImpl`, but they ended up breaking several existing tests in `ResearcherProfileRestRepositoryIT`. Given the complexity of how the Hibernate session is managing those child entities, the current approach in this PR seems to be the most stable way to fix the issue without causing regressions.

If you're comfortable with it, I’d like to leave it as is for now.

Comment (tdonohue) [reply dspace-api/src/main/java/org/dspace/app/customurl/consumer/CustomUrlConsumer.java]: @AdamF42 : That's fine.  We can leave it as-is since there seems to be no other workaround that works.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @AdamF42 !  I've verified this fixes the bug.  My prior questions were all answered about the changes to `CustomUrlConsumer`.

File: dspace-api/src/main/java/org/dspace/app/customurl/consumer/CustomUrlConsumer.java (hunk 1 above)
Comment (tdonohue) [reply dspace-api/src/main/java/org/dspace/app/customurl/consumer/CustomUrlConsumer.java]: @AdamF42 : Pinged you also in #12353, but the changes in this PR which add the `context.uncacheEntity()` have caused unexpected side effects.  See #12353.

**Comment by tdonohue** [comment]
NOTE: just for the record for the future, part of the changes in this PR were reverted in #12357, where @AdamF42 found a better fix to the core issue.
