### PR TITLE
Fix for DSpace#9667: Request-a-copy link generation for base URLs that have sub-paths

### LINKED ISSUE #9667: Request-a-copy link has subpath stripped from dspace.ui.url
In a dspace instance configured to run at a subpath, that subpath is stripped when request-a-copy link is generated here:

https://github.com/DSpace/DSpace/blob/87f66fbc55cf2b8f8e265d74ce2c902ac2ee7e26/dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/RequestItemRepository.java#L300

URIBuilder.setPathSegments removes any exiting path segments from the base url before adding the new segments.

### PR DESCRIPTION
**Pull request by kshepherd**
Ensure DSpace URLs with extra segments are included fully in the generated link, instead of replacing all segments so that just the hostname and port are in the generated link (some dspace.ui.url values may have /sub/paths/)

## References
* Fixes #9667 

## Description
URIBuilder is still used to build the URL but instead of using `setPathSegments(...)`, I use `getPath()`, trim any trailing slash, and concatenate with `/request-a-copy/{token}` in `setPath(...)`.

## Instructions for Reviewers
To reproduce in main branch:
1. Set `dspace.ui.url` (backend) and `dspace.ui.nameSpace` (frontend) so that the frontend URL includes an extra URL segment like "http://localhost:4000/dspace". (also, update `rest.cors.allowed-origins` to include http://localhost:4000 as an additional allowed origin)
2. Enable request-a-copy and disable mail server (`mail.server.disabled=true`) so that mails will be logged instead of sent
3. Request a restricted file and inspect the link in the logged email: the link with the token for the approver will not contain the /dspace/ segment

To test the fix:
1. Repeat previous steps with this PR applied
2. This time when you inspect the link in the logged email, the /dspace/ segment should appear, and the link will work

List of changes in this PR:
* Updated `RequestItemRepository#getLinkTokenEmail` to build URIs using the existing full path instead of replacing segments, and made this a public method for testing
* Added new `RequestItemRepositoryIT#testGetLinkTokenEmail` test to the integration tests for this repository

Didn't see a big issue with making the method public, even if it is just so I can call it from the IT (but if there is something else we should do while we're changing it, like move it to RequestItemService, or a utility class, let me know)

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by kshepherd** [comment]
I accidentally broke non-subpath URLs with my earlier commit! I've fixed that and added a new test so both scenarios are tested for in the IT

**Comment by tdonohue** [comment]
@kshepherd : Please rebase this on main.  The IT failures you have in this PR were fixed on main in #9691 and are unrelated to your PR.

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/RequestItemRepository.java [hunk 1]
```diff
@@ -287,19 +288,18 @@ public Class<RequestItemRest> getDomainClass() {
...
-        URI link = new URIBuilder(base)
-                .setPathSegments("request-a-copy", token)
-                .build();
-
-        return link.toURL().toExternalForm();
+        URIBuilder uriBuilder = new URIBuilder(base);
+        // Add request-a-copy/token to the existing path (without breaking /sub/dir dspace URLs)
+        URI uri = uriBuilder.setPath(
+                (uriBuilder.getPath() == null ? "" : StringUtils.stripEnd(uriBuilder.getPath(), ""))
+                        + "/request-a-copy/" + token).build();
```
Comment (mwoodiupui) [inline dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/RequestItemRepository.java:302]: Rather than doing this string-wise, how about `Collections.addAll(uriBuilder.getPath(), "request-a-copy", token)`?  UriBuilder knows how to get the separators right in all cases.

Comment (kshepherd) [reply dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/RequestItemRepository.java:302]: @mwoodiupui thanks for the review.

In my testing, simple usage like `URI uri = uriBuilder.setPathSegments(uriBuilder.getPath(), "request-a-copy", token).build();` results in extra stringify array elements ([null], or [], or encoded slashes) no matter how stripping is handled in that first segment (which is either null/empty or the sub-path).

Not sure where `Collections.addAll` exactly fits in (did you mean the static method?), though we could prepare a list instead of string concatenation, is that what you were thinking?

Here is a non-concatenation approach that works. I'm happy to run with this instead:


```
        List<String> segments = new LinkedList<>();
        if (StringUtils.isNotBlank(uriBuilder.getPath())) {
            segments.add(StringUtils.strip(uriBuilder.getPath(), "/"));
        }
        segments.add("request-a-copy");
        segments.add(token);
        URI uri = uriBuilder.setPathSegments(segments).build();
```

(I know concatenation is viewed as 'bad', I just didn't see this as necessarily any more readable or performant for such a small string in my first go around, and I couldn't see any security issues with concat either:)

If there is a shorter way using Collections.addAll that I've missed, please let me know

Comment (mwoodiupui) [reply dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/RequestItemRepository.java:302]: I think your suggestion should work.

I forgot that trailing slashes are an unavoidable problem with HTTP URL syntax.  Should've tested before suggesting.  I've made [a Gist](https://gist.github.com/mwoodiupui/1a308774c1030fc8deb9b7a416f13cc0) of the version of my approach that eventually worked with every base URL I've tried, in case anyone is interested.

Comment (kshepherd) [reply dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/RequestItemRepository.java]: Thanks @mwoodiupui , I have pushed the changes as recommended. Is it looking better to you now?

**Review by mwoodiupui — APPROVED** [review]
Looks good.  +1 by inspection, ITs are passing.

`getLinkTokenEmail` can be package-private if the IT is moved down to `dspace/app/rest/repository` where it seems to belong, but it's not a big deal.
