### PR TITLE
Submission performance

### LINKED ISSUE #8791: Workspace items are loading too much information
**Describe the bug**
In the submission process, a workspace item is requested with full projection. As a consequence a lot of unnecessary information is retrieved such as all of the submitter data, the collection with all its embedded objects, the item with all of its embedded objects. This drastically slows down the creation and loading of submission items when a lot of information is available. 

**To Reproduce**
* Set up a submitter with metadata
* Set up a collection with embedded objects such as a template item, related groups, a logo, ...
* Open the network tab, and run the angular app in dev mode so all requests are visible
* Start a new submission as the submitter in the aforementioned collection
* Verify that the created workspace items is retrieved using a full projection, and contains all the embedded objects such as the collection with its embeds, the full submitter data, ...

**Expected behavior**
Only the necessary information should be retrieved, not a full projection with all of the possible embeds.

### LINKED ISSUE #9164: WorkflowItems and WorkspaceItems do not obey projections and always embed all data.
Discovered in #9053, and also related to #8791 (which might be solved by the same solution)

## Describe the bug
When WorkflowItems and WorkspaceItems are represented in REST API responses, they **always** embed a large amount of data.  This embedding is hardcoded into our code, and [CANNOT be controlled via projections](https://github.com/DSpace/RestContract/blob/main/projections.md).  The results is that these objects always return the equivalent of a `?projection=full` request, with no way to turn it off.

**This behavior can result in performance issues on the MyDSpace page (`/mydspace`).**  These performance issues are easier to see on the "Workflow Tasks" view (`/mydspace?configuration=workflow`), see #9053 as one example. It also can impact the "Your Submissions" view (`/mydspace?configuration=workspace`) when the page size is a very large value.  

## To Reproduce
1. From the UI, open of your browser's DevTools "Network" tab (to watch the REST API requests/responses)
2. Login. go to "MyDSpace" 
3. By default the "Your Submissions" view is shown.  This makes a request to REST that is structured like: `/server/api/discover/search/objects?sort=lastModified,DESC&page=0&size=10&configuration=workspace&embed=thumbnail&embed=item%2Fthumbnail&embed=accessStatus`
    * Notice this request has no `projection` param, and only a few `embed` params
    * If you look at the response to that request, you'll find that it's a _very large_ JSON response.  For each `workspaceitem` listed, you'll find it embeds the following (in the `_embedded` section)
        * All data about the `submitter`
        * All data about the `item`
        * All data about the `submissionDefinition`
        * All data about the `collection`
     * **BUG:** This is more information than is necessary, as this page doesn't need information like the `submissionDefinition` (which is the entire submission configuration), etc.  There's also no way to turn off these embeds. 
4. Now, using the "Show" selectbox, change to the "Workflow tasks" view.  This makes a request to REST that is structured like: `/server/api/discover/search/objects?sort=lastModified,DESC&page=0&size=10&configuration=workflow&embed=thumbnail&embed=item%2Fthumbnail&embed=accessStatus`  (This is the same request as above except `configuration=workflow` is used to load Workflow Items)
    * Notice this request has no `projection` param, and only a few `embed` params
    * If you look at the response to that request, you'll find that it's AGAIN a _very large_ JSON response.  For each `claimedtask` or `pooltask` listed, you'll find it embeds the following (in the `_embedded` section)
        * All data about the `group` that can claim the task (for `pooltask` objects only) or the `owner` who claimed the task (for `claimedtask` objects only)
        * All data about the `workflowitem`
            * All data about this workflowitem's `submitter`
            * All data about this workflowitem's `item`
            * All data about this workflowitem's `submissionDefinition`
            * All data about this workflowitem's `collection`
     * **BUG:** This is more information than is necessary, as this page doesn't need information like the `submissionDefinition` (which is the entire submission configuration), etc.  There's also no way to turn off these embeds. 

## Expected behavior
REST API responses should all obey the [rules for projections](https://github.com/DSpace/RestContract/blob/main/projections.md) & the ideal default behavior is to embed as little data as possible.  This gives the User Interface more control over requesting the exact embedded data it requires for different pages.

The core problem appears to be that the `AInprogressItemConverter` (used for both WorkspaceItems and WorkflowItems) embeds all data by default.  For example, this section of code always embeds the entire SubmissionDefinition in each of these objects: 
https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/AInprogressItemConverter.java#L82-L126

This Converter is used (by the REST API) anytime a `WorkspaceItem` or `WorkflowItem` is returned (i.e. displayed in the UI). even when they are returned/displayed in lists/searches, like on the MyDSpace page.  This causes every object listed on the MyDSpace page to load its `SubmissionDefinition` (and other unnecessary embedded data). 

This obviously impacts performance. If you change the pagesize to 100 on MyDSpace, that will result in all objects loading their SubmissionDefinition...so you will find 100 SubmissionDefinitions in the final REST response.  Logically, the SubmissionDefinition is only needed when **editing** a submission (or an item in workflow), so this extra data is wasteful and hurts performance.

**Related work**
Related to #9053
A fix to this bug might also fix #8791 (which is a similar ticket, but limited just to WorkspaceItems).

### PR DESCRIPTION
**Pull request by Atmire-Kristof**
## References
* Fixes #9164 
* Fixes #8791
* [7_x REST PR](https://github.com/DSpace/DSpace/pull/9507)
* [7_x angular PR](https://github.com/DSpace/dspace-angular/pull/2987)
* [main REST PR](https://github.com/DSpace/DSpace/pull/9508) (this PR)
* [main angular PR](https://github.com/DSpace/dspace-angular/pull/2988)

## Description
This PR aims to improve performance for submission by removing default full projection for workflow/workspace items and instead allowing support for embedded properties.

## Instructions for Reviewers
Changes:
* Added links for "item", "submitter" and "collection" on workflow/workspace items (annotations, link repositories etc.)
* Removed `projection=full` from submission item on angular side and replaced with embed parameters, this should reduce _a lot_ of the server and page's load.
* Modified test cases that expect embedded properties to either remove the expectation or add embedded parameter to the request

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/AInprogressItemConverter.java [hunk 1]
```diff
@@ -70,11 +70,11 @@ protected void fillFromModel(T obj, R witem, Projection projection) {
...
         witem.setId(obj.getID());
-        witem.setCollection(collection != null ? converter.toRest(collection, projection) : null);
-        witem.setItem(converter.toRest(item, projection));
-        if (submitter != null) {
-            witem.setSubmitter(converter.toRest(submitter, projection));
-        }
+//        witem.setCollection(collection != null ? converter.toRest(collection, projection) : null);
+//        witem.setItem(converter.toRest(item, projection));
+//        if (submitter != null) {
+//            witem.setSubmitter(converter.toRest(submitter, projection));
```
Comment (tdonohue) [inline dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/AInprogressItemConverter.java:76]: @Atmire-Kristof : Please don't include commented out code in PRs.  This code should either be removed (if no longer needed) or uncommented (if needed).  I'm guessing it should be removed.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @Atmire-Kristof !  I've reviewed & tested this today.  The code makes perfect sense and has ITs.  I also verified it works well in the Submission UI (tested with https://github.com/DSpace/dspace-angular/pull/2988).

I'll go ahead and merge this.  However, I'm flagging it with `needs documentation` because this PR requires *minor updates* to our REST Contract.  Namely, I think the new "submitter" link is missing from both Workspace & Workflow items:
* https://github.com/DSpace/RestContract/blob/main/workspaceitems.md#linked-entities
* https://github.com/DSpace/RestContract/blob/main/workflowitems.md#linked-entities

(I think that's the only new linked entity.  But, I'd recommend double checking our REST Contract is still accurate for these endpoints based on this new PR.)
