### PR TITLE
Fix index issue and long script running for suggestion script

### LINKED ISSUE #10718: Suggestion script issue with large repository
## Describe the bug
When plenty of suggestions are imported using the publication suggestion loader script the script slows down and sometimes crashes leading to a broken SOLR index due to a missing commit operation

## To Reproduce

1. 1500 - 2000 researchers are needed
2. run the script `./dspace import-loader-suggestions -l <loader>` (where loader is openalex or openaire)
3. the script slows down and requires a lot of time to complete, the SOLR index during this process might also "lose" some items

## Expected behavior
No slow down or odd behavior is encountered

## Related work
https://github.com/DSpace/DSpace/pull/10719

### PR DESCRIPTION
**Pull request by steph-ieffam**
## References
* Fixes https://github.com/DSpace/DSpace/issues/10718

## Description
When plenty of suggestions are imported using the publication suggestion loader script the script slows down and sometimes crashes leading to a broken SOLR index due to a missing commit operation

List of changes in this PR:
* added commit and uncache operation

## To Reproduce

1. 1500 - 2000 researchers are needed
2. run the script `./dspace import-loader-suggestions -l <loader>` (where loader is openalex or openaire)
3. the script slows down and requires a lot of time to complete, the SOLR index during this process might also "lose" some items

## Checklist

- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR **passes Checkstyle** validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR **includes Javadoc** for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR **passes all tests and includes new/updated Unit or Integration Tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

File: dspace-api/src/main/java/org/dspace/app/suggestion/runnable/PublicationLoaderRunnable.java [hunk 1]
```diff
@@ -121,6 +121,8 @@ public void internalRun() throws Exception {
                 Item researcher = researchers.next();
                 publicationLoader.importRecords(context, researcher);
                 setLastImportMetadataValue(researcher);
+                context.commit();
+                context.uncacheEntity(researcher);
```
Comment (tdonohue) [inline dspace-api/src/main/java/org/dspace/app/suggestion/runnable/PublicationLoaderRunnable.java:125]: I think the problem here may that you've closed the database transaction which was connected to `researchers` and `researcher`.  You might need to do a `context.reloadEntity(researcher);` above right after you call `Item researcher = researchers.next()` in order to reconnect it to the current context.

For example, see how a similar process is managed here https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/identifier/doi/DOIOrganiser.java#L228-L239

**Review by tdonohue — CHANGES_REQUESTED** [review]
@steph-ieffam : This fix doesn't work for me.  Using this PR, if I simply run `import-loader-suggestions -l openalex` as a Process from the Admin UI, I get an immediate error that says this:
```
Exception in thread "dspaceRunnableThreadExecutor-1" java.lang.RuntimeException: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: org.dspace.content.DSpaceObject.metadata: could not initialize proxy - no Session
   at org.dspace.app.rest.scripts.handler.impl.RestDSpaceRunnableHandler.handleException(RestDSpaceRunnableHandler.java:166)
   at org.dspace.app.rest.scripts.handler.impl.RestDSpaceRunnableHandler.handleException(RestDSpaceRunnableHandler.java:133)
   at org.dspace.scripts.DSpaceRunnable.run(DSpaceRunnable.java:153)
   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
   at java.base/java.lang.Thread.run(Thread.java:840)
 Caused by: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: org.dspace.content.DSpaceObject.metadata: could not initialize proxy - no Session
   at org.hibernate.collection.spi.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:634)
   at org.hibernate.collection.spi.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:217)
   at org.hibernate.collection.spi.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:613)
   at org.hibernate.collection.spi.AbstractPersistentCollection.read(AbstractPersistentCollection.java:136)
   at org.hibernate.collection.spi.PersistentBag.iterator(PersistentBag.java:371)
   at org.dspace.content.DSpaceObjectServiceImpl.getMetadata(DSpaceObjectServiceImpl.java:123)
   at org.dspace.content.ItemServiceImpl.getMetadata(ItemServiceImpl.java:1771)
   at org.dspace.content.ItemServiceImpl.getEntityTypeLabel(ItemServiceImpl.java:1848)
   at org.dspace.content.ItemServiceImpl.getEntityType(ItemServiceImpl.java:1871)
   at org.dspace.content.RelationshipMetadataServiceImpl.getRelationshipMetadata(RelationshipMetadataServiceImpl.java:61)
   at org.dspace.content.ItemServiceImpl.getMetadata(ItemServiceImpl.java:1779)
   at org.dspace.content.ItemServiceImpl.getMetadata(ItemServiceImpl.java:1763)
   at org.dspace.content.ItemServiceImpl.getMetadata(ItemServiceImpl.java:100)
   at org.dspace.content.DSpaceObjectServiceImpl.getMetadata(DSpaceObjectServiceImpl.java:164)
   at org.dspace.content.DSpaceObjectServiceImpl.getMetadataByMetadataString(DSpaceObjectServiceImpl.java:152)
   at org.dspace.content.DSpaceObjectServiceImpl.getMetadata(DSpaceObjectServiceImpl.java:171)
   at org.dspace.app.suggestion.openalex.OpenAlexPublicationLoader.lambda$searchMetadataValues$0(OpenAlexPublicationLoader.java:43)
   at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
   at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
   at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
   at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
   at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
   at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
   at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
   at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
   at org.dspace.app.suggestion.openalex.OpenAlexPublicationLoader.searchMetadataValues(OpenAlexPublicationLoader.java:45)
   at org.dspace.app.suggestion.loader.PublicationLoader.importRecords(PublicationLoader.java:114)
   at org.dspace.app.suggestion.runnable.PublicationLoaderRunnable.internalRun(PublicationLoaderRunnable.java:122)
   at org.dspace.scripts.DSpaceRunnable.run(DSpaceRunnable.java:150)
   ... 3 more
```

I think the issue is that you are closing a database transaction (via a commit()) call, while still keeping objects open that depend on that database transaction.  See my notes inline below of how we might need to fix this code.  I have **not yet tested** my recommendations, but there are other areas of our code which do something similar.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @steph-ieffam !  This is working well now.  While I don't have enough researchers to verify the performance issue, I can verify that this works well with smaller sets of researchers (~100), and the code looks correct to me.  Thanks!
