### PR TITLE
Consider all selected dc.types when validating input fields in submission/review-form

### LINKED ISSUE #10601: Input field values (with type-bind) not saved if dc.type is repeatable
## Describe the bug
If "dc.type" is repeatable, any type-bound input field values are not saved during a submission/review if the first chosen dc.type does not match with the type-binding of the other input field. Or, in other words, only the first dc.type value is read, all other types are ignored.

## To Reproduce

1. Make sure your dc.type field is defined as repeatable
```
            <row>
                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>type</dc-element>
                    <dc-qualifier></dc-qualifier>
                    <repeatable>true</repeatable>
                    <label>Type</label>
                    <input-type value-pairs-name="common_types">list</input-type>
                    <hint>Select the type(s) of content of the item. To select more than one value in the list, you may
                        have to hold down the "CTRL" or "Shift" key.
                    </hint>
                    <required>You must choose at least one type.</required>
                </field>
            </row>
```
2. Configure your submission-form with at least one field, where the type-bind looks like this e.g.:
```
          <row>
                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>title</dc-element>
                    <dc-qualifier>alternative</dc-qualifier>
                    <repeatable>true</repeatable>
                    <label>Other Titles</label>
                    <type-bind>Article</type-bind>
                    <input-type>onebox</input-type>
                    <hint>If the item has any alternative titles, please enter them here.</hint>
                    <required></required>
                </field>
            </row>
```
3. Open your local DSpace instance in the browser and log-in (as administrator e.g.)
4. Start a new submission with the collection containing the new type-bound field (dc.title.alternative in my case)
5. First choose any dc.type, but not "Article" from the checkbox list
6. Choose now "Article" -- as a result, the "Other titles" input field should appear
7. Enter any value to the new "Other titles" input field
8. Save your submission
9. Reload your submission - the previously entered data in the type-bound input field are gone

## Expected behavior
The values of any input field with a type-bind to the dc.type values should not get lost during a saving process in the submission/review.

## Related issue
- (https://github.com/DSpace/dspace-angular/issues/4014) - this pull request does not handle any issues in the frontend

### PR DESCRIPTION
**Pull request by jlipka**
If the "dc.type" metadata is configured as "repeatable", the validation will now check for all selected types, not just the first one, with the benefit of not losing data in type-bound input fields.

## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #10601

## Description
The code before this change did only recognize the first dc.type value. Now you can have multiple types selected and the validation as well as the form sections data returned by the backend should contain all data.

## Instructions for Reviewers / Guidance how to test
1. Make sure your dc.type field is defined as repeatable
```
            <row>
                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>type</dc-element>
                    <dc-qualifier></dc-qualifier>
                    <repeatable>true</repeatable>
                    <label>Type</label>
                    <input-type value-pairs-name="common_types">list</input-type>
                    <hint>Select the type(s) of content of the item. To select more than one value in the list, you may
                        have to hold down the "CTRL" or "Shift" key.
                    </hint>
                    <required>You must choose at least one type.</required>
                </field>
            </row>
```
2. Configure your submission-form with at least one field, where the type-bind looks like this e.g.:

```
            <row>
                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>title</dc-element>
                    <dc-qualifier>alternative</dc-qualifier>
                    <repeatable>true</repeatable>
                    <label>Other Titles</label>
                    <type-bind>Article</type-bind>
                    <input-type>onebox</input-type>
                    <hint>If the item has any alternative titles, please enter them here.</hint>
                    <required></required>
                </field>
            </row>
```
 3. Open your local DSpace instance in the browser and log-in (as administrator e.g.)
 4. Start a new submission with the collection containing the new type-bound field (dc.title.alternative in my case)
 5. First choose any dc.type, but not "Article" from the checkbox list
 6. Choose now "Article" -- as a result, the "Other titles" input field should appear
 7. Enter any value to the new "Other titles" input field
 8. Save your submission
 9. Check the PATCH response for the "dc.title.alternative" metadata at two places:
Bildschirmfoto 2025-04-14 um 16 35 07

10. After a page reload, the other titles information should still be present

**List of changes in this PR:**
* Check for more than the first dc.type value
* I wanted to leave the old logic as much as possible, but had of course to rewrite the conditions, and extended the logic to handle a List<String>, e.g. like this line of code:
  * `(documentTypes.isEmpty() && input.isAllowedFor("")) || documentTypes.stream().anyMatch(dt -> input.isAllowedFor(dt.getValue()))`
* `SubmissionConfigTest` extended with new cases

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome).
However, reviewers may request that you complete any actions in this list if you have not done so. If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR **passes Checkstyle** validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [ ] My PR **includes Javadoc** for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR **passes all tests and includes new/updated Unit or Integration Tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [ ] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [ ] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [ ] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

File: dspace-api/src/main/java/org/dspace/app/util/DCInputSet.java [hunk 1]
```diff
@@ -225,4 +225,42 @@ public List<String> populateAllowedFieldNames(String documentTypeValue) {
         return allowedFieldNames;
     }
 
+    public List<String> populateAllowedFieldNames(List<String> documentTypeValues) {
```
Comment (kshepherd) [inline dspace-api/src/main/java/org/dspace/app/util/DCInputSet.java:288]: This method needs javadoc (similar to the single value one), and I see that the single-value method is only used by Tests, so I recommend we remove it completely and change the tests to call your new method with `List.of("Book")` or so on, since it also handles single-value lists just fine

**Comment by kshepherd** [comment]
@jlipka Sorry for my very belated review on this useful improvement - I made one comment recommending that we remove the old method (that accepted a String param) in favour of your new, more versatile one, and update Tests accordingly. Once we've sorted that out and resolved the git conflict, I will approve this :) thanks!

**Review by kshepherd — CHANGES_REQUESTED** [review]

**Comment by jlipka** [comment]
I just pulled all new changes from the `main` branch and updated my pull request. As there have been couple changes in the meanwhile (validators had been moved to other files for example), I had to make little more changes than before, e.g. usage of "TypeBindUtils" and rename the static method.

File: dspace-api/src/main/java/org/dspace/app/util/DCInputSet.java (hunk 1 above)
Comment (jlipka) [reply dspace-api/src/main/java/org/dspace/app/util/DCInputSet.java:288]: - removed single-valued method now

**Review by kshepherd — APPROVED** [review]
+1 looking great now thanks @jlipka

**Comment by kshepherd** [comment]
@tdonohue I have tested this PR practically, and re-reviewed the code.
So if we need another +1 for this fairly small improvement, it could be code inspection rather than a full e2e test

**Comment by tdonohue** [comment]
@jlipka : Could you fix the merge conflict in this PR?  I've taken a look at the code and it looks good to me.  Based on @kshepherd 's [feedback as well](https://github.com/DSpace/DSpace/pull/10600#issuecomment-4135076275), I think this can be merged as soon as the merge conflicts are resolved.

**Comment by jlipka** [comment]
@tdonohue Thanks for the reminder. I just pulled all new changes from the main branch into this working branch.

**Comment by tdonohue** [comment]
Merging as code looks good to me & was previously reviewed/tested by @kshepherd !  Thanks again @jlipka !

**Comment by tdonohue** [comment]
@jlipka : While this was merged into 10.0, it was unable to be auto-backported to `dspace-9_x` or `dspace-8_x`.  If you'd like to see this change in either of those older releases, please create a backport PR specific to those branches with the same changes as this PR.
