### PR TITLE
Handles versioning for ORCID publications.

### LINKED ISSUE #8662: Versioning and ORCID
**Describe the bug**
Versioning and ORCID are not playing well together.
All the versions are pushed to ORCID. I would expect to have the existing record updated on the ORCID side with the most recent version.

**Expected behavior**
The ORCID record should be updated with the new version. The item should reuse the same PUT code from ORCID instead than remove and create a new record.

### PR DESCRIPTION
**Pull request by vins01-4science**
#### _Please note that this development has been funded by the [ORCID Global Participation Fund](https://info.orcid.org/global-participation-program/global-participation-fund/)._
---
DSpace 8_x version here: [#9723](https://github.com/DSpace/DSpace/pull/9723)
DSpace 7_x version here: [#9722](https://github.com/DSpace/DSpace/pull/9722)

## References
* Fixes #8662

## Description
This PR adds improvements to the ORCID synchronization feature.
Whenever an item is versioned, and is queued for synchronization, its reference will be updated in order to have an updated publication on the ORCID side.
Whenever an item is versioned, but its already published, it will be updated.

## Instructions for Reviewers
Just try to create a new publication, and leave it inside the ORCID synchronization queue.
Now try to create a new version of it, and check that the pending publication is updated with the new version (you can check it inside the `orcid_queue` table).
In the same way you should publish the update to the ORCID servers and then try to versionate it again. In this case you should check that the entry inside the `orcid_history` table has been updated correctly.

List of changes in this PR:
The changes will introduce the followings:

Consumer
  - orcid queue will be populated only by latest version of items
Versioning
  - Items in orcid queue that are related to an older version will be deleted
  - Older items' version in the orcid history will be updated with the last one in order to have only one entry per-item.

## Checklist
- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR **passes Checkstyle** validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR **includes Javadoc** for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR **passes all tests and includes new/updated Unit or Integration Tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by sheilarabun** [comment]
For the funding acknowledgement for this PR and any others that are part of the DSpace/ORCID grant via Lyrasis, please use the following language: "Please note that this development has been funded by the [ORCID Global Participation Fund](https://info.orcid.org/global-participation-program/global-participation-fund/).

File: dspace-api/src/main/java/org/dspace/content/ItemServiceImpl.java [hunk 1]
```diff
@@ -1931,4 +1937,40 @@ private void deleteOrcidQueueRecords(Context context, Item item) throws SQLExcep
         }
     }
 
+    @Override
+    public boolean isLatestVersion(Context context, Item item) throws SQLException {
```
Comment (tdonohue) [inline dspace-api/src/main/java/org/dspace/content/ItemServiceImpl.java:1941]: Would it be possible to add an automated test for this method in either `ItemTest` or `ItemServiceIT`?  Ideally, all new methods should have a basic test to prove their behavior works.  This one seems to be missing a test that it's returning true/false in the proper scenarios.

**Review by tdonohue — COMMENTED** [review]
@vins01-4science : Thanks for this PR!  We gave this a group code review in the Developer Meeting today. Overall, the code looks good, but we noticed a missing automated test (see below).  The code comments & Javadocs are all great though!

This also needs someone to manually test that the behavior looks correct now. But, from the existing OrcidQueueConsumerIT, it looks like it should work.  Thanks again!

**Review by tdonohue — APPROVED** [review]
👍 Thanks @vins01-4science !  I was able to give this a basic test today, and verify manually that the "orcid_queue" is updated when a new version is created, and that it always includes the latest *archived* version.

Tests and code look good as well
