### PR TITLE
Clarify checker and checker-emailer -related command line options, messages and report formatting

### LINKED ISSUE #8999: Checksum checker email reports mention a checksum checker option `-u`, that does not exist in code or documentation
**Describe the bug**
The checksum checker email report includes at the end a section of unchecked bitstreams. I suppose, there was just not enough time allocated to the checker to check those?

The report says:

> The following is a UN-CHECKED BITSTREAM REPORT report for 7/30/23
> To add these bitstreams to be checked run the checksum checker with the -u option

Neither the documentation at https://wiki.lyrasis.org/display/DSDOC7x/Validating+CheckSums+of+Bitstreams nor the code `dspace-api/src/main/java/org/dspace/app/checker/ChecksumChecker.java` known an option `-u`.

If you start the checker with option `-u` you receive this error in the logs:

```
2023-08-01 11:34:08,457 FATAL unknown unknown org.dspace.app.checker.ChecksumChecker @ org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -u
```

**Expected behavior**
- If this option makes sense and had existed in the past, perhaps we should bring it back,
- if it is just a not valid text in the report, this text should be changed or removed.

### LINKED ISSUE #10008: `checker-emailer` command options and documentation are a mess
<https://wiki.lyrasis.org/display/DSDOC7x/Validating+CheckSums+of+Bitstreams#ValidatingCheckSumsofBitstreams-AutomatedChecksumCheckers'Results>

1. The long options are all named with capital letters at the start, which is not usual command-line tool style (it doesn’t match the style used by other `dspace` sub-commands. This would be okay – just a little weird – except also …
2. The `--Not Processed` option has a space in the name. This means you have to enter it at the shell at `'--Not Processed'` or `--Not\ Processed`, which is far from intuitive (how many users of DSpace are not command line experts and don’t even know how to insert spaces within a single token?)
3. There’s an option called `--Unchanged` which says its job is to ‘Send the Unchecked bitstream report’. Why is it called Un*changed* if it actually has to do with Un*checked* things? Which is correct, the option name or the documentation?

### PR DESCRIPTION
**Pull request by minurmin**
## References

* Fixes #10008
* Fixes #8999 (replacement patch to https://github.com/arvoConsultores/DSpaceGithub/pull/1 by @aroman-arvo )

For reference, older issues that are related to checker-related command line options (with new functionality) include #5272 and #5853. As PRs related to these have not been merged to official DSpace (even though issues have been marked as "completed"), they may be of interest when planning future development of checker and emailer.

## Description

Clarifies and harmonizes command-line options, related help, error messages, and report mails related checksum checker and checker-emailer.

## Instructions for Reviewers

List of changes in this PR:
 
 - Additional clarification (with a new error message) about mutually exclusive commánd-line options in checker (i.e. user must select only one dispatcher mode)
 - Lowercased longer form command-line options in checker-emailer (e.g. `--Not\ Processed` changed to `--not-processed`)
 - To make checker options more in line with other DSpace command line tools checker `-a` option (handle-based check) has been changed to `-i`
 - Removed reference to nonexistent -u option in a emailer message

Includes also other minor formatting related fixes not strictly mentioned in original issues. These include:
 - Spelling fixes in emailer reports (i.e. `The following is a BITSTREAM SET DELETED report for14.2.2025 to 16.2.2025` has been updated to `The following is a BITSTREAM SET DELETED report from 14.2.2025 to 16.2.2025`)
 - checker `-b` option and related error message included reference to numeric (pre DSpace 6.x) IDs. Text updated such that UUIDs are mentioned
 - Log item about sent email messages has been added to checker log.

AS this PR is mostly related to documentation and messages (and less about actual functionality), testing this PR involves trying out different command-line options (including invalid combinations, such as `checker -c 10 -L`), as well as observing formatting used in generated e-mail reports. The code has been tested with DSpace 7 -based installation but it seems that no essential changes related to these have been made in newer codebase so it should work out of the box.

## Checklist

- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR **passes Checkstyle** validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [ ] My PR **includes Javadoc** for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [ ] My PR **passes all tests and includes new/updated Unit or Integration Tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by minurmin** [comment]
While further testing checker and checker-emailer (in DSpace 8 but the same issue is present in newer versions as well) I noticed that email subject (_Checksum checker Report - n Bitstreams found with POSSIBLE issues on ..._) for "all" report is confusing when _Not to be processed_ report is included (as it has been broken for some time, see #7143) as the bitstreams are counted twice. For example, if after the latest checker run 25 bitstreams are found to be deleted, 50 is highlighted in the subject (as same bitstreams appear in two reports). I revised the PR such that bitstreams in Not processed - report are not counted (when -a parameter is used) as they are already present in BITSTREAM NOT FOUND or BITSTREAM SET DELETED reports. In addition, help text on Not processed -report has been clarified.

File: dspace-api/src/main/java/org/dspace/checker/DailyReportEmailer.java [hunk 1]
```diff
@@ -186,7 +190,9 @@ public static void main(String[] args) {
                 writer.write("\n--------------------------------- Report Spacer ---------------------------\n\n");
                 numBitstreams += reporter.getBitstreamNotFoundReport(context, yesterday, tomorrow, writer);
                 writer.write("\n--------------------------------- Report Spacer ---------------------------\n\n");
-                numBitstreams += reporter.getNotToBeProcessedReport(context, yesterday, tomorrow, writer);
+                // not to be processed report includes deleted and not found bitstreams so it is not necessary to
+                // incude the sum in the counter
```
Comment (nwoodward) [inline dspace-api/src/main/java/org/dspace/checker/DailyReportEmailer.java]: Typo: `incude` -> `include`.

**Review by nwoodward — APPROVED** [review]
👍 Thanks @minurmin. This PR significantly improves the `checker` and `checker-emailer` commands. I tried all the command-line options, and everything looks good. As you mentioned, it will require updates to the documentation to reflect these changes.

**Comment by minurmin** [comment]
Thank you for the review @nwoodward! Typo fixed.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @minurmin !  This looks good to me too.  I gave it some light testing via the command-line and it is much improved.

**Comment by tdonohue** [comment]
I went ahead and made minor updates to the documentation at https://wiki.lyrasis.org/display/DSDOC10x/Validating+CheckSums+of+Bitstreams  and copied those changes to the 9.x, 8.x, and 7.x documentation.
