### PR TITLE
multiple bitstream deletion endpoint

### LINKED ISSUE #8029: DSpace 7: Cannot delete multiple bitstreams at the same time
**Describe the bug**
In item edit page, only one bitstream can be deleted at a time. If we delete multiple bitstreams at once, only the first on get properly deleted, the rest got marked as deleted in bitstream table but still show up in item page.

**To Reproduce**
Steps to reproduce the behavior: (tested on DSpace 7.1 on demo7 site)
1. Add a few bitstreams to an item
2. Go to item edit page -> Bitstream
3. Select multiple bitstreams for deletion
4. Click save
5. Only the first bitstream got properly deleted.
6. The rest of the bitstreams still show up, but cannot be downloaded.

**Expected behavior**
All selected bitstreams are properly deleted.

**More information**
- The first bitstream got marked as deleted and got deleted from bundle2bitstream table.
- The other bitstreams got marked as deleted but are still there in bundle2bitstream table. 
- We see the following Exception in log file when tested on our installation (7.0):

`
javax.persistence.OptimisticLockException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: update public.bundle2bitstream set bitstream_id='a610b77b-92fa-460a-8d0b-9ea8b63ee95a'::uuid where bundle_id='9e30efa6-84db-48a3-97ea-5c6f923aa901'::uuid and bitstream_order=131
        at org.hibernate.internal.ExceptionConverterImpl.wrapStaleStateException(ExceptionConverterImpl.java:238) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:93) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1348) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1331) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at jdk.internal.reflect.GeneratedMethodAccessor306.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.hibernate.context.internal.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:351) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at com.sun.proxy.$Proxy185.flush(Unknown Source) ~[?:?]
        at org.dspace.core.HibernateDBConnection.commit(HibernateDBConnection.java:159) ~[dspace-api-7.0.jar:7.0]
        at org.dspace.core.Context.commit(Context.java:432) ~[dspace-api-7.0.jar:7.0]
[...]
`

### PR DESCRIPTION
**Pull request by JensRoets-Atmire**
## References
* Fixes #8029 (for backend)
* REST Contract https://github.com/DSpace/RestContract/pull/203
* Frontend PR: https://github.com/DSpace/dspace-angular/pull/2280

## Description
Adds an endpoint to delete more than one Bitstream at the same time in a given REST call. According to the [REST Contract on Multiple Bitstreams Delete](https://github.com/DSpace/RestContract/pull/203)

## Instructions for Reviewers
* Added a delete method in the RestResourceController that accepts a list of text/uri elements
* Added a delete method in the BitstreamRestRepository to catch this & forward it to implementing repositories
* Added a delete method in the DSpaceRestRepository taking a list of DSpaceObjects
* Added ITs for this functionality in the BitstreamRestRepositoryIT
  - deleteListOneBitStream()
  - deleteListOneOfMultipleBitstreams()
  - deleteListAllBitstreams()
  - deleteListForbidden()
  - deleteListUnauthorized()
  - deleteListEmpty()
  - deleteListNotBitstream()
  - deleteListDifferentItems()
  - deleteListLogo()
  - deleteListMissing()
  - deleteListOneMissing()
  - deleteListOneMissingDifferentItems()
  - deleteListDeleted()
  - deleteListOneDeleted()

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [ x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/RestResourceController.java [hunk 1]
```diff
@@ -1050,6 +1053,13 @@ public ResponseEntity<RepresentationModel<?>> delete(HttpServletRequest request,
         return deleteInternal(apiCategory, model, uuid);
     }
 
+    @RequestMapping(method = RequestMethod.DELETE, consumes = {"text/uri-list"})
```
Comment (tdonohue) [inline dspace-server-webapp/src/main/java/org/dspace/app/rest/RestResourceController.java:1056]: @JensRoets-Atmire and @benbosman :  Unfortunately, I don't this this is valid.  A `DELETE` request cannot contain a body/data.

See the discussion about this in this StackOverflow: https://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request

The general consensus seems to be that one should *never* send a body in a `DELETE` request because, while the specs don't disallow it, some proxies may not be able to process it, and some clients may not be able to send it.  So, going down this path can cause issues in the long run.

Looking around to find a better way to achieve this, the most frequent idea appears to be to pass multiple ids/uris as *parameters* to the request.  So, possibly we could restructure this to be more like: `DELETE /bitstreams?id=[first-uuid]&id=[second-uuid]`.

The only other approach I've seen mentioned is that some APIs like AWS use a `POST` to send a batch of requests, including batch deletions.  Here's more on that concept https://stackoverflow.com/a/41539479/3750035

Pulling in @abollini into this discussion as well, as this seems to be a concept we have not yet tackled in our REST API & may require some discussion among us all.  I don't believe we support batch deletion, or any batch actions (other than PATCH which sometimes can batch several edits at once).

**Comment by tdonohue** [comment]
Moving this to 7.5... unfortunately I don't think we'll have time to resolve the redesign of this PR in time for 7.4, as I suspect it will require more thought/discussion

**Comment by abollini** [comment]
@JensRoets-Atmire @tdonohue  I just want to ping you about the last comment in the rest contract as we could be able to resume this work https://github.com/DSpace/RestContract/pull/203#issuecomment-1400193414

**Comment by tdonohue** [comment]
@JensRoets-Atmire & @benbosman  & @abollini : I'm OK with this work being restarted whenever someone is ready to pick it up.  For now, I've moved the PR to "Stalled / On Hold" on our board simply because no one appears to be working on a fix...and it's been that way since Sept.  As soon as a new solution is able to be designed/built, we can move this work forward.

File: dspace-server-webapp/src/test/java/org/dspace/app/rest/BitstreamRestRepositoryIT.java [hunk 2]
```diff
@@ -2279,6 +2291,223 @@ public void findByHandleAndFileNameForPublicItemWithEmbargoOnFile() throws Excep
...
+
+    public boolean bitstreamNotFound(String token, Bitstream ...bitstreams) throws Exception {
+        for (Bitstream bitstream : bitstreams) {
+            if (getClient(token).perform(get("/api/core/bitstreams/" + bitstream.getID()))
+                                .andReturn().getResponse().getStatus() != SC_NOT_FOUND) {
+                return false;
+            }
+        }
+        return true;
+    }
```
Comment (abollini) [inline dspace-server-webapp/src/test/java/org/dspace/app/rest/BitstreamRestRepositoryIT.java:2512]: tests with unpriviledged users and with authorized users that are not repository managers are missing

**Review by abollini — CHANGES_REQUESTED** [review]
thanks for this PR @JensRoets-Atmire . Please take a look to my inline comments

**Comment by tdonohue** [comment]
@JensRoets-Atmire : When you have the chance, please resolve the merge conflicts with this PR so that it is able to run automated tests again, etc.  This will likely require rebasing your work on the latest `main` or similar.

**Comment by jensvannerum** [comment]
@tdonohue @abollini  I updated this branch to the latest main and all checks seem to be succeeding. Please re-review my new changes and @Raf-atmire's comment on why I did not change the exception being thrown.

Also @JensRoets-Atmire is no longer a developer at Atmire, I took over this PR. Bit confusing since we have the same first name 😅

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/BitstreamRestRepository.java [hunk 3]
```diff
@@ -248,4 +255,25 @@ public BundleRest performBitstreamMove(Context context, Bitstream bitstream, Bun
...
+    /**
+     * Method that will transform the provided PATCH json body into a list of operations.
+     * The operations will be handled by a supporting class resolved by the
+     * {@link org.dspace.app.rest.repository.patch.ResourcePatch#patch} method.
+     *
+     * @param context The context
+     * @param jsonNode the json body provided from the request body
+     */
+    public void patchBitstreamsInBulk(Context context, JsonNode jsonNode) throws SQLException {
+        int operationsLimit = configurationService.getIntProperty("patch.operations.limit", 1000);
```
Comment (tdonohue) [inline dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/BitstreamRestRepository.java:268]: This appears to be a new configuration, but it's not added to any of the *.cfg files?  It should be added to our configs and documented there.

We may want to rename this `rest.patch.operations.limit` and add it to the `rest.cfg` file (in the top section for the "RESTv7", perhaps just before all the `rest.properties.exposed` values).

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/patch/operation/BitstreamRemoveOperation.java [hunk 4]
```diff
@@ -0,0 +1,65 @@
...
+    BitstreamService bitstreamService;
+    public static final String OPERATION_PATH_BITSTREAM_REMOVE = "/bitstreams/";
+
+    @Override
+    public Bitstream perform(Context context, Bitstream resource, Operation operation) throws SQLException {
+        String bitstreamIDtoDelete = operation.getPath().replace(OPERATION_PATH_BITSTREAM_REMOVE, "");
+        Bitstream bitstreamToDelete = bitstreamService.find(context, UUID.fromString(bitstreamIDtoDelete));
+        if (bitstreamToDelete == null) {
+            throw new RESTBitstreamNotFoundException(bitstreamIDtoDelete);
+        }
```
[the remark this answers is not in the document]
Comment (tdonohue) [reply dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/patch/operation/BitstreamRemoveOperation.java:54]: @Raf-atmire : I agree with you that I'd rather this throw an error for now if the Bitstream is not found.   While I'm not strongly againts @abollini 's idea, I don't think it's necessary at this time...and I'd also prefer the error approach for now. (If we ever find a reason to change this later, we can obviously do so in a later PR)

**Review by tdonohue — COMMENTED** [review]
@jensvannerum : Thanks for the updates!  I think this is looking very good and it aligns with the REST Contract.  I'm nearly a +1, but I have a minor inline comment below to be addressed (the new config is not documented or in our `rest.cfg`).

I have not yet tested this because I'm assuming it should be tested with a `dspace-angular` PR which uses this `PATCH`. (Is that PR coming soon?)  But, the ITs look correct to me and verify the feature should work as expected.

I've also verified that @abollini 's feedback looks to have been addressed. So, @abollini , I've asked you for a re-review.

Once the `dspace-angular` PR is ready, I'd be glad to test this alongside that PR.

**Comment by tdonohue** [comment]
@JensRoets-Atmire or @benbosman or @artlowel  :  Is there a frontend PR corresponding to this backend PR?   I went to test this again, and I'm finding there's still not a frontend PR which uses these new endpoints.  If that's coming still, we'd need it as soon as reasonably possible to get this ready in time for 7.6.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @JensRoets-Atmire !  Tested this today with the frontend PR and it's working as expected.  The PATCH command also looks correct based on the agreed upon Contract.  Tests look good as well and prove it should work properly for full admins as well as community/collection admins.

**Comment by tdonohue** [comment]
@abollini : I believe all your feedback has been addressed.  I'll give you until end-of-day on Monday to take a look, and then I'll merge this.  Thanks!
