### PR TITLE
Removal of automatically added 'query' parameter for entries subpath

### LINKED ISSUE #2954: External Sources "entries" subpath should not include "query" parameter by default
**Describe the bug**
Discovered in testing https://github.com/DSpace/dspace-angular/pull/715#issuecomment-686569302

The `/api/integration/externalsources/[source]` endpoint always prepends an empty `query` parameter in the REST API's `link` to the `entries`.

This is unexpected behavior to the Angular UI, and it results in the Angular UI sending requests to the REST API that include *two query parameters*, e.g. `http://localhost:8080/server/api/integration/externalsources/[source]/entries?query=&sort=score,DESC&page=0&size=10&query=[actual query]`  (Notice that the first and last parameter are both a `query` parameter.  The first is prepended by the REST API, while the last is the actual query sent by the Angular UI.)

**To Reproduce**

This can be seen on the demo site, e.g. https://dspace7.4science.cloud/server/#https://dspace7.4science.cloud/server/api/integration/externalsources/orcidV2  (Look at the `entries` link returned by that response, and you'll see it includes an empty `query` parameter.)

**Expected behavior**
The REST API should not prepend this parameter.  Instead, the `entries` link should include no parameters by default.

### PR DESCRIPTION
**Pull request by jonas-atmire**
## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes [#2954](https://github.com/DSpace/DSpace/issues/2954)

## Description
This PR removes the automatically added "query" parameter that is prepended on the REST API's link to the entries. This makes sure that the related Angular UI doesn't add it's own 'query' parameter, resulting in two query params -> Breaking the functionality
## Instructions for Reviewers

* In the [ExternalSourceHalLinkFactory](https://github.com/DSpace/DSpace/compare/main...atmire:74271-External-sources-query-param-issue?expand=1#diff-b5b52aa15f3babdf9b5b5d98f6a2b8118e21d8ae830371cc9b81c403890b1337R34), the link was created using the buildLink method rather than the previously used getMethodOn() method
    * The reason for this is that the link generated by spring getMethod on and will add the mandatory param automatically
* The tests were added to make sure that the JSON path contains the entries link without the query parameter

To reproduce this, go to an externalsources endpoint (ie, `server/api/integration/externalsources/orcidV2`), and check out the entries link returned by that response. This should NOT include the query parameter

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Review by abollini — CHANGES_REQUESTED** [review]
Hi @jonas-atmire thanks to look to that.
I'm not sure how to proceed with this PR as it seems to me that we are not using the concept of templated URI in Spring hateoas that is purposed for these scenario
https://docs.spring.io/spring-hateoas/docs/current/reference/html/#fundamentals.uri-templates
The REST should return an URL containing `{?query}` and an additional `templated: true` attribute in the link so that the client can understand that a query parameter is expected and can be used to build the final link.
How much work would be required on the REST side to start to support such characteristic? how this would impact angular? @tdonohue  I would appreciate your input here

If we decide to stay without template URI, for now or for 7.0 at all, as this PR is a bug fix I would appreciate a test showing the current issue so that we can avoid regression in future.

File: dspace-server-webapp/src/test/java/org/dspace/app/rest/matcher/ExternalSourceMatcher.java [hunk 1]
```diff
@@ -22,7 +23,9 @@ private ExternalSourceMatcher() {
         return allOf(
             hasJsonPath("$.id", is(id)),
             hasJsonPath("$.name", is(name)),
-            hasJsonPath("$.hierarchical", is(hierarchical))
+            hasJsonPath("$.hierarchical", is(hierarchical)),
+            hasJsonPath("$._links.entries.href", is(REST_SERVER_URL +
+                                                            "integration/externalsources/" + name + "/entries"))
```
Comment (abollini) [inline dspace-server-webapp/src/test/java/org/dspace/app/rest/matcher/ExternalSourceMatcher.java:28]: this actually demonstrate the existence of the bug and the solution, so if we wan't to deal with URI template this PR can be accepted

**Comment by tdonohue** [comment]
@jonas-atmire and @abollini : Just adding a quick note here.  At a glance, I think @abollini is correct, that **ideally** this should be a templated URI/link.  For reference, we do have a few examples of templated links in the codebase already...namely these two endpoints:

* `/api/dso/find{?uuid}` - which is implemented in [`UUIDLookupRestController`](https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/UUIDLookupRestController.java) with tests in [`UUIDLookupRestControllerIT`](https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/test/java/org/dspace/app/rest/UUIDLookupRestControllerIT.java)
* `/api/pid/find{?id}` - which is implemented in [`IdentifierRestController`](https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/IdentifierRestController.java) with tests in [`IdentifierRestControllerIT`](https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/test/java/org/dspace/app/rest/IdentifierRestControllerIT.java)

However, I'll admit, I also do not know how the Angular UI will handle this sort of change. In other words, if we update these links to be of the form `/api/integration/externalsources/orcidV2{?query}`, will the UI be able to properly add in the query param similar to the above endpoints?

@jonas-atmire would you be able to investigate this further to see what this would take & possibly provide an estimate? It may also be good to touch base with @artlowel to get his feedback.

Overall, I agree with @abollini that this PR is "ok"....but it's not entirely aligned with Spring HATEOAS.  My preference would be to align with Spring HATEOAS if possible...however, if this effort will require major work, we could schedule this cleanup (in a separate ticket) for a later date (e.g. for 7.1 or 7.2).

**Comment by jonas-atmire** [comment]
@abollini / @tdonohue 
I've checked this with @artlowel, and he mentions that this also would require additional Angular related work to handle this. (while mentioning that this is a good solution 😉 )

This requires some additional work, since, for the previous example mentioned by Tim `/api/dso/find{?uuid}`, a [custom 'find/replace'](https://github.com/DSpace/dspace-angular/blob/main/src/app/core/data/dso-redirect-data.service.ts#L51-L52) is used in Angular that handles this.
Simply updating the 'ExternalSourceHalLinkFactory' would need updates in the related Angular code. 

IMO: We should avoid 'handling' this for this specific case, but rather, create a separate issue that takes a deep dive into the possibilities of the templated URIs, where they are used, the possible pitfalls, and any other related improvement that we could come across.
To avoid possibly going over it too fast while estimating, and missing possible problems I'll create 2 new issue so we can follow up on this separately from this PR (So we already can get the current problem out of the way for the time being)
Please note that I have simply currently created WIP issues, so if anyone knows of more specific use cases that we could take up in those issue, feel free to add them accordingly:
* https://github.com/DSpace/dspace-angular/issues/980
* https://github.com/DSpace/DSpace/issues/3108

**Review by tdonohue — APPROVED** [review]
👍 Thanks @jonas-atmire for the analysis here.  I agree with you that we should treat the larger issue of templated HAL Link support as a separate ticket...so thanks for creating those tickets (I've tentatively scheduled both for 7.1, but if we all find them to be higher priority we could move them up).

I've tested this PR & reviewed it.  It fixes the problem described, so I think it's a "good enough" solution until broader support for HAL templates is added.  So, I'm +1 this as-is.  

@abollini could you give this a second look & let us know if this can be merged despite your "requested changes" prior review?

**Review by abollini — APPROVED** [review]

**Comment by abollini** [comment]
I'm ok with this solution for the specific issue and dealing later with the uri link template. Thanks @jonas-atmire to have investigate and created the issues for that
