### PR TITLE
Downloading restricted bitstreams does not work when opening a new tab/window

### LINKED ISSUE #1809: Downloading restricted bitstreams does not work when opening a new tab/window
**Describe the bug**

This issue was previously described in #924, but has reappeared (or perhaps was never fully solved)

When attempting to download an access restricted bitstream in a new tab/window, you will ALWAYS see a 401 "Whitelabel Error Page".  If you look at the backend logs, you'll see something like this (notice the 403 on the /shortlivedtokens endpoint followed by the 401 which is returned to the user)
```
2022-09-02 16:34:58,058 INFO  109b29a1-ab54-41b1-9ad3-3367a846504a 14181de8-5060-43df-aac4-0902b2689d7b org.dspace.app.r
est.utils.DSpaceAPIRequestLoggingFilter @ Before request [GET /server/api/authn/shortlivedtokens] originated from /bitst
reams/56279468-a4af-40e0-a6dc-71324803fa38/download
2022-09-02 16:34:58,060 WARN  109b29a1-ab54-41b1-9ad3-3367a846504a 14181de8-5060-43df-aac4-0902b2689d7b org.dspace.app.r
est.exception.DSpaceApiExceptionControllerAdvice @ Access is denied (status:403 exception: Requests to this endpoint sho
uld be made from a trusted IP address. at: org.dspace.app.rest.AuthenticationRestController.shortLivedTokenViaGet(Authen
ticationRestController.java:232))
2022-09-02 16:34:58,269 INFO  unknown fdcf354a-d940-47c9-8731-0e9ad02f95d0 org.dspace.app.rest.utils.DSpaceAPIRequestLog
gingFilter @ Before request [GET /server/api/core/bitstreams/56279468-a4af-40e0-a6dc-71324803fa38/content] originated fr
om https://tim-dspace.loca.lt/
2022-09-02 16:34:58,293 WARN  unknown fdcf354a-d940-47c9-8731-0e9ad02f95d0 org.dspace.app.rest.exception.DSpaceApiExcept
ionControllerAdvice @ Authentication is required (status:401 exception: Access is denied at: org.springframework.securit
y.access.vote.AffirmativeBased.decide(AffirmativeBased.java:73))
```

**To Reproduce**

This issue appears to ONLY be reproducible on a public, "production" site. It doesn't seem to be reproducible when running the frontend on http://localhost:4000 ... likely because localhost is considered a "trusted IP" so that the above `/shortlivedtoken` request succeeds.  

However, it is reproducible on https://demo7.dspace.org.  It is also possible to reproduce it locally if you run the UI (and backend) behind a public proxy (like https://localtunnel.me) and then access the UI via that proxy URL.

There are several ways to reproduce this error in the UI:
1. One way is via the Submission/Workflow process.
    * Simply create a new submission & upload a file.  Then attempt to download the file you just uploaded (from the submission form).  You'll receive this 401 error as the download is opened in a new tab.  This bug is also described in https://github.com/DSpace/DSpace/issues/8378
2. Another way is to create an Item with an access restricted bitstream.  Then *authenticate* into DSpace, copy the bitstream download URL and paste it into a new tab (or Ctrl + Click the bitstream should open it in a new tab).  You'll receive the same 401 error.
3. A third way is to download an access-restricted PDF.  Click the back button in your browser and you'll see this same 401 error.  This bug is described in #1743

These three issues all appear to be related to the same problem, that it's currently not possible to download restricted bitstreams in a new tab.

**Expected behavior**
Assuming you have an active authenticated session, it should be possible to download bitstreams in a new tab.  We even have code to support this via the `isBlank` flag in the [`file-download-link.component.ts`](https://github.com/DSpace/dspace-angular/blob/main/src/app/shared/file-download-link/file-download-link.component.ts#L38).  However, this `isBlank` flag only works for non-restricted bitstreams.

**Related work**
Related directly to https://github.com/DSpace/DSpace/issues/8378 and #1743 .  Fixing this bug would likely fix both of those tickets as well.

### PR DESCRIPTION
**Pull request by MarieVerdonck**
## References
* Fixes https://github.com/DSpace/DSpace/issues/8378
* Fixes https://github.com/DSpace/dspace-angular/issues/1809
* Replaced by https://github.com/DSpace/dspace-angular/pull/2076

## Description
**UPDATE: This removes the ability to `GET /api/authn/shortlivedtokens`, as now POST is used at all times.**

Since [this change](https://github.com/DSpace/dspace-angular/commit/ff4bd59de0d280121420d5fd4721891ac30f7e6f) the server side angular rendering now uses the GET endpoint for `/api/authn/shortlivedtokens` instead of the POST, so the
[POST endpoint](https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/AuthenticationRestController.java#L209): no trusted proxy check
[GET endpoint](https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/AuthenticationRestController.java#L231): trusted proxy check

The IP of the node process/angular that is in trusted proxies list may get added to this request when sent from the node server in the `X-forwarded-for` heading, testing on servers (with apache setup before tomcat) showed that once it reached this endpoint the IP of node/angular was no longer present in the request, not in remote address, nor in `X-forwarded-for` header.

Since previously the proxy check was not done either (since used POST endpoint), and we saw no real reason to keep it, the proxy check has been removed.

## Instructions for Reviewers
- During submission add a file, clicking the download button in submission form should now again successfully open file in new tab
- Set a bitstream as restricted (e.g. embargoed) => On item page open the file in new tab by shift clicking => should again open successfully in new tab

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by tdonohue — COMMENTED** [review]
@MarieVerdonck :  I think this requires more discussion, as I think this PR might accidentally open the `GET /api/authn/shortlivedtokens` to CSRF-style attacks.

This PR essentially appears to "undo" the changes @KevinVdV made in #3223 when he created this `GET` endpoint.  From what I recall, the original reasons for the `GET` endpoint having IP-related checks was because `GET` is inherently _less secure_ than `POST`.   

All `POST` requests require CSRF-protection in DSpace 7.  However, `GET` requests _bypass_ that CSRF-protection.

By allowing `GET` from any IP address, I think this opens sites to a possible vulnerability of this sort:
* Suppose an attacker uses a phishing email or similar, to trick a DSpace user to click a link that sends them to `GET /api/authn/shortlivedtokens`.
* The attacker could then potentially intercept the "shortlivedtoken" which temporarily provides them with the same rights as that DSpace user. (Technically, they might not "intercept" the token, but it could be a bit of Javascript which the DSpace user unknowingly executes which performs the GET to retrieve the token, and then does something with that token, like change the user's password)
* (NOTE: This same attack isn't possible via `POST` because `POST` requests all require CSRF tokens to verify that the request is "trusted")

There obviously is some inherent "protection" in that the shortlivedtoken only works for 2 seconds (based on the default value of `jwt.shortLived.token.expiration`). But, with an automated script, there's a lot that could be done in just 2 seconds if you trick someone to generate a "shortlivedtoken" for you.

Therefore, I think the intention of the "Trusted Proxy" limitation was to **ensure** that a `GET /api/authn/shortlivedtoken` request could ONLY BE MADE from a trusted IP address (namely only by server-side Node.js).

@KevinVdV, @benbosman and @artlowel  : I'd like to draw your attention to this PR...as I want to be sure this (small) change is closely analyzed.  I'm personally worried this PR might accidentally introduce a vulnerability (as described above)

UPDATE: One option here might be to see if this specific `GET /api/authn/shortlivedtoken` request could be configured to also require CSRF tokens.  That'd make it different from all other GET requests, but maybe it's a reasonable way to verify that the request is "trusted" without basing it on an IP address.

**Comment by benbosman** [comment]
@tdonohue thanks for your feedback.

It would be possible to add CSRF tokens. That would require:
* Updating REST to reject the call when the cookie is present
* Updating Angular to send the CSRF it retrieves from e.g. `/server/api`

This should be realistic to adjust, I'm just not sure whether it can be adjusted in time.
I assume this can be fixed later as well if it doesn't make the deadline, since the CSRF token only has limited impact (any attacker able to intercept the shortlivedtoken, can also add a CSRF token if necessary)

We initially focussed on ensuring that the requests came from the trusted node, but noticed that that IP is frequently omitted from the X-Forwarded-For headers, depending on the setup. That was not a reliable solution.

**Comment by tdonohue** [comment]
@benbosman : I'm worried you may have misunderstood my concern, as I don't think this could be "fixed later".

The security vulnerability I see in this PR is a possible CSRF attack.  Just for reference, here's a diagramed example: https://learn.snyk.io/lessons/csrf-attack/javascript/   I believe with the changes in this PR, a CSRF-style attack could be performed on DSpace 7 as follows:

1. Hacker creates a malicious site with embedded malicious Javascript, which does something like this:
    * First, it calls `GET /api/authn/shortlivedtoken`
    * Then it uses the shortlivedtoken to gain access to access restricted information from DSpace (e.g. download an access restricted bitstream, change a user's password, or even potentially call DELETE on some object.)
    * My assumption is this malicious code would likely take <2 seconds to process (as the default lifespan of a shortlivedtoken is 2 seconds)
2. Hacker then tricks someone who is already authenticated in DSpace to visit the malicious site.  Usually this would be by tricking them to click on a link in an email or similar.
3. Assuming the user clicks on the link, the code embedded in the malicious site would run in the victim's browser.  If the victim happens to be logged into DSpace at that moment, the attack is likely to succeed:
    * Because `GET /api/authn/shortlivedtoken` is no longer limited by IP, it would now be able to run in the victim's browser as that logged in user.
    * Then the malicious Javascript in the victim's browser would have that shortlivedtoken to perform other actions as defined by the Hacker.  (NOTE however that the Hacker themselves may never "intercept" or see the shortlivedtoken. The important part is that the hacker's Javascript *code* running in the victim's browser **can see the shortlivedtoken**.)

On `main`, we protect against this scenario by limiting `GET /api/authn/shortlivedtoken` by IP address... that way the initial `GET` call would be immediately blocked (as we only allow the IP address of the UI by default).  If we remove that protection, we need a new way to avoid a malicious site being able to call this endpoint.

My suggestion was we could require a CSRF token to call `GET /api/authn/shortlivedtoken` (in the same way that `POST /api/authn/shortlivedtoken` requires a CSRF token).  I believe this **would** protect us because the following would occur:
* Suppose a logged in DSpace user is tricked into visiting that malicious website.
* The malicious website runs `GET /api/authn/shortlivedtoken`.  In this scenario, that call will always *FAIL* the CSRF token check, because you need two things for CSRF protection to succeed.  You need the token to be sent to the DSpace backend *both* in the `X-XSRF-TOKEN` header and in the `DSPACE-XSRF-COOKIE` cookie.  (This is a [double submit cookie](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#double-submit-cookie) type of protection.) In this scenario the malicious site cannot predict what the (previously set) CSRF token may be & they cannot read it from the victim's in-browser cookie because that cookie is HTTPOnly (meaning it's inaccessible to JavaScript, including inaccessible from our own UI).

So, unless I'm missing something, I don't think we can move this PR forward as-is.  I think it must have a new form of protection for the `GET /api/authn/shortlivedtoken` endpoint if we are removing the IP-address based protection.

**Comment by benbosman** [comment]
Thanks for the update Tim,
I did assume the hacker would be able to see the response of the short live token.

I would indeed expect that CORS would block this GET request.
We'll check whether we can create an IT for that, or otherwise check whether we can add the CSRF cookie

**Comment by tdonohue** [comment]
@benbosman : Sounds good. My main concern here is that I'm not convinced yet that this `GET /api/authn/shortlivedtoken` will trigger CORS.  CORS preflight checks are not triggered for a "simple request"... and I'm worried this endpoint might be possible to call via a "simple request".  For more on this see https://www.baeldung.com/cs/cors-preflight-requests

However, I fully agree with you that if we can *prove* this GET endpoint is not vulnerable to attack via ITs or similar, we can move forward.  I'm just stressing that we added an IP-check to this endpoint in the first place for security purposes.  We now have to prove that this endpoint is secure without that IP-check **or** find a new way to secure it (whether that's CSRF checks or a new code to manually verify it comes from a trusted `Origin` or some other similar solution).

**Comment by tdonohue** [comment]
Sounds good @benbosman and thanks for the update!  If, for some reason, the CSRF token approach is complex, I think a possible fallback solution is just to replace the IP check with a version of `isRequestFromTrustedProxy()` that verifies that the `Origin` header matches an origin listed in `rest.cors.allowed-origins`.  This would minimally ensure this GET is being requested from a trusted site listed in `rest.cors.allowed-origins`.

**Comment by MarieVerdonck** [comment]
@tdonohue In testing it showed the node server request to the GET shortlivedtokens  endpoint as it was didn't contain an Origin header either (at least not one that made it to the endpoint) so this wasn't a possibility to check this against `rest.cors.allowed-origins`

So the CSRF check approach (to the POST version of endpoint) from the node server was implemented in https://github.com/DSpace/dspace-angular/pull/2076. This is a replacement for this PR suggestion.

I've altered this PR to remove the GET endpoint for shortlivedtokens (& related test) since they would no longer be needed if https://github.com/DSpace/dspace-angular/pull/2076 meets approval.

File: dspace-api/src/main/java/org/dspace/service/ClientInfoService.java [hunk 1]
```diff
@@ -43,4 +43,13 @@ public interface ClientInfoService {
...
     boolean isRequestFromTrustedProxy(String ipAddress);
 
+    /**
+     * Whether a request is from a trusted proxy or not. Only returns true if trusted proxies are specified
+     * and the ipAddress (remote address or from X-forwarded-for header) is contained in those proxies. False in all
+     * other cases
+     * @param request The request to check if it is from trusted proxy
+     * @return true if trusted, false otherwise
+     */
+    boolean isRequestFromTrustedProxy(HttpServletRequest request);
```
Comment (tdonohue) [inline dspace-api/src/main/java/org/dspace/service/ClientInfoService.java:53]: This new `isRequestFromTrustedProxy` method is not used anywhere.  I believe it can be removed from here & from `ClientInfoServiceImpl`, as it's not necessary anymore.

**Review by tdonohue — COMMENTED** [review]
@MarieVerdonck : Thanks for getting this updated!  Overall, I'm +1 the changes here and they look good.  However, it looks like you've accidentally forgotten to remove unnecessary changes to `ClientInfoService` & `ClientInfoServiceImpl`.  Once those are removed, then I'm +1 this PR as the rest of it looks good.

**Comment by MarieVerdonck** [comment]
@tdonohue Reset to only last commit, since other changes weren't needed.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @MarieVerdonck ! This looks good now.

**Comment by tdonohue** [comment]
Per this removal of `GET /api/authn/shortlivedtokens`, I've just updated the REST Contract at https://github.com/DSpace/RestContract/blob/main/authentication.md
