### PR TITLE
Fixes access information at file level when embargoes are expired

### LINKED ISSUE #10529: In OpenAIRE OAI crosswalk, embargoe at the bitstream level (oaire:file) are not handled properly.
## Describe the bug
If a temporary embargo is set on a bitstream of an item, when it expires, the information is not updated in the OpenAIRE OAI records. The bitstream is still mentionned as under embargo.

This is only true for the File Location (oaire:file, accessRightsURI attribute). The Access Rights (datacite:rights) element is correctly handled and updated when an embargo is lifted.

For exemple, if an item that as the following policy (image below) at the bitstream level (embargo date has passed), 

Image

It will still be flagged as embargoed in Openaire OAI as shown below: 

Image

"http://purl.org/coar/access_right/c_f1cf" is the COAR Access rights URI for embargoe access.

## To Reproduce
1. Edit an item and apply a bitstream policy with an embargo end date before today (ex: 2025-01-01)
2. Rebuild OAI index
3. Look at the edited record in OAI OpenAIRE context: [serverURL]/server/oai/openaire4?verb=GetRecord&metadataPrefix=oai_openaire&identifier=oai:[item OAI identifier]

## Expected behavior
If an embargo is lifted, the OAI OpenAIRE records should display the file as open access.

### PR DESCRIPTION
**Pull request by amgciadev**
## References
* Fixes #10529 

## Description
Minor fix to check if embargoes at the bitstream level are expired, and if so, then the start date info at the policy level is not include to allow for status to be calculated corrected

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome).
However, reviewers may request that you complete any actions in this list if you have not done so. If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [X] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [X] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [X] My PR **passes Checkstyle** validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [X] My PR **includes Javadoc** for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [X] My PR **passes all tests and includes new/updated Unit or Integration Tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [X] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [X] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [X] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [X] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [X] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by amgciadev** [comment]
This fix is also applicable to the Rioxx crosswalk, as it also makes use of resource policies

File: dspace-oai/src/main/java/org/dspace/xoai/util/ItemUtils.java [hunk 1]
```diff
@@ -194,7 +195,8 @@ private static void addResourcePolicyInformation(Context context, Bitstream bits
             resourcePolicyEl.getField().add(createValue("group", groupName));
             resourcePolicyEl.getField().add(createValue("user", user));
             resourcePolicyEl.getField().add(createValue("action", action));
-            if (startDate != null) {
+            // Only add start-date if group is different to anonymous, or there is an active embargo
+            if (startDate != null && (!groupName.equals(Group.ANONYMOUS) || startDate.isAfter(LocalDate.now()))) {
```
Comment (kshepherd) [inline dspace-oai/src/main/java/org/dspace/xoai/util/ItemUtils.java:199]: I'm not sure I fully get the group name check... I would have thought the start date is actually most useful only if it results in a public (anonymous) read, e.g. `startDate != null && groupName.equals(Group.ANONYMOUS) && startDate.isAfter(LocalDate.now())` ... is there a reason we'd want to see a start date in the past because the READ group is not ANONYMOUS?

**Review by kshepherd — COMMENTED** [review]
Looks good, I just had a question about the groupName check as I didn't quite understand the relevance

File: dspace-oai/src/main/java/org/dspace/xoai/util/ItemUtils.java (hunk 1 above)
Comment (amgciadev) [reply dspace-oai/src/main/java/org/dspace/xoai/util/ItemUtils.java:199]: Hi @kshepherd, I added the group check as if the group is not anonymous, the policy would be adding an access restriction rather than an embargo, but I think you are right in that in those cases we do not probably need the start date to check whether something is restricted or not. Let me re-check the crosswalk file itself - where this information is used to determine the access level

Comment (amgciadev) [reply dspace-oai/src/main/java/org/dspace/xoai/util/ItemUtils.java:199]: I think we do not need the group check as I've put it: I'll replace with just `startDate.isAfter(LocalDate.now()` as it may still be useful to have the start date for all groups (e.g. a policy for an admin group that will take effect in the future, therefore the item may be temporarily open, and then restricted after the start date)

**Review by kshepherd — APPROVED** [review]
thanks @amgciadev , looks great! merging with one approval

**Comment by kshepherd** [comment]
@amgciadev the backport for dspace-8_x fails to build because of the `Date` -> `LocalDate` and `SimpleDateFormat` -> `DateTimeFormatter` changes. So you might want to either push changes to the opened backport or open a manual backport PR.
