### PR TITLE
Fix 10740: Add more efficient Collection.findAuthorized() to improve performance of SWORDv2 servicedocument

### LINKED ISSUE #10740: (DS 7.6.1) SWORDv2 - Long times to get the servicedocument when are a significative number of collections
## Describe the bug
We have a repository,  comum.rcaap.pt , with 100 communities (Each community is an institution) with multiple subcommunities and a great number of collections (approximately 2000). The problem is the time to get the servicedocument in DS7 significantly compared to DS5 from 65 seconds to 30 minutes (It's only 1 user!!). As we have another service (cienciavitae.pt) that uses this mechanism to deposit and therefore is not acceptable! We have 2 more repositories where the times are 5 min and 10 min apprx. (700 collections and 900 collections) and before (DS5) were less than 1 minute. 

The problem is the number of collections and is seen the code below:

**List<Collection> cols = collectionService.findAuthorized(authContext, community, Constants.ADD);** (SwordAuthenticator)

We need to increase the connection timeout to swordv2 in apache to be able to use SWORDv2 functionality or cache the servicedocument. 
Now we disabled deposits in instances where more than 5 min is the time a user has to wait to get the servicedocument.

We also tested with an instance of DS9 and the problem exists but is slightly quicker! And we also tried using faster SSD disks but the problem persists!

## To Reproduce
1. An instance with a significant number of collection (say more than 600)
2. Make a curl command to get the sevicedocument
3. Wait

## Expected behavior
This shouldn't take more than 1-2 minutes to get the servicedocument. It was faster in DS5

## Related work
**It's only a suggestion.** 
It is possible to get the collection(s) for the user with deposit permissions faster but it's a straightforward query. And no other verifications are made. As I said it's only a suggestion.

select * from handle where resource_type_id = 3 AND resource_id in (
select dspace_object from resourcepolicy where epersongroup_id in (
select uuid from epersongroup where uuid in ( 
select eperson_group_id from epersongroup2eperson where eperson_id = (USER_UUID))))

### PR DESCRIPTION
**Pull request by fribeiro-fccn**
…dle the queries to get collections of the current user only

## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #10740 

## Description
We've noticed long waiting times to get the servicedocument in swordv2 when repositories have a complex structure with a great number of collections. This are relate to finAll (Collections) in swordv2 and the need to verify all  if the eperson has rights to deposit and in which Collections. This PR tries to solve this issue by getting only the collections where the eperson actually is defined (directly or added to a group).

## Instructions for Reviewers

List of changes in this PR:
* First, the method getAllowedCollections in swordv2 was modified and a new argument is passed: an EPerson. 
* Added a new method (findAuthorized) in CollectionService and a new method (findAuthorizedByEPerson) in CollectionDAO. 

The behaviour of the new findAuthorized is similar to the previous one except it will only get all collections if the org.dspace.content.Collection.findAuthorizedPerformanceOptimize is set to false (it will get all Collections) and, if community is not null, follows the expeted behaviour to gel the collection of that community, The default now is: get only the collections where the EPerson is defined.

We tried to use existing methods and combine them to get the same results as the new one defined in the DAO class. But we had correct values when using this new method which uses a NativeQuery to get all collection for the logged EPerson only.

A Test is also provided in CollectionTest class: testAuthorizedByEPerson.

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome).
However, reviewers may request that you complete any actions in this list if you have not done so. If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [ ] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [ ] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [ ] My PR **passes Checkstyle** validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [ ] My PR **includes Javadoc** for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [ ] My PR **passes all tests and includes new/updated Unit or Integration Tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [ ] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by paulo-graca** [comment]
@tdonohue I didn’t implement this, and I cannot take part in the review process of this PR since @fribeiro-fccn is a colleague of mine. That said, I believe the title may be somewhat misleading. This PR addresses a **serious performance issue** when retrieving collections into which a user can deposit items (via SWORD). In our case (though not exclusively), with a larger number of collections and layered permissions, the current solution takes **several minutes** just to return the result for `/swordv2/servicedocument`. With the tests performed so far on this PR, the response time is reduced to just a **few seconds**.

Since it adds/changes a collection service with a specific DAO implementation, I also believe this PR could improve other areas of the software where it is necessary to obtain the collections a user can deposit into—for example, during the submission process.

I would therefore suggest flagging this PR as "`performance/cache`" with "`high priority`".

File: dspace-api/src/main/java/org/dspace/content/dao/impl/CollectionDAOImpl.java [hunk 1]
```diff
@@ -157,6 +158,55 @@ public List<Collection> findAuthorizedByGroup(Context context, EPerson ePerson,
 
     }
 
+    /**
+     * Get all collections in the system. These are alphabetically sorted by
+     * collection name.
```
Comment (tdonohue) [inline dspace-api/src/main/java/org/dspace/content/dao/impl/CollectionDAOImpl.java]: This description doesn't seem accurate. This isn't returning all Collections, but seems to be searching for Collections that this EPerson has specific access rights to (based on "actions" list)?  At least I think that's what's going on, so it needs a better description

File: dspace-api/src/main/java/org/dspace/content/dao/impl/CollectionDAOImpl.java [hunk 2]
```diff
@@ -157,6 +158,55 @@ public List<Collection> findAuthorizedByGroup(Context context, EPerson ePerson,
...
+     * @return the collections the eperson is defined
+     * @throws SQLException if database error
+     */
+    @Override
+    public List<Collection> findAuthorizedByEPerson(Context context, EPerson ePerson, List<Integer> actions)
+            throws SQLException {
+
+        StringBuilder query = new StringBuilder();
+
+        query.append("WITH RECURSIVE parent(epgid) AS ( ");
```
Comment (tdonohue) [inline dspace-api/src/main/java/org/dspace/content/dao/impl/CollectionDAOImpl.java]: This query is highly complex and needs some inline comments to describe what it is doing and why.

File: dspace-api/src/main/java/org/dspace/content/dao/impl/CollectionDAOImpl.java [hunk 3]
```diff
@@ -157,6 +158,55 @@ public List<Collection> findAuthorizedByGroup(Context context, EPerson ePerson,
...
+            }
+            query.append("rp.action_id=").append(action);
+        }
+        query.append(" AND rp.resource_type_id=").append(Constants.COLLECTION);// only Collections
+        query.append(" AND ( ");
+        query.append("        rp.eperson_id = :eperson_id ");  // direct permission
+        query.append("        OR rp.epersongroup_id IN (SELECT epgid FROM parent) "); // permission via group
+        query.append("    )");
+
+        NativeQuery<Collection> nativeQuery = getHibernateSession(context).createNativeQuery(query
```
Comment (tdonohue) [inline dspace-api/src/main/java/org/dspace/content/dao/impl/CollectionDAOImpl.java]: Is there no way to achieve the same query in Hibernate?  We try to avoid using `createNativeQuery()` in DSpace, because you are bypassing Hibernate and writing direct SQL.

It looks like there are ways in Hibernate to potentially support "WITH RECURSIVE" queries (see https://vladmihalcea.com/hibernate-with-recursive-query/ as an example), which makes me wonder why we are using `createNativeQuery()`?

File: dspace-api/src/main/java/org/dspace/content/dao/CollectionDAO.java [hunk 4]
```diff
@@ -48,6 +48,19 @@ public List<Collection> findAll(Context context, MetadataField order, Integer li
 
     List<Collection> findAuthorizedByGroup(Context context, EPerson ePerson, List<Integer> actions) throws SQLException;
 
+    /**
+     * Get all collections in the system. These are alphabetically sorted by
+     * collection name.
```
Comment (tdonohue) [inline dspace-api/src/main/java/org/dspace/content/dao/CollectionDAO.java]: Same here, this description isn't accurate based on the code.

File: dspace-api/src/main/java/org/dspace/content/CollectionServiceImpl.java [hunk 5]
```diff
@@ -838,6 +838,29 @@ public List<Collection> findAuthorized(Context context, Community community, int
...
+
+        List<Integer> actions = new ArrayList<Integer>();
+        actions.add(actionID);
+
+        List<Collection> myCollections;
+
+        if (community != null) {
+            myCollections = community.getCollections();
+        } else {
+            myCollections = collectionDAO.findAuthorizedByEPerson(context, eperson, actions);
```
Comment (tdonohue) [inline dspace-api/src/main/java/org/dspace/content/CollectionServiceImpl.java]: I'm not understanding this method.  It seems like this code has two completely different behaviors.  If you pass in a `Community` then you just get all Collections in that Community.  But, if you don't pass in a `Community` then this limits your collections to only those which the EPerson has specific permissions on.

That behavior seems very messy to me.  In one scenario we are checking the EPerson permissions, but in the other we are **not checking permissions**.   

That means this method does two different things based on whether Community is passed in. Shouldn't we have two different methods here...one which returns all Collections in a Community, and the other which allows you to find the Collections which an EPerson has specific permissions on?

**Review by tdonohue — CHANGES_REQUESTED** [review]
@fribeiro-fccn : Thanks for this contribution. I gave this a quick code review.  I'm a little concerned about the code structure here, and I'd prefer if we could find a way to run this query via Hibernate.  See comments inline below.

File: dspace-api/src/main/java/org/dspace/content/dao/impl/CollectionDAOImpl.java (hunk 3 above)
Comment (mwoodiupui) [reply dspace-api/src/main/java/org/dspace/content/dao/impl/CollectionDAOImpl.java]: May I suggest considering a CriteriaQuery here, to replace this fragile string composition.

File: dspace-api/src/main/java/org/dspace/content/CollectionServiceImpl.java (hunk 5 above)
Comment (fribeiro-fccn) [reply dspace-api/src/main/java/org/dspace/content/CollectionServiceImpl.java]: Hi,
Yes, it's a bit confusing. The community comes in the SwordAuthenticator method getAllowedCollections which has a parameter - community (null except if swordv2-server.cfg expose-communities = false is set to true). 

The previous method findAuthorized in CollectionServiceImpl was called in swordAuthenticator as:
            // short cut by obtaining the collections to which the authenticated user can submit
            List<Collection> cols = collectionService.findAuthorized(
                authContext, community, Constants.ADD);

and in **CollectionServiceImp**l:
public List<Collection> findAuthorized(Context context, Community community, int actionID) throws SQLException {
        List<Collection> myResults = new ArrayList<>();
        List<Collection> myCollections;
        if (community != null) {
            myCollections = community.getCollections();
        } else {
            myCollections = findAll(context);
        }

Then, if community is not null then the collections of that community are retrieved otherwise it calls a findAll method retrieving all of the collections of the repository (This is the one who is taking long times to get and process all collections, especially in big repositories)

In this PR, I've decided not to mess with this method and created a new findAuthorized where a EPerson is also passed as a argument (come from authContext). the behavior is the same as the previous one. So, do the same as previously if community is not null get all collections of the community or else instead of the findAll it calls directly the findAuthorizedByEperson. 
Also, to maintain the need of the findAll method I've used a similar approach as in ficndAuthorizedOptimized when the org.dspace.content.Collection.findAuthorizedPerformanceOptimize is defined.

Note: I tried to use findAuthorizedOptimized defined in CollectionServiceImpl, but the tests I've done weren't the expected ones...

Comment (tdonohue) [reply dspace-api/src/main/java/org/dspace/content/CollectionServiceImpl.java]: @fribeiro-fccn : To clarify my concern, I'm not a fan of the behavior of this method because in *one scenario* the EPerson parameter is used, but in the other it is *ignored*.  That seems like odd behavior based on the purpose of the method.

If a Community param is *not* included, then a permissions check is performed using the `EPerson` param to determine which Collections you have permissions within

But, if a Community param *is included*, then the `EPerson` param is disregarded and you are given all Collections (of that Community) regardless of whether the EPerson has proper permissions in those Collections.

I find this behavior odd because you are only using the `EPerson` param if the `Community` is *not specified*...and that disobeys the description of this method which says (in JavaDocs) `get all authorized collections of the current EPerson`.

So, my proposal would be to *always* use the `EPerson` object.  If the `Community` is included as a param, then we should be returning Collections *within that Community* where the `EPerson` has autorization.  This would allow the `Community` param to act as a "filter", rather than resulting in entirely different behavior when the `Community` param is specified.

**Comment by fribeiro-fccn** [comment]
@tdonohue 

I made some changes, hopefully more in line with your comments.

1. Notes:

Made changes to findByEPersonGroupTypeIdAction to the return call (return list(context, criteriaQuery, false, ResourcePolicy.class, -1, -1);)

- Possible Issue: DAO methods not returning expected results in authorization flow.

- Context:

Some methods in CollectionServiceImpl and CollectionDAO—notably findAuthorized and findAuthorizedOptimized—do not return the expected list of authorized collections for a given EPerson.

- Findings:

findAuthorized(Context, EPerson, List<Integer>) returns empty results, even though it’s used throughout CollectionServiceImpl. So I've created Created findAuthorizedByEperson(...). This in CollectionDAO.
findAuthorizedOptimized (used via SwordAuthenticator) also fails to return the expected results. Several TODO comments suggest the authorization logic might be incomplete. This in CollectionServiceImpl.


2. ResourcePolicy Class Observation

Field:
```
@Column(name = "resource_type_id")
private int resourceTypeId;
```

This value is set in:

public void setdSpaceObject(DSpaceObject dSpaceObject) {
```
    this.dSpaceObject = dSpaceObject;
    this.resourceTypeId = dSpaceObject.getType();
}
```

However, there is no getter method for resourceTypeId.
Adding one (e.g., getResourceTypeId()) would improve API consistency, even though the same value can be indirectly accessed via dSpaceObject.getType().

3. Possible Bugs:

- **ResourcePolicyDAO:**

Methods findByEPersonGroupTypeIdAction() and findByTypeGroupActionExceptId() use:
return list(context, criteriaQuery, false, ResourcePolicy.class, 1, -1);

This limits results to one record. 

Should be changed to:
return list(context, criteriaQuery, false, ResourcePolicy.class, -1, -1);

File: dspace-api/src/test/java/org/dspace/content/CollectionTest.java [hunk 6]
```diff
@@ -1159,6 +1159,49 @@ public void testFindAuthorizedOptimized() throws Exception {
...
     }
 
+    /**
+     * Test of findAuthorizedEpersonAndGroups method, of class Collection.
+     * We create some collections and a user and groups and subgroups and add the user to one subgroup
+     * and one collection
+     * The parent group will be added to the other collection.
+     */
+    @Test
+    public void testFindAuthorizedByEPerson() throws Exception {
```
Comment (tdonohue) [inline dspace-api/src/test/java/org/dspace/content/CollectionTest.java:1169]: This test is a good start.  But, I'd also like to see a test the verifies permissions for a Community Administrator (since there's a good amount of code dealing with that scenario).  I'd also like to see a EPerson added who does *not* have a specific permission to a specific collection, to verify the negative.

So, basically, we need tests that prove all scenarios.  A person inheriting permissions from a parent group (which you already have), a person inheriting permissions as they have Community Admin, and a person who doesn't have the correct permissions (maybe they have a permissions for a *different* action than the one specified).

**Review by tdonohue — CHANGES_REQUESTED** [review]
@fribeiro-fccn : Thanks!  This is looking better to me now.  However, I'd like to request that we add a few more automated tests (see comment below) to fully verify the new functionality.

I've tested it manually, and it appears to be working. But, I'd appreciate it if we can add a few more tests as requested below.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @fribeiro-fccn !  This looks good to me now.  I appreciate that you added more tests to prove that other scenarios are working properly.

I'm going to squash merge this to make it easier to backport to all active branches (as the number of commits is large which can complicate backports).
