### PR TITLE
fix(#9774): Restore eager loading for CSRF tokens

### LINKED ISSUE #9774: CSRF Token is not generated/returned automatically after update to Spring Security 6 (in DSpace 8.0)
## Problem description

DSpace 8 comes with an update of **Spring Security** (from version 5 to 6). Spring Security 6 contains some changes in the CSRF handling that are listed here: https://docs.spring.io/spring-security/reference/servlet/exploits/csrf.html#migrating-to-spring-security-6

The changes in Spring Security result in a change of the behaviour of the DSpace REST API.

In **DSpace 7.6.2 (and below)** the response of a `GET` request on (almost) every REST endpoint contains a valid `DSPACE-XSRF-TOKEN` header. The value of this header can be used to create a successful `POST` request on `/api/authn/login`.

Example Request (on a running DS 7.6.2 instance):

```sh
curl -sS -D - 'https://api-depositonce.tu-berlin.de/server/api/' -o /dev/null
```

Excerpt from HTTP Response:

```sh
Set-Cookie: DSPACE-XSRF-COOKIE=b088b74c-9717-4c91-8371-688bbd6f0ff8; Path=/server; Secure; HttpOnly; SameSite=None
DSPACE-XSRF-TOKEN: b088b74c-9717-4c91-8371-688bbd6f0ff8
```

In DSpace 8 the response of this `GET` request does **not** contain the CSRF token and the `Set-Cookie` header with `DSPACE-XSRF-COOKIE`:

Example Request:

```sh
curl -sS -D - 'https://demo.dspace.org/server/api' -o /dev/null
```

In DSpace 7.6.2 a new REST endpoint was introduced to receive a valid CSRF token from the DS backend. The reponse of a `GET` request on `/api/security/csrf` contains a valid CSRF token in the `DSPACE-XSRF-TOKEN` header (both in DS 7.6.2 and DS 8.0):

```sh
curl -sS -D - 'https://demo.dspace.org/server/api/security/csrf' -o /dev/null
```

Excerpt from HTTP Response:

```sh
dspace-xsrf-token: 5e35e246-c942-4dc9-977c-40a2d4cc561c
set-cookie: DSPACE-XSRF-COOKIE=5e35e246-c942-4dc9-977c-40a2d4cc561c; Path=/server; Secure; HttpOnly; SameSite=None
set-cookie: DSPACE-XSRF-COOKIE=5e35e246-c942-4dc9-977c-40a2d4cc561c; Path=/server; Secure; HttpOnly; SameSite=None
```

(note that the `Set-Cookie` header is duplicated - this issue is addressed in #9773)

## How to proceed futher?

- Analyze the change in the DSpace API behaviour in DS 8 in more detail
- Adapt the way Spring Security is used to create / manage CSRF tokens and undo the change of the behaviour of the DS 8 API
- If this is not possible: add a note to https://github.com/DSpace/RestContract (and the DS 8 release notes) that there was a breaking change in the CSRF handling in DSpace 8 (this means that the implementation of DSpace API clients with respect to CSRF token handling has to be changed slightly)

### PR DESCRIPTION
**Pull request by JohnnyMendesC**
## References
* Fixes #9774

## Description
This pull request resolves a breaking change introduced in DSpace 8 where the DSPACE-XSRF-TOKEN was no longer automatically generated on most GET requests. The configuration for Spring Security is updated to restore the eager token loading behavior from DSpace 7, ensuring backward compatibility for REST API clients.

## Instructions for Reviewers
This PR modifies WebSecurityConfiguration.java to restore the automatic generation of CSRF tokens on GET requests, a behavior that existed in DSpace 7.x but was altered by the upgrade to Spring Security 6 in DSpace 8.x.

List of changes in this PR:
* In WebSecurityConfiguration.java, a CsrfTokenRequestAttributeHandler instance is now explicitly created and configured.
* By calling requestHandler.setCsrfRequestAttributeName(null), we opt-out of Spring Security's default "deferred loading" behavior.
* This configured handler is then passed to the .csrf() configuration chain, forcing the CSRF token to be eagerly loaded on every request, thus matching the previous, expected behavior.

How to test this PR:
### 1 - Before this change (on the main branch):
* Run DSpace(8, 9 or 10) and execute the following command: curl -i -X GET http://localhost:8080/server/api/core/communities
* Observe that the response headers **don't** contain DSPACE-XSRF-TOKEN.
image

### 2 - After this change (on the fix/9774-csrf-token-not-generated-spring-security-6 branch):
* Run DSpace and execute the same command: curl -i -X GET http://localhost:8080/server/api/core/communities
* Verify that the response headers **now include** the DSPACE-XSRF-TOKEN and Set-Cookie: DSPACE-XSRF-COOKIE headers, confirming the fix.
image

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome).
However, reviewers may request that you complete any actions in this list if you have not done so. If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR **passes Checkstyle** validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR **includes Javadoc** for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [ ] My PR **passes all tests and includes new/updated Unit or Integration Tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by saschaszott** [comment]
Thanks, @JohnnyMendesC! I can confirm that your PR provides a valid fix for the problem described in issue #9774.

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/security/WebSecurityConfiguration.java [hunk 1]
```diff
@@ -88,6 +88,17 @@ public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
         // Get the current AuthenticationManager (defined above) to apply filters below
         AuthenticationManager authenticationManager = authenticationManager();
 
+        // Create a custom CsrfTokenRequestHandler to restore the eager loading of the CSRF token.
+        // In DSpace 8+, the upgrade to Spring Security 6 changed the default behavior to "deferred loading",
+        // which meant the DSPACE-XSRF-TOKEN was no longer automatically sent on most GET requests.
+        // This was a breaking change for REST API clients expecting the DSpace 7.x behavior.
+        // <P>
```
Comment (saschaszott) [inline dspace-server-webapp/src/main/java/org/dspace/app/rest/security/WebSecurityConfiguration.java]: Why do we need this line (`<P>`)?

**Review by saschaszott — CHANGES_REQUESTED** [review]

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/security/WebSecurityConfiguration.java (hunk 1 above)
Comment (JohnnyMendesC) [reply dspace-server-webapp/src/main/java/org/dspace/app/rest/security/WebSecurityConfiguration.java]: Hi @saschaszott , thanks for the review and guidance!
I've removed the `<P>` tag and replaced it with a blank line for readability as you suggested. I've just pushed the update.
I'm really excited about this fix, as I'm hopeful this will be my first merged contribution to DSpace. 
Thanks again for your help!

Comment (saschaszott) [reply dspace-server-webapp/src/main/java/org/dspace/app/rest/security/WebSecurityConfiguration.java]: Thanks, @JohnnyMendesC . Looks good!

**Review by saschaszott — APPROVED** [review]

**Review by tdonohue — APPROVED** [review]
👍 Thanks @JohnnyMendesC !  This seems to work.  I've tested at the REST API level to verify that CSRF token is now returned on the first request.  Also tested the UI to verify this updated behavior doesn't negatively impact any of the features there (no issues found)
