### PR TITLE
proxies.trusted.ipranges fixes

### LINKED ISSUE #8393: proxies.trusted.ipranges not reliable for ranges
**Describe the bug**
proxies.trusted.ipranges uses the `IPTable` class.
This class doesn't support ranges with a broader net mask than /24 (last section differs)
It also defines a start and end, but the end is never used to determine the range

**Expected behavior**
IP ranges are correctly supported, and can be broad (instead of silently ignoring such config)

### PR DESCRIPTION
**Pull request by benbosman**
## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #8393

## Description
`proxies.trusted.ipranges` uses the `IPTable` class.
This class didn't support ranges with a broader net mask than /24 (last section differs)
It also defined a start and end, but the end is never used to determine the range

This has been refactored to use a `long` representation of an IP internally.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Review by abollini — APPROVED** [review]
Thanks @benbosman for you work on that. I have done a code review and everything look fine to me, new test seems to cover all the touched scenarios, previous test should guarantee us against regression

File: dspace-api/src/main/java/org/dspace/statistics/util/IPTable.java [hunk 1]
```diff
@@ -45,155 +79,131 @@ public class IPTable {
...
 
-            //now populate fourth place (* or value 0-254);
-
-            if (start.length == 3) {
-                third.add("*");
+            if (ip.contains("/")) {
+                String[] parts = ip.split("/");
+                try {
+                    byte[] octets = InetAddress.getByName(parts[0]).getAddress();
+                    long result = 0;
```
Comment (mwoodiupui) [inline dspace-api/src/main/java/org/dspace/statistics/util/IPTable.java:116]: long result = ipToLong(InetAddress.getByName(parts[0])); // instead of this duplication?

**Review by mwoodiupui — APPROVED** [review]
Looks correct.  Tests succeed.

File: dspace-api/src/main/java/org/dspace/statistics/util/IPTable.java (hunk 1 above)
Comment (tdonohue) [reply dspace-api/src/main/java/org/dspace/statistics/util/IPTable.java:116]: @benbosman : waiting for you to see this comment before merging this PR.  I think @mwoodiupui is correct that you could remove code duplication here by replacing lines 115-120 in `IPTable` with simply:
```
long result = ipToLong(InetAddress.getByName(parts[0]));
```
It looks to be a nice simplification...so, I'd appreciate it if we could add this simplification before merging.  Thanks!

**Comment by mwoodiupui** [comment]
Still looks correct, tests still pass.  Thanks!
