### PR TITLE
handle redirect for items not working - REST Implementation

### LINKED ISSUE #3113: Handle redirect for items not working
**Describe the bug**
The "pid" endpoint which is used to retrieve DSpace Objects based on a handle does not work for items.
The endpoint does however work to retrieve a collection/community when used with a handle.

TThis used to work when it was tested in angular PR [#934](https://github.com/DSpace/dspace-angular/pull/934).
There [do not seem to be any integration tests](https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/test/java/org/dspace/app/rest/IdentifierRestControllerIT.java) to verify the behavior for items, only for communities.

**To Reproduce**
Example: The item with ID [df376455-2790-434a-9957-5e1ba740fff9](https://dspace7.4science.cloud/server/api/core/items/df376455-2790-434a-9957-5e1ba740fff9) contains the handle '123456789/238'.
Therefore the following url should redirect to the corresponding item: https://dspace7.4science.cloud/server/api/pid/find?id=123456789%2F238
Instead it gives a 404 error.

**NOTE FROM TIM:** Note, this bug is ONLY reproducible if the Handle in question starts with a *different* prefix than the one specified in your `handle.prefix` setting.  If it has the *same* prefix, then the Handle redirect will work successfully.

**Expected behavior**
When the request is done with a valid item handle, the user should be redirected to the item page.

### PR DESCRIPTION
**Pull request by Raf-atmire**
## References
* Fixes https://github.com/DSpace/DSpace/issues/3113

## Description
This PR fixes the REST side for the above mentioned issue.
It'll take the identifier given in all the handleProviders and it'll remove any known prefixes like "hdl:". This will ensure that the actual handle is used in each resolve method.

## Instructions for Reviewers

List of changes in this PR:
* Added a method in the HandleService to strip the prefixes from the handles
* Used this method in each of the three HandleProviders in both the supports and resolve methods

How to test this PR:
* Build and deploy the code
* Call the `/api/pid/find?id=hdl:{handle}` endpoint
* Verify that a "Location" header is present in the response with the Item's location in it

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

File: dspace-api/src/main/java/org/dspace/handle/HandleServiceImpl.java [hunk 1]
```diff
@@ -376,4 +385,38 @@ protected String createId(Context context) throws SQLException {
     public int countTotal(Context context) throws SQLException {
         return handleDAO.countRows(context);
     }
+
+    public String formatHandle(String identifier) {
```
Comment (tdonohue) [inline dspace-api/src/main/java/org/dspace/handle/HandleServiceImpl.java:389]: Could we add a Unit Test to verify this is working as expected for all of the `IDENTIFIER_PATTERNS` you've defined?  Currently, we seem to only test that it works for "hdl:", and only from the REST API.  We should have some basic Unit tests for this method to ensure it returns the expected string when passed different `identifier` values.

Two other things to note about this method:
* I think it's improperly named. It's not *formatting* a Handle.  It's parsing the handle out of an identifier string. So, I think we should call this `parseHandle()` and describe it as "Parses/extracts the handle prefix/suffix from an identifier string"
* Also this needs an `@Override`

**Review by tdonohue — CHANGES_REQUESTED** [review]
@Raf-atmire : Gave this a quick code review (haven't tested yet).  I think the code looks good overall, but the new method in HandleServiceImpl should have Unit Tests to verify it works as expected.  Once those are added, I'll give this another look & test.

**UPDATE:** I've tested this PR now alongside the frontend PR (https://github.com/DSpace/dspace-angular/pull/1065).  It works great.  So, as soon as the missing Unit Tests are added, I think these can both be merged.

**Comment by tdonohue** [comment]
@ybnd : Just a quick note, unit tests are showing a missing license header in `HandleServiceTest.java`.  Once you add the standard DSpace header this error should go way.  (The tests themselves look to succeed though)

**Comment by ybnd** [comment]
@tdonohue oh shoot, sorry about that.

**Review by tdonohue — APPROVED** [review]
👍 Looks good now! Thanks @Raf-atmire and @ybnd !
