### PR TITLE
Clear primary bistream when it's deleted- Fix issue #9099

### LINKED ISSUE #9099: Deleted primary bitstream still referenced in the bundle
**Describe the bug**
Primary Bitstreams are used for Access Status calculations, but when the that bitstream is deleted, the bundle primary bitstream reference isn't changed. So, Access Status calculations will return wrong status.

**To Reproduce**
1. Create a new item
2. Upload several files into the item and fill the required data
3. Deposit the item
4. As an admin, Edit that Item and promote one bitstream to be Primary Bitstream (this will reference that bitstream at the bundle level)
5. Please take note of that bitstream's UUID 
6. Delete that bitstream that we promote to primary
7. Check the database (please consider your UUID here):
``` sql
SELECT * FROM bundle WHERE primary_bitstream_id='814aefff-4874-4a97-a7aa-b654172e7a40'
```

**Expected behavior**
Apparently nothing changes, but the deleted bitstream is still referenced as that bundle primary bitstream. It's hoped that, when a bitstream is deleted, also that bundle's primary bitstream reference is also removed. This issue is also present in older DSpace versions (like 5.X).

### PR DESCRIPTION
**Pull request by paulo-graca**
## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #9099

## Description
This PR fixes issue #9099.

## Instructions for Reviewers
The description for reviewing and testing it's on the issue #9099

**To Reproduce**
1. Create a new item
2. Upload several files into the item and fill the required data
3. Deposit the item
4. As an admin, Edit that Item and promote one bitstream to be Primary Bitstream (this will reference that bitstream at the bundle level)
5. Please take note of that bitstream's UUID 
6. Delete that bitstream that we promote to primary
7. Check the database (please consider your UUID here):
``` sql
SELECT * FROM bundle WHERE primary_bitstream_id='814aefff-4874-4a97-a7aa-b654172e7a40'
```
8. You should expect to see the `primary_bitstream_id` as `null`

List of changes in this PR:
* I've changed the bundle to force a setModified()
* I've created a new test to address the issue
* I've created a migration sql script to fix existing deleted primary bitstreams

### CODE REVIEW

File: dspace-api/src/test/java/org/dspace/content/BundleTest.java [hunk 1]
```diff
@@ -513,6 +513,41 @@ public void testRemoveBitstreamAuth() throws SQLException, AuthorizeException, I
...
+        //set a value different than default
+        File f = new File(testProps.get("test.bitstream").toString());
+        Bitstream bs = bitstreamService.create(context, new FileInputStream(f));
+        bundleService.addBitstream(context, b, bs);
+        b.setPrimaryBitstreamID(bs);
+        context.restoreAuthSystemState();
+
+        assertThat("testRemoveBitstreamAuthAndUnsetPrimaryBitstreamID 0", b.getPrimaryBitstream(), equalTo(bs));
+        //remove bitstream
+        bundleService.removeBitstream(context, b, bs);
```
Comment (toniprieto) [inline dspace-api/src/test/java/org/dspace/content/BundleTest.java:546]: I think it would be good to do a similar test but directly testing  `bitstreamService.delete(context, bs)` instead of `bundleService.removeBitstream(context, b, bs)`

**Review by toniprieto — APPROVED** [review]
Thanks @paulo-graca ! 

I just tested this PR and it works OK. The primary bitstream relation is correctly removed when the bitstream is deleted.

For testing the migration script I used a test instance with some primary bitstreams referenced to deleted bitstreams or that are not linked to the bundle and was able to verify that they were cleared correctly.

I used this SQL statement before and after the migration to verify that it did not remove any valid primary bitstream:

```
select count(*) from bundle b where primary_bitstream_id in
   (select uuid from bitstream bit where deleted is false and bit.uuid in
      (select bitstream_id from bundle2bitstream bb where bb.bundle_id = b.uuid));
```
I think this also fixes this issue: https://github.com/DSpace/DSpace/issues/7348

I have only added a comment about the test.

**Comment by alanorth** [comment]
Thanks @paulo-graca! This works as described. I tested on DSpace 7.6 by adding a bitstream, setting it as primary, and deleting it. Before the patch the bitstream ID remains referenced in the bundle. After the patch it is correctly removed.

I also see that the migration ran successfully. This is +1 by testing for me as well. Only remains to address review comments by @toniprieto.

**Comment by paulo-graca** [comment]
Thank you all for reviewing. I've just added the test to use bitstreamService to ensure delete also removes the primary bitstream.

File: dspace-api/src/test/java/org/dspace/content/BundleTest.java (hunk 1 above)
Comment (paulo-graca) [reply dspace-api/src/test/java/org/dspace/content/BundleTest.java:546]: Please check commit:
https://github.com/DSpace/DSpace/pull/9106/commits/e6d108a94e41e58d6d701f3ef0429fda438e6555

File: dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/postgres/V7.6_2023.10.12__Fix-deleted-primary-bitstreams.sql [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+-- Remove all primary bitstreams that are marked as deleted
+UPDATE bundle
+SET primary_bitstream_id = NULL
+WHERE primary_bitstream_id IN
+    ( SELECT bs.uuid
+           FROM bitstream AS bs
+           INNER JOIN bundle as bl ON bs.uuid = bl.primary_bitstream_id
+           WHERE bs.deleted IS TRUE );
+
+-- Remove all primary bitstreams that don't make part on bundle's bitstreams
```
Comment (alanorth) [inline dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/postgres/V7.6_2023.10.12__Fix-deleted-primary-bitstreams.sql:20]: @paulo-graca can you update the comment here? I don't understand what this migration is doing.

I _think_ it is checking for primary bitstream IDs that are not currently part of any bundle (ie, they were marked as primary bitstreams at one point, but are no longer).

Comment (paulo-graca) [reply dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/postgres/V7.6_2023.10.12__Fix-deleted-primary-bitstreams.sql:20]: Yes, that's right. Instead of saying "make part" I meant "belong". I will try to better explain what it does.

**Review by alanorth — APPROVED** [review]

**Comment by misilot** [comment]
> 
> I think this also fixes this issue: #7348
> 
> I have only added a comment about the test.

It does not fix the Foreign key constraint
