### PR TITLE
Fixes authentication issues involving Special Groups and various Authentication Methods 

### LINKED ISSUE #9226: Shibboleth special groups don't populate when IP authentication also used in 7.6.1
**Describe the bug**

When using IP-based groups assignment along with Shibboleth groups assignment, the Shibboleth groups do not get applied. This seems to be related to the if condition introduced in [PR #9130](https://github.com/DSpace/DSpace/pull/9130) for `dspace-api/src/main/java/org/dspace/authenticate/AuthenticationServiceImpl.java`.

Logs show the `getSpecialGroups` method of `dspace-api/src/main/java/org/dspace/authenticate/ShibAuthentication.java` only returning the cached special groups, and when investigated the cached special groups are only the ones from IP authentication. It never reaches the "Starting to determine special groups" log line to apply the Shibboleth-configured groups.

I don't know the code or authentication flows super well, but my best guess is that when `dspace-api/src/main/java/org/dspace/authenticate/AuthenticationServiceImpl.java` does the check to make sure the login type aligns with the context, it causes the Shibboleth groups to be applied later in the order, after the IP authentication groups have already been added to the context. Then in `dspace-api/src/main/java/org/dspace/authenticate/ShibAuthentication.java` the check on line 296 can only check if there's anything in the specialGroups in the context object, but doesn't know what authentication plugin put the special groups there to know if the Shibboleth plugin has already applied groups. It sees the groups from IP authentication and just returns the cached groups.

If I turn off the IPAuthentication plugin, the Shibboleth groups get applied as expected. I am unsure if the same applies to password or other forms of Authentication in relation to IP Authentication.

We have not experienced this issue with 7.6 or earlier 7.x versions of DSpace.

**To Reproduce**

1. In DSpace 7.6.1, configure groups to be added by the IP Authentication Plugin and the Shibboleth Authentication plugin
2. Log in with Shibboleth from an IP address configured to apply a special group
3. Check groups in user's profile

**Expected behavior**

Groups from both IP Authentication and Shibboleth authentication would be added to the user.

**Related work**

Seems to be related to:
[Issue #9127](https://github.com/DSpace/DSpace/issues/9127)
[PR #9130](https://github.com/DSpace/DSpace/pull/9130)

### LINKED ISSUE #9498: Shibboleth special groups are not working
**Describe the bug**
When you're using shibboleth as authentication method and want to use the special-group functionality, these special groups are not set. I think this might be the same reason why the bug reported in #9226 exits. As reported there, the problem lies in the newly introduced [if condition](https://github.com/DSpace/DSpace/pull/9130/files#diff-7c4b6ff98f27dc9164aac10fd917be18d28e268cbeb8ee5487dffacbb5769ec8) in #9130. I digged a bit deeper into this and found, that if I overwrite the `areSpecialGroupsApplicable()` method in the `ShibAuthentication.java` according to the overwrite made [in `IPAuthentication.java` always returning `true`](https://github.com/DSpace/DSpace/pull/9130/files#diff-a0a532400af44c7c4b19f271b8b343cb3d3155185a1a89ad338ae60f447f2a76), it works. I'm still analysing, what is the real cause behind this (so why `areSpecialGroupsApplicable()` does not return true for shibboleth if needed), but I wanted to post this already.

**To Reproduce**
1. Activate shibboleth authentication on your backend
2. Set a group mapping for special-groups as described in the docs.
3. Login with a user-account via shibboleth, which has the needed affiliation
4. Check if the special-groups appear in your profile

**Expected behavior**
The user should be placed in the corresponding special-groups.

**Related work**
* #9226 
* #9130

### LINKED ISSUE #9726: Special group configuration for authentications is also added to unrelated logins
## Describe the bug
When one of the authentication configurations has a 'special' group configured that should be added by default, it does not matter what authentication method is used, it's added by default

## To Reproduce
* Set a special default group for either password or shibboleth authentication
    * authentication-password.cfg 
        * `authentication-password.login.specialgroup = Special_PW_group
    * authentication-shibboleth.cfg
        * authentication-shibboleth.default-roles = internal
        * authentication-shibboleth.role.internal = Special_SSO_group

Log in through the password authentication,  as the default role is used, and nothing else is matched, that Special_SSO_group mapping is also automatically added

```2024-07-26 09:08:48,205 INFO  unknown unknown org.dspace.authenticate.ShibAuthentication @ Added current EPerson to special groups: [org.dspace.eperson.Group@fbbc5521]```

If you have any specific restrictions to that group that should ONLY be visible for SSO authenticated EPerson logins, regular password logins will also be able to see that restricted bitstreams/items/whatever

I've checked that setting a special group for the password login would have an effect on that, but then it's also just added on top of that
https://github.com/DSpace/DSpace/blob/main/dspace/config/modules/authentication-password.cfg#L26

## Expected behavior
Any configuration should be completely separate and split of from 
If you are a specific login, it should ONLY pass through the relevant authentication login code, and nothing else.
SSO configuration for special groups should NOT be added to password logins

## Related work
Link to any related tickets or PRs here.
https://github.com/DSpace/DSpace/issues/8405

### PR DESCRIPTION
**Pull request by vins01-4science**
## References
Fixes https://github.com/DSpace/DSpace/issues/9226
Fixes https://github.com/DSpace/DSpace/issues/9498
Fixes https://github.com/DSpace/DSpace/issues/9726

Improves upon work started in https://github.com/DSpace/DSpace/pull/11462

## Description
This PR addresses an issue where the authentication method was not being correctly set in the context upon successful login. It also relaxes the check for special groups applicability to include cases where the authentication method is currently in use, ensuring that special groups are correctly resolved during the authentication process.

## Improvements over PR #11462
This PR offers a significant improvement over the approach taken in PR #11462 in terms of **clearness, readability, and testability**:

*   **Clearness**: Instead of complex logic involving servlet path enumeration and iterating through the authentication stack to guess the method, this solution simply sets the authentication method in the `Context` at the exact moment of successful login in `AuthenticationServiceImpl`. This reduces the change to essentially two lines of logic.
*   **Readability**: The changes are minimal and located exactly where one would expect the authentication state to be managed (in the service implementation and the method interface), making the code easy to follow and maintain.
*   **Testability**: Unlike the previous attempt, this PR includes comprehensive integration tests (`AuthenticationRestControllerIT`) that verify:
    *   The authentication method is correctly set in the response.
    *   Special groups are correctly mapped and returned *only* for the active authentication method.
    *   Scenarios for both Shibboleth and Password authentication are covered to ensure no regression or cross-contamination of special groups.

## Instructions for Reviewers
List of changes in this PR:
*   **`AuthenticationServiceImpl.java`**: Explicitly set the authentication method in the `Context` when authentication is successful.
*   **`AuthenticationMethod.java`**: Updated `areSpecialGroupsApplicable` to return `true` if the authentication method `isUsed` by the current request.
*   **`AuthenticationRestControllerIT.java`**: Added integration tests to verify that the authentication method is correctly set and that special groups are applied only when the corresponding authentication method is used.

**Include guidance for how to test or review your PR.**
Reviewers should verify that logging in with an authentication method (e.g., Shibboleth or Password) correctly sets the authentication method in the context and that special groups associated with that method are correctly applied. The new integration tests cover these scenarios.

## Checklist

- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR **passes Checkstyle** validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR **includes Javadoc** for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [ ] My PR **passes all tests and includes new/updated Unit or Integration Tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [ ] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [ ] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

File: dspace-api/src/main/java/org/dspace/authenticate/AuthenticationMethod.java [hunk 1]
```diff
@@ -166,7 +166,7 @@ public List<Group> getSpecialGroups(Context context, HttpServletRequest request)
      *                 otherwise
      */
     public default boolean areSpecialGroupsApplicable(Context context, HttpServletRequest request) {
-        return getName().equals(context.getAuthenticationMethod());
+        return getName().equals(context.getAuthenticationMethod()) || isUsed(context,request);
```
Comment (saschaszott) [inline dspace-api/src/main/java/org/dspace/authenticate/AuthenticationMethod.java]: Just a minor thing, but please add a space after the comma and before request.

**Review by saschaszott — CHANGES_REQUESTED** [review]

**Comment by saschaszott** [comment]
I have integrated the changes of this PR into my local DSpace test instance, where the special groups mechanism was not working. I can confirm that after applying the changes of this PR, the special groups mechanism works correctly again for both password-based and LDAP-based authentication. @vins01-4science , thanks for your contribution!

**Comment by saschaszott** [comment]
What do you think, @vins01-4science. Does the extension of the check by `isUsed` also need to be included in the `canChangePassword` method of class `AuthenticationServiceImpl`?

**Comment by tdonohue** [comment]
@vins01-4science : If you have a chance to update this PR quickly and respond to @saschaszott 's feedback above, I'd love to see if we can still include this in the upcoming maintenance releases for 9.x, 8.x and 7.x.  However, we plan to (hopefully) release those new versions by/on Weds, Dec 17.  Thanks!

File: dspace-api/src/main/java/org/dspace/authenticate/AuthenticationMethod.java (hunk 1 above)
Comment (vins01-4science) [reply dspace-api/src/main/java/org/dspace/authenticate/AuthenticationMethod.java]: Sure, I am going to place that additional space!

**Comment by vins01-4science** [comment]
> What do you think, @vins01-4science. Does the extension of the check by `isUsed` also need to be included in the `canChangePassword` method of class `AuthenticationServiceImpl`?

If we don't have a bug regarding this specific point, I wouldn't add that check, since at that point the authentication method should be already placed inside the `DSpaceContext`.

**Comment by vins01-4science** [comment]
> @vins01-4science : If you have a chance to update this PR quickly and respond to @saschaszott 's feedback above, I'd love to see if we can still include this in the upcoming maintenance releases for 9.x, 8.x and 7.x. However, we plan to (hopefully) release those new versions by/on Weds, Dec 17. Thanks!

Replied and updated the code, thank you both @saschaszott  & @tdonohue !

File: dspace-api/src/main/java/org/dspace/authenticate/AuthenticationMethod.java (hunk 1 above)
Comment (saschaszott) [reply dspace-api/src/main/java/org/dspace/authenticate/AuthenticationMethod.java]: Thank you, @vins01-4science .

**Review by saschaszott — APPROVED** [review]

**Review by tdonohue — APPROVED** [review]
👍 Thanks @vins01-4science !  The code looks good to me and the tests prove the corrected behavior.  I also gave it some light testing with Password Auth and found no issues.

**Comment by jameswsullivan** [comment]
Hi @tdonohue or @vins01-4science , did you happen to know if this solution also works for other authentication methods like OIDC, compared to [11462](https://github.com/DSpace/DSpace/pull/11462) ? I haven't tested yet but I think at the time 11462 also included work for OIDC special groups support.

**Comment by tdonohue** [comment]
@jameswsullivan : The small changes in this PR appear to be generic and would apply to all authentication methods.  That said, this wasn't tested with OIDC directly (to my knowledge)...so I cannot comment on that.

If you find issues or problems though, then I'd recommend moving them to either dspace-tech or a separate ticket.  We don't tend to monitor comments on closed PRs, so comments here are unlikely to be seen as broadly (and may be lost/ignored by accident).
