### PR TITLE
[ #2161] Provide a way to require Creative Commons license in submission form

### LINKED ISSUE #2161: Provide a way to require Creative Commons license in submission form
**Describe the bug**
I need the Creative Commons step to be required in submission process. I tried changing "mandatory" to "true" in step definitions (item-submission.xml) but it didn't work.

<step-definition id="cclicense" mandatory="true">...</step-definition> 

**To Reproduce**
1. Change configuration "mandatory" to "true"
2. Restart tomcat
3. Start new submission
4. Fill all required fields, except cc license
5. Submit submission
6. Done, but shouldn't

**Expected behavior**
Expected that form validation does not allow the submission to be submitted

### PR DESCRIPTION
**Pull request by Sondissimo**
## References

* Fixes https://github.com/DSpace/dspace-angular/issues/2161

Angular pr for label: https://github.com/DSpace/dspace-angular/pull/3287

## Description
Provided new validation for cclicense
It can be enabled through the new property "cc.license.required"
Disabled by default

## Instructions for Reviewers
Please test the behaviour of the new property making submissions both providing and non providing cclicense during both enabled and non enabled cclicense required

List of changes in this PR:
1 Provided new cclicense validator class
2 Added property setting in dspace cfg
3 provided the class in the dspace-addon-validation-services.xml
4 provided test case

image

## Checklist

- [x ] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [ x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [ x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [ x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x ] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [ x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/submit/step/validation/CclicenseValidator.java [hunk 1]
```diff
@@ -0,0 +1,135 @@
...
+    private ItemService itemService;
+
+    @Autowired
+    private CreativeCommonsServiceImpl creativeCommonsService;
+
+    public static final String ERROR_VALIDATION_CCLICENSEREQUIRED = "error.validation.cclicense.required";
+
+    private String name;
+
+    private Boolean required;
```
Comment (vins01-4science) [inline dspace-server-webapp/src/main/java/org/dspace/app/rest/submit/step/validation/CclicenseValidator.java:57]: Please remove this property since we are relying directly on the `configurationService` to retrieve values.

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/submit/step/validation/CclicenseValidator.java [hunk 2]
```diff
@@ -0,0 +1,135 @@
...
+    public void setItemService(ItemService itemService) {
+        this.itemService = itemService;
+    }
+
+    /**
+     * Check if at least one Creative Commons License is required when submitting a new Item.
+     * @return true if a Creative Commons License is required setting true for the property cc.license.required.
+     */
+    public Boolean isRequired() {
+        if (required == null) {
```
Comment (vins01-4science) [inline dspace-server-webapp/src/main/java/org/dspace/app/rest/submit/step/validation/CclicenseValidator.java:89]: just return the value obtained with the configurationService itself
```java
return configurationService.getBooleanProperty("cc.license.required", false);
```

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/submit/step/validation/CclicenseValidator.java [hunk 3]
```diff
@@ -0,0 +1,135 @@
...
+            return configurationService.getBooleanProperty("cc.license.required", false);
+        }
+        return required;
+    }
+
+    /**
+     * Set whether at least one Creative Commons License is required when submitting a new Item.
+     * @param required true if a Creative Commons License is required.
+     */
+    public void setRequired(Boolean required) {
```
Comment (vins01-4science) [inline dspace-server-webapp/src/main/java/org/dspace/app/rest/submit/step/validation/CclicenseValidator.java:99]: Please remove this setter since we are relying on the `configurationService`

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/submit/step/validation/CclicenseValidator.java [hunk 4]
```diff
@@ -0,0 +1,135 @@
...
+    private Boolean required;
+
+    /**
+     * Validate the license of the item.
+     * @param item The item whose cclicense is to be validated.
+     * @param config The configuration for the submission step for cclicense.
+     * @return A list of validation errors.
+     */
+    private List<ErrorRest> validateLicense(Item item, SubmissionStepConfig config) {
+        List<ErrorRest> errors = new ArrayList<>();
```
Comment (vins01-4science) [inline dspace-server-webapp/src/main/java/org/dspace/app/rest/submit/step/validation/CclicenseValidator.java:66]: Here, just initialize the array with the capacity (1), since we will add at most only one error :+1:

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/submit/step/validation/CclicenseValidator.java [hunk 5]
```diff
@@ -0,0 +1,135 @@
...
+     * @return A list of validation errors.
+     * @throws SQLException If there is a problem accessing the database.
+     */
+
+    @Override
+    public List<? extends ErrorRest> validate(SubmissionService submissionService,
+                                              InProgressSubmission obj,
+                                              SubmissionStepConfig config)
+            throws DCInputsReaderException, SQLException {
+        List<ErrorRest> errors = new ArrayList<>();
```
Comment (vins01-4science) [inline dspace-server-webapp/src/main/java/org/dspace/app/rest/submit/step/validation/CclicenseValidator.java:121]: Since we call only validateLicense to fillout the errors arraylist, you can improve this method by using an if/else statement
```java
if (this.isRequired()) {
  return validateLicense(....);
} else {
  return List.of(); // empty list
}
```

**Review by vins01-4science — CHANGES_REQUESTED** [review]
Thank you @Sondissimo for this PR.
I checked your work and it looks good overall.
I requested some minor changes / improvements that I would like to be addressed.

**Review by vins01-4science — APPROVED** [review]
Thank you @Sondissimo  for the addressed changes.
Everything looks good to me, so I am :+1:  on this PR!

**Review by tdonohue — COMMENTED** [review]
@Sondissimo : I gave this a test today, and it works.  However, it appears that there's a small PR missing for the `dspace-angular` project.   Whenever I see the CC License required error message displayed, it's untranslated like this:

untranslated

Can you submit a small PR to the frontend to fix that?  Beyond that, I'm +1 this change

**Comment by Sondissimo** [comment]
Provided pr angular side with label regarding the error https://github.com/DSpace/dspace-angular/pull/3287

**Review by tdonohue — APPROVED** [review]
👍 Thanks @Sondissimo !  Looks great to me now.
