### PR TITLE
Errorprone upgrade

### LINKED ISSUE #9826: Upgrade google error prone from 2.10.0 to latest (2.32.0)
## Describe the bug
The version of google error prone that we are using (7x, 8x, main) dates back from Nov 2021
If you compile DSpace with java 22, you get this error:
https://github.com/google/error-prone/issues/4370 also reported on
https://groups.google.com/g/dspace-tech/c/aDkd-k3ceGQ

This is fixed when upgrading to the latest version of error prone.

### PR DESCRIPTION
**Pull request by mwoodiupui**
## References
* Fixes #9826

## Description
Upgrade Error Prone to a more recent version, and fix new ERRORs.

## Instructions for Reviewers
List of changes in this PR:
* Updated Error Prone version number in POM.
* Fixed things that that broke.
* Fixed some warnings, since I had the code open.
* Usual IDE hints and documentation adjustments.

To test:  build and check that Error Prone did not fail the build.

## Checklist
- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR **passes Checkstyle** validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR **includes Javadoc** for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR **passes all tests and includes new/updated Unit or Integration Tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

File: dspace-api/src/main/java/org/dspace/curate/Curation.java [hunk 1]
```diff
@@ -300,9 +300,17 @@ private void initGeneralLineOptionsAndCheckIfValid() {
         // scope
         if (this.commandLine.getOptionValue('s') != null) {
             this.scope = this.commandLine.getOptionValue('s');
-            if (this.scope != null && Curator.TxScope.valueOf(this.scope.toUpperCase()) == null) {
```
Comment (mwoodiupui) [inline dspace-api/src/main/java/org/dspace/curate/Curation.java:303]: This was a "never null" error.  Enum.valueOf throws an exception if the object has no such value.  It never returns 'null'.  The null test was not only pointless but invalid as well.

File: dspace-api/src/main/java/org/dspace/authenticate/LDAPAuthentication.java [hunk 2]
```diff
@@ -503,6 +503,7 @@ protected String getDNOfUser(String adminUser, String adminPassword, Context con
                     } else {
                         searchName = ldap_provider_url + ldap_search_context;
                     }
+                    @SuppressWarnings("BanJNDI")
```
Comment (mwoodiupui) [inline dspace-api/src/main/java/org/dspace/authenticate/LDAPAuthentication.java:506]: These are suppressed because the sysadmin. has control of the directory and can ensure safety.

File: dspace-server-webapp/src/test/java/org/dspace/app/rest/AuthorizationRestRepositoryIT.java [hunk 3]
```diff
@@ -977,16 +977,18 @@ public void findByObjectInternalServerErrorTest() throws Exception {
             .andExpect(status().isInternalServerError());
     }
 
-    @Test
     /**
-     * Verify that the search by object and feature works properly in allowed scenarios:
```
Comment (mwoodiupui) [inline dspace-server-webapp/src/test/java/org/dspace/app/rest/AuthorizationRestRepositoryIT.java:982]: Doc comments are meant to be extracted and formatted by e.g. Javadoc, so they should be marked up such that the formatted output is neat and readable.  In particular, the topic sentence should end with a period and lists should be marked up as such.

File: dspace-server-webapp/src/test/java/org/dspace/app/rest/CommunityRestRepositoryIT.java [hunk 4]
```diff
@@ -1410,11 +1410,11 @@ public void findAllSubCommunitiesGrantAccessAdminsTest() throws Exception {
                 .withAdminGroup(child2Admin)
                 .build();
 
-        Community ommunityChild1Child1 = CommunityBuilder.createSubCommunity(context, communityChild1)
+        Community communityChild1Child1 = CommunityBuilder.createSubCommunity(context, communityChild1)
                 .withName("Sub1 Community 1")
                 .build();
 
-        Community сommunityChild2Child1 = CommunityBuilder.createSubCommunity(context, communityChild2)
```
Comment (mwoodiupui) [inline dspace-server-webapp/src/test/java/org/dspace/app/rest/CommunityRestRepositoryIT.java:1417]: EP said that this line contained a Unicode character which should not be in code.  I could never find it so I retyped the line as I saw it, and deleted the original.

File: dspace-services/src/test/java/org/dspace/servicemanager/config/DSpaceConfigurationServiceTest.java [hunk 5]
```diff
@@ -306,7 +306,6 @@ public void testGetPropertyAsTypeStringClassOfT() {
         assertEquals(Boolean.FALSE, bool2);
 
         boolean bool3 = configurationService.getPropertyAsType("INVALID.PROPERTY", boolean.class);
-        assertNotNull(bool3);
```
Comment (mwoodiupui) [inline dspace-services/src/test/java/org/dspace/servicemanager/config/DSpaceConfigurationServiceTest.java:309]: Primitive values cannot be null.

**Comment by alanorth** [comment]
This should be safe to merge ASAP as it is mostly fixing issues in tests, and on that note it's passing all tests in CI. I see one instance where the pull request removes unused imports, which is a good thing as well. Lastly, this starts to allow us to use newer versions of Java.

**Review by kshepherd — APPROVED** [review]
+1 code changes reviewed and all look good, tests pass.
Curation task practical tests pass, LDAP auth provider starts properly, DSO rest repos work properly (since these were the non-IT changes aside from one annotation in EmailService)
Thanks @mwoodiupui ! Merging now

**Comment by tdonohue** [comment]
Cherry-picked these changes to 8.x in #10216 , as that PR is updating us to latest errorprone on the `dspace-8_x` branch.

Cherry-picked these changes to 7.x in #10218 , as that PR is updating us to latest errorprone on the `dspace-7_x` branch.
