### PR TITLE
On error in DOI Organiser bulk operations, continue instead of panic-stopping.

### LINKED ISSUE #9828: DOI Organizer: an error on a single item shouldn't block the processing of the whole queue
## Describe the bug
Whenever the DOI organizer errors out on a problem with a specific item, the processing just shuts down completely.
It would be better that the error is logged, the item is skipped and that the rest of the queue is still processed.

## To Reproduce
1. Ensure DOI registration is active
2. Make sure there are multiple update or registration actions sitting in the queue
3. Make sure one item has a problem in metadata, for example an empty value on dc.contributor.author

## Expected behavior
The single offending item should be logged and skipped, but the rest of the queue should be processed.

### PR DESCRIPTION
**Pull request by mwoodiupui**
## References
* Fixes #9828

## Description
Catch appropriate exceptions inside the loops, report and continue.

## Instructions for Reviewers
List of changes in this PR:
* Catch blocks surround remote operations, keeping some exception handling inside the loop.
* Commit each successful operation immediately so that, in the event of unrecoverable errors, completed work is not lost.
* Explicitly roll back on an unsuccessful operation.

Testing:  see #9828.

## Checklist
- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR **passes Checkstyle** validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR **includes Javadoc** for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR **passes all tests and includes new/updated Unit or Integration Tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

File: dspace-api/src/main/java/org/dspace/identifier/doi/DOIOrganiser.java [hunk 1]
```diff
@@ -227,8 +226,16 @@ public static void runCLI(Context context, DOIOrganiser organiser, String[] args
                 }
 
                 for (DOI doi : dois) {
-                    organiser.reserve(doi);
-                    context.uncacheEntity(doi);
```
Comment (vins01-4science) [inline dspace-api/src/main/java/org/dspace/identifier/doi/DOIOrganiser.java:231]: Why did you removed the `uncacheEntity`?

File: dspace-api/src/main/java/org/dspace/identifier/doi/DOIOrganiser.java [hunk 2]
```diff
@@ -227,8 +226,16 @@ public static void runCLI(Context context, DOIOrganiser organiser, String[] args
...
+                    doi = context.reloadEntity(doi);
```
Comment (vins01-4science) [inline dspace-api/src/main/java/org/dspace/identifier/doi/DOIOrganiser.java:229]: The `reloadEntity` has been introduced to reload `detached` entities after a `context.rollback()`?

File: dspace-api/src/main/java/org/dspace/identifier/doi/DOIOrganiser.java [hunk 3]
```diff
@@ -245,8 +252,16 @@ public static void runCLI(Context context, DOIOrganiser organiser, String[] args
...
+                    try {
+                        organiser.register(doi);
+                        context.commit();
+                    } catch (SQLException e) {
+                        System.err.format("DOI %s for object %s registration failed, skipping:  %s%n",
+                                doi.getDSpaceObject().getID().toString(),
+                                doi.getDoi(), e.getMessage());
+                        context.rollback();
+                    }
```
Comment (vins01-4science) [inline dspace-api/src/main/java/org/dspace/identifier/doi/DOIOrganiser.java:264]: The `register` method can throw  `IllegalStateException | RuntimeException` that are not catched inside this block. Those exception would block the whole process.

**Review by vins01-4science — COMMENTED** [review]
The changes looks good overall :+1: .
I found out that some `exceptions` are not properly catched. If we want to be sure that the process wouldn't be stopped entirely we should try to catch at least `RuntimeException` / `Exception`.
What do you think about this - @mwoodiupui  @tdonohue  ?

I left some question for you @mwoodiupui.

File: dspace-api/src/main/java/org/dspace/identifier/doi/DOIOrganiser.java (hunk 3 above)
Comment (mwoodiupui) [reply dspace-api/src/main/java/org/dspace/identifier/doi/DOIOrganiser.java:264]: Thanks for catching that.  Ugh, unchecked exceptions.  Undocumented in `register`'s signature, too.  I'll fix that.

File: dspace-api/src/main/java/org/dspace/identifier/doi/DOIOrganiser.java (hunk 2 above)
Comment (mwoodiupui) [reply dspace-api/src/main/java/org/dspace/identifier/doi/DOIOrganiser.java:229]: Yes, rollback or commit.  Both cause database entities to be detached.

File: dspace-api/src/main/java/org/dspace/identifier/doi/DOIOrganiser.java (hunk 1 above)
Comment (mwoodiupui) [reply dspace-api/src/main/java/org/dspace/identifier/doi/DOIOrganiser.java:231]: It is replaced by `commit`, which will accomplish the same.

**Review by pnbecker — APPROVED** [review]
@mwoodiupui thank you! I love to see this PR.

I reviewed the code, it looks good to me. I have not tested it. 👍

**Review by vins01-4science — APPROVED** [review]
@mwoodiupui Thank you for the changes and the improvements!

I'm going to approve it :+1: !

**Review by tdonohue — COMMENTED** [review]
Merging as this is at +2.  Code looks good to me too.  Thanks @mwoodiupui !
