### PR TITLE
Get request-copy response email body from backend templates, as with all other emails

### LINKED ISSUE #2221: Request copy grant email body is in `dspace-angular`; should be in `dspace`
**Describe the bug**
When an author or helpdesk person grants a copy request, the email body is found in the front-end rather than among the back-end templates which supply all other email bodies.  This means that the process must be configured in two separate places, one of which requires a rebuild and reinstall to take effect.  The methods for inserting parameters are different and the set of parameters in the front-end is much narrower, requiring one to hack on the component itself in some cases.

**To Reproduce**
1. Try to find the body of the grant message, for editing.  Discover that it is nowhere to be found among the expected templates.
2. Rummage around and eventually discover it in the `DSpace/dspace-angular` message catalog.

**Expected behavior**
All email bodies should be kept together, should be parameterized in the same way, and be editable without rebuilding.

### PR DESCRIPTION
**Pull request by mwoodiupui**
## References
* Fixes DSpace/dspace-angular#2221
* Requires DSpace/dspace-angular#2244

## Description
When sending a "granted" response to a request for copy, use a template from the backend instead of hardwired text from the frontend's message catalog.  This keeps all of the configuration for request-copy in the backend, in one place, and makes it available to alternate frontends.

## Instructions for Reviewers
List of changes in this PR:
* Compose the email from a backend Velocity template as we do with other emails.
* Conditionally include a custom message from the grantor.
* Make the sender class into a bean, and autowire it into the frontend, so that it gets its own collaborators injected.
* Provide the beginning of a test suite for the class.

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

File: dspace-api/src/main/java/org/dspace/app/requestitem/RequestItemEmailNotifier.java [hunk 1]
```diff
@@ -147,12 +151,38 @@ static public void sendRequest(Context context, RequestItem ri, String responseL
...
+            grantorAddress = grantor.getEmail();
+        }
+
         // Build an email back to the requester.
-        Email email = new Email();
-        email.setContent("body", message);
+        Email email = Email.getEmail(I18nUtil.getEmailFilename(context.getCurrentLocale(),
+                "request_item.granted"));
+        email.addArgument(ri.getReqName()); // {0} requestor's name
+        email.addArgument(ri.getItem().getID().toString()); // {1} URL of the requested Item
```
Comment (tdonohue) [inline dspace-api/src/main/java/org/dspace/app/requestitem/RequestItemEmailNotifier.java:181]: I agree that this *should be* the URL... but, currently it's just the UUID. This should probably use something like:
```
handleService.getCanonicalForm(ri.getItem().getHandle())
``` 
That's what we use for `request_item.author`.  While I realize we want to get away from Handles, that may be the best approach for now.

File: dspace-api/src/main/java/org/dspace/app/requestitem/RequestItemEmailNotifier.java [hunk 2]
```diff
@@ -147,12 +151,38 @@ static public void sendRequest(Context context, RequestItem ri, String responseL
...
+        email.addArgument(ri.getItem().getName()); // {2} title of the requested Item
+        email.addArgument(grantorName);     // {3} name of the grantor
+        email.addArgument(grantorAddress);  // {4} email of the grantor
```
Comment (tdonohue) [inline dspace-api/src/main/java/org/dspace/app/requestitem/RequestItemEmailNotifier.java:184]: Remove this as noted.

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/utils/ApplicationConfig.java [hunk 3]
```diff
@@ -13,17 +13,29 @@
...
  * @author Tim Donohue
  */
 @Configuration
-@ComponentScan( {"org.dspace.app.rest.converter", "org.dspace.app.rest.repository", "org.dspace.app.rest.utils",
-        "org.dspace.app.configuration", "org.dspace.iiif", "org.dspace.app.iiif"})
+// Component scanning ignores any parent {@code ApplicationContext}s, so any
+// bean which is in the scope of both will be duplicated.  dspace-services makes
+// its context the parent of this one.  If a bean is explicitly configured in
+// the parent, it won't be so configured in this context and you may have
+// trouble.  IOW be careful what you add here.
```
Comment (tdonohue) [inline dspace-server-webapp/src/main/java/org/dspace/app/rest/utils/ApplicationConfig.java:30]: I'd recommend spelling out "IOW" to be "In other words".  It's helpful for those who are not familiar with the abbreviation or not native English speakers.

**Review by tdonohue — CHANGES_REQUESTED** [review]
@mwoodiupui : Overall, this looks good and it works well (tested both for default request-a-copy settings & helpdesk settings).  However, I recommend we change the text of the email now that it's on the backend *and* I think we should refrain from sharing the author's email address (as that can be considered a privacy concern).

Beyond that, this looks good.  All my requests for changes should be small & quick to fix... see inline below.

File: dspace/config/emails/request_item.granted [hunk 4]
```diff
@@ -0,0 +1,26 @@
+## Sent to the person requesting a copy of a restricted document when the
+## request is granted.
+##
+## Parameters:
+##  {0} name of the requestor
+##  {1} unique ID of the requested Item
+##  {2} title of the requested Item
+##  {3} name of the grantor
+##  {4} email address of the grantor
```
[the remark this answers is not in the document]
Comment (mwoodiupui) [reply dspace/config/emails/request_item.granted:9]: Suggestion:  continue to make this available for sites that want it, but don't use it in the stock message.

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/utils/ApplicationConfig.java (hunk 3 above)
Comment (mwoodiupui) [reply dspace-server-webapp/src/main/java/org/dspace/app/rest/utils/ApplicationConfig.java:30]: "IOW" doesn't really add any meaning here, so I think I'll just remove it.

File: dspace-api/src/main/java/org/dspace/app/requestitem/RequestItemEmailNotifier.java (hunk 1 above)
Comment (mwoodiupui) [reply dspace-api/src/main/java/org/dspace/app/requestitem/RequestItemEmailNotifier.java:181]: Agreed, well caught!

File: dspace/config/emails/request_item.granted [hunk 5]
```diff
@@ -0,0 +1,26 @@
...
+  ${params[1]}
+
+of which I am an author.
+#if( $params[5] )
+
+${params[5]}
+#end
+
+Best regards,
+${params[3]} <${params[4]}>
```
[the remark this answers is not in the document]
Comment (mwoodiupui) [reply dspace/config/emails/request_item.granted:26]: I agree.  Individual sites which use the default strategy can make their texts more personal if they wish.  Will do.

File: dspace/config/emails/request_item.granted [hunk 6]
```diff
@@ -0,0 +1,26 @@
+## Sent to the person requesting a copy of a restricted document when the
+## request is granted.
+##
+## Parameters:
+##  {0} name of the requestor
+##  {1} unique ID of the requested Item
```
[the remark this answers is not in the document]
Comment (mwoodiupui) [reply dspace/config/emails/request_item.granted:6]: I agree.  My method in this patch was "make the existing template work with my code changes" and I didn't really look at the template as a whole.  But it's a good opportunity to fix things like this.  Will do.

File: dspace-api/src/main/java/org/dspace/app/requestitem/RequestItemEmailNotifier.java [hunk 7]
```diff
@@ -147,12 +151,38 @@ static public void sendRequest(Context context, RequestItem ri, String responseL
...
+
+        String grantorName;
+        String grantorAddress;
+        if (grantors.isEmpty()) {
+            grantorName = configurationService.getProperty("mail.admin.name");
+            grantorAddress = configurationService.getProperty("mail.admin");
+        } else {
+            RequestItemAuthor grantor = grantors.get(0); // XXX Cannot know which one
+            grantorName = grantor.getFullName();
+            grantorAddress = grantor.getEmail();
```
[the remark this answers is not in the document]
Comment (mwoodiupui) [reply dspace-api/src/main/java/org/dspace/app/requestitem/RequestItemEmailNotifier.java:174]: As I said above, I think this should be *available* if the site wants to use it.

File: dspace-api/src/main/java/org/dspace/app/requestitem/RequestItemEmailNotifier.java (hunk 2 above)
Comment (mwoodiupui) [reply dspace-api/src/main/java/org/dspace/app/requestitem/RequestItemEmailNotifier.java:184]: Again, why not make it available for those who want it, since the logic is worked out, but require a conscious effort to expose it in the email.

File: dspace/config/emails/request_item.granted (hunk 4 above)
[the remark this answers is not in the document]
Comment (tdonohue) [reply dspace/config/emails/request_item.granted:9]: @mwoodiupui : That's fine with me.  I'm OK with it existing, but I think it shouldn't be used by default (as I'm worried this would be an issue with GDPR and similar regulations). 

In that case, I'd recommend adding a note into the template then that the email address is currently **unused**, but is available if sites want to include the email of the grantor in the response.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @mwoodiupui !  This looks good to me now.  Retested today and it's all working and my feedback has been resolved.
