### PR TITLE
fix: Failure of org.dspace.app.rest.SitemapRestControllerIT when running locally

### LINKED ISSUE #9215: Failure of org.dspace.app.rest.SitemapRestControllerIT when running locally
**Describe the bug**
The `org.dspace.app.rest.SitemapRestControllerIT` integration test can fail when running locally, but not in GitHub CI. I've tested on Linux with Java temurin-11.0.19+7 and temurin-17.0.9+9:

```
[ERROR] Failures:
[ERROR]   SitemapRestControllerIT.testSitemap_sitemap0Xml:235 Content type expected:<application/xml;charset=UTF-8> but was:<text/xml;charset=UTF-8>
[ERROR]   SitemapRestControllerIT.testSitemap_sitemapIndexXml:219 Content type expected:<application/xml;charset=UTF-8> but was:<text/xml;charset=UTF-8>
```

It's unclear what difference in environments can cause this.

**To Reproduce**
```console
$ mvn install -DskipIntegrationTests=false -Dit.test=org.dspace.app.rest.SitemapRestControllerIT -DfailIfNoTests=false
...
[INFO] Running org.dspace.app.rest.SitemapRestControllerIT
[ERROR] Tests run: 7, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 40.252 s <<< FAILURE! - in org.dspace.app.rest.SitemapRestControllerIT
[ERROR] testSitemap_sitemapIndexXml(org.dspace.app.rest.SitemapRestControllerIT)  Time elapsed: 1.813 s  <<< FAILURE!
java.lang.AssertionError: Content type expected:<application/xml;charset=UTF-8> but was:<text/xml;charset=UTF-8>
        at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:59)
        at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:122)
        at org.springframework.test.web.servlet.result.ContentResultMatchers.lambda$contentType$0(ContentResultMatchers.java:86)
        at org.springframework.test.web.servlet.MockMvc$1.andExpect(MockMvc.java:214)
        at org.dspace.app.rest.SitemapRestControllerIT.testSitemap_sitemapIndexXml(SitemapRestControllerIT.java:219)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
        at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
        at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

[ERROR] testSitemap_sitemap0Xml(org.dspace.app.rest.SitemapRestControllerIT)  Time elapsed: 1.568 s  <<< FAILURE!
java.lang.AssertionError: Content type expected:<application/xml;charset=UTF-8> but was:<text/xml;charset=UTF-8>
        at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:59)
        at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:122)
        at org.springframework.test.web.servlet.result.ContentResultMatchers.lambda$contentType$0(ContentResultMatchers.java:86)
        at org.springframework.test.web.servlet.MockMvc$1.andExpect(MockMvc.java:214)
        at org.dspace.app.rest.SitemapRestControllerIT.testSitemap_sitemap0Xml(SitemapRestControllerIT.java:235)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
        at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
        at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   SitemapRestControllerIT.testSitemap_sitemap0Xml:235 Content type expected:<application/xml;charset=UTF-8> but was:<text/xml;charset=UTF-8>
[ERROR]   SitemapRestControllerIT.testSitemap_sitemapIndexXml:219 Content type expected:<application/xml;charset=UTF-8> but was:<text/xml;charset=UTF-8>
[INFO]
[ERROR] Tests run: 7, Failures: 2, Errors: 0, Skipped: 0
```

**Expected behavior**

### PR DESCRIPTION
**Pull request by ksankeerth**
## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #9215

## Description
Fixes #9215 

## Instructions for Reviewers
- Proposed change in https://github.com/DSpace/DSpace/issues/9215 was added in code

List of changes in this PR:
* First, ...
* Second, ...

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [ -] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [ -] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [ -] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [ -] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ -] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ -] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [- ] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [- ] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by tdonohue** [comment]
Thanks @ksankeerth ! 

@alanorth : Any chance you could give this a test in your local environment to verify it fixes the issue you reported in #9215?  It looks (to me) like it should fix the problem.

**Comment by alanorth** [comment]
Thanks @ksankeerth! Your patch fixes the failing `testSitemap_sitemapIndexXml` test, but we need the same fix on the `testSitemap_sitemap0Xml` test as well.

**Comment by alanorth** [comment]
Thank you @ksankeerth. This fixes the failing tests locally.

Regarding the fixed tests, I am not familiar with junit and I'm surprised we can't do something simpler like adding a logical or with our second condition:

```java
.andExpect(content().contentType("text/xml;charset=UTF-8") || content().contentType("application/xml;charset=UTF-8"))
```

File: dspace-server-webapp/src/test/java/org/dspace/app/rest/SitemapRestControllerIT.java [hunk 1]
```diff
@@ -216,7 +217,13 @@ public void testSitemap_sitemapIndexXml() throws Exception {
                                       //** THEN **
                                       .andExpect(status().isOk())
                                       //We expect the content type to match
-                                      .andExpect(content().contentType("application/xml;charset=UTF-8"))
+                                      .andExpect(res -> {
+                                          String actual = res.getResponse().getContentType();
+                                          assertNotNull("Content type not set", actual);
```
Comment (alanorth) [inline dspace-server-webapp/src/test/java/org/dspace/app/rest/SitemapRestControllerIT.java:222]: I don't understand why we needed this. Was there ever a concern that the result was null? We weren't testing this before.

**Comment by ksankeerth** [comment]
> ```java
> content().contentType("text/xml;charset=UTF-8")
> ```

I also tried to find something very simple like you said. Unfortunately it's not possible. We use some Spring classes for testing with Junit.  The metho`AndExpect` expects a ResultMatcher in its argument.

File: dspace-server-webapp/src/test/java/org/dspace/app/rest/SitemapRestControllerIT.java (hunk 1 above)
Comment (ksankeerth) [reply dspace-server-webapp/src/test/java/org/dspace/app/rest/SitemapRestControllerIT.java:222]: I think you want to know why we have to check `null`.  The method `content().contentType(<string>)`  do above checks by default. So I included that in custom ResultMatcher. If null check is not required, We may remove it.

Comment (alanorth) [reply dspace-server-webapp/src/test/java/org/dspace/app/rest/SitemapRestControllerIT.java:222]: Yes, I was wondering because we weren't checking for null here before, and none of the other tests in this class check for null. My personal philosophy is that pull requests should be atomic and only fix the reported issue. I know that others feel less strongly about that though...

Comment (alanorth) [reply dspace-server-webapp/src/test/java/org/dspace/app/rest/SitemapRestControllerIT.java:221]: OK great. You can remove the null check from both, as well as the extra import of `static org.junit.Assert.assertNotNull`. Thank you!

**Review by alanorth — APPROVED** [review]

**Comment by alanorth** [comment]
Great, thank you for the good work @ksankeerth!
