### PR TITLE
Sort options are not reported in the proper order

### LINKED ISSUE #3227: Sort options are not reported in the proper order
**Describe the bug**
The `discovery.xml` file allows to configure which sortOptions are available for each configuration and set also a default sorting
see
https://github.com/DSpace/DSpace/blob/main/dspace/config/spring/api/discovery.xml#L160
https://github.com/DSpace/DSpace/blob/main/dspace/config/spring/api/discovery.xml#L157-L159

The structure is not efficient as having the default sort set in a separate property can lead to different scenarios that need to be managed
- the default sort option is included in the list of available options
- the default sort option is an additional one

Moreover, in the current implementation the default sort is always appended as last options in the REST response, see
https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/DiscoverConfigurationConverter.java#L39

and there is no explicit mention of the default sort in the REST response, instead the example of the default configuration seems to indicate that the order of sort options matter (using the blame link as I haven't found a different way to link directly the line)
https://github.com/DSpace/RestContract/blame/main/search-endpoint.md#L151

**To Reproduce**
1. https://api7.dspace.org/server/#https://api7.dspace.org/server/api/discover/search
2. look to the sortOptions 
```
"sortOptions": [
    {
      "name": "dc.title"
    },
    {
      "name": "dc.date.issued"
    },
    {
      "name": "dc.date.accessioned"
    },
    {
      "name": "score"
    }
```
**Expected behavior**
We propose to simplify the discovery.xml configuration revisiting the sortOption bean definition to include a defaultDirection property that can be used to set the default direction of the sort option (i.e. DESC for score and date, ASC for title).
We suggest to don't include any restriction about the directions that can be manually applied to the sort, i.e. it will be possible for the user to ask for result in score ASC, this is currently supported by solr and the REST API so we should introduce this constraint only if we get an explicit motivated request from our users as it would lead obviously to extra complexity (in configuration and validation)

`discovery.xml`

```
  <bean id="defaultConfiguration" class="org.dspace.discovery.configuration.DiscoveryConfiguration" scope="prototype">
         ...
            <property name="searchSortConfiguration">
            <bean class="org.dspace.discovery.configuration.DiscoverySortConfiguration">
                <property name="sortFields">
                    <list>
                        <ref bean="sortScore" />
                        <ref bean="sortTitle" />
                        <ref bean="sortDateIssued" />
                        <ref bean="sortDateAccessioned"/>
                    </list>
                </property>
            </bean>
        </property>
     ....
</bean>
...
     <bean id="sortScore" class="org.dspace.discovery.configuration.DiscoverySortFieldConfiguration">
        <!-- no metadataField specified to represent the score or a different implementation of the sortFieldConfiguration. TBD during implementation -->
        <property name="defaultSortOrder" value="desc"/>
    </bean>

   <bean id="sortTitle" class="org.dspace.discovery.configuration.DiscoverySortFieldConfiguration">
        <property name="metadataField" value="dc.title"/>
        <property name="defaultSortOrder" value="desc"/>
    </bean>
```

**Related work**
This is related to https://github.com/DSpace/dspace-angular/issues/1071 and the corresponding PR https://github.com/DSpace/dspace-angular/pull/1086

### PR DESCRIPTION
**Pull request by Micheleboychuk**
## Description
Fixes #3227

Should be tested with https://github.com/DSpace/dspace-angular/pull/1086

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

File: dspace-server-webapp/src/test/java/org/dspace/app/rest/DiscoveryRestControllerIT.java [hunk 1]
```diff
@@ -988,14 +989,76 @@ public void discoverSearchTest() throws Exception {
...
+                                         DiscoverySortFieldConfiguration.SORT_ORDER.desc.name()),
+                       SortOptionMatcher.sortOptionMatcher("dc.date.accessioned",
+                                         DiscoverySortFieldConfiguration.SORT_ORDER.desc.name()),
+                       SortOptionMatcher.sortOptionMatcher("person.familyName",
+                                         DiscoverySortFieldConfiguration.SORT_ORDER.asc.name()),
+                       SortOptionMatcher.sortOptionMatcher("person.givenName",
+                                         DiscoverySortFieldConfiguration.SORT_ORDER.asc.name()),
+                       SortOptionMatcher.sortOptionMatcher("person.birthDate",
+                                         DiscoverySortFieldConfiguration.SORT_ORDER.desc.name()),
+                       SortOptionMatcher.sortOptionMatcher("dc.date.accessioned",
```
Comment (tdonohue) [inline dspace-server-webapp/src/test/java/org/dspace/app/rest/DiscoveryRestControllerIT.java:1031]: This is the second time `dc.date.accessioned` appears in this list.  While not a bug of this PR, it's proof that our configuration in `discovery.xml` has a bug.  One of these duplicate values should be removed from our config at https://github.com/DSpace/DSpace/blob/main/dspace/config/spring/api/discovery.xml#L1377

**Review by tdonohue — APPROVED** [review]
👍 Overall, this looks good, thanks @Micheleboychuk!  I just have one minor suggested fix (see inline below).  I tested this on its own, and I also tested it with the Angular PR (https://github.com/DSpace/dspace-angular/pull/1086) and I couldn't find any issues.

**Review by tdonohue — APPROVED** [review]
👍 Looks good now @Micheleboychuk !  Thanks.  This will be merged alongside the corresponding Angular PR (https://github.com/DSpace/dspace-angular/pull/1086) as soon as it is ready.
