### PR TITLE
Make discovery more resilient to stale objects

### LINKED ISSUE #3243: Concurrent deletion of large communities/collections can cause trouble
**Describe the bug**
During the testhaton the solr search index was out of sync with the database. This result in empty search results when indeed there were still some contents.
The main reason for that is because the first page of results contains references only to objects that were deleted.

**To Reproduce**
Looking to the apache/dspace log files we where able to spot the possible cause
Apache log

Compound Journal Community
```
****** - "" [21/Apr/2021:13:43:37 +0000] "DELETE /server/api/core/communities/8b632938-77c2-487c-81f0-e804f63e68e6 HTTP/1.1" 204 1614 "https://demo7.dspace.org/" "Mozilla/5.0 (Wi
ndows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
****** - "" [21/Apr/2021:13:43:38 +0000] "DELETE /server/api/core/communities/8b632938-77c2-487c-81f0-e804f63e68e6 HTTP/1.1" 500 1886 "https://demo7.dspace.org/" "Mozilla/5.0 (Wi
ndows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
****** - "" [21/Apr/2021:13:43:40 +0000] "DELETE /server/api/core/communities/8b632938-77c2-487c-81f0-e804f63e68e6 HTTP/1.1" 500 1886 "https://demo7.dspace.org/" "Mozilla/5.0 (Wi
ndows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
****** - "" [21/Apr/2021:13:43:43 +0000] "DELETE /server/api/core/communities/8b632938-77c2-487c-81f0-e804f63e68e6 HTTP/1.1" 500 1886 "https://demo7.dspace.org/" "Mozilla/5.0 (Wi
ndows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
****** - "" [21/Apr/2021:13:43:42 +0000] "DELETE /server/api/core/communities/8b632938-77c2-487c-81f0-e804f63e68e6 HTTP/1.1" 500 1886 "https://demo7.dspace.org/" "Mozilla/5.0 (Wi
ndows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
```

Publications community
```
****** - "" [21/Apr/2021:13:45:15 +0000] "DELETE /server/api/core/communities/0958c910-2037-42a9-81c7-dca80e3892b4 HTTP/1.1" 204 1054 "https://demo7.dspace.org/" "Mozilla/5.0 (Wi
ndows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
****** - "" [21/Apr/2021:13:45:40 +0000] "DELETE /server/api/core/communities/0958c910-2037-42a9-81c7-dca80e3892b4 HTTP/1.1" 500 1886 "https://demo7.dspace.org/" "Mozilla/5.0 (Wi
ndows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
****** - "" [21/Apr/2021:13:45:45 +0000] "DELETE /server/api/core/communities/0958c910-2037-42a9-81c7-dca80e3892b4 HTTP/1.1" 500 1886 "https://demo7.dspace.org/" "Mozilla/5.0 (Wi
ndows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
```

but similar logs exists also for the other test communities.

Looking to the dspace.log file for the entries related to the publications deletion we found
```
...
2021-04-21 13:45:51,844 WARN  org.dspace.discovery.IndexEventConsumer @ MODIFY_METADATA event, could not get object for ITEM id=e7bd0d24-e83a-486a-bc0c-8aaaeb19dc7d, perhaps it has been deleted.
2021-04-21 13:45:51,845 WARN  org.dspace.discovery.IndexEventConsumer @ MODIFY event, could not get object for ITEM id=e7bd0d24-e83a-486a-bc0c-8aaaeb19dc7d, perhaps it has been deleted.
2021-04-21 13:45:51,845 ERROR org.dspace.event.BasicDispatcher @ Consumer("discovery").consume threw: java.lang.NullPointerException
java.lang.NullPointerException: null
        at org.dspace.discovery.indexobject.factory.IndexObjectFactoryFactory.getIndexableObjects(IndexObjectFactoryFactory.java:90) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.discovery.IndexEventConsumer.consume(IndexEventConsumer.java:159) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.event.BasicDispatcher.dispatch(BasicDispatcher.java:104) [dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.core.Context.dispatchEvents(Context.java:455) [dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.core.Context.commit(Context.java:424) [dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.app.rest.repository.DSpaceRestRepository.deleteById(DSpaceRestRepository.java:173) [classes/:7.0-beta5-SNAPSHOT]
        at org.dspace.app.rest.repository.DSpaceRestRepository$$FastClassBySpringCGLIB$$615525f9.invoke(<generated>) [classes/:7.0-beta5-SNAPSHOT]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687) [spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.dspace.app.rest.repository.CommunityRestRepository$$EnhancerBySpringCGLIB$$4616f34f.deleteById(<generated>) [classes/:7.0-beta5-SNAPSHOT]
        at org.dspace.app.rest.RestResourceController.deleteInternal(RestResourceController.java:1065) [classes/:7.0-beta5-SNAPSHOT]
        at org.dspace.app.rest.RestResourceController.delete(RestResourceController.java:1049) [classes/:7.0-beta5-SNAPSHOT]
        at jdk.internal.reflect.GeneratedMethodAccessor807.invoke(Unknown Source) ~[?:?]

....

2021-04-21 13:45:56,869 INFO  org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl @ HHH000010: On release of batch it still contained JDBC statements
2021-04-21 13:45:56,869 ERROR org.hibernate.engine.jdbc.batch.internal.BatchingBatch @ HHH000315: Exception executing batch [org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: update public.collection set admin=NULL, logo_bitstream_id=NULL, submitter='906d27ce-792c-4eed-ae8b-26d5aeaf24c3'::uuid, template_item_id=NULL where uuid='282164f5-d325-4740-8dd1-fa4d6d3e7200'::uuid], SQL: update public.collection set admin=?, logo_bitstream_id=?, submitter=?, template_item_id=? where uuid=?
2021-04-21 13:45:56,870 INFO  org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl @ HHH000010: On release of batch it still contained JDBC statements
2021-04-21 13:45:56,870 ERROR org.hibernate.engine.jdbc.batch.internal.BatchingBatch @ HHH000315: Exception executing batch [org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: update public.collection set admin=NULL, logo_bitstream_id=NULL, submitter='906d27ce-792c-4eed-ae8b-26d5aeaf24c3'::uuid, template_item_id=NULL where uuid='282164f5-d325-4740-8dd1-fa4d6d3e7200'::uuid], SQL: update public.collection set admin=?, logo_bitstream_id=?, submitter=?, template_item_id=? where uuid=?
2021-04-21 13:45:56,869 ERROR org.dspace.app.rest.exception.DSpaceApiExceptionControllerAdvice @ An exception has occurred (status:500)
javax.persistence.OptimisticLockException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: update public.collection set admin=NULL, logo_bitstream_id=NULL, submitter='906d27ce-792c-4eed-ae8b-26d5aeaf24c3'::uuid, template_item_id=NULL where uuid='282164f5-d325-4740-8dd1-fa4d6d3e7200'::uuid
        at org.hibernate.internal.ExceptionConverterImpl.wrapStaleStateException(ExceptionConverterImpl.java:238) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:93) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1535) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.query.Query.getResultList(Query.java:165) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.dspace.core.AbstractHibernateDAO.list(AbstractHibernateDAO.java:203) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.handle.dao.impl.HandleDAOImpl.getHandlesByDSpaceObject(HandleDAOImpl.java:62) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.handle.HandleServiceImpl.getInternalHandles(HandleServiceImpl.java:347) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.handle.HandleServiceImpl.findHandle(HandleServiceImpl.java:264) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.identifier.VersionedHandleIdentifierProvider.lookup(VersionedHandleIdentifierProvider.java:301) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.identifier.IdentifierServiceImpl.lookup(IdentifierServiceImpl.java:151) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.content.DSpaceObjectServiceImpl.getIdentifiers(DSpaceObjectServiceImpl.java:89) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.content.ItemServiceImpl.rawDelete(ItemServiceImpl.java:683) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.content.ItemServiceImpl.delete(ItemServiceImpl.java:671) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.content.ItemServiceImpl.delete(ItemServiceImpl.java:71) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.content.CollectionServiceImpl.removeTemplateItem(CollectionServiceImpl.java:594) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.content.CollectionServiceImpl.delete(CollectionServiceImpl.java:721) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.content.CollectionServiceImpl.delete(CollectionServiceImpl.java:75) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.content.CommunityServiceImpl.removeCollection(CommunityServiceImpl.java:428) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.content.CommunityServiceImpl.rawDelete(CommunityServiceImpl.java:534) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.content.CommunityServiceImpl.delete(CommunityServiceImpl.java:498) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.content.CommunityServiceImpl.delete(CommunityServiceImpl.java:51) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.app.rest.repository.CommunityRestRepository.delete(CommunityRestRepository.java:273) ~[classes/:7.0-beta5-SNAPSHOT]
```

in the between we see a lot of modify event related to deleted objects and the first attempt to retrieve deleted object still present in the search indexes

**Expected behavior**
Concurrent deletion should be managed or at least the search index should not end out of sync

**Related work**
A possible solution/workaround could be to introduce a mechanism to self-maintain the solr index in a good status. When during a search stale objects are detected they should be removed and the search automatically re-run

### PR DESCRIPTION
**Pull request by Micheleboychuk**
## Description
Fixes #3243

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Comment by tdonohue** [comment]
@benbosman : I'd appreciate your feedback/review on this one if you get the chance, so assigning to you & I.

File: dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java [hunk 1]
```diff
@@ -860,141 +857,154 @@ protected SolrQuery resolveToSolrQuery(Context context, DiscoverQuery discoveryQ
...
-                    continue;
-                }
-
-                DiscoverResult.SearchDocument resultDoc = new DiscoverResult.SearchDocument();
-                //Add information about our search fields
-                for (String field : searchFields) {
-                    List<String> valuesAsString = new ArrayList<>();
-                    for (Object o : doc.getFieldValues(field)) {
-                        valuesAsString.add(String.valueOf(o));
+    protected DiscoverResult retrieveResult(Context context, DiscoverQuery query)
```
Comment (tdonohue) [inline dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java:860]: I'd appreciate it if we could either add new JavaDocs to this method, or add more inline comments.  Otherwise, some of the logic here regarding `valid` and `zombieDocs` may not make much sense to future developers.  I think we need to clearly document what the purpose of those variables are...as this code is difficult to read overall

File: dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java [hunk 2]
```diff
@@ -860,141 +857,154 @@ protected SolrQuery resolveToSolrQuery(Context context, DiscoverQuery discoveryQ
...
+
+                List<String> searchFields = query.getSearchFields();
+                for (SolrDocument doc : solrQueryResponse.getResults()) {
+                    IndexableObject indexableObject = findIndexableObject(context, doc);
+
+                    if (indexableObject != null) {
+                        result.addIndexableObject(indexableObject);
+                    } else {
+                        log.error(LogManager.getHeader(context,
+                                "Error while retrieving DSpace object from discovery index",
```
Comment (tdonohue) [inline dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java:884]: I think this error should be reworded. If I understand this properly, we might say something like: "Stale entry found in  Discovery index, as we could not find the DSpace object it refers to."

Also, should this be an `log.error`?  Or should this be a `log.warn`, since we will attempt to cleanup after it later in this method.

File: dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java [hunk 3]
```diff
@@ -860,141 +857,154 @@ protected SolrQuery resolveToSolrQuery(Context context, DiscoverQuery discoveryQ
...
                     }
                 }
             }
-
-            if (solrQueryResponse.getSpellCheckResponse() != null) {
-                String recommendedQuery = solrQueryResponse.getSpellCheckResponse().getCollatedResult();
-                if (StringUtils.isNotBlank(recommendedQuery)) {
-                    result.setSpellCheckQuery(recommendedQuery);
-                }
+            if (zombieDocs.size() != 0) {
```
Comment (tdonohue) [inline dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java:1000]: We should comment what is going on here. Something like: "If any stale entries are found in the current page of results, we remove those stale entries and rerun the same query again.  Otherwise, the query is valid and the results are returned."

**Review by tdonohue — CHANGES_REQUESTED** [review]
@Micheleboychuk : The overall code here looks correct, but I think we should add more JavaDocs or inline comments to describe the new logic (so that we remember why this was done). 

I haven't had a chance to test this yet, but I hope to do so later in the week.

File: dspace-api/src/test/java/org/dspace/discovery/DiscoveryIT.java [hunk 4]
```diff
@@ -316,14 +320,153 @@ public void solrRecordFromMessyItemTest() throws Exception {
...
+
+        assertSearchQuery(IndexableCollection.TYPE, 3, 3, 0, -1);
+        assertSearchQuery(IndexableItem.TYPE, 6, 6, 0, -1);
+        collectionService.delete(context, col3);
+        context.restoreAuthSystemState();
+
+        assertSearchQuery(IndexableCollection.TYPE, 2, 2, 0, -1);
+        assertSearchQuery(IndexableItem.TYPE, 2, 6, 0, 2);
+        assertSearchQuery(IndexableItem.TYPE, 1, 3, 2, 4);
+        assertSearchQuery(IndexableItem.TYPE, 3, 3, 0, -1);
```
Comment (benbosman) [inline dspace-api/src/test/java/org/dspace/discovery/DiscoveryIT.java:452]: Can you add some comments to describe these test, they are hard to read

File: dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java [hunk 5]
```diff
@@ -860,141 +857,154 @@ protected SolrQuery resolveToSolrQuery(Context context, DiscoverQuery discoveryQ
...
-                for (String field : searchFields) {
-                    List<String> valuesAsString = new ArrayList<>();
-                    for (Object o : doc.getFieldValues(field)) {
-                        valuesAsString.add(String.valueOf(o));
+    protected DiscoverResult retrieveResult(Context context, DiscoverQuery query)
+        throws SQLException, SolrServerException, IOException, SearchServiceException {
+        boolean valid = false;
+        DiscoverResult result = null;
+        SolrQuery solrQuery = resolveToSolrQuery(context, query);
+        while (!valid) {
```
Comment (benbosman) [inline dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java:865]: There's no limit to how often this loop occurs. Depending on how likely this problem occurs, this loop may keep on being iterated for a long time until you get a search where all incorrect documents have been removed

File: dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java [hunk 6]
```diff
@@ -860,141 +857,154 @@ protected SolrQuery resolveToSolrQuery(Context context, DiscoverQuery discoveryQ
...
-                        for (String key : highlightedFields.keySet()) {
-                            List<String> highlightOriginalValue = highlightedFields.get(key);
-                            List<String[]> resultHighlightOriginalValue = new ArrayList<>();
-                            for (String highlightValue : highlightOriginalValue) {
-                                String[] splitted = highlightValue.split("###");
-                                resultHighlightOriginalValue.add(splitted);
-
-                            }
-                            resultMap.put(key.substring(0, key.lastIndexOf("_hl")), highlightedFields.get(key));
+                    DiscoverResult.SearchDocument resultDoc = new DiscoverResult.SearchDocument();
```
Comment (benbosman) [inline dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java:889]: If a problem occurred with a previous item, all code starting from this line is useless (and time-consuming)
It will happen again in the next iteration.
The only relevant thing to do after a problem occurred, is to verify whether there are more items which may have an issue

**Review by benbosman — CHANGES_REQUESTED** [review]
@Micheleboychuk , I wonder how often can we expect these issues?

I noticed in the changes to `org.dspace.discovery.SolrServiceImpl#retrieveResult` that this will keep on performing the solr queries until it's valid, but it will also perform all logic to the search results each time (even when it's not valid, it will process all subsequent records). If this is not an extremely rare use-case, it should at least limit the remaining results to a check whether it occurs in the index
There's also no limit to how often this loop occurs. Again depending on how likely this problem occurs, this loop may keep on being iterated

File: dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java (hunk 5 above)
Comment (tdonohue) [reply dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java:865]: I agree with @benbosman on this.  I think there should be some sort of limit to the number of times this loop is run.  We could limit it to running 10 times max. If it bypasses that limit, we throw (and log) an error that says something like: "The Discovery (Solr) index has a large number of stale entries, and we could not complete this request. Please reindex all content to remove these stale entries (e.g. dspace index-discovery -f)."   

I would hope this limit would never be hit (as this seems like something that should occur rarely), but it'd ensure there is a "timeout" to this request.

**Review by Raf-atmire — COMMENTED** [review]
Hi @Micheleboychuk Thank you for the PR! I do have a few comments regarding the PR that I'd like to see changed. 
Firstly, the valid loop in the search should have some sort of max iterations that it can "try" to provide a valid response until it should cancel out and throw an error, like Ben and Tim have described in [this](https://github.com/DSpace/DSpace/pull/3265#discussion_r632495464) thread

Secondly, Ben touched on this briefly [here](https://github.com/DSpace/DSpace/pull/3265#discussion_r632496744).  Could we ensure that we don't have to execute all the remaining code if we're just going to say "invalid and try again" at the end? We could do this by providing a check [here](https://github.com/DSpace/DSpace/pull/3265/files#diff-88fd0583d93c5f2634f5f3f69e9569c63af6cfed036a3676d5ccf411a0f58545R886) which will ensure that if we find a document that's invalid, it'll instantly check all the other documents in the results, process them and then repeat the valid loop without processing anymore results/fields/facets. 
This will ensure that we don't execute any more code than we have to, because if one document is invalid, we'll have to redo the entire search anyway. We may as well instantly stop after finding one, processing the remaining documents to see if they need to be deleted as well, and restarting the loop.

Thirdly, I'd like a config parameter that allows us to turn off this behaviour all together. A configuration parameter that would allow us to ensure that the added code here is not being ran incase it's not meant to in the future.

Lastly, this is a fix for when Solr is malfunctioning and not working as it's supposed to, however could we add a test in the DiscoveryIT with the default dispatcher that proves that the deletion of collection will delete the items and their corresponding Solr documents from Solr as well? This would essentially be a test that'd do the following:
- Create Collections and Items
- Check that they're properly located in Solr
- Delete a collection
- Check that that collection and its items aren't in Solr anymore and thus ensuring that our default workflow is correct and not bugged

**Review by Raf-atmire — CHANGES_REQUESTED** [review]
Please refer to my comments [here](https://github.com/DSpace/DSpace/pull/3265#pullrequestreview-660669405)

File: dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java [hunk 7]
```diff
@@ -861,141 +858,180 @@ protected SolrQuery resolveToSolrQuery(Context context, DiscoverQuery discoveryQ
...
+            if (zombieDocs.size() != 0) {
+                log.info("Cleaning " + zombieDocs.size() + " stale objects from Discovery Index");
+                solrSearchCore.getSolr().deleteById(zombieDocs);
+                solrSearchCore.getSolr().commit();
+            } else {
+                valid = true;
             }
+        } while (!valid && executionCount <= maxAttempts);
+
+        if (!valid && executionCount == maxAttempts) {
```
Comment (tdonohue) [inline dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java:1028]: If `maxAttempts` ends up set to zero, this `if` will never be triggered (as executionCount has a minimum value of 1).

**Review by tdonohue — CHANGES_REQUESTED** [review]
@Micheleboychuk : Gave this another review. It appears to work, but I think it has a flaw which is hard to prove in tests...I think we should be setting `discovery.removestale.attempts = 0` in order to *disable* (instead of setting to -1), as a value of zero (0) currently doesn't seem to make sense based on my reading of the code.  It looks like setting it to 0 means it'll run once, which is the same as setting it to 1.

Beyond that, my manual tests show the logic works.  I think the configuration just has a flaw.

**Comment by abollini** [comment]
hi @tdonohue 
we agree with you about rephrasing the comment and rename the variable to make it easier to understand the design. Before to do that I'm trying to summarize what we want to achieve so that we can properly finalize that
`discovery.removestale.attempts  = -1` the goal of this settings is to preserve the current search behavior, zombie objects will stay in the system and in the search 

`discovery.removestale.attempts  = 0` the goal in this case is to cleanup the zombie objects have been found but no perform any attempt to fix the result window so no additional solr query will be performed (no more attempts). I noted that right now no result are returned as the solr response is invalidated and no processed, I would suggest to fix that. With such configuration we would stay very close to the current performance (only the additional delete are triggered) and we will return the same result to the rest client

`discovery.removestale.attempts  =  x`  with `x > 0` in this case we allow to re-run the solr query a maximum of x times, this mean that at the end the solr query will be performed `x+1` times

**Comment by tdonohue** [comment]
@abollini : Because there are very few comments in the code of this PR, I had to assume what you were attempting to achieve, and it sounds like I assumed incorrectly. Your approach sounds more reasonable now that you describe it, but I'd ask that you document that in the `discovery.cfg` (as it currently makes no mention of what a value of "0" should do, and how it differs from a value of >=1) and describe the code better with inline comments.  Additionally, it looks like currently the ITs only test two scenarios...they test a value of -1 and a value of 3....they don't show the behavior expected when the value is set to 0.

So, overall, your described approach sounds reasonable. However, based on your new description my request would be to add  an IT for a value of 0, and add more description of what 0 vs -1 vs >0 means into the `discovery.cfg` file to document this new configuration.

**Comment by abollini** [comment]
@tdonohue I have pushed the additional test and cleanup the code logic. Please let me know what do you think

**Review by tdonohue — APPROVED** [review]
@abollini and @Micheleboychuk :  This is looking better to me now.  I made one final inline comment below (which could simplify the code / make it easier to read & understand for future developers).  But, this works as-is, so I'll go ahead and approve it.

File: dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java [hunk 8]
```diff
@@ -861,141 +858,184 @@ protected SolrQuery resolveToSolrQuery(Context context, DiscoverQuery discoveryQ
...
-                        //We need to remove all the "_hl" appendix strings from our keys
-                        Map<String, List<String>> resultMap = new HashMap<>();
-                        for (String key : highlightedFields.keySet()) {
-                            List<String> highlightOriginalValue = highlightedFields.get(key);
-                            List<String[]> resultHighlightOriginalValue = new ArrayList<>();
-                            for (String highlightValue : highlightOriginalValue) {
-                                String[] splitted = highlightValue.split("###");
-                                resultHighlightOriginalValue.add(splitted);
-
+                    if (!skipLoadingResponse) {
```
[the remark this answers is not in the document]
Comment (corrad82-4s) [reply dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java:908]: Hi @tdonohue , sorry for jumping into this thread. If I am not wrong, this if and the one following are into an iteration through query response, so only the second (line 920) could be embedded into the first. While the remaining (lines 944, 981 and 1013 would have to be embedded into an ad hoc if (if (!skipLoadingResponse)).

File: dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java [hunk 9]
```diff
@@ -861,141 +858,184 @@ protected SolrQuery resolveToSolrQuery(Context context, DiscoverQuery discoveryQ
...
-            if (solrQueryResponse.getSpellCheckResponse() != null) {
-                String recommendedQuery = solrQueryResponse.getSpellCheckResponse().getCollatedResult();
-                if (StringUtils.isNotBlank(recommendedQuery)) {
-                    result.setSpellCheckQuery(recommendedQuery);
-                }
+            // If any stale entries are found in the current page of results,
+            // we remove those stale entries and rerun the same query again.
+            // Otherwise, the query is valid and the results are returned.
+            if (zombieDocs.size() != 0) {
+                log.info("Cleaning " + zombieDocs.size() + " stale objects from Discovery Index");
```
Comment (Raf-atmire) [inline dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java:1024]: Could we possibly add the logging of the UUIDs here as well? This way we'll have logs incase docs are ever deleted and we don't know why

**Review by Raf-atmire — CHANGES_REQUESTED** [review]
Hi @Micheleboychuk @abollini Thank you for the work on this PR, it's much appreciated!
I'd like to add two more change requests, they're very very minor ones and just improve readability and logging.
I agree with @tdonohue about nesting that particular if right after the initial skipLoadingResponse check.
I'd greatly appreciate it if those minor comments could be addressed. Thank you!

**Comment by tdonohue** [comment]
@Micheleboychuk : As #3301 was just merged, this PR will need to be rebased on `main` in order to run the newly updated CI build process.

**Review by tdonohue — APPROVED** [review]
👍 Retested today & reviewed the recent updates.  This all looks great to me... thanks again @Micheleboychuk !

@Raf-atmire or @benbosman : If one of you could give this a final look, it looks (to me) like your feedback has been addressed.

**Review by Raf-atmire — APPROVED** [review]
Thank you for the work @Micheleboychuk and @abollini 
Everything does indeed look fine to me! +1 from me.
