### PR TITLE
fix(#10721): Sanitize non-characters during OAI indexing

### LINKED ISSUE #10721: OAI harvesting crashes when it encounters forbidden XML characters
## Describe the bug
OAI harvesting crashes when it encounters a [forbidden character in XML](https://en.wikipedia.org/wiki/Valid_characters_in_XML) such as U+FFFE or U+FFFF. This prevents OAI harvesting from completing, responding with an HTTP 500.

Snippet from `dspace.log`:

```
2025-05-08 14:39:47,893 ERROR unknown a52ce868-baa5-4f06-9ffb-caf6cb95428c org.dspace.xoai.controller.DSpaceOAIDataProvider @ org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 3978; Character reference "&#xfffe" is an invalid XML character.
com.lyncode.xoai.dataprovider.exceptions.OAIException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 3978; Character reference "&#xfffe" is an invalid XML character.
```

Full stack trace: [error.log](https://github.com/user-attachments/files/20118629/error.log)

Removing the character from the item allows OAI harvesting to complete successfully.

## To Reproduce
1. Add a U+FFFE character (literal: `￾`) into an item's description, abstract, title, or any other field used in OAI.
2. Re-index OAI with `dspace oai import`
3. Clean OAI response cache with `dspace oai clean-cache`
4. Attempt to harvest OAI (in my case the error always happened on page 200 of the results, which took a bit of trial and error to find)

To harvest OAI, use a loop iterating over the pages of results 100 at a time like:

```console
$ for start in {20000..21000..100}; do curl -o /dev/null -s -w "%{http_code}\n" "https://demo.dspace.org/server/oai/request?resumptionToken=xoai////$start&verb=ListRecords" ; done
200
200
500
^C
```

## Expected behavior
DSpace should not crash.

### PR DESCRIPTION
**Pull request by JohnnyMendesC**
## References
* Fixes #10721 

## Description
This pull request prevents OAI-PMH harvesting from crashing when encountering items with invalid XML non-characters (like U+FFFE and U+FFFF) in their metadata. The fix sanitizes metadata values during the OAI indexing process, ensuring that the generated XML is always well-formed.

## Instructions for Reviewers
This PR introduces a sanitization step within the OAI indexing process to solve a fatal SAXParseException caused by invalid XML characters in item metadata. The core change is in dspace-oai/src/main/java/org/dspace/xoai/util/ItemUtils.java.

List of changes in this PR:
* A new private static String sanitize(String value) method has been added to ItemUtils.java. This method removes the XML 1.0 non-characters U+FFFE and U+FFFF.
* The existing public static Element.Field createValue(String name, String value) method in the same class has been modified to use this sanitize function on all values before creating a metadata field. This ensures all metadata processed for OAI is clean, preventing the XML parser from crashing.
* The original item data in the PostgreSQL database remains untouched.

### 1 - How to reproduce the bug (before this fix):
* Create an item and, through the UI or directly in the database, add a U+FFFE or U+FFFF character to a metadata field (e.g., dc.title).
* Run a full OAI re-index: [dspace]/bin/dspace oai -c import.
* Attempt to harvest all records via OAI-PMH: curl -v "[dspace.server.url]/oai/request?verb=ListRecords&metadataPrefix=oai_dc".
* Expected result (without fix): An HTTP 500 error is returned, and the dspace.log shows a SAXParseException for an invalid XML character.

### 2 - How to verify the fix:
* Apply this PR, rebuild DSpace (mvn package), and update your installation (ant update).
* With the "dirty" data still in the database, run a full OAI re-index again: [dspace]/bin/dspace oai -c import.
* Attempt to harvest all records again: curl -v "[dspace.server.url]/oai/request?verb=ListRecords&metadataPrefix=oai_dc".
* Expected result (with fix): The command returns HTTP 200 OK. The OAI-PMH XML response is displayed successfully, and the metadata for the problematic item appears with the invalid characters removed. The dspace.log shows no errors.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome).
However, reviewers may request that you complete any actions in this list if you have not done so. If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is created against the main branch of code.
- [x] My PR is small in size (it's a change to a single file).
- [x] My PR passes Checkstyle validation (I've followed the existing style of the file).
- [x] My PR includes Javadoc for the new sanitize method.
- [ ] My PR **passes all tests and includes new/updated Unit or Integration Tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR includes details on how to test it.
- [x] My PR does not include new libraries/dependencies.
- [x] My PR does not modify REST API endpoints.
- [x] My PR does not include new configurations.
- [x] My PR fixes an issue ticket and I've linked them together.

### CODE REVIEW

File: dspace-oai/src/main/java/org/dspace/xoai/util/ItemUtils.java [hunk 1]
```diff
@@ -165,6 +165,19 @@ private static Element createBundlesElement(Context context, Item item) throws S
...
+     * Sanitizes a string to remove characters that are invalid in XML 1.0.
+     * Currently targets the non-characters U+FFFE and U+FFFF.
+     * @param value The string to sanitize.
+     * @return A sanitized string, or null if the input was null.
+     */
+    private static String sanitize(String value) {
+        if (value == null) {
+            return null;
+        }
+        return value.replace("\ufffe", "").replace("\uffff", "");
```
Comment (tdonohue) [inline dspace-oai/src/main/java/org/dspace/xoai/util/ItemUtils.java]: @JohnnyMendesC : Rather than hardcoding this to only replace these two characters, I wonder if it'd be better to use
```
return StringEscapeUtils.escapeXml10(value);
```

According to the documentation for `org.apache.commons.text.StringEscapeUtils`, it sounds like that utility class may be all we need here: https://commons.apache.org/proper/commons-text/javadocs/api-release/org/apache/commons/text/StringEscapeUtils.html

Generally, it's obviously better to use an existing sanitization method (if we can find one).  So, I think this might be our best approach, assuming it also fixes the bug.

Comment (JohnnyMendesC) [reply dspace-oai/src/main/java/org/dspace/xoai/util/ItemUtils.java]: Thank you for the guidance, Tim.
Using the existing utility class is definitely a more robust and maintainable approach. 
I'll update the code, re-run the tests to confirm it fixes the bug, and will report back here with the results.

Comment (JohnnyMendesC) [reply dspace-oai/src/main/java/org/dspace/xoai/util/ItemUtils.java]: Hi @tdonohue ,

Just wanted to confirm that the tests were successful with the StringEscapeUtils method. 

It works perfectly, the OAI harvest completes successfully, the malformed XML error is resolved and no longer returns a 500 error.

Thanks again for your great suggestion!

**Comment by nwoodward** [comment]
Hi @JohnnyMendesC. This PR looks good, but I'm unable to reproduce the bug. I don't think I'm adding the invalid XML characters correctly. Could you tell me how you're doing that?

**Comment by JohnnyMendesC** [comment]
Hi @nwoodward, thanks for looking into this!

These non-characters are indeed tricky to generate manually. To make it as easy as possible to reproduce the bug, you can use this simple Python one-liner to print a string containing the invalid U+FFFE non-character to your console:
`python -c "print('Test title with non-character \ufffe')"`
You can then copy the output of that command and paste it directly into a metadata field (e.g., dc.title) in the submission page of DSpace. This is the most direct way to trigger the original bug.

For more comprehensive testing, I've prepared a Python script that generates a text file with a wider range of invalid XML characters. Running the script below will create a file named `invalid_xml_characters` in the same directory.
```python
# Script to generate a file with various invalid XML characters for testing DSpace issue #10721

# Define the invalid/problematic XML characters to be tested
# Based on the XML 1.0 standard, section 2.2 Characters
ufff0 = '\ufff0'
ufff1 = '\ufff1'
ufff2 = '\ufff2'
ufff3 = '\ufff3'
ufff4 = '\ufff4'
ufff5 = '\ufff5'
ufff6 = '\ufff6'
ufff7 = '\ufff7'
ufff8 = '\ufff8'
ufff9 = '\ufffa'
ufffa = '\ufffa'
ufffb = '\ufffb'
ufffc = '\ufffc'
ufffd = '\ufffd' # Replacement character
ufffe = '\ufffe' # Non-character
uffff = '\uffff' # Non-character
x00 = '\x00'   # Null character

# Content that will be written to the file
file_content = (
    f"This is a test file for DSpace issue #10721.\n\n"
    f"It contains several characters that are considered invalid in XML 1.0:\n\n"
    f"Unassigned Characters (part of the U+FDD0-U+FDEF block):\n"
    f"ufff0 = '{ufff0}'\n ufff1 = '{ufff1}'\n ufff2 = '{ufff2}'\n ufff3 = '{ufff3}'\n"
    f"ufff4 = '{ufff4}'\n ufff5 = '{ufff5}'\n ufff6 = '{ufff6}'\n ufff7 = '{ufff7}'\n"
    f"ufff8 = '{ufff8}'\n\n"
    f"Special-Use Characters:\n"
    f"ufff9 = '{ufff9}'\n ufffa = '{ufffa}'\n ufffb = '{ufffb}'\n ufffc = '{ufffc}'\n\n"
    f"Replacement Character:\n"
    f"ufffd = '{ufffd}'\n\n"
    f"Non-characters (the primary cause of the issue):\n"
    f"ufffe = '{ufffe}'\n uffff = '{uffff}'\n\n"
    f"Null Character:\n"
    f"NUL (x00) = '{x00}'\n"
)

# Name of the file to be created
file_name = "invalid_xml_characters"

try:
    # Open the file in write mode ('w') with UTF-8 encoding
    with open(file_name, "w", encoding="utf-8") as f:
        f.write(file_content)
    print(f"File '{file_name}' created successfully in the current directory.\n")
    print("You can now use its content to create a new submission in DSpace.\n")

except Exception as e:
    print(f"An error occurred while creating the file: {e}")
``` 
Which generates the following file after you run the script:
[invalid_xml_characters.txt](https://github.com/user-attachments/files/22406983/invalid_xml_characters.txt)

You can then use the content of the generated file for your tests. It's best to open it with a code editor that properly handles UTF-8 (like VS Code, Sublime Text, or Notepad++) to inspect the characters.

Hope this helps, and please let me know if you have any other questions!

**Review by nwoodward — APPROVED** [review]
👍 Thanks @JohnnyMendesC! That's what I needed. I tested with the characters provided and confirmed this PR fixes the 500 error when harvesting from the OAI feed.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @JohnnyMendesC !  This looks good to me too
