### PR TITLE
Uri parameters not added for self link

### LINKED ISSUE #2919: URI parameters not properly added for self-links
**Describe the bug**
The self-links for calls that contain uri parameters are not correct.
They are missing the initial parameters, which results in incorrect links being created.
For a full scope of the problem. This is also mentioned in https://github.com/DSpace/DSpace/pull/2782#issuecomment-648078138
  
**To Reproduce**
This is not limited to the PR for the Usage reports, this was previously also the case for other search endpoints as well
* Go to https://dspace7-demo.atmire.com/server/#/server/api/core/metadatafields/search/bySchema?schema=dc
    * That self link contains only 'https://dspace7-demo.atmire.com/server/api/core/metadatafields/search/bySchema', so the schema parameter is missing, resulting in an error when following that link

**Expected behavior**
The self-link should be the same at the initial request and resolve to a correct endpoint

**Related work**
This was initially noticed for PR: https://github.com/DSpace/DSpace/pull/2782

### PR DESCRIPTION
**Pull request by jonas-atmire**
## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #2919 
* Initially noticed in [this issue](https://github.com/DSpace/DSpace/pull/2782#issuecomment-648078138)
#### List of changes in this PR:
* The executeSearchMethods method in RestResourceController.java has been extended to now also return the parameters that were initially send in the request back using the self link
* The parameters are passed along to 'getEncodedParameterStringFromRequestParams' which basically takes in the request parameters, and similarly to [SearchFacetValueHalLinkFactory](https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/link/search/SearchFacetValueHalLinkFactory.java#L35) utilises the UriComponentsBuilder to build the URI, with the addition of an encode, to make sure that the link remains exactly the same

#### Steps to test
* Navigate to {url}/api/core/metadatafields/search/bySchema?schema=dc
    * That self link should contain exactly the same {url}/api/core/metadatafields/search/bySchema?schema=dc
* Navigate to {url}/api/core/metadatafields/search/bySchema (So, without parameters)
    * That self link should contain exactly the same {url}/api/core/metadatafields/search/bySchema

The self-links should be the same as the initial request and resolve to a correct endpoint

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

File: dspace-server-webapp/src/test/java/org/dspace/app/rest/RestResourceControllerIT.java [hunk 1]
```diff
@@ -71,4 +73,24 @@ public void notExistentResourceValidSubPath() throws Exception {
...
+                           "/api/core/metadatafields/search/byFieldName?schema=dc&offset=0")));
+    }
+
+    @Test
+    public void selfLinkDevoidOfRequestParametersWhenNoneProvided() throws Exception {
+        // When we call the root endpoint
+        getClient().perform(get("/api/core/metadatafields/search/byFieldName"))
+                   // The status has to be 404 Not Found
+                   .andExpect(jsonPath("$._links.self.href",
+                                       endsWith("/api/core/metadatafields/search/byFieldName")));
```
Comment (abollini) [inline dspace-server-webapp/src/test/java/org/dspace/app/rest/RestResourceControllerIT.java:91]: please update / remote the comments as they don't apply to these tests

**Review by abollini — APPROVED** [review]
thanks @jonas-atmire the fix looks good to me, just for your reference I have hit the same bug a couple of weeks ago but I miss to create a PR (sorry for that) see https://github.com/4Science/DSpace/commit/abe46193df9924a634165134e0a771879b73dcf7 

anyway your code seems cleaner to me so we should include your solution.
Can you just fix the two comments in the test before merge?

I have also noted that the same exact issue apply to the findAll, can you check if it is something quick to include in this PR or that otherwise should go in a separate PR?

File: dspace-server-webapp/src/test/java/org/dspace/app/rest/RestResourceControllerIT.java (hunk 1 above)
Comment (jonas-atmire) [reply dspace-server-webapp/src/test/java/org/dspace/app/rest/RestResourceControllerIT.java]: @abollini Good catch, I'd copied the previous tests, but neglected to update the code docs.
Update these accordingly
