### PR TITLE
[CST-4882] The search loads indefinitely if the written query is invalid

### LINKED ISSUE #1365: The search loads indefinitely if the written query is invalid
**Describe the bug**
The search that can be done from the search page and from the mydspace does not produce results, and loads indefinitely, if the query entered in the input is not valid. 
Example: https://demo7.dspace.org/search?spc.page=1&query=test:&spc.sf=score&spc.sd=DESC

**To Reproduce**
1. Search for a string like 'test:' or for any other string that does not represent a syntactically valid query

**Expected behavior**
At least one error message should be shown when this problem occurs.
It should also be considered whether to allow the user to search by escaping the characters entered in the input or using the DisMax Query Parser (https://solr.apache.org/guide/8_1/the-dismax-query-parser.html). A search of this type could be useful for example if you want to search for a word ending with ':' .

### PR DESCRIPTION
**Pull request by davide-negretti**
## References
* Fixes DSpace/dspace-angular#1365
* Related to DSpace/dspace-angular#1419

## Description
Return 422 instead of 500 when Solr query is not valid.

## Instructions for Reviewers
If Solr query throws an exception containing "Cannot parse" in its message error then the GET request throws an `UnprocessableEntityException` (error 422)

This can by tested by searching `test:`.

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Review by mspalti — COMMENTED** [review]
@davidenegretti-4science , this looks good to me. The error response was returned as expected in my testing. I'm happy to approve, pending responses to my very minor question about debugging messages.

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/DiscoveryRestController.java [hunk 1]
```diff
@@ -198,13 +211,23 @@ public RepresentationModel getFacetValues(@PathVariable("name") String facetName
...
+        try {
+            FacetResultsRest facetResultsRest = discoveryRestRepository
+                .getFacetObjects(facetName, prefix, query, dsoTypes, dsoScope, configuration, searchFilters, page);
+
+            FacetResultsResource facetResultsResource = converter.toResource(facetResultsRest);
+
+            halLinkService.addLinks(facetResultsResource, page);
+            return facetResultsResource;
+        } catch (Exception e) {
+            System.out.println("ERROR = " + e.getMessage());
```
[the remark this answers is not in the document]
Comment (davidenegretti-4science) [reply dspace-server-webapp/src/main/java/org/dspace/app/rest/DiscoveryRestController.java]: Sorry, not needed, I removed both of them

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/DiscoveryRestController.java [hunk 2]
```diff
@@ -149,13 +152,22 @@ public SearchResultsResource getSearchObjects(@RequestParam(name = "query", requ
...
+        try {
+            SearchResultsRest searchResultsRest = discoveryRestRepository.getSearchObjects(query, dsoTypes, dsoScope,
+                configuration, searchFilters, page, utils.obtainProjection());
+
+            //Convert the Search JSON results to paginated HAL resources
+            SearchResultsResource searchResultsResource = new SearchResultsResource(searchResultsRest, utils, page);
+            halLinkService.addLinks(searchResultsResource, page);
+            return searchResultsResource;
+        } catch (IllegalArgumentException e) {
+            boolean isParsingException = e.getMessage().contains(SOLR_PARSE_ERROR_MESSAGE);
```
Comment (tdonohue) [inline dspace-server-webapp/src/main/java/org/dspace/app/rest/DiscoveryRestController.java:164]: I'm worried that this is a fragile way of determining whether Solr threw a SyntaxError. Usually, we don't try to depend on the text of an error message to determine the error type (as if Solr changes the error message here, our code will start to strangely fail)

Are you sure this is the only way to achieve this?  It looks, to me, like the `IllegalArgumentException` thrown here is wrapping a `org.apache.solr.search.SyntaxError` (which is what Solr actually throws).  Maybe we could just check what error we are wrapping, somewhat like this https://stackoverflow.com/a/29252884

```
if (ExceptionUtils.indexOfThrowable(e, SyntaxError.class) != 1) {
    throw new UnprocessableEntityException(e.getMessage());
}
```

That might remove the need for this `SOLR_PARSE_ERROR_MESSAGE` constant altogether.

**Review by tdonohue — COMMENTED** [review]
@davidenegretti-4science : I tested this alongside https://github.com/DSpace/dspace-angular/pull/1419 and the basics work.

However, I have an inline suggestion below on how to create less fragile code... I'm worried your current implementation is a bit fragile.

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/DiscoveryRestController.java (hunk 2 above)
Comment (davidenegretti-4science) [reply dspace-server-webapp/src/main/java/org/dspace/app/rest/DiscoveryRestController.java:164]: @tdonohue I do agree that this solution is not robust but I haven't been able to find a better solution.

I cannot use `ExceptionUtils` because that specific exception is thrown by Solr server, not by DSpace. The root exception in the stack trace is:

```
Caused by: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://localhost:8983/solr/search: org.apache.solr.search.SyntaxError: Cannot parse 'test:': Encountered "<EOF>" at line 1, column 5.
```

The only Java exception that can be handled with `ExceptionUtils` is `RemoteSolrException`, which is too much generic, and `org.apache.solr.search.SyntaxError` is just plain text in the error message. However, I could replace the value of `SOLR_PARSE_ERROR_MESSAGE` with the name of the exception. This could make the code slightly less non-robust, assuming that the exception name is more unlikely to be changed rather than exception message.

Comment (tdonohue) [reply dspace-server-webapp/src/main/java/org/dspace/app/rest/DiscoveryRestController.java:164]: @davidenegretti-4science : OK, in that case, I'd recommend we change the value of `SOLR_PARSE_ERROR_MESSAGE` to include the name of the exception, as you suggested.  I'd also ask that you add some inline code comments to describe *why* we are doing this approach (as it's not very robust & I don't want to recommend that other developers "borrow" or reuse this code elsewhere in future work).  So, even saying something like:

"We unfortunately have to do a string comparison to locate the source of the error, as Solr only sends back a generic exception, and the org.apache.solr.search.SyntaxError is only available in the error message."

Comment (davidenegretti-4science) [reply dspace-server-webapp/src/main/java/org/dspace/app/rest/DiscoveryRestController.java]: @tdonohue I've pushed this correction

**Review by mspalti — APPROVED** [review]
This looks good to me.  

@davidenegretti-4science , I'm glad you and @tdonohue discussed the fragile string comparison here. I almost commented on it was well, and I agree that the exception name is probably less fragile than the error message.

**Review by tdonohue — APPROVED** [review]
👍 Looks good to me now too. Thanks @davidenegretti-4science !  Tested with https://github.com/DSpace/dspace-angular/pull/1419 and it works
