### PR TITLE
[DURACOM-149] correctly handle dates in pubmed live import

### LINKED ISSUE #8877: Item imported from Pubmed contains an invalid date
**Describe the bug**
Importing an item from Pubmed using the Live Import Framework, I noticed that the dc.date.issued contains an invalid date.

**To Reproduce**
1. Go to MyDSpace
2. Start the Import metadata from an external source
3. Enter the DOI `10.1016/j.nepr.2023.103548` and specify Pubmed
4. Start the submission with the item
5. The Date of Issue field contains `NaN` for month, since it was `Feb` on the pubmed publication https://pubmed.ncbi.nlm.nih.gov/36708638/

Following a video about the issue:
[screencast-localhost_4000-2023.06.01-08_47_46.webm](https://github.com/DSpace/DSpace/assets/36161521/34e0062e-8740-45ed-9aa7-fb3f88e7278e)

**Expected behavior**
The Pubmed integration should handle better the date issued.

### PR DESCRIPTION
**Pull request by francescopioscognamiglio**
## References
* Fixes #8877 

## Description
The date mapper used by Pubmed Live Import use the right formatter for each format.

## Instructions for Reviewers
I changed the mapper `PubmedDateMetadatumContributor.java` to format the date properly.
Since there are no integration tests for the Pubmed integration of Live Import, I created a new class `PubmedImportMetadataSourceServiceIT.java` and added them.

Steps to test the improvement:
1. Go to MyDSpace
2. Start the Import metadata from an external source
3. Enter the DOI 10.1016/j.nepr.2023.103548 and specify Pubmed
4. Start the submission with the item
5. The Date of Issue field contains 2023-02 (pubmed publication https://pubmed.ncbi.nlm.nih.gov/36708638/)

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [ ] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

File: dspace-server-webapp/src/test/java/org/dspace/app/rest/PubmedImportMetadataSourceServiceIT.java [hunk 1]
```diff
@@ -0,0 +1,213 @@
...
+import org.dspace.importer.external.metadatamapping.MetadatumDTO;
+import org.dspace.importer.external.pubmed.service.PubmedImportMetadataSourceServiceImpl;
+import org.junit.Test;
+import org.mockito.ArgumentMatchers;
+import org.mockito.Mockito;
+import org.springframework.beans.factory.annotation.Autowired;
+
+/**
+ * Integration tests for {@link PubmedImportMetadataSourceServiceImpl}
+ *
```
Comment (alanorth) [inline dspace-server-webapp/src/test/java/org/dspace/app/rest/PubmedImportMetadataSourceServiceIT.java:33]: Trailing whitespace here.

Comment (francescopioscognamiglio) [reply dspace-server-webapp/src/test/java/org/dspace/app/rest/PubmedImportMetadataSourceServiceIT.java]: Thank you @alanorth, I removed it.

**Comment by alanorth** [comment]
Reviewed by testing an import with PubMed ID 35101981 and the date was handled correctly. I had previously noticed that the date format was "2022-Feb-08", which translates to NaN when you import it.

First, the PubMed item import preview:
 
<p align="center">
  
</p>

Then the correct date in the submission form:

<p align="center>
  
</p>

**Review by alanorth — APPROVED** [review]
