### PR TITLE
Fixed item edit relationships with same type name but different entities all being shown under same label

### LINKED ISSUE #1387: Entities relations with invalid associations shown
**Describe the bug**
My model has two relation types, with same relation name, but involving different entities:
```
	<type>
		<leftType>Publication</leftType>
		<rightType>Person</rightType>
		<leftwardType>isAuthorOfPublication</leftwardType>
		<rightwardType>isPublicationOfAuthor</rightwardType>
		<leftCardinality>
			<min>0</min>
		</leftCardinality>
		<rightCardinality>
			<min>0</min>
		</rightCardinality>
	</type>
	<type>
		<leftType>Publication</leftType>
		<rightType>OrgUnit</rightType>
		<leftwardType>isAuthorOfPublication</leftwardType>
		<rightwardType>isPublicationOfAuthor</rightwardType>
		<leftCardinality>
			<min>0</min>
		</leftCardinality>
		<rightCardinality>
			<min>0</min>
		</rightCardinality>
	</type>
```
But when I try to associate a Person as an author, that Person, will be shown simultaneously as `Authors (persons)` relation and `Authors (organizational units)`

**To Reproduce**
1. You can use `/dspace/config/entities/openaire4-relationships.xml` as your model
2. And set `dspace.​entity.​type = Publication` to any existing Item
3. At edit item `Relationships` separator, use lookup to associate an author
4. After you added the relations to that entity, strange associations will be shown
image

And if you refresh the page, you will get 2 associations:
 image

It seems an issue with Relationships separator, because item page is shown as expected.

**Expected behavior**
I was expecting to have only one association, or to be shown only one `Authors (persons)` relation.

### PR DESCRIPTION
**Pull request by alexandrevryghem**
## References
* Fixes DSpace/dspace-angular#1387
* Requires DSpace/dspace-angular#3098
* RestContract DSpace/RestContract#270

## Description
Fixes the item edit relationships tab showing relationships under multiple labels when those relationship types have the same `leftwardType`/`rightwardType` (but different entity types).

## Instructions for Reviewers
List of changes in this PR:
* Added the `relatedEntityType` parameter to the `/server/api/core/relationships/search/byLabel` endpoint. This parameter only works when the `dso` parameter is provided and will filter out the relationship types that don't have the dso's entity type & the given related entity type as `leftType`/`rightType`.

**Guidance for how to test/review this PR:** See DSpace/dspace-angular#1387

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

File: dspace-server-webapp/src/test/java/org/dspace/app/rest/RelationshipRestRepositoryIT.java [hunk 1]
```diff
@@ -2322,6 +2322,61 @@ public void findRelationshipByLabelTest() throws Exception {
...
+                                .param("dso", publication1.getID().toString())
+                                .param("relatedEntityType", "Person")
+                                .param("projection", "full"))
+
+            .andExpect(status().isOk())
+            .andExpect(jsonPath("$.page", is(PageMatcher.pageEntryWithTotalPagesAndElements(0, 20, 1, 1))))
+            .andExpect(jsonPath("$._embedded.relationships", containsInAnyOrder(
+                RelationshipMatcher.matchRelationship(relationship1)
+            )))
+        ;
```
Comment (tdonohue) [inline dspace-server-webapp/src/test/java/org/dspace/app/rest/RelationshipRestRepositoryIT.java:2377]: Could you also add a GET request to this test for the `OrgUnit`?  That would be an enhanced test that this `relatedEntityType` param is returning _different_ objects for different values.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @alexandrevryghem !  This looks good overall & works, but I'd appreciate it if we could make a **minor enhancement** to the IT in this PR.  I think we need to "prove" that `relatedEntityType` is returning different objects for different values.  See inline comment below.

Overall, I'm +1 this PR but would appreciate this minor improvement to the IT.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @alexandrevryghem !  This looks good to me now
