### PR TITLE
Inherit custom, non-admin policies when creating new bundles

### LINKED ISSUE #9212: A new bundle does not inherit resource policies from the item if the itemConditionStep was activated in submission
**Describe the bug**
I discoverd this when looking into [dspace-angular#2665](https://github.com/DSpace/dspace-angular/issues/2665). I'm not entirely sure if this is a bug, but I think we should discuss it.

If an item is created in DSpace, it inherits resource policies from the collection (`DEFAULT_ITEM_READ`, `DEFAULT_BITSTREAM_READ`). These policies will be of type `TYPE_INHERITED`. If the `itemAccessCondition` is active in submission, it  will create item resource policies of the type `TYPE_CUSTOM`.

When a new bundle is creted, it will inherit resource policies from the item, unless resource policies of type `ADMIN` and of type `TYPE_CUSTOM` (see [AuthorizeServiceImple in DSpace's backend](https://github.com/DSpace/DSpace/blob/1e82ca7998c45bd628cd84cefce9ae3f0a0ce046/dspace-api/src/main/java/org/dspace/authorize/AuthorizeServiceImpl.java#L520)). This leads to a situation where bundles do not inherite resource policies from items if the resource policies of the item are of type `TYPE_CUSTOM` for example because the `itemAccessCondition` set the resource policies on the item.

In a very short test, I changed the code to inherit also resource policies of type `TYPE_CUSTOM`. This lead to multiple identical resource policies being generated for an item.

I think we should inherit resource policies of type `TYPE_CUSTOM` and filter out identical resource policies. If there are reasons to not do this in general, we should at least do this when we create new bundles and inherit resource policies from their items. As this might have lager side-effects, I would like to discuss this.

**To Reproduce**
1. Create an item with a file for which you can create thumbnails (e.g. a PDF file)
2. Activate the itemAccessCondition in `item-submission.xml`
3. Create an item with a file for which you can create thumbnails (e.g. a PDF file)
5. run `/dspace/bin/dspace filter-media`
6. Check the resource policies of the bundle `THUMBNAIL` of both items

**Expected behavior**
Bundles should inherite resource policies of type `TYPE_CUSTOM` without creating duplicate resource policies.

**Related work**
[dspace-angular#2665](https://github.com/DSpace/dspace-angular/issues/2665)

### PR DESCRIPTION
**Pull request by kshepherd**
This pull request ensures that resource policies of TYPE_CUSTOM (for example, those created by an item access condition step during submission) are inherited by newly created bundles (for example, a new THUMBNAIL bundle created by filter-media).
Also shifted some resource policy methods from ItemService to AuthorizeService as they seemed better suited there.

## References
* Fixes #9212

**Note:** Though this solves the specific issue addressed in #9212, and I have added tests, it is not the only way of solving this and some more discussion on the issue itself might be preferable.

This is tangentially related to
*  https://github.com/DSpace/DSpace/issues/9679 in as much as inheritance isn't always working as expected.
* https://github.com/DSpace/DSpace/issues/9279 same as above
* https://github.com/DSpace/DSpace/issues/8325 related to thumbnails of restricted bitstreams

## Instructions for Reviewers
To reproduce, I have copied the instructions from the related issue:

Create an item with a file for which you can create thumbnails (e.g. a PDF file)
Activate the itemAccessCondition in item-submission.xml
Create an item with a file for which you can create thumbnails (e.g. a PDF file)
run /dspace/bin/dspace filter-media
Check the resource policies of the bundle THUMBNAIL of both items

I would also recommend creating other combinations of custom and inherited permissions, creating child objects and inspecting which policies are being inherited and which are not.

If there are objections to this being default behaviour, I can add configuration.

If we decide that instead / as well as this change, we should create a new `TYPE_EMBARGO` to be more clear about how we treat inheritance of these policies, I can also alter this PR or create a new one.

List of changes in this PR:
* Some methods moved from `ItemService` to `AuthorizeService` as they just seemed better suited there
* New `AuthorizeService#inheritPolicies(..., boolean)` added where the boolean flag specifies whether custom policies should also be inherited (if not already present)
* `ItemService#addBundle` passes `true` to the above new method. All other usages remain unchanged. The default behaviour of the existing `inheritPolicies` method with no boolean arg is to call the new one with `false`
* New tests written in `AuthorizeServiceTest` to ensure the new code works

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome).
However, reviewers may request that you complete any actions in this list if you have not done so. If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR **passes Checkstyle** validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR **includes Javadoc** for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR **passes all tests and includes new/updated Unit or Integration Tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by nwoodward — APPROVED** [review]
Thanks @kshepherd! I tested this locally, and it fixes a very common (>100k items) problem in our repositories with `itemAccessCondition` enabled. 

The approach seems reasonable to me, as well as moving the methods to `AuthorizeService`. It makes sense that the `THUMBNAIL` and `TEXT` bundles would get the same `TYPE_CUSTOM` type as the `ORIGINAL` and `LICENSE` bundles.

While I could see the potential benefit of a new `TYPE_EMBARGO` type in terms of making things more clear, I think others can speak for if it's necessary or a superior solution to this one.

File: dspace-api/src/main/java/org/dspace/authorize/AuthorizeServiceImpl.java [hunk 1]
```diff
@@ -507,17 +511,26 @@ public List<ResourcePolicy> getPoliciesActionFilter(Context c, DSpaceObject o,
...
     public void inheritPolicies(Context c, DSpaceObject src,
-                                DSpaceObject dest) throws SQLException, AuthorizeException {
+                                DSpaceObject dest, boolean includeCustom) throws SQLException, AuthorizeException {
         // find all policies for the source object
         List<ResourcePolicy> policies = getPolicies(c, src);
 
-        //Only inherit non-ADMIN policies (since ADMIN policies are automatically inherited)
-        //and non-custom policies as these are manually applied when appropriate
+        // Only inherit non-ADMIN policies (since ADMIN policies are automatically inherited)
+        // and non-custom policies (usually applied manually?) UNLESS specified otherwise with includCustom
```
Comment (nwoodward) [inline dspace-api/src/main/java/org/dspace/authorize/AuthorizeServiceImpl.java:527]: Typo: includCustom => includeCustom

**Review by tdonohue — APPROVED** [review]
👍 Thanks @kshepherd !  I've reviewed the code and new tests.  The overall code changes here are small (most of the PR is moving methods between ItemServiceImpl and AuthorizeService).  The new behavior seems reasonable to me to have enabled by default.

**Comment by tdonohue** [comment]
@kshepherd : Could you manually backport this to `dspace-7_x`?  It looks like only the backports to 9.x and 8.x worked properly (see above)
