### PR TITLE
Fixed embedding data not working on model objects ending with an `s`

### LINKED ISSUE #9240: Embedding data doesn't work for some rest objects
**Describe the bug**
Some rest objects throw a 404 error when you try to embed data, this only happens for rest objects who's singular form ends with an `s`, for example `process`. This is because the [`Utils#getLinkResourceRepository`](https://github.com/DSpace/DSpace/blob/4bf7d178049a28e24b452455bf2db64cc13953b8/dspace-server-webapp/src/main/java/org/dspace/app/rest/utils/Utils.java#L345) always expects the second parameter to be in plural form but this isn't always the case, sometimes it receives the singular form and then the `makeSingular('process')` method removes the last `s` from the model name and so it tries to find the bean `system.proces.files` instead of  `system.process.files`.

**To Reproduce**
Go to a process page in the HAL browser and add an embed parameter to the url like this: [/server/api/system/processes/1?embed=files](https://demo.dspace.org/server/#/server/api/system/processes/1?embed=files), you should see a 404 error

**Expected behavior**
Rest controllers actually don't use the singular name, but the plural name in their beans. It would be better to normalise this behaviour so that the repositories also work like this. This would also mean that we won't have to use the `makeSingular` method anymore to find the beans.

### PR DESCRIPTION
**Pull request by alexandrevryghem**
## References
* Fixes #9240
* Related to DSpace/RestContract#254

## Description
Standardised the repository & rest controller beans, by using the plural name for both of them. This automatically fixes the problems with some endpoints as described in #9240

## Instructions for Reviewers
List of changes in this PR:
* Made the `RestModel#getTypePlural` abstract, this way every rest object has to set the plural name correctly in it's class
* Added the `PLURAL_NAME` variables in all the rest object classes with the correct translation
* Refactored all the `@Components` to use the `PLURAL_NAME` variable instead
* Removed the usages of `makeSingular` in `Utils#getResourceRepository` & `Utils#getLinkResourceRepository`
* Replaced all the usages of `English#plural` that were used on `RestModel#getType`/`RestModel#NAME` with `RestModel#getPluralType`/`RestModel#PLURAL_NAME`
* The `HarvestedCollectionRest` object uses `collections` as value for `NAME` & `PLURAL_NAME`, this is problematic because `CollectionRest` also uses the value `collections` for `PLURAL_NAME`. So I change the `NAME` & `PLURAL_NAME` values from `HarvestedCollectionRest` to `harvestedcollection` & `harvestedcollections` respectively.
* Fixed the tests using incorrect endpoints. Previously both `/server/api/core/site/` & `/server/api/core/sites/` for example were supported because of this bug, but now only the plural form exists anymore. Angular already only used the plural form so no changes were needed there
* Did some other minor refactoring
  * Standardised the name of variables & to some `@RequestMapping`
REGEX_REQUESTMAPPING_IDENTIFIER_AS_UUID

To test this you should verify that you can now embed data on the process endpoint like this: [/server/api/system/processes/1?embed=files](https://demo.dspace.org/server/#/server/api/system/processes/1?embed=files)
Also verify that everything still works like it's supposed to in Angular

## Checklist
- [ ] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by tdonohue — APPROVED** [review]
👍 Thanks @alexandrevryghem !  This looks great.  I've added a few inline notes (mostly for @abollini or other reviewers).  The only one that needs a minor fix is the request for a minor update to our Rest Contract.

I've tested this with the frontend and found no obvious problems.  I've also verified the bug described in #9240 has been fixed.  Honestly, this looks good and seems to fix the problems described without causing new issues.

@abollini : I wanted to alert you though that this makes minor changes to all Rest Model objects.  So, merging this will cause minor code conflicts with PRs which add new endpoints.  I don't think this will be difficult to clean up these conflicts, but it's something to be aware of.  That said, I wanted to alert you as your team has several PRs which create new endpoints.  I'll wait to merge until you have a chance to look at this PR.

File: dspace-server-webapp/src/test/java/org/dspace/app/rest/AuthorizationRestRepositoryIT.java [hunk 1]
```diff
@@ -2575,22 +2575,22 @@ public void findByMultipleObjectsAndFeatureInternalServerErrorTest() throws Exce
...
-            .param("type", "core.site")
+            .param("type", "core.sites")
             .param("uuid", siteId)
             .param("feature", alwaysException.getName()))
             .andExpect(status().isInternalServerError());
 
         // verify that it works for anonymous users
         getClient().perform(get("/api/authz/authorizations/search/objects")
-            .param("type", "core.site")
+            .param("type", "core.sites")
```
[the remark this answers is not in the document]
Comment (abollini) [reply dspace-server-webapp/src/test/java/org/dspace/app/rest/AuthorizationRestRepositoryIT.java:2593]: this is quite impactful as with the previous implementation essentially plural and singular were working equivalent. This is because if we apply the makeSingular function to singular word we get the original input and the lookup for the rest repositories was based on the singular name. With this PR we are looking up the rest repository by their plural name without performing transformation of the user input that mean that we have now a much strict control as demonstrate the need to fix all the url to use the right plural form in the test.
We need to highlight this change as a huge breaking change in DSpace 8.

Please note that also the URI example in https://github.com/DSpace/RestContract/blob/main/authorizations.md#object must be updated to use the correct plural form

Last but not least, due to the lack of e2e coverage for angular, I'm a bit worry about the absence of a corresponding angular PR... maybe our angular UI is already doing things in the right way always using the plural form but what about the `/api/authz/authorizations/search/objects?uuid=<:uuid>&type=<:type>[&eperson=<:uuid>&feature=<:string>]` endpoint? is it not used at all in angular @atarix83 ?

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/authorization/AuthorizationRestUtil.java [hunk 2]
```diff
@@ -66,7 +67,8 @@ public BaseObjectRest getObject(Context context, String id) throws SQLException
         String[] objType;
         try {
             objType = parts[2].split("\\.");
-            DSpaceRestRepository repository = utils.getResourceRepositoryByCategoryAndModel(objType[0], objType[1]);
+            DSpaceRestRepository repository = utils
+                .getResourceRepositoryByCategoryAndModel(objType[0], English.plural(objType[1]));
```
Comment (abollini) [inline dspace-server-webapp/src/main/java/org/dspace/app/rest/authorization/AuthorizationRestUtil.java:71]: why is this required? this seems to be against the goal of this PR to remove the dependency from a computation of the plural

**Review by abollini — CHANGES_REQUESTED** [review]
hi @alexandrevryghem thanks for looking into this needed housekeeping task!
I have added few inline comments, I would like to get some very quick extra test to be protected against future refactoring and I need a clarification about the change in the `AuthorizationRestUtil` class.
@tdonohue please review my inline comment related to the backward compatibility warning to add to the DSpace 8 release, I'm in favor of this cleanup but IMHO we should highlight it in the release note

**Comment by abollini** [comment]
before to be able to merge, we also need the small REST contract PR

**Comment by tdonohue** [comment]
I'm realizing as well that, because of the larger [REST Contract modification](https://github.com/DSpace/DSpace/pull/9241#discussion_r1479310128), this "bug fix" may be difficult to backport to 7.6.x.  Arguably, as a bug fix, we should find a way to backport this as well.  But, for now, I'll remove the `port to dspace-7_x` label as this bug may only be fixable in 8.0

**Comment by tdonohue** [comment]
@alexandrevryghem : I believe this needs to be updated on latest `main`, as I'm now encountering compilation issues when I try to run this locally.  The compilation issues are likely from #8280 as it added some new model objects that aren't updated to align with this PR.

Also, it appears that @abollini 's [feedback](https://github.com/DSpace/DSpace/pull/9241#pullrequestreview-1864384275) hasn't been addressed yet?  Could you either respond to the feedback or address it?

Trying to get this moved forward so that related work can be merged that requires this.

File: dspace-server-webapp/src/test/java/org/dspace/app/rest/AuthorizationRestRepositoryIT.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (alexandrevryghem) [reply dspace-server-webapp/src/test/java/org/dspace/app/rest/AuthorizationRestRepositoryIT.java:2593]: @tdonohue: I already created the rest contract PR to fix the singular endpoints, but I did not create the `CHANGELOG.md` file yet since I don't know if this needs to be in a certain format/what kind of info should be added

[the remark this answers is not in the document]
Comment (tdonohue) [reply dspace-server-webapp/src/test/java/org/dspace/app/rest/AuthorizationRestRepositoryIT.java:2593]: @alexandrevryghem : I'll take care of the CHANGELOG.md once this PR is ready.  You can leave this comment "unresolved" and I'll resolve it once it is documented. So, please just address everything else.

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/authorization/AuthorizationRestUtil.java (hunk 2 above)
Comment (tdonohue) [reply dspace-server-webapp/src/main/java/org/dspace/app/rest/authorization/AuthorizationRestUtil.java:71]: @alexandrevryghem : Did [this question](https://github.com/DSpace/DSpace/pull/9241#discussion_r1479312626) get answered?

Comment (alexandrevryghem) [reply dspace-server-webapp/src/main/java/org/dspace/app/rest/authorization/AuthorizationRestUtil.java:71]: @abollini: thnx for the feedback, I implemented the changes you requested. For the remaining `English.plural`, I did not change it because this would also require all the feature's `getSupportedTypes` methods to be updated as well. I fixed it on a separate branch if you want to include this in this PR too: https://github.com/alexandrevryghem/DSpace/commit/2cf979260aac48c9742d9e4f0d46ea0645855877. I can also open a new PR after this one is merged with these changes, this way we can already merge the process polling PRs 🤷‍♂️

Comment (abollini) [reply dspace-server-webapp/src/main/java/org/dspace/app/rest/authorization/AuthorizationRestUtil.java:71]: it is ok for me to open a separate PR for this additional refactoring (to be considered for DSpace 8 or 9)

**Review by abollini — APPROVED** [review]
my feedback looks addressed, the only residual one https://github.com/DSpace/DSpace/pull/9241#discussion_r1499450901
can be postponed to a separate PR

**Review by tdonohue — APPROVED** [review]
👍 Thanks @alexandrevryghem !  This looks good to me now. Merging immediately along with the process polling PR.

I'm going to add the `needs documentation` flag to this PR simply as a reminder to me that we need to have a `CHANGELOG.md` added to the REST Contract & this change needs to be listed there and in the Release Notes as we [discussed above](https://github.com/DSpace/DSpace/pull/9241#discussion_r1480013617).
