### PR TITLE
Search links in facet values dont contain the configuration

### LINKED ISSUE #3057: Search links in facet values don't contain the configuration
**Describe the bug**
If you retrieve facet values for a discovery search with a particular configuration, the search links for those values don't contain that configuration. As a consequence if the UI uses that link to update the search results, the results will no longer match the configuration, or REST may throw an exception if that facet doesn't work for the default configuration

**To Reproduce**
1. Sign in to the hal browser as an admin
2. Retrieve the `discoverable` facet with the `administrativeView` configuration: https://dspace7.4science.cloud/server/#/server/api/discover/facets/discoverable?page=0&size=10&sort=score,DESC&page=0&size=10&configuration=administrativeView
3. Take a look at the search links for the returned values, they don't contain the configuration
4. If you follow a search link you'll get an exception because the discoverable filter isn't configured for the default configuration

**Expected behavior**
The search links should contain all paramaters from the original request that affect the search results. Note that configuration may not be the only one that is needed. It's just the one I noticed was missing.

**Related work**
This came up during the work on https://github.com/DSpace/dspace-angular/issues/915

### PR DESCRIPTION
**Pull request by Micheleboychuk**
## Description
Fixes #3057

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/DiscoveryRestController.java [hunk 1]
```diff
@@ -201,6 +201,8 @@ public RepresentationModel getFacetValues(@PathVariable("name") String facetName
         FacetResultsRest facetResultsRest = discoveryRestRepository
             .getFacetObjects(facetName, prefix, query, dsoTypes, dsoScope, configuration, searchFilters, page);
 
+        facetResultsRest.setConfiguration(configuration);
```
Comment (Raf-atmire) [inline dspace-server-webapp/src/main/java/org/dspace/app/rest/DiscoveryRestController.java:204]: Could you please move this setter to the method that is responsible for creating the `FacetResultsRest` object? That method is the following `org.dspace.app.rest.converter.DiscoverFacetResultsConverter#convert`

File: dspace-server-webapp/src/test/java/org/dspace/app/rest/DiscoveryRestControllerIT.java [hunk 2]
```diff
@@ -4960,4 +4960,141 @@ public void discoverSearchObjectsTestForAdministrativeViewWithFilters() throws E
                 ))
                 .andExpect(jsonPath("$._links.self.href", containsString("/api/discover/search/objects")));
     }
+
```
Comment (Raf-atmire) [inline dspace-server-webapp/src/test/java/org/dspace/app/rest/DiscoveryRestControllerIT.java:4963]: Since @artlowel mentioned that the issue could occur with more than just the configuration parameter, could you provide a test in which all of the params for the endpoint (listed here `org.dspace.app.rest.DiscoveryRestController#getFacetValues`) are tested and verified? This way we can be sure that we haven't missed any

**Review by Raf-atmire — CHANGES_REQUESTED** [review]
Hi @Micheleboychuk Thank you for the work! I've provided a few change requests inline in the code, could you please have a look when you get around to it? Thanks!

File: dspace-server-webapp/src/test/java/org/dspace/app/rest/DiscoveryRestControllerIT.java (hunk 2 above)
Comment (abollini) [reply dspace-server-webapp/src/test/java/org/dspace/app/rest/DiscoveryRestControllerIT.java]: test to verify the other parameters have been added

**Review by Raf-atmire — APPROVED** [review]

**Comment by tdonohue** [comment]
Merging as this was flagged for `1 Approval`.  I've also done a quick review of the code myself and it all looks good to me.  Thanks @Micheleboychuk !
