### PR TITLE
[DS-4149] porting XOAI additional indexer

### LINKED ISSUE #3284: OAI response contains wrong URL for bitstream
**Describe the bug**
The xoai document contains the old style bitstream URL with unreplaced place holder instead that the new one

**To Reproduce**
1. check the xoai response of any record that contains files
2. https://api7.dspace.org/server/oai/request?verb=GetRecord&metadataPrefix=xoai&identifier=oai:demo7.dspace.org:10673/248
3. the url looks like  `<field name="url">bitstream.baseUrl/bitstream/10673/248/1/Video-Based%20Solution-Focused%20Brief%20Coaching.pdf</field>`

**Expected behavior**
The bitstream URL should work, the right one is https://demo7.dspace.org/bitstreams/b54bc2e4-e37d-4418-a108-79314f95f5a3/download

### PR DESCRIPTION
**Pull request by lap82**
The porting for DSpace 7 has been requested on https://github.com/DSpace/DSpace/pull/2709

The PR contains:
- new Spring context loader for "dspace-oai" project
- new infrastructure to add additional element to the item.compile field (XOAIItemCompilePlugin)
- single implementation for https://openaire-guidelines-for-literature-repository-managers.readthedocs.io/en/v4.0.0/field_licensecondition.html

Jira Ticket here: https://jira.lyrasis.org/browse/DS-4149
 
---
Addition on 27.05.2021
Fixes #3284

### CODE REVIEW

**Comment by tdonohue** [comment]
@lap82 : Could you add details for reviewers on how to test this appropriately?  It's a little unclear even to me the best way to go about testing it....and testing is obviously important here as there's not many automated tests in the `dspace-oai` module.

File: dspace-oai/src/main/java/org/dspace/xoai/app/CCElementAdditional.java [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+import org.dspace.authorize.AuthorizeException;
+import org.dspace.content.Item;
+import org.dspace.core.Context;
+import org.dspace.license.CCLookup;
+import org.dspace.license.factory.LicenseServiceFactory;
+import org.dspace.license.service.CreativeCommonsService;
+import org.dspace.xoai.util.ItemUtils;
+
+/**
+ * Utility class to build xml element to support Creative Commons information
```
Comment (abollini) [inline dspace-oai/src/main/java/org/dspace/xoai/app/CCElementAdditional.java:28]: @tdonohue I would suggest a better description here, can you help me?
what about: OAIItemCompile to add in the xoai document details about the Item CCLicense

File: dspace-oai/src/main/java/org/dspace/xoai/app/CCElementAdditional.java [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+            }
+        } catch (SQLException | IOException | AuthorizeException e) {
+            log.error(e.getMessage(), e);
+        }
+        other.getField().add(ItemUtils.createValue("cc", ccLicense));
+        return metadata;
+    }
+
+    public CreativeCommonsService getCreativeCommonsService() {
+        if (creativeCommonsService == null) {
```
Comment (abollini) [inline dspace-oai/src/main/java/org/dspace/xoai/app/CCElementAdditional.java:65]: is there a reason for this local cache? why not retrieve the CreativeCommonsService via the factory each time? or eventually, can we use autowiring?

File: dspace-oai/src/main/java/org/dspace/xoai/app/XOAI.java [hunk 3]
```diff
@@ -698,4 +708,21 @@ private static void usage() {
...
         }
     }
+
+    /**
+     * Do any additional content on "item.compile" field, depends on the plugins
+     * 
+     * @return
+     */
+    public List<XOAIItemCompilePlugin> getxOAIItemCompilePlugins() {
+        if (xOAIItemCompilePlugins == null) {
```
Comment (abollini) [inline dspace-oai/src/main/java/org/dspace/xoai/app/XOAI.java:718]: is there a reason for this local cache? can we use autowiring?

File: dspace-oai/src/main/java/org/dspace/xoai/app/XOAIItemCompilePlugin.java [hunk 4]
```diff
@@ -0,0 +1,23 @@
...
+import org.dspace.core.Context;
+
+
+/**
+ * Used to enrich item.compile field description
+ *
+ */
+public interface XOAIItemCompilePlugin {
+
+    public Metadata additionalMetadata(Context context, Metadata metadata, Item item);
```
Comment (abollini) [inline dspace-oai/src/main/java/org/dspace/xoai/app/XOAIItemCompilePlugin.java:21]: javadoc is needed here.
what about:
This method allows XOAIItemCompilePlugins to add content to the xoai document generated for the item.
metadata: the basic xoai representation of the item that can be manipulated by the plugin
item: the dspace item to index

File: dspace/config/spring/oai/oai.xml [hunk 5]
```diff
@@ -0,0 +1,24 @@
...
+       xsi:schemaLocation="http://www.springframework.org/schema/beans
+                  http://www.springframework.org/schema/beans/spring-beans-2.5.xsd
+                  http://www.springframework.org/schema/context
+                  http://www.springframework.org/schema/context/spring-context-2.5.xsd">
+
+    <context:annotation-config /> <!-- allows us to use spring annotations in beans -->
+
+	<!-- Additional item.compile plugin to enrich field with information about Creative Commons License metadata -->
+	<bean id="CCElementAdditional"
+	class="org.dspace.xoai.app.CCElementAdditional"/>
```
Comment (abollini) [inline dspace/config/spring/oai/oai.xml:23]: can we indent better please?

**Review by abollini — COMMENTED** [review]
Overall the code looks good to me, I have added some requests inline.

To test this PR it is needed (or at least this is what I have checked)

to have one or more items with CreativeCommons information in it and verify that such information are exposed in the OAI document for the openaire4 context, see
https://openaire-guidelines-for-literature-repository-managers.readthedocs.io/en/v4.0.0/field_licensecondition.html

it is also useful to verify that other items, without CreativeCommons, are still properly exposed in the openaire4 context. The other context are untouched by these changes so no test are needed

File: dspace-oai/src/main/java/org/dspace/xoai/app/XOAIItemCompilePlugin.java [hunk 6]
```diff
@@ -0,0 +1,23 @@
...
+import com.lyncode.xoai.dataprovider.xml.xoai.Metadata;
+import org.dspace.content.Item;
+import org.dspace.core.Context;
+
+
+/**
+ * Used to enrich item.compile field description
+ *
+ */
+public interface XOAIItemCompilePlugin {
```
Comment (paulo-graca) [inline dspace-oai/src/main/java/org/dspace/xoai/app/XOAIItemCompilePlugin.java:19]: As referred this name is confusing to me. Perhaps with a more detailed description I can help you finding a better name.

File: dspace/config/spring/oai/oai.xml [hunk 7]
```diff
@@ -0,0 +1,24 @@
...
+       xmlns:context="http://www.springframework.org/schema/context"
+       xsi:schemaLocation="http://www.springframework.org/schema/beans
+                  http://www.springframework.org/schema/beans/spring-beans-2.5.xsd
+                  http://www.springframework.org/schema/context
+                  http://www.springframework.org/schema/context/spring-context-2.5.xsd">
+
+    <context:annotation-config /> <!-- allows us to use spring annotations in beans -->
+
+	<!-- Additional item.compile plugin to enrich field with information about Creative Commons License metadata -->
+	<bean id="CCElementAdditional"
```
Comment (paulo-graca) [inline dspace/config/spring/oai/oai.xml:22]: I really like what you are proposing. But I would like you to test the real impact of this change and if it affects the xoai processing times in any way.

File: dspace-oai/src/main/java/org/dspace/xoai/app/XOAI.java [hunk 8]
```diff
@@ -455,7 +458,14 @@ private SolrInputDocument index(Item item)
 
         ByteArrayOutputStream out = new ByteArrayOutputStream();
         XmlOutputContext xmlContext = XmlOutputContext.emptyContext(out, Second);
-        retrieveMetadata(context, item).write(xmlContext);
+        Metadata metadata = retrieveMetadata(context, item);
+
+        // Do any additional metadata element, depends on the plugins
+        for (XOAIItemCompilePlugin xOAIItemCompilePlugin : getxOAIItemCompilePlugins()) {
+            metadata = xOAIItemCompilePlugin.additionalMetadata(context, metadata, item);
```
Comment (paulo-graca) [inline dspace-oai/src/main/java/org/dspace/xoai/app/XOAI.java:465]: The camel for XOAI abreviation looks weird here `xOAIItemCompilePlugin` I would prefer to have `xoaiItemCompilePlugin`. 
But as referred I'm also not in love with this name since It's not clear to me what it is. Could you call it xoaiExtensionPlugin  or xoaiAdditionalElementPlugin. I have some difficulty in proposing better names. I would need to better understand what the interface helps doing.

File: dspace/config/crosswalks/oai/metadataFormats/oai_openaire.xsl [hunk 9]
```diff
@@ -81,7 +81,9 @@
             <!-- oaire:citation* -->
             <xsl:apply-templates
                 select="doc:metadata/doc:element[@name='oaire']/doc:element[@name='citation']" mode="oaire"/>
-
+			<!-- CREATIVE COMMON LICENSE -->
+			<xsl:apply-templates
+				select="doc:metadata/doc:element[@name='others']/doc:field[@name='cc']" mode="oaire" />
```
Comment (paulo-graca) [inline dspace/config/crosswalks/oai/metadataFormats/oai_openaire.xsl:86]: I think you could have this with a different structure like a specific element with multiple fields

**Review by paulo-graca — CHANGES_REQUESTED** [review]
Thank you @lap82 for adding this. I didn't yet test it. But this PR seems to add a extension for XOAI (like plugins) and create the support for Creative Commons field. The pull request name doesn't suggest that. I had some difficulty in understanding what you were proposing and I left some comments.
My major concert with this PR is the potential overhead that might bring to XOAI. I propose you to do some testing with master and with this PR and try to evaluate if it has any significant impact.
Again thank you for your work and for bringing more extensibility to XOAI interface!

**Comment by paulo-graca** [comment]
Please mind this PR - https://github.com/DSpace/DSpace/pull/2764
It may affect this work if merged before.

**Comment by tdonohue** [comment]
@lap82 : Just a reminder that this work still needs updates in order to be ready for 7.0.  As 7.0 beta 4 is almost ready to go, I'm rescheduling this for beta 5.  Thanks

**Comment by tdonohue** [comment]
@lap82 : Just a friendly reminder that these changes have *not* made their way into 7.0 yet (even though they are in 6.x).  We've just started development on 7.0 beta 5, and it'd be necessary to get this PR merged into beta 5 if it is to be include in 7.0.  Any chance you can update this in the coming weeks/month?

**Comment by tdonohue** [comment]
@lap82 and @abollini : Reminder that this change is still not updated for 7.0 (now beta 5) even though it was merged into 6.x already.  Any chance of getting this PR updated before we release Beta 5 or 7.0?  It'd be a shame if we release this in 6.4 only to *remove it* again in 7.0.

**Comment by tdonohue** [comment]
@lap82 and @abollini : This PR is being moved to 7.0 in the hopes that it might still make it into 7.0 final.

File: dspace/config/crosswalks/oai/metadataFormats/oai_openaire.xsl (hunk 9 above)
Comment (abollini) [reply dspace/config/crosswalks/oai/metadataFormats/oai_openaire.xsl]: done

File: dspace/config/crosswalks/oai/metadataFormats/oai_openaire.xsl [hunk 10]
```diff
@@ -1527,7 +1529,26 @@
...
+		match="doc:element[@name='others']/doc:field[@name='cc']"
+		mode="oaire">
+		<oaire:licenseCondition>
+			<xsl:attribute name="startDate">
+				<xsl:value-of
+					select="$ccstart"/>
+			</xsl:attribute>
+			<xsl:attribute name="uri">
+				<xsl:value-of
+					select="substring-after(./text(),'|||')" />
```
[the remark this answers is not in the document]
Comment (abollini) [reply dspace/config/crosswalks/oai/metadataFormats/oai_openaire.xsl]: done

File: dspace/config/spring/oai/oai.xml (hunk 7 above)
Comment (abollini) [reply dspace/config/spring/oai/oai.xml]: I have simplified the implementation. No impact on performance

File: dspace/config/spring/oai/oai.xml (hunk 5 above)
Comment (abollini) [reply dspace/config/spring/oai/oai.xml]: done

File: dspace-oai/src/main/java/org/dspace/xoai/app/XOAIItemCompilePlugin.java (hunk 6 above)
Comment (abollini) [reply dspace-oai/src/main/java/org/dspace/xoai/app/XOAIItemCompilePlugin.java]: done

File: dspace-oai/src/main/java/org/dspace/xoai/app/XOAI.java (hunk 8 above)
Comment (abollini) [reply dspace-oai/src/main/java/org/dspace/xoai/app/XOAI.java]: done

File: dspace-oai/src/main/java/org/dspace/xoai/app/CCElementAdditional.java [hunk 11]
```diff
@@ -0,0 +1,74 @@
...
+        }
+        String ccLicense = null;
+
+        try {
+            String licenseURL = getCreativeCommonsService().getLicenseURL(context, item);
+            if (StringUtils.isNotBlank(licenseURL)) {
+                CCLookup ccLookup = new CCLookup();
+                ccLookup.issue(licenseURL);
+                String licenseName = ccLookup.getLicenseName();
+                ccLicense = licenseName + "|||" + licenseURL;
```
[the remark this answers is not in the document]
Comment (abollini) [reply dspace-oai/src/main/java/org/dspace/xoai/app/CCElementAdditional.java]: done

File: dspace-oai/src/main/java/org/dspace/xoai/app/CCElementAdditional.java [hunk 12]
```diff
@@ -0,0 +1,74 @@
...
+import org.dspace.license.CCLookup;
+import org.dspace.license.factory.LicenseServiceFactory;
+import org.dspace.license.service.CreativeCommonsService;
+import org.dspace.xoai.util.ItemUtils;
+
+/**
+ * Utility class to build xml element to support Creative Commons information
+ *
+ */
+public class CCElementAdditional implements XOAIItemCompilePlugin {
```
[the remark this answers is not in the document]
Comment (abollini) [reply dspace-oai/src/main/java/org/dspace/xoai/app/CCElementAdditional.java]: done

**Comment by abollini** [comment]
@tdonohue @paulo-graca I have updated the PR. Previous feedback should be addressed.
Please note that this PR also fixes https://github.com/DSpace/DSpace/issues/3284 and I have created a PR also for a bug on the angular side https://github.com/DSpace/dspace-angular/pull/1209 that would prevent the cc license step to work. Enable it and make a test submission followed by a `./dspace oai -c import` is the easier way to test this PR

**Review by paulo-graca — APPROVED** [review]
I took a look and everything looks fine to me but I didn't had the change to test it.
Thank you @abollini and your team for this contribution!

**Comment by paulo-graca** [comment]
Meanwhile I had the change to test it. It's working as expected but I had a warning `Warning at xsl:stylesheet on line 14 column 35` and it took just extra 4 seconds to execute to the same amount of records.

```
# /dspace/bin/dspace oai -c import
OAI 2.0 manager action started
Clearing index
Index cleared
Using full import.
Full import
Total: 657 items
Total: 1 items
Purging cached OAI responses.
OAI 2.0 manager action ended. It took 71 seconds.
```


After these changes:
```
dspace-installer]# /dspace/bin/dspace oai -c import
OAI 2.0 manager action started
Clearing index
Index cleared
Using full import.
Full import
Warning at xsl:stylesheet on line 14 column 35
  Unrecognized version 1.1: treated as 1.0
Total: 657 items
Total: 1 items
Purging cached OAI responses.
OAI 2.0 manager action ended. It took 75 seconds.
```

**Review by tdonohue — APPROVED** [review]
👍 Thanks @lap82 and @abollini .  The code here looks good. I've also tested it briefly (just by making sure OAI still works and reindexing still works) and it all seems good.  I'm *not* able to reproduce the issue that @paulo-graca noted about line 14 of an XSL...and I notice that this PR doesn't modify that line, so I expect that's an unrelated issue.

Since this is at +2. I'm going to go ahead and merge it.  If we notice other issues later on, we can followup in a separate PR.
