### PR TITLE
Designate "tilted" relationships to improve performance

### LINKED ISSUE #3125: Performance when using hundreds of relationships
**Describe the bug**
We've performed a performance test creating a Person entity with hundreds of relationships to various Publications. This is a realistic use-case, e.g. if the Person is a high-profile researcher who's co-author of many publications in their department.

We noticed the duration for adding e.g. the one-hundred or three-hundred relationship is much higher compared to the first relationship

**To Reproduce**
1. Start with a database with many publications
2. Iterate the publications, and add a relationship to the same Person
3. Verify the response time when adding a relationship

**Expected behavior**
The performance can be optimized a lot by excluding the generation of virtual metadata on some relationships where it's not relevant. The virtual metadata in the Person item containing all publications is currently not used, excluding it can help a lot

**Related work**
https://github.com/DSpace/DSpace/pull/2895 has initially been started for this improvement, but hit some issues. Although the concept is still good, the implementation needs to be revised

### PR DESCRIPTION
**Pull request by aprilherron**
## References
* Previous attempt at resolving this issue: [PR #2895](https://github.com/DSpace/DSpace/pull/2895)

## Description
DSpace 7 entities with many relationships can become incredibly slow to load. To compensate for this performance issue, this PR allows the ability to designate a relationship type as tilting to the Left or Right -- to whichever side is expected to have more members.

For instance, an OrgUnit might be expected to have thousands Publications, but a Publication might only be expected to be related to one or two OrgUnits. Therefore, we can designate the relationship as being "tilted" in the direction of Publication. This, in turn, allows DSpace to know not to retrieve the relationship metadata in this direction. e.g. It will skip the thousands of Publications when returning OrgUnit metadata.

This significantly improve performance when loading these types of item pages. In my tests, this did not seem to have any other unintended negative side-effects.

## Instructions for Reviewers
This PR adds a new properties to `relationship-type` definitions: `<tiltedLeft>` and `<tiltedRight>`. These are simple boolean values, e.g. `<tiltedLeft>true</tiltedLeft>`. Designating a relationship type as tilted will result in filtered results from `ItemRelationshipLinkRepository. getRelationships()`, `EntityServiceImpl.findByItemId()`, and `RelationshipMetadataServiceImpl.getRelationshipMetadata()`.

To test:
* Apply flyway database update
* Create or find an item with many relationships of a particular type
* Designate that relationship type as tilted (either directly in the database or by updating the config and running `InitializeEntities`)
* Load the item's REST page
* Observe that relationships in the "tilted" direction are not present and performance is significantly improved.

## Checklist

- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [X] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).

### CODE REVIEW

**Review by tdonohue — COMMENTED** [review]
@KingKrimmson :  Looking at the code, the overall reasoning behind this change makes sense...however, I have some questions around the current implementation.

It seems like what we are representing here is that any relationship has two-sides...those sides might be "balanced" (relatively equal), "tilted left" (left side much larger) , or "tilted right" (right side much larger)... so, there are 3 possible "states".  That all makes sense.

What I'm not sure about is the current implementation of having two booleans `tilted_left` and `tilted_right`.  That implementation seems to imply there's a 4th possible state where both `tiltedLeft=true` **and** `tiltedRight=true` (your code itself seems to imply this by allowing for separate getters/setters, which can be controlled separately).  Instead, to me, if there's only 3 states, then it should not be possible to set something as _both_ tilted left & tilted right.

I wonder if it'd be easier here to have a single new column/setting named `tilted` or `slanted` which can have 3 possible values:
1. `null`/empty - this is a balanced (relatively equal) relationship
2. The value of `left_type` (or the literal string "leftType") - means the left side is much larger
3. The value of `right_type` (or the literal string "rightType") - means the right side is much larger

This would mean the `isOrgUnitOfPublication` relationship would look like:
```
<type>
    <leftType>Publication</leftType>
    <rightType>OrgUnit</rightType>
    <tilted>Publication</tilted>
    <!-- Or, <tilted>leftType</tilted> -->
    ....
</type>
```

**UPDATE:** I meant to add, if there actually *are* 4 possible states here, then your implementation would be correct.  However, the term "tilted" would no longer be accurate, as it's not possible for something to be tilted left & right at the same time.  If this is the case, then we should use a different term like "weighted"...to note that one side, or both could be weighed down with a large number of relationships.

File: dspace-api/src/test/java/org/dspace/content/RelationshipServiceImplTest.java [hunk 1]
```diff
@@ -110,10 +110,10 @@ public void testFindByItem() throws Exception {
         relationshipTest.add(getRelationship(cindy, hank, hasFather,0,0));
         relationshipTest.add(getRelationship(fred, cindy, hasMother,0,0));
         relationshipTest.add(getRelationship(bob, cindy, hasMother,1,0));
-        when(relationshipService.findByItem(context, cindy, -1, -1)).thenReturn(relationshipTest);
+        when(relationshipService.findByItem(context, cindy, -1, -1, false)).thenReturn(relationshipTest);
```
Comment (tdonohue) [inline dspace-api/src/test/java/org/dspace/content/RelationshipServiceImplTest.java:113]: I forgot to note this above, but we also should add some **new** tests to this PR to test the behavior when `excludeTilted=true`...namely we should test that that side of the relationship is actually excluded as expected.

**Comment by mwoodiupui** [comment]
The 3-valued nature of "tilt" maps naturally in Java to an `enum`, which Hibernate will then map to the ordinals (by default) or names [`@Enumerated(EnumType.STRING)`] in the table.

**Comment by KingKrimmson** [comment]
@tdonohue 

I agree that it would make more sense to represent only 3 states (tilted-left, balanced, tilted-right) as tilted in both directions doesn't make logical sense. I will try and push this change by next week 👍

**Review by benbosman — COMMENTED** [review]
I've performed some tests of this branch, similar to my tests from https://github.com/DSpace/DSpace/pull/3131

I've verified the performance with the following use case:
* I've adjusted the relationships configuration to ensure a person doesn't contain the publications as virtual metadata
* I've created a publication linked to 2 people
* I have a third person, already linked to 99 publication
* I'm creating a link to these 2 items (a third person for the publication, and a 100th publication for the person)
* This new code on average only needs 15% of the time to create the relationship vs the main code (I did compare to the main code excluding #3131 because this branch also doesn't contain #3131)

I've also verified the impact on requesting a person item, this new code on average only needs 12% of the time to request a person (having 100 publications) via REST


I would suggest to also modify the default tilt: e.g. configuring by default that a person doesn't contain the publications as virtual metadata (it can still be enabled to support the use case, but doesn't require it). This may help with ensuring there are tests for the use case where the tilt is enabled

**Comment by KingKrimmson** [comment]
I have updated this PR to use a 3-state Enum for the "tilted" property. Each relationship in the relationship XML document now needs only a single `<tilted>` node which can be (case-insensitive) "right", "left", "none"/`null`/omitted.

**Review by benbosman — COMMENTED** [review]
I've checked this PR out in detail, and also compared it with other performance improvements such as https://github.com/DSpace/DSpace/pull/3170

From my tests it seems:
* For most use cases, performance is already good without this PR (assuming the other performance improvements would already be merged in main)
* But when creating an item which is related to 600 or more other items, the item start feeling a bit slow (over 500ms to create a relationship and to retrieve the item). This only occurs when it's a single item related to this many other items, having 1000s of relationships more spread out doesn't impact performance noteworthy
* This PR has an enormous impact on the performance for retrieving an item, where the retrieval of an item with 1000 relationships is still below 25ms. This is because the duration is a constant, and not dependent on the amount of relationships at all
* Creating relationships has also improved, but not drastically (at least when assuming the other performance improvements would already be merged in main)

This branch has the disadvantage that it gets the performance improvements from excluding the relationships in the response, implying they cannot be used (in the direction that's configured to be excluded). This implies it may not always be desired, and the repository manager has to think about the desired relationships to display. It doesn't impact storage, so an incorrect setting can simply be adjusted and there's no further impact.

Based on this info, I would suggest to:
* Make sure this branch can be merged, to support the use cases where a single item is related to many other items
* But keep this disabled in the default configuration, only recommending it to be used when the performance is posing problems.
* This will ensure there's no additional complexity for the setup, but for the use-cases with 1000s of relationships, the performance can be improved using config only

File: dspace-server-webapp/src/test/java/org/dspace/app/rest/TiltedRelationshipRestRepositoryIT.java [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+
+import org.dspace.content.RelationshipType;
+import org.junit.Before;
+
+/**
+ * This class carries out the same test cases as {@link RelationshipRestRepositoryIT}.
+ * The only difference being that a RelationshipType is set on
+ * {@link RelationshipRestRepositoryIT#isAuthorOfPublicationRelationshipType}.
+ */
+public class TiltedRelationshipRestRepositoryIT extends RelationshipRestRepositoryIT {
```
Comment (benbosman) [inline dspace-server-webapp/src/test/java/org/dspace/app/rest/TiltedRelationshipRestRepositoryIT.java:18]: This seems to prove that the results from the parent test are not affected. This is most likely because the parent test doesn't verify the metadata on the Person item in the isAuthorOfPublication relationship.

This seems a bit confusing, and it may just as well pass if the setup method doesn't work correctly. So it would be good to add an additional test to the parent which verifies the metadata on the Person item in the isAuthorOfPublication relationship. Something similar to TiltedRelationshipMetadataServiceIT, but verifying REST also complies to these changes

**Review by benbosman — CHANGES_REQUESTED** [review]
This looks good to me.

I've included some feedback inline, to add some comments, to ease the reviewing, and to add tests. The changes should all be minor

File: dspace-api/src/main/java/org/dspace/content/RelationshipType.java [hunk 3]
```diff
@@ -113,6 +113,13 @@
      */
     @Column(name = "copy_to_right", nullable = false)
     private boolean copyToRight;
+
+    /**
+     * The value indicating whether the relationship has more relationships on the right/left/neither.
```
[the remark this answers is not in the document]
Comment (KingKrimmson) [reply dspace-api/src/main/java/org/dspace/content/RelationshipType.java]: I fixed the wording on this comment

File: dspace-api/src/main/java/org/dspace/content/dao/impl/RelationshipDAOImpl.java [hunk 4]
```diff
@@ -27,22 +28,42 @@
...
 
         CriteriaBuilder criteriaBuilder = getCriteriaBuilder(context);
         CriteriaQuery criteriaQuery = getCriteriaQuery(criteriaBuilder, Relationship.class);
         Root<Relationship> relationshipRoot = criteriaQuery.from(Relationship.class);
         criteriaQuery.select(relationshipRoot);
-        criteriaQuery
-            .where(criteriaBuilder.or(criteriaBuilder.equal(relationshipRoot.get(Relationship_.leftItem), item),
-                                      criteriaBuilder.equal(relationshipRoot.get(Relationship_.rightItem), item)));
+        if (excludeTilted) {
+            criteriaQuery
```
[the remark this answers is not in the document]
Comment (KingKrimmson) [reply dspace-api/src/main/java/org/dspace/content/dao/impl/RelationshipDAOImpl.java:46]: I added inline comments about what this query is doing to improve legibility

**Comment by tdonohue** [comment]
@KingKrimmson : Just a quick FYI, It looks like this PR is currently failing one Integration Test.

**Comment by tdonohue** [comment]
@KingKrimmson or @bruno-atmire : If you rebase this on the latest `main`, the strange IT failures have been fixed in #3213

File: dspace-server-webapp/src/test/java/org/dspace/app/rest/TiltedRelationshipRestRepositoryIT.java (hunk 2 above)
Comment (benbosman) [reply dspace-server-webapp/src/test/java/org/dspace/app/rest/TiltedRelationshipRestRepositoryIT.java:26]: This looks good to me now

**Review by benbosman — APPROVED** [review]
Thanks @KingKrimmson @bruno-atmire 
This looks all good to me

File: dspace-api/src/test/java/org/dspace/content/TiltedRelationshipMetadataServiceIT.java [hunk 5]
```diff
@@ -0,0 +1,97 @@
...
+        leftItem = ItemBuilder.createItem(context, col).withRelationshipType("Publication").build();
+        rightItem = ItemBuilder.createItem(context, col).withRelationshipType("Author")
+                .withPersonIdentifierLastName("familyName")
+                .withPersonIdentifierFirstName("firstName").build();
+        isAuthorOfPublicationRelationshipType =
+                RelationshipTypeBuilder.createRelationshipTypeBuilder(context, publicationEntityType, authorEntityType,
+                        "isAuthorOfPublication", "isPublicationOfAuthor",
+                        null, null, null, null).build();
+
+        isAuthorOfPublicationRelationshipType.setTilted(RelationshipType.Tilted.LEFT);
```
Comment (tdonohue) [inline dspace-api/src/test/java/org/dspace/content/TiltedRelationshipMetadataServiceIT.java:44]: I'm wondering we don't have a similar test for a `Tilted.RIGHT` relationship?  It seems like we should be testing both values of `Tilted` (though we don't need any for `Tilted.NONE` since that's the default and is tested by all other tests).

File: dspace-server-webapp/src/test/java/org/dspace/app/rest/TiltedRelationshipRestRepositoryIT.java [hunk 6]
```diff
@@ -0,0 +1,77 @@
...
+
+    @Before
+    public void setUp() throws Exception {
+        super.setUp();
+
+        context.turnOffAuthorisationSystem();
+
+        isAuthorOfPublicationRelationshipType.setTilted(RelationshipType.Tilted.LEFT);
```
Comment (tdonohue) [inline dspace-server-webapp/src/test/java/org/dspace/app/rest/TiltedRelationshipRestRepositoryIT.java:34]: Same here...it'd be nice to have a second test in this class which verifies that a `Tilted.RIGHT` relationship also works as expected.

**Review by tdonohue — CHANGES_REQUESTED** [review]
@KingKrimmson : Thanks for this work. I've finally gotten back to re-review it.  Overall, it looks very good to me.  However, I think it could still be slightly improved by adding integration tests that also verify `Tilted.RIGHT` is working....currently we only seem to have tests which use `Tilted.LEFT`.

Overall, I realize the two should work the same (just opposite of each other), but having a test for both would validate that both values of Tilted work as expected. (As I said below, there's no need to test `Tilted.NONE` as that's the default being used in all other tests.)

**Review by tdonohue — APPROVED** [review]
👍 Looks good to me now. Thanks @KingKrimmson for the additional tests for Right tilted relationships!

**Comment by KingKrimmson** [comment]
Thanks goes to @bruno-atmire ;)

**Comment by tdonohue** [comment]
My apologies @bruno-atmire !  I meant to thank you as well, and I appreciate @KingKrimmson pointing that out.  Thanks @bruno-atmire !
