### PR TITLE
DS-8478: restores member variables used in sharding functions

### LINKED ISSUE #8478: Statistics don't load after sharding
**Describe the bug**
DSpace 7.3

After setting `usage-statistics.shardedByYear = true` the statistics don't load anymore.

I've tracked it down to a NullPointerException in `SolrLoggerServiceImpl.initSolrYearCores`. `statisticsCoreBase` is never initialized, but accessed there.

**To Reproduce**
1. Set `usage-statistics.shardedByYear = true` in the configuration
2. Start the DSpace Backend
3. Open the statistics
4. Page loads indefinitely after receiving a status 500

**Expected behavior**
Statistics page loads normally after sharding

**Related work**
Link to any related tickets or PRs here.

### PR DESCRIPTION
**Pull request by nwoodward**
## References
* Fixes #8478 

## Description
A recent PR to solve https://github.com/DSpace/DSpace/issues/7777 removed two member variables of the SolrLoggerServiceImpl class that are used in a few functions related to statistics shards. This PR brings them back.

## Instructions for Reviewers

1. Set `usage-statistics.shardedByYear = true` in the configuration
2. Restart the backend
3. Open the Statistics page
4. Observe that the page now loads

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [X] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [X] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [X] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [X] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [X] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [X] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [X] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

File: dspace-api/src/main/java/org/dspace/statistics/SolrLoggerServiceImpl.java [hunk 1]
```diff
@@ -174,6 +177,23 @@ protected SolrLoggerServiceImpl() {
...
+                .getName(statisticsPath.getNameCount() - 1)
+                .toString();
+        } else {
+            log.warn("Unable to find solr-statistics.server parameter in DSpace configuration. This is required for " +
+                     "sharding statistics.");
+            statisticsCoreBase = null;
+        }
+
+        log.info("solr-statistics.server:  {}", statisticsCoreURL);
+        log.info("usage-statistics.dbfile:  {}",
```
Comment (tdonohue) [inline dspace-api/src/main/java/org/dspace/statistics/SolrLoggerServiceImpl.java:194]: @nwoodward : I'm curious why we need these `log.info` statements?  It looks like these are both logged already in `SolrStatisticsCore.initSolr()`, so it seems duplicative to log them here again.  Was there a reason you added them here again, or maybe this was just for debugging & it should be removed?

(For me, in the logs, I'm seeing this logged now both from SolrStatisticsCore and then again by SolrLoggerServiceImpl, which is why it looks odd to me.)

**Review by tdonohue — APPROVED** [review]
@nwoodward :  Thanks!  Overall this looks good, and it appears to work (at least I now get the the log statements where the shards should load, e.g. "Loading core with name...").  Unfortunately, I don't have a sharded core to test from, but this at least fixes a very obvious bug.

That said, I have a minor recommendation inline below. I don't think the log.info statements are necessary, as I see these already in my dspace.log.  Once that's cleaned up or responded to, I think this is ready to merge.

File: dspace-api/src/main/java/org/dspace/statistics/SolrLoggerServiceImpl.java (hunk 1 above)
Comment (nwoodward) [reply dspace-api/src/main/java/org/dspace/statistics/SolrLoggerServiceImpl.java]: You're right. I didn't notice them up just a little ways in the logs.
