### PR TITLE
Fix #9383: Set email subject for request copy form

### LINKED ISSUE #9383: When answering a request for copy the email subject field will be ignored
**Describe the bug**
When you answer a request for copy, regardless whether you grant or deny the request, you are presented with a form, that has fields for a subject and a message. The subject gets ignored and the subject from the email template is used instead. I post the issue here, because the problem lies with the backend.

Screenshot 2024-02-29 at 10 11 05

I already have a fix. I will provide a pull request today or tomorrow.

**To Reproduce**
1. Request a copy of a bitstream under embargo
2. Click the link to grant or deny the request
3. Enter a custom subject line
4. Verify the email sent: the subject line provided by you in the form was ignored and the subject from the email template used instead.

**Expected behavior**
The subject you enter in the form should become the subject of the email you send

**Related work**
I have a fix. I will provide a pull request today or tomorrow.

### PR DESCRIPTION
**Pull request by MW3000**
## References
Fixes #9383

## Description
1. Make sure, the email subject does not get overwritten with the subject from the email template if the subject is set explicitly via `Email>>setSubject()` as described in the comment of `Email>>send()` but not implemented:

> <p>"subject" is treated specially:  if {@link setSubject()} has not been    
> called, the value of any "subject" property will be used as if setSubject    
> had been called with that value.  Thus a template may define its subject,    
> but the caller may override it.    

2. Test for empty subject in `RequestItemRepository>>put()`.

## Instructions for Reviewers
Please add a more detailed description of the changes made by your PR. At a minimum, providing a bulleted list of changes in your PR is helpful to reviewers.

1. Request a copy of a bitstream under embargo
2. Click the link to grant or deny the request
3. Enter a custom subject line
4. Verify the email sent: the subject you entered in the form should now be the subject of the email sent.

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR passes all tests ~~and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).~~
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/RequestItemRepository.java [hunk 1]
```diff
@@ -247,11 +247,15 @@ public RequestItemRest put(Context context, HttpServletRequest request,
             message = responseMessageNode.asText();
         }
 
+        JsonNode responseSubjectNode = requestBody.findValue("subject");
+        String subject = null;
+        if (responseSubjectNode != null && !responseSubjectNode.isNull()) {
```
Comment (MW3000) [inline dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/RequestItemRepository.java:252]: I used both `!= null` and `isNull()` because you did so in line 246, @tdonohue. But I wonder why both would be necessary.

Comment (tdonohue) [reply dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/RequestItemRepository.java:252]: @MW3000 : It's necessary to fix this behavioral bug https://github.com/DSpace/DSpace/pull/9136

**Comment by MW3000** [comment]
You added the port to 7.x label. The pull request is for the 7.x branch. It must be ported to 8.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @MW3000 !  Finally got to testing this.  I verified this bug still exists on `main` and then applied this PR and verified it works.
