### PR TITLE
[Port dspace-7_x] Fixing Crossref document type issue with new metadata mapping processor

### LINKED ISSUE #9900: Crossref imported works aren't considering DSpace default document types
## Describe the bug
When using Crossref live import:
imagem
the stored dc.type value isn't any of the default DSpace listed types:
https://github.com/DSpace/DSpace/blob/dspace-8.0/dspace/config/submission-forms.xml#L1395-L1484
this will create unwanted faceted values.

## To Reproduce
1. Import a new document from Crossref based on a DOI, example: 10.1200/jco.2007.25.18_suppl.3507

## Expected behavior
The imported value should be mapped to one of the default DSpace types, like: "Article", instead of "journal-article"

### PR DESCRIPTION
**Pull request by paulo-graca**
## References
* Fixes #9900
* Main version: #9910

## Description
This PR makes use of a mechanism available for external sources that enable you to do value mapping. Meaning, you can replace a value by defining something like:
```
journal-article=Article
```
## Instructions for Reviewers
To test this, you can see it on the original issue #9900, you can use the user interface and you just need to go to your "mydspace" area and do an import metadata from crossref. Then, when you try to import a record, You will see "Article" instead the "journal-article" as the Publication type.

List of changes in this PR:
* I've changed crossref integration spring configuration to support to new SimpleMapConverter
* I've added a file with mapped values (I've tried to do my best here)
* I've created a new JSON processor

### CODE REVIEW

File: dspace-api/src/main/java/org/dspace/importer/external/metadatamapping/transform/StringJsonValueMappingMetadataProcessorService.java [hunk 1]
```diff
@@ -0,0 +1,86 @@
...
+import org.dspace.importer.external.metadatamapping.contributor.JsonPathMetadataProcessor;
+import org.dspace.util.SimpleMapConverter;
+
+/**
+ * This class is a Metadata processor from a structured JSON Metadata result
+ * and uses a SimpleMapConverter, with a mapping properties file
+ * to map to a single string value based on mapped keys.<br/>
+ * Like:<br/>
+ * <code>journal-article = Article<code/>
+ *
```
Comment (alanorth) [inline dspace-api/src/main/java/org/dspace/importer/external/metadatamapping/transform/StringJsonValueMappingMetadataProcessorService.java:31]: Trailing whitespace in patch.

**Comment by alanorth** [comment]
Thanks @paulo-graca! I tried this on DSpace 7.6.3 and it worked as expected. I imported a journal article and a book chapter using custom type mappings for our repository (we use `Journal Article` and `Book Chapter`).

File: dspace-api/src/main/java/org/dspace/importer/external/metadatamapping/transform/StringJsonValueMappingMetadataProcessorService.java (hunk 1 above)
Comment (paulo-graca) [reply dspace-api/src/main/java/org/dspace/importer/external/metadatamapping/transform/StringJsonValueMappingMetadataProcessorService.java:31]: removed

**Comment by paulo-graca** [comment]
@alanorth if it's ok with you, could you approve this PR?

**Comment by alanorth** [comment]
@paulo-graca thanks for the reminder. I had already tested this and it's https://github.com/DSpace/DSpace/labels/1%20APPROVAL so I'm merging it after looking it over again briefly. I also squashed all the commits into one to keep the history cleaner.

File: dspace-api/src/main/java/org/dspace/importer/external/metadatamapping/transform/StringJsonValueMappingMetadataProcessorService.java (hunk 1 above)
Comment (alanorth) [reply dspace-api/src/main/java/org/dspace/importer/external/metadatamapping/transform/StringJsonValueMappingMetadataProcessorService.java:31]: I just noticed after merging this that you did not actually fix the trailing whitespace on line 31. I suppose it doesn't really matter. It is a preference of mine rather than a convention in DSpace coding standards and git complained when I applied the patch.
