### PR TITLE
Provide a script to delete old processes

### LINKED ISSUE #7974: Provide a script to delete old processes
It would be useful to have a script that deletes from the database all COMPLETED processes older than a given input.
It should also be possible to force the cancellation of processes in FAILED and RUNNING status. The deletion could be configurable by looking for processes older than x days.
We are interested in this functionality and could implement it ourselves.

### PR DESCRIPTION
**Pull request by LucaGiamminonni**
## References
* Fixes [#7974](https://github.com/DSpace/DSpace/issues/7974)

## Description
This PR introduces a new script named process-cleaner that deletes from the database all processes with the specified statuses older than the configured days.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [X] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [X] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [X] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [X] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [X] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

File: dspace-api/src/main/java/org/dspace/administer/ProcessCleaner.java [hunk 1]
```diff
@@ -0,0 +1,133 @@
...
+    public void setup() throws ParseException {
+
+        this.configurationService = DSpaceServicesFactory.getInstance().getConfigurationService();
+        this.processService = ScriptServiceFactory.getInstance().getProcessService();
+
+        this.cleanFailed = commandLine.hasOption('f');
+        this.cleanRunning = commandLine.hasOption('r');
+        this.cleanCompleted = commandLine.hasOption('c') || (!cleanFailed && !cleanRunning);
+
+        this.days = configurationService.getIntProperty("process-cleaner.days", 14);
```
Comment (tdonohue) [inline dspace-api/src/main/java/org/dspace/administer/ProcessCleaner.java:62]: This setting should be added to our configuration. It'd be fine to just add this to dspace.cfg (since I don't see any other cfg file that's more appropriate).

File: dspace-api/src/main/java/org/dspace/administer/ProcessCleanerConfiguration.java [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+
+    @Autowired
+    private AuthorizeService authorizeService;
+
+    private Class<T> dspaceRunnableClass;
+
+    @Override
+    public boolean isAllowedToExecute(Context context) {
+        try {
+            return authorizeService.isAdmin(context);
```
Comment (tdonohue) [inline dspace-api/src/main/java/org/dspace/administer/ProcessCleanerConfiguration.java:31]: We need to add a test which verifies that non-Admins cannot run this script. I'm not seeing a test for this (unless I'm overlooking it)

File: dspace-api/src/main/java/org/dspace/administer/ProcessCleanerConfiguration.java [hunk 3]
```diff
@@ -0,0 +1,68 @@
...
+
+            options.addOption("r", "running", false, "delete the process with RUNNING status");
+            options.getOption("r").setType(boolean.class);
+
+            options.addOption("f", "failed", false, "delete the process with FAILED status");
+            options.getOption("f").setType(boolean.class);
+
+            options.addOption("c", "completed", false,
+                "delete the process with COMPLETED status (default if no statuses are specified)");
+            options.getOption("c").setType(boolean.class);
```
Comment (tdonohue) [inline dspace-api/src/main/java/org/dspace/administer/ProcessCleanerConfiguration.java:51]: We should add a `-h` (--help) option to every script to document the valid settings.  Otherwise, there's no easy way to see these options from the commandline.

**Review by tdonohue — CHANGES_REQUESTED** [review]
@LucaGiamminonni : Thanks for this! Overall, this works well & the code looks good.  I just have some minor improvements to suggest before this could be merged.  See inline comments below.

File: dspace/config/dspace.cfg [hunk 4]
```diff
@@ -1542,6 +1542,10 @@ solr-database-resync.time-until-reindex = 600000
 # Keep in mind, changing the schedule requires rebooting your servlet container, e.g. Tomcat.
 solr-database-resync.cron = 0 15 2 * * ?
 
+## PROCESS CLEANER SCRIPT
+# Defines how many days to go back from the current date to find out which old processes to delete (default is 14)
+# process-cleaner.days = 14
```
Comment (tdonohue) [inline dspace/config/dspace.cfg:1547]: Tiny thing, but I'd prefer if we could make this it's own "section" as it currently appears like it's part of the "solr-database-resync" settings.  Maybe update this as follows (this includes some minor cleanup to the description):
```
#----------------------------------------------------------#
#----------PROCESS CLEANER SCRIPT CONFIGURATION------------#
#----------------------------------------------------------#
# Processes older than this number of days will be deleted when the "process-cleaner" script is next run. Default is 14 (i.e. processes that are two weeks or older will be deleted)
# process-cleaner.days = 14
```

This is very minor obviously and doesn't impact the code of this PR.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @LucaGiamminonni !  However, I'd recommend a very minor change to the `dspace.cfg` to clarify this new configuration.  After that, this is ready to be merged.

File: dspace-api/src/main/java/org/dspace/administer/ProcessCleanerConfiguration.java (hunk 2 above)
Comment (tdonohue) [reply dspace-api/src/main/java/org/dspace/administer/ProcessCleanerConfiguration.java:31]: Good point. We can leave this out since it already is verified elsewhere. If we ever change process access rights, we can readdress this at a later time.

File: dspace/config/dspace.cfg (hunk 4 above)
Comment (tdonohue) [reply dspace/config/dspace.cfg:1547]: @LucaGiamminonni : Could I get the above minor update made to the `dspace.cfg` in this PR?  That way I can get this PR merged.  Thanks!

Comment (tdonohue) [reply dspace/config/dspace.cfg:1550]: Thanks @LucaGiamminonni !  Looks good & I'll get this merged then
