### PR TITLE
Fix GoogleBitstreamComparator to return 0 when equal

### LINKED ISSUE #8211: GoogleBitstreamComparator - Comparison method violates its general contract
**Describe the bug**
GoogleBitstreamComparator - Comparison method violates its general contract

**To Reproduce**
1. Submit a new item. With many/more than 10 files/bitstreams with the same file extension and the same size.
2. The following Exception is thrown:
`java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.TimSort.mergeLo(TimSort.java:777)
        at java.util.TimSort.mergeAt(TimSort.java:514)
        at java.util.TimSort.mergeForceCollapse(TimSort.java:457)
        at java.util.TimSort.sort(TimSort.java:254)
        at java.util.Arrays.sort(Arrays.java:1438)
        at java.util.List.sort(List.java:478)
        at java.util.Collections.sort(Collections.java:175)
        at org.dspace.app.util.GoogleMetadata.findLinkableFulltext(GoogleMetadata.java:1054)
        at org.dspace.app.util.GoogleMetadata.getPDFSimpleUrl(GoogleMetadata.java:1008)
        at org.dspace.app.util.GoogleMetadata.addSingleField(GoogleMetadata.java:259)`

In our submission we have many scans of a book (TIFFs) with the same resolution. -> Uncompressed TIFF, same resolution -> same file size.

**Expected behavior**
A compare method that not violates the contract. 

`
 public int compare(Bitstream b1, Bitstream b2) {
        int priority1 = getPriorityFromBitstream(b1);
        int priority2 = getPriorityFromBitstream(b2);

        if (priority1 > priority2) {
            return 1;
        } else if (priority1 == priority2) {
            if (b1.getSizeBytes() <= b2.getSizeBytes()) {
                return 1;
            } else {
                return -1;
            }
        } else {
            return -1;
        }
    }
`

bitstream1, bitstream2 have the same file size and the same extension (priority1 == priority2 is true).
The method say for: 
 - compare(bitstream1, bitstream2) -> 1
 - compare(bitstream2, bitstream1) -> also 1
This is a violation.

The bug is found in the code of DSpace 6.x, but I think there is also a copy of the code in DSpace 7.x.

### PR DESCRIPTION
**Pull request by tdonohue**
## References
Fixes #8211

## Description
Fix `compare()` by returning 0 when bitstreams are "equal" in size & priority.

This was already partially tested in the existing `GoogleBitstreamComparatorTest.testSameMimeTypeSameSize()` test method, but I added tests to ensure equality is always returned. This will ensure we don't trigger an `IllegalArgumentException: Comparison method violates its general contract!` in some scenarios.

## Instructions for Reviewers
* Review code changes & changes to test.  This likely only needs a code review, as the test proves it works.

### CODE REVIEW

File: dspace-api/src/main/java/org/dspace/app/util/GoogleBitstreamComparator.java [hunk 1]
```diff
@@ -86,8 +86,10 @@ public int compare(Bitstream b1, Bitstream b2) {
         if (priority1 > priority2) {
             return 1;
         } else if (priority1 == priority2) {
-            if (b1.getSizeBytes() <= b2.getSizeBytes()) {
+            if (b1.getSizeBytes() < b2.getSizeBytes()) {
                 return 1;
```
Comment (mwoodiupui) [inline dspace-api/src/main/java/org/dspace/app/util/GoogleBitstreamComparator.java:90]: Isn't this backward?  Shouldn't `compare(b1, b2)` return -1 if b1 is smaller than b2, and 1 if b1 is larger than b2, priority being equal?

**Review by mwoodiupui — APPROVED** [review]
Test looks correct.  The old `compare` was clearly wrong, and this version is correct given that it is meant to cause sort in **descending** order by size.

File: dspace-api/src/main/java/org/dspace/app/util/GoogleBitstreamComparator.java (hunk 1 above)
Comment (tdonohue) [reply dspace-api/src/main/java/org/dspace/app/util/GoogleBitstreamComparator.java:90]: Correct, I didn't change the logic here...it was already sorting largest first.  I just split up this `if` into an `if` and and `else if`
