### PR TITLE
Fix database connection leak on failed login attempts

### LINKED ISSUE #11202: Context (DB Connection) leak in unsuccessfulAuthentication in StateLessLoginFilter and ORCID login
## Describe the bug

Repeated logins with an incorrect password can bring DSpace to its knees, as each failed login blocks a DB connection because the context isn't closed.

## To Reproduce
1. Either with password login, or ORCID login, perform authentications with an incorrect password
2. Look at available DB connections in the pool

## Expected behavior
unsuccessful authentication should close the context

### PR DESCRIPTION
**Pull request by alexandrevryghem**
## References
* Fixes #11202
* Related to #10599

## Description
Currently when you enter an incorrect email/password combination, the open `Context` is not closed properly. This leads to a dangling DB connection, which can cause a DB connection exhaustion.

## Instructions for Reviewers
List of changes in this PR:
* Created new method in `StatelessLoginFilter` to close open `Context`s
* Updated the `StatelessLoginFilter#unsuccessfulAuthentication` & `OrcidLoginFilter#unsuccessfulAuthentication` to use this new method

**Guidance for how to test or review this PR.**
- Run the following query in your database:
  ```sql
  SELECT datname, backend_start, state, query
  FROM pg_stat_activity
  WHERE query != 'ROLLBACK' AND query != 'COMMIT' AND datname is not null AND datname != 'postgres'
  ORDER BY backend_start;
  ```
- Perform an invalid authentication attempt without the fix and verify that a new "idle in transaction" connection appears
- Perform an invalid authentication attempt with the fix and verify that no new connection is created anymore

## Checklist
- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR **passes Checkstyle** validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR **includes Javadoc** for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR **passes all tests and includes new/updated Unit or Integration Tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by nwoodward — APPROVED** [review]
👍 Thanks @alexandrevryghem. I tested this locally and verified that failed logins no longer add "idle in transaction" results.

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/security/StatelessLoginFilter.java [hunk 1]
```diff
@@ -133,6 +136,27 @@ protected void unsuccessfulAuthentication(HttpServletRequest request,
...
+     * {@link #continueChainBeforeSuccessfulAuthentication} is {@code false} by default, which prevents the
+     * {@link org.dspace.app.rest.filter.DSpaceRequestContextFilter} from being called. Without this call, the request
+     * would leave an open database connection.
+     *
+     * @param request The current request.
+     */
+    protected void closeOpenContext(HttpServletRequest request) {
+        if (ContextUtil.isContextAvailable(request)) {
+            try (Context context = ContextUtil.obtainContext(request)) {
+                if (context != null) {
```
Comment (tdonohue) [inline dspace-server-webapp/src/main/java/org/dspace/app/rest/security/StatelessLoginFilter.java]: @alexandrevryghem : Could we add a `&& context.isValid()` check to this `if` statement?  There's no reason to call `context.complete()` on the next line if the context is no longer valid.

While, technically, your code will work...if `isValid()==false` then when `complete()` is called we'll get a logged INFO which says `complete() was called on a closed Context object. No changes to commit.`

**Review by tdonohue — COMMENTED** [review]
@alexandrevryghem : From a code review perspective, this looks good. But, I have a minor suggestion inline below.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @alexandrevryghem ! This looks good to me now too.
