### PR TITLE
dspace-api: tell ImageMagick about the PDF CropBox

### LINKED ISSUE #8549: ImageMagick produces a strange two-page thumbnail layout for certain PDFs
ImageMagick uses the PDF `MediaBox` by default when rasterizing PDFs. In certain PDFs this can lead to an unexpected layout in the resulting thumbnail, for example (open the following image in a new tab to see the blank white page):

<p align="center">
  
</p>

This happens because certain PDFs have different sizes for their `MediaBox` (which is the parent container for all page content) and their `CropBox`. In many PDFs these two boxes are the same, but PDFs meant for print often set one content area size for print and one for displaying on screen.

The source PDF for the thumbnail above has the following page boxes according to `pdfinfo` (from the poppler package):

```console
$ pdfinfo -box 10568-116598.pdf
...
MediaBox:            0.00     0.00  1190.55   841.89
CropBox:           594.38     0.00  1190.55   839.18
BleedBox:          594.38     0.00  1190.55   839.18
TrimBox:           594.38     0.00  1190.55   839.18
ArtBox:            594.38     0.00  1190.55   839.18
```

Notice the `MediaBox` and `CropBox` are different sizes. We have hundreds (thousands?) of PDFs with this issue in our repository.

**Related work**
1. See this [bug report and response from the Ghostscript developers](https://bugs.ghostscript.com/show_bug.cgi?id=705994) (ImageMagick uses Ghostscript for rasterization under the hood).

### PR DESCRIPTION
**Pull request by alanorth**
## References
* Fixes: https://github.com/DSpace/DSpace/issues/8549

## Description
ImageMagick uses the `MediaBox` by default when rasterizing PDFs because the PDF specification says that all PDFs *must* contain one. This page box is the parent for all other boxes that a PDF *may* contain, for example a `CropBox`, `ArtBox`, etc. In many cases these are the same, but when they are not the `CropBox` is generally used to define the area displayed to a user when they open the PDF on screen (as opposed to when printing on paper). Using the wrong page box can result in strange-looking thumbnails.

If a PDF has a `CropBox` that has a different size than its `MediaBox` then we should tell ImageMagick to use it because it more accurately resembles what the user would see if they opened the PDF.

**Before (open the image to see the blank white space):**

<p align="center">
  
</p>

**After:**

<p align="center">
  
</p>

And example PDF can be found in our repository: https://hdl.handle.net/10568/116598

## Instructions for Reviewers
Test generating an ImageMagick PDF thumbnail for several items before and after this patch, ie:

```console
$ dspace filter-media -p 'ImageMagick PDF Thumbnail' -v -f -i 10568/120157
```

List of changes in this PR:
* Include several imports from pdfbox (which we are already using elsewhere) in `dspace-api/src/main/java/org/dspace/app/mediafilter/ImageMagickThumbnailFilter.java`
* Add logic to check the `MediaBox` and `CropBox`
* Add logic to pass the `-define pdf:use-cropbox=true` option to ImageMagick

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).

### CODE REVIEW

File: dspace-api/src/main/java/org/dspace/app/mediafilter/ImageMagickThumbnailFilter.java [hunk 1]
```diff
@@ -119,6 +122,25 @@ public File getImageFile(File f, int page, boolean verbose)
...
+        // Check the PDF's MediaBox and CropBox to see if they are the same.
+        // If not, then tell ImageMagick to use the CropBox when generating
+        // the thumbnail because the CropBox is generally used to define the
+        // area displayed when a user opens the PDF on a screen, whereas the
+        // MediaBox is used for print. Not all PDFs set these correctly, so
+        // we can use ImageMagick's default behavior unless we see an explit
+        // CropBox. Note: we don't need to do anything special to detect if
+        // the CropBox is missing or empty because pdfbox will set it to the
+        // same size as the MediaBox if it doesn't exist.
+        PDPage pdfPage = PDDocument.load(f).getPage(1);
```
Comment (alanorth) [inline dspace-api/src/main/java/org/dspace/app/mediafilter/ImageMagickThumbnailFilter.java:135]: We only need to test page one since we are only generating a thumbnail from page one. I'm not sure if we need to add that to the inline comment?

**Comment by nwoodward** [comment]
Do you have an example PDF in your repository I could use to test this?

**Comment by alanorth** [comment]
> Do you have an example PDF in your repository I could use to test this?

Ah yes, I should have linked one! Here is the sample I used: https://hdl.handle.net/10568/116598

**Review by nwoodward — APPROVED** [review]
👍 tested and confirmed this works. 

I looked but couldn't find when the use-cropbox option was added to ImageMagick or if it's been there forever. There isn't a minimum version of ImageMagick mentioned in the DSpace 7 documentation, but if the cropbox option isn't available in older versions then it would be a good idea to note that.

**Comment by alanorth** [comment]
> I looked but couldn't find when the use-cropbox option was added to ImageMagick or if it's been there forever.

Good question! Using some rudimentary `git show` I checked the ImageMagick history for `coders/pdf.c` and found the option existing in [git commits dating back to at least 2015](https://github.com/ImageMagick/ImageMagick/blob/151b66dffc9e3c2e8c4f8cdaca37ff987ca0f497/coders/pdf.c#L508).

Also, I did a test on a CentOS 7 box I still have laying around and the `-define pdf:use-cropbox=true` option works correctly with ImageMagick 6.9.10.68 there, so I think it's pretty safe to assume this will work "everywhere" for current systems.

File: dspace-api/src/main/java/org/dspace/app/mediafilter/ImageMagickThumbnailFilter.java (hunk 1 above)
Comment (alanorth) [reply dspace-api/src/main/java/org/dspace/app/mediafilter/ImageMagickThumbnailFilter.java]: There was actually an issue here in that PDDocument's `getPage()` uses a zero-based index, so I was actually checking the *second* page and this was failing on PDFs with only one page!

**Comment by alanorth** [comment]
I found an issue with my original patch: PDDocument's `getPage()` is actually zero based, so we need to get page 0 if we want to check the first page. I've updated the patch.

**Comment by tdonohue** [comment]
@alanorth : I've used the automatic rebase button on this PR as it was previously failing on a broken test (and that broken test has been fixed on `main` now).

**Comment by alanorth** [comment]
@tdonohue that's OK. It's only one commit so it is clean and easy to rebase. Thanks.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @alanorth !  This looks good to me.  I tested it today and verified the sample PDF creates a correct thumbnail.  I also tested it against a few other PDFs just to be certain there are no other side effects -- and I didn't find any.
