### PR TITLE
Changing the name of a group should not recalculate group2groupcache table

### LINKED ISSUE #8155: Changing the name of a group should not recalculate group2groupcache table
**Describe the bug**
The Group class has a boolean property `groupsChanged` that is used to know if others groups have been added or removed from this group. This property is used during the update of a group to know if the group2groupcache table should be recalculated. 

See:
https://github.com/DSpace/DSpace/blob/b0a704b96256a36ba66d12aa0a4d24cfadf433d0/dspace-api/src/main/java/org/dspace/eperson/GroupServiceImpl.java#L594

And rethinkGroupCache function:
https://github.com/DSpace/DSpace/blob/b0a704b96256a36ba66d12aa0a4d24cfadf433d0/dspace-api/src/main/java/org/dspace/eperson/GroupServiceImpl.java#L610-L618

I have seen recently that this property is also set to true if the group's name changes. This is an error because the name of the group is not relevant to recalculate the group2groupcache table.

In an instance with many relations between groups the function that recalculates the values of group2groupcache table could be expensive, and it could affect the performance.

**To Reproduce**
This bug can be reproduced in a instance with many groups relations (1000 entries in group2group table).
1) Go to group administration
2) Create a new group and change the name
The response should be quicker than adding a new subgroup.

**Expected behavior**
The group2groupcache table should not be recalculated after changing the name of one group.

### PR DESCRIPTION
**Pull request by toniprieto**
## References
* Fixes #8155

## Description
Remove the line that set to true the property `groupsChanged` when the name of the group is changed. 

## Instructions for Reviewers
It is a small change.
I have tested it in a DSpace 6x instance with many groups relations (1000 entries in group2group table).
1) Go to group administration
2) Create a new group and change the name
The response should be quicker than adding a new subgroup.

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

File: dspace-api/src/main/java/org/dspace/eperson/Group.java [hunk 1]
```diff
@@ -201,7 +201,6 @@ public String getName() {
     void setName(String name) throws SQLException {
         if (!StringUtils.equals(this.name, name) && !isPermanent()) {
             this.name = name;
-            groupsChanged = true;
```
Comment (tdonohue) [inline dspace-api/src/main/java/org/dspace/eperson/Group.java:204]: @toniprieto : While I think your change is correct, it made me realize that this line probably was *meant* to be a call to `setMetadataModified()` (which will trigger a MODIFY_METADATA event, but *won't* recalculate the group2groupcache).  Otherwise, it looks like a group name change won't trigger any events, which means the Group may not be reindexed if necessary.

Comment (toniprieto) [reply dspace-api/src/main/java/org/dspace/eperson/Group.java:204]: You're right! I will add a new commit to add this call.

**Comment by toniprieto** [comment]
@tdonohue I have added the suggested change. I have also done a quick test enabling the TestConsumer to confirm that it triggers a MODIFY_METADATA event.

**Review by tdonohue — APPROVED** [review]
Thanks @toniprieto !  This looks very obviously correct... group name changes should only trigger MODIFY_METADATA actions, and not re-creation of group mappings.
