### PR TITLE
Fixes for scope based searching and indexing in Discovery

### LINKED ISSUE #8622: Discovery scope based searching issues
**Describe the bug**
Discovery scope based searching and indexing currently isn't working correctly. When different configurations are defined on different levels of the repository such as community and collections, the current code will not retrieve the correct configuration for the provided scope and will not index the correct fields for items in different scopes either. 

The code will not index filters and facets defined for community scopes. Furthermore, child collections of a community with a custom configuration will not inherit this configuration and fall back to the default one. 

**To Reproduce**
General setup: 
* Set up a repository with at least one community and collection and some items.
* Configure a discovery configuration for a community. 
* Add additional filters and facets for this configuration that are not present in the default configuration.

To test the indexing: 
* Index the repository
* Verify in SOLR that the custom additional filters/facets are not indexed correctly

To the test the configuration retrieval for sub elements: 
* Retrieve the facets for the child collection by providing its handle in the scope parameter in the request
* Verify that the "default" facets are returned and not the ones from the community configuration

**Expected behavior**
The indexing process is expected to index all possible facets and filters from the scopes an item belongs to. This includes both communities and collections so that depending on the requested scope, data is present. 

When requesting the scope for a collection where none can be found, the first parent configuration should be returned. 

**Related work**
#8623
DSpace/dspace-angular#2021

### PR DESCRIPTION
**Pull request by YanaDePauw**
## References
* Fixes #8622
* Related Angular PR https://github.com/DSpace/dspace-angular/pull/2021

## Description
This PR fixed the Discovery scope based indexing and configuration retrieval. 

When indexing items, all present configurations will be taken into account to index all necessary filters and facets. 
Furthermore, when retrieving a configuration for a scope that does not have a custom configuration, it will now take the first encountered parent's configuration and use the "default" one when none is found. 

## Instructions for Reviewers
1. Set up a repository with at least different communities, sub-communities and collections with each containing at least one item and some collections containing a mapped item.
2. Configure custom discovery configurations for some of the communities and collections, each containing one unique facet. 
3. Make sure each item has a metadata value for each of the custom facets
4. Reindex the repository
5. Verify that for each collection, sub-community and community, the correct facets are shown containing the relevant values for the (mapped) items in them. 

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by tdonohue — CHANGES_REQUESTED** [review]
@YanaDePauw : Thanks for this refactor & the detailed tests.  Overall, it appears to be working (I tested it with https://github.com/DSpace/dspace-angular/pull/2021).
However, I have some suggestions inline below.  I'm most concerned about caching the entire DiscoveryConfiguration _for every single object_.... if I'm understanding the code correctly, it seems like it'd result in a lot of duplicative data in memory.  More inline below.  (That said, if I'm misunderstanding this code, please let me know)

**NOTE for other reviewers:**  This PR is a *lot smaller* than it looks.  Nearly 4,000 lines of it are test-related (and most of that is a new test `discovery.xml` which sets up various "inherited" discovery configs to verify this is all working.)

File: dspace-api/src/main/java/org/dspace/discovery/SearchUtils.java [hunk 1]
```diff
@@ -74,34 +77,67 @@ public static void clearCachedSearchService() {
     }
 
     public static DiscoveryConfiguration getDiscoveryConfiguration() {
```
Comment (abollini) [inline dspace-api/src/main/java/org/dspace/discovery/SearchUtils.java:79]: if possible please add a javadoc here as it was originally missing. Just to say that it is a shortcut of ... with all null parameter

File: dspace-api/src/main/java/org/dspace/discovery/SearchUtils.java [hunk 2]
```diff
@@ -74,34 +77,67 @@ public static void clearCachedSearchService() {
...
-        return getDiscoveryConfiguration(null, null);
+        return getDiscoveryConfiguration(null, null, null);
     }
 
-    public static DiscoveryConfiguration getDiscoveryConfiguration(DSpaceObject dso) {
-        return getDiscoveryConfiguration(null, dso);
+    public static DiscoveryConfiguration getDiscoveryConfiguration(final Context context,
```
Comment (abollini) [inline dspace-api/src/main/java/org/dspace/discovery/SearchUtils.java:83]: if possible please add a javadoc here as it was originally missing. Just to say that it is a shortcut of ... with a null prefix

File: dspace-api/src/main/java/org/dspace/discovery/SearchUtils.java [hunk 3]
```diff
@@ -128,46 +176,54 @@ public static List<String> getIgnoredMetadataFields(int type) {
      * A configuration object can be returned for each parent community/collection
      *
      * @param item the DSpace item
+     * @param context   the database context
      * @return a list of configuration objects
      * @throws SQLException An exception that provides information on a database access error or other errors.
      */
-    public static List<DiscoveryConfiguration> getAllDiscoveryConfigurations(Item item) throws SQLException {
+    public static List<DiscoveryConfiguration> getAllDiscoveryConfigurations(Item item, Context context)
```
Comment (abollini) [inline dspace-api/src/main/java/org/dspace/discovery/SearchUtils.java:183]: this signature looks a bit odd, usually the context is the first parameter

File: dspace-api/src/main/java/org/dspace/discovery/SolrServiceFileInfoPlugin.java [hunk 4]
```diff
@@ -53,10 +53,16 @@ public void additionalIndex(Context context, IndexableObject indexableObject, So
                         if (bitstreams != null) {
                             for (Bitstream bitstream : bitstreams) {
                                 document.addField(SOLR_FIELD_NAME_FOR_FILENAMES, bitstream.getName());
+                                document.addField(SOLR_FIELD_NAME_FOR_FILENAMES + "_keyword", bitstream.getName());
+                                document.addField(SOLR_FIELD_NAME_FOR_FILENAMES + "_filter", bitstream.getName());
```
[the remark this answers is not in the document]
Comment (abollini) [reply dspace-api/src/main/java/org/dspace/discovery/SolrServiceFileInfoPlugin.java:57]: this is needed to allow us to filter or facet by bitstream name. It is an unrelated issue than this PR but I'm ok with it

File: dspace-api/src/main/java/org/dspace/discovery/configuration/DiscoveryConfigurationService.java [hunk 5]
```diff
@@ -22,9 +30,17 @@
...
+    private static final Logger log = LogManager.getLogger();
+
     private Map<String, DiscoveryConfiguration> map;
     private Map<Integer, List<String>> toIgnoreMetadataFields = new HashMap<>();
 
+    /**
+     * Discovery configurations, cached by DSO UUID. When a DSO doesn't have its own configuration, we take the one of
+     * the first parent that does. This cache ensures we don't have to go up the hierarchy every time.
+     */
+    private final Map<UUID, DiscoveryConfiguration> uuidMap = new HashMap<>();
```
[the remark this answers is not in the document]
Comment (abollini) [reply dspace-api/src/main/java/org/dspace/discovery/configuration/DiscoveryConfigurationService.java:42]: the entry in this second cache is just a reference to the DiscoveryConfiguration so there is no memory overhead due to the DiscoveryConfiguration. Nevertheless, such cache is problematic as a full reindex would result in a large map with the uuid of all the dspace object in memory. Moreover, if an object is moved changing its parent the map will become inconsistent (an item moved to a different collection). Without such a cache the indexing performance would decrease drastically so we need to found a more sophisticated mechanism such as a Thread bound cache limiting the entry to only communities and collections uuid (reusable).

File: dspace-api/src/main/java/org/dspace/discovery/configuration/DiscoveryConfigurationService.java [hunk 6]
```diff
@@ -41,38 +57,94 @@ public void setToIgnoreMetadataFields(Map<Integer, List<String>> toIgnoreMetadat
         this.toIgnoreMetadataFields = toIgnoreMetadataFields;
     }
 
-    public DiscoveryConfiguration getDiscoveryConfiguration(IndexableObject dso) {
+    public DiscoveryConfiguration getDiscoveryConfiguration(final Context context,
```
Comment (abollini) [inline dspace-api/src/main/java/org/dspace/discovery/configuration/DiscoveryConfigurationService.java:60]: if possible please add a javadoc here as it was originally missing

File: dspace-api/src/main/java/org/dspace/discovery/configuration/DiscoveryConfigurationService.java [hunk 7]
```diff
@@ -41,38 +57,94 @@ public void setToIgnoreMetadataFields(Map<Integer, List<String>> toIgnoreMetadat
...
+            try {
+                parentObject = dSpaceObjectService.getParentObject(context, dso);
+            } catch (SQLException e) {
+                log.error(e);
+            }
+            configuration = getDiscoveryDSOConfiguration(context, parentObject);
+        }
+
+        // Cache the resulting configuration
+        uuidMap.put(dso.getID(), configuration);
```
Comment (abollini) [inline dspace-api/src/main/java/org/dspace/discovery/configuration/DiscoveryConfigurationService.java:111]: only collection and community uuid should be cached and only for a thread duration

File: dspace-server-webapp/src/test/data/dspaceFolder/config/spring/api/discovery.xml [hunk 8]
```diff
@@ -0,0 +1,3722 @@
+<?xml version="1.0" encoding="UTF-8"?>
```
Comment (abollini) [inline dspace-server-webapp/src/test/data/dspaceFolder/config/spring/api/discovery.xml:1]: I'm a bit worried about duplicate a such important configuration file for testing. For example if we accidentally remove an indexer that is needed by our application we would not note this change in our CI.
Should we refactor such configuration splitting it in more files? one for the mapping, one for the provider, one for each actual configuration? in this way we could add just the "extra configuration" in the test env and override the mapping

File: dspace-server-webapp/src/test/java/org/dspace/app/rest/matcher/FacetEntryMatcher.java [hunk 9]
```diff
@@ -99,6 +99,17 @@ public static Matcher<? super Object> hasContentInOriginalBundleFacet(boolean ha
         );
     }
 
+    public static Matcher<? super Object> matchFacet(String name, String facetType, boolean hasNext) {
```
Comment (abollini) [inline dspace-server-webapp/src/test/java/org/dspace/app/rest/matcher/FacetEntryMatcher.java:102]: all the other methods have hasNext as first argument

File: dspace/config/spring/api/discovery.xml [hunk 10]
```diff
@@ -53,9 +53,6 @@
                 <!-- Same as the "default" configuration, but does NOT filter out older versions of items -->
                 <!-- Used to display related items on single-item pages, because a relationship does not always point to the latest version of the related item -->
                 <entry key="default-relationships" value-ref="defaultRelationshipsConfiguration" />
-
-                <!--Use site to override the default configuration for the home page & default discovery page-->
-                <entry key="site" value-ref="homepageConfiguration" />
                 <!--<entry key="123456789/7621" value-ref="defaultConfiguration"/>-->
```
Comment (abollini) [inline dspace/config/spring/api/discovery.xml:56]: why are we removing such option? it was supported in previous version and implemented on the rest side. This allow institution to add custom components in their home page that use a different configuration than the default search

**Review by abollini — CHANGES_REQUESTED** [review]
thanks @YanaDePauw  for this PR. I have put some inline comments, the most important one is related to the new uuid based cache that must be revisited

**Comment by tdonohue** [comment]
@YanaDePauw : I wanted to let you know that we discussed this PR in today's dev meeting and decided we'd have to delay it for 7.6 (as we are wrapping up 7.5 now).  Unfortunately there are concerns that the cached map would cause issues during a full reindex or when an item is moved, see https://github.com/DSpace/DSpace/pull/8623#discussion_r1090001919   So, we feel this needs more analysis & discussion which we won't have time for before the 7.5 release

File: dspace-api/src/main/java/org/dspace/discovery/configuration/DiscoveryConfigurationService.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (ybnd) [reply dspace-api/src/main/java/org/dspace/discovery/configuration/DiscoveryConfigurationService.java:42]: For "deep" Comm/Coll hierarchies the performance impact of this cache is pretty significant when searching, and likely even more so during indexing... so I don't think we can get rid of it entirely.

However, if we limit it to Community/Collection only there I don't think there is as much to worry about 
* inconsistency → Communities/Collections don't support moves/mapping like Items do
* memory → Comm/Coll hierarchy is not likely to be large enough for this to be a concern

If consistency is still a concern we can also move the cache out to a separate service with a public method to clear it. Then we can play it safe and start from scratch whenever the Comm/Coll hierarchy is changed (on create, delete, ...)

Another approach we could take would be to look further into the performance of recursively retrieving all of a DSO's parents -- this is likely our bottleneck, if it can be improved the cache may become less crucial. This is something we'd have to look at anyway if we'd consider doing away with Solr-indexed authorizations for #8644.

All in all I don't think we need the additional complexity of a thread-bound cache here.

File: dspace-api/src/main/java/org/dspace/discovery/configuration/DiscoveryConfigurationService.java (hunk 7 above)
Comment (ybnd) [reply dspace-api/src/main/java/org/dspace/discovery/configuration/DiscoveryConfigurationService.java:111]: @abollini limiting the cache to a single thread would undermine the performance gain for e.g. regular REST requests.

I don't think this is really necessary if we limit the cache to Comm/Coll only, since this makes the structure much simpler
* Comm/Coll structure can only change ~ create/delete
* When a Comm/Coll is created, it will be added to the cache the first time its discovery config is resolved
* When a Comm/Coll is deleted, it will remain in the cache until Tomcat is restarted. However, we only ever retrieve configurations for _existing_ DSOs, so this is not a problem.

File: dspace-server-webapp/src/test/data/dspaceFolder/config/spring/api/discovery.xml (hunk 8 above)
Comment (ybnd) [reply dspace-server-webapp/src/test/data/dspaceFolder/config/spring/api/discovery.xml:1]: > Should we refactor such configuration splitting it in more files? one for the mapping, one for the provider, one for each actual configuration

@abollini Good point, but I think this needs some more discussion & feels out of scope for this PR.

For now we can remove the duplicate `discovery.xml` and move the "test configurations" to a separate file?

File: dspace/config/spring/api/discovery.xml (hunk 10 above)
Comment (YanaDePauw) [reply dspace/config/spring/api/discovery.xml:56]: The homepage configuration is not being used in DSpace (both REST and Angular).
Both the search bar on the homepage and the search icon in the header go to the general "/search" page using the "default" configuration where you can also go back and forth between community/collection based scopes. 

I removed this configuration since it is confusing to have a configuration present that does not do anything.

File: dspace-server-webapp/src/test/data/dspaceFolder/config/spring/api/discovery.xml (hunk 8 above)
Comment (YanaDePauw) [reply dspace-server-webapp/src/test/data/dspaceFolder/config/spring/api/discovery.xml]: Moved the changes to a `test-discovery.xml`. In this file the `DiscoveryConfigurationService` is overwritten because the additional configuration needs to be added to the map defined in the service. 

As a consequence there are two instances of the service definition but the test one is used correctly in the tests. 

Whenever there are more changes to the mapping, it will still need to be updated in the test file as well, but plugins or the beans representing the configuration  will not need to be copied.

File: dspace-server-webapp/src/test/java/org/dspace/app/rest/DiscoveryScopeBasedRestControllerIT.java [hunk 11]
```diff
@@ -0,0 +1,625 @@
...
+ *      -- Collection 222
+ *
+ * Each custom configuration contains a unique index for a unique metadata field, to verify if correct information is
+ * indexed and provided for the different search scopes.
+ *
+ * Each collection has an item in it. Next to these items, there are two mapped items, one in collection 111 and 222,
+ * and one in collection 122 and 211.
+ *
+ * The tests will verify that for each object, the correct facets are provided and that all the necessary fields to
+ * power these facets are indexed properly.
```
Comment (tdonohue) [inline dspace-server-webapp/src/test/java/org/dspace/app/rest/DiscoveryScopeBasedRestControllerIT.java:60]: Can we add a comment to this IT class that it uses/requires the `src/test/data/dspaceFolder/config/spring/api/test-discovery.xml` file?  I think it's important that this IT links back to the test configs, as they are very dependent on one another.

File: dspace-server-webapp/src/test/java/org/dspace/app/rest/DiscoveryScopeBasedRestControllerIT.java [hunk 12]
```diff
@@ -0,0 +1,625 @@
...
+                                               FacetValueMatcher.matchEntry("collection111field",
+                                                                            "collection111field-mappedItem111222", 1)
+                                       )
+                   ));
+    }
+
+    @Test
+    public void ScopeBasedIndexingAndSearchTestCollection112() throws Exception {
+
+        getClient().perform(get("/api/discover/facets").param("scope", String.valueOf(collection112.getID())))
```
Comment (tdonohue) [inline dspace-server-webapp/src/test/java/org/dspace/app/rest/DiscoveryScopeBasedRestControllerIT.java:362]: It'd be very useful to add inline comments to these tests...to make it easier to understand the scenario each one is testing for.  E.g. This test seems to be testing for proper inheritance, as it inherits from `SubCommunity11`... while the SubCommunity11 test above is testing that a unique configuration in test-discovery.xml is loaded.

Having brief comments above each test which tell a developer what we are testing for would make this MUCH easier to read.  Otherwise, I have to have a few windows open and compare the data structure to what is in test-discovery.xml and also what is in this test. In other words, this is a bit of a maintenance nightmare as the tests are not self-describing... so we need to describe them with inline comments.

File: dspace/config/spring/api/discovery.xml (hunk 10 above)
Comment (tdonohue) [reply dspace/config/spring/api/discovery.xml:60]: I agree that we should remove this as it's no longer used/needed.  It makes no sense to keep configurations in `discovery.xml` which are unused.

File: dspace-api/src/main/java/org/dspace/discovery/configuration/DiscoveryConfigurationService.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (tdonohue) [reply dspace-api/src/main/java/org/dspace/discovery/configuration/DiscoveryConfigurationService.java]: I see this cache has been updated to only include Communities and Collections, and this approach seems better.  So, I think this looks good now. Thanks @ybnd

**Review by tdonohue — COMMENTED** [review]
@YanaDePauw and @ybnd : I finally got back to this PR today.  I appreciate the refactors & the code cleanup.  Everything is looking good to me now.. I just have a few *very minor* suggestions (primarily adding some additional comments to make the code easier to understand, especially the ITs).  

I'm basically a +1 to this code though, and I feel it looks good.  @abollini : I also verified that all your prior feedback now looks to be addressed.

File: dspace-api/src/main/java/org/dspace/discovery/configuration/DiscoveryConfigurationService.java [hunk 13]
```diff
@@ -22,9 +32,18 @@
...
+
     private Map<String, DiscoveryConfiguration> map;
     private Map<Integer, List<String>> toIgnoreMetadataFields = new HashMap<>();
 
+    /**
+     * Discovery configurations, cached by Community/Collection UUID. When a  Community or Collection does not have its
+     * own configuration, we take the one of the first parent that does.
+     * This cache ensures we do not have to go up the hierarchy every time.
+     */
+    private final Map<UUID, DiscoveryConfiguration> comColToDiscoveryConfigurationMap = new HashMap<>();
```
Comment (abollini) [inline dspace-api/src/main/java/org/dspace/discovery/configuration/DiscoveryConfigurationService.java:45]: @YanaDePauw ok we can keep it simple and don't use a thread bound map but in this case we need to pick a Thread-safe implementation like the `ConcurrentHashMap` otherwise we could get issues il multiple users make changes to this map. Please note that it is not completely true that community and collection cannot be moved as we have a script to do that but this is not a very frequent scenario that would require in any case a reindex, so I'm ok with that. @tdonohue would be better to add a message in the `org.dspace.administer.CommunityFiliator` output to remind about the need to restart tomcat and reindex the content?

**Review by abollini — CHANGES_REQUESTED** [review]
thanks @YanaDePauw my feedback is almost processed, please take a look to my inline comment

**Review by abollini — CHANGES_REQUESTED** [review]
thanks @YanaDePauw my feedback is almost processed, please take a look to my inline comment

**Review by abollini — CHANGES_REQUESTED** [review]
thanks @YanaDePauw my feedback is almost processed, please take a look to my inline comment

File: dspace-api/src/main/java/org/dspace/discovery/configuration/DiscoveryConfigurationService.java (hunk 13 above)
Comment (tdonohue) [reply dspace-api/src/main/java/org/dspace/discovery/configuration/DiscoveryConfigurationService.java:45]: @abollini : While I'm not against adding a message to CommunityFiliator, I think we can also simply just add a note to the documentation here: https://wiki.lyrasis.org/display/DSDOC7x/Managing+Community+Hierarchy

In fact, I'm going to add that note immediately, simply because I suspect reindexing is already necessary (it's just undocumented).  The only new requirement we are adding in this PR is that you likely also need to restart Tomcat in order to reset any cached community/collection information.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @YanaDePauw !  My feedback has been addressed.  I gave this one last test with the frontend PR (https://github.com/DSpace/dspace-angular/pull/2021) and it's working well.

I also setup a Collection locally with a custom `discovery.xml` configuration (based on collection handle) with a different set of Facets & was able to verify in my Chrome DevTools that the request to `/api/discover/facets?scope=[collection-uuid]` returned those custom facets from `discovery.xml`. 

So, this appears to be working as designed.  Thanks!

@abollini : If you have a chance to re-review, it appears your feedback has been addressed.
