### PR TITLE
Unify treatment of DOIs

### LINKED ISSUE #9901: Improved storage of DOIs in DSpace
## References
* This ticket *replaces* #5565 and #7055.  
    * These previous tickets identified the problems, but documented outdated solutions.
* This ticket documents a consensus that occurred in the [DevMtg on Oct 17, 2024](https://wiki.lyrasis.org/display/DSPACE/2024-10-17+DSpace+Developers+Meeting). The ticket details the recommendations out of that meeting, and are based on @pilasou 's slides shared in the meeting notes.

## Describe the bug
In DSpace 7.x and 8.x, DSpace stores DOIs generated by DSpace inconsistently alongside Handles (see also #5565)
* Handles in `dc.identifier.uri`
* DataCite DOIs in `dc.identifier.uri`
* EZID DOIs in `dc.identifer`

In addition, DSpace has no recommendations for where to store Publisher (or externally generated) DOIs (see #7055).  Some sites will store these also in `dc.identifier.doi` (or based on the decisions of sites)

Finally, a deprecated DOI proxy of "dx.doi.org" is used for storage of DOIs.

## Expected / Improved behavior
Per consensus in the [DevMtg on Oct 17, 2024](https://wiki.lyrasis.org/display/DSPACE/2024-10-17+DSpace+Developers+Meeting), we recommend the following changes to DSpace's behavior.

* Handles should remain in `dc.identifier.uri` (as they have been historically)
* DataCite DOIs **should move** to `dc.identifier.doi`
* EZID DOIs **should move** to `dc.identifier.doi`

In addition, the following updates should be made
1. Publisher or externally generated DOIs should be store in `dc.relation.hasversion`.  This keeps externally-generated DOIs separate.
    * All [external sources](https://wiki.lyrasis.org/pages/viewpage.action?pageId=104566672#ImportingItemsviabasicbibliographicformats(Endnote,BibTex,RIS,CSV,etc)andonlineservices(arXiv,PubMed,CrossRef,CiNii,etc)-SupportedExternalSources) which import DOIs should be updated to use `dc.relation.hasversion` for these external identifiers
    * This `dc.relation.hasversion` field should be displayed on the Item page **by default**, with a label similar to "Related Works" or "Related Identifiers"
2. The "dc.identifier.doi" field should be displayed on the Item Page **by default** (if it is not already).
3. All DOIs should be updated to use the recommended DOI Proxy of "https://doi.org"
4. DSpace should have an (optional) migration script to move existing DOIs to these new fields.  This script should move existing DOIs to the appropriate field (based on whether the DOI is created by DSpace or externally created), and update all DOIs to use "https://doi.org" instead of "dx.doi.org".
    * This script should be documented in the Release Notes as **highly recommended** for all sites.  We should also document that, if you use this script to move your DOIs, then they will display better (by default) on the Item Pages.

### PR DESCRIPTION
**Pull request by quasipoint**
## References

* Fixes #9901

## Description

- [x] Consistently mint new DOIs to the `dc.identifier.doi` metadata field
  - [x] coding done
  - [x] tested
- [x] Consistently put external DOIs in the `dc.relation.hasversion`
  - [x] coding done
  - [x] tested
- [x] Provide a migration/normalization tool to move all existing DOIs into the new metadata regime
  - [x] coding done
  - [x] tested
- [x] miscellaneous changes, e.g. OAI should get DOIs from `dc.identifier.doi` in future?
  - [x] don’t use deprecated `Option.builder().build()` method in `DOIOrganiser`

The exact metadata fields used are now customizable, even if they previously weren’t. Where applicable, I have cherry-picked the commits for the existing functionality for this from DSpace-CRIS, so that it should be apparent when merging the projects in future that this functionality has already been adopted.

Developed by The Library Code with the support of Technische Universität Dortmund and Deutsche Forschungsgemeinschaft DFG.

## Instructions for Reviewers

Mint some test DOIs with DataCite and EZID

Import some external sources that have DOIs

Try running the migration tool to normalize items which have a DOI in the wrong place

Please also try to find places in the rest of the DSpace source code which look for DOI metadata specifically in some metadata field and need to be updated to look in the new standard fields. They may also expect the metadata in some other format than `https://doi.org/10.whatever`, in which case they will also need to be updated. We tried to find as many places like this as possible but we might have missed some.

### Draft documentation of the `doi-migrate` tool for DSpace wiki

The `doi-migrate` command helps to migrate DOI metadata between fields and normalize their format.

As of DSpace 10 the default practice for storing DOI metadata has changed:

- DOIs minted from within DSpace will be stored in `dc.identifier.doi` metadata
- DOIs of documents imported from crosswalks will be stored in `dc.relation.hasversion`

In both cases, DOIs will now be stored in the HTTPS URL form `https://doi.org/10.<whatever>`, rather than just plain `10.<whatever>` or `doi:10.<whatever>` or the old HTTP URL form `http://dx.doi.org/10.<whatever>`.

In previous versions, DOIs could end up inconsistently in `dc.identifier` or `dc.identifier.doi` or `dc.identifier.uri`, and may have had different formats, in both cases depending where they came from.

The `doi-migrate` tool helps to move existing DOI metadata from the older fields and formats to this newer standard, but can also move to other fields if desired.

#### Usage

```
Selecting which DOIs to migrate:

--only-prefix <doi-prefix>     Only migrate DOIs with the given prefix
--except-prefix <doi-prefix>   Only migrate DOIs without the given prefix

Choosing which fields to affect:

-f, --from <field-name>    Move DOIs from this field
-t, --to <field-name>      Move DOIs into this field
(--from and --to can be the same if only the formatting of DOIs should be adjusted)

Operating modes:

-n, --dry-run  Don’t actually perform a migration, just generate a CSV (on standard output)
--rehydrate    Perform the migrations from a previous --dry-run invocation (CSV read from standard input)
```

You must either give both `--to` and `--from` plus one of `--only-prefix` and `--except-prefix`, OR `--rehydrate`.

The tool recognizes DOIs in any of the following formats:

- a plain DOI such as `10.1234/56789`
- an old-style DOI URL like `http://dx.doi.org/10.1234/56789` (including if HTTPS was used)
- a new-style DOI URL like `https://doi.org/10.1234/56789` (including if plain HTTP was used)
- a DOI URI like `doi:10.1234/56789`

It normalizes all of these to a new-style DOI URL with HTTPS (`https://doi.org/10.1234/56789`)

#### How-to guide for a typical institution

The tool is set up to assume that all of your DOI minted in-house have the same prefix, and all other prefixes are external. (The prefix is the part of the DOI before the `/` character.) This example will assume an institution whose own publications have the prefix `10.1729`. The institution’s minted DOIs have so far been placed in `dc.identifier`.

First we will create a CSV file of all the in-house DOIs that need to be migrated. We will move them into `dc.identifier.doi` field in the new format.

```
dspace doi-migrate --dry-run --from dc.identifier --to dc.identifier.doi --only-prefix 10.1729 > in-house-dois.csv
```

This will create a file `in-house-dois.csv` that can be checked in any spreadsheet software, including Microsoft Excel, Apple Numbers, Google Sheets, or LibreOffice Calc. Check that all of the proposed changes to metadata look correct. The columns are in the order: Item UUID; field name that the metadata will be moved from; current value of that metadata field on the item; field name that the metadata will be moved to; changed/normalized value of the metadata field on that item.

Having checked that the proposed changes look okay, run the migration with:

```
dspace doi-migrate --rehydrate < in-house-dois.csv
```

If there are multiple prefixes for publications whose DOIs were minted locally, this process can be repeated several times.

Then we will migrate all the DOIs for publications which were imported from external sources like ArXiv. The importers used to store these in `dc.identifier.doi` without the HTTPS URL; following the new DSpace standard, we will move them to `dc.relation.hasversion`. The usage is very similar:

```
dspace doi-migrate --dry-run --from dc.identifier.doi --to dc.relation.hasversion --except-prefix 10.1729 > imported-dois.csv
```

Again, we check the `imported-dois.csv` file to make sure that everything looks to be in order. Then we actually run the migrations:

```
dspace doi-migrate --rehydrate < imported-dois.csv
```

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome).
However, reviewers may request that you complete any actions in this list if you have not done so. If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR **passes Checkstyle** validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR **includes Javadoc** for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR **passes all tests and includes new/updated Unit or Integration Tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

This work was developed by The Library Code with support of Technische Universität Dortmund and Deutsche Forschungsgemeinschaft.

### CODE REVIEW

**Comment by mwoodiupui** [comment]
On Thu, Nov 13, 2025 at 05:39:38PM +0000, Alan Orth wrote:
>   *   Perhaps a wider discussion, but why don't we start using Dublin Core Terms (2008) instead of Qualified Dublin Core (2000)

That's a good question.  On the one hand, it would be a fair amount of
work:  the 'dc' namespace is deeply embedded in DSpace code.  On the
other...what would that work buy us?

We can use any namespace that DSpace knows about, so we could use
'dcterms' (or something else) where it is the best fit for a new
feature, without pulling out existing uses of 'dc'.  That's one of the
nice things about the way metadata was realized in DSpace.  We already
have and use a 'dspace' namespace for concepts that are specific to
the product.

Right now I would rather see us implement schema support for our
namespaces.  DCMI (and, presumably, others) publish type and validity
information that we are not using.  It would be nice, for example, if
DSpace would know that dc.date.accessioned *is* a date and refuse to
store something silly like "Tuesday" or "woops, I meant to put this in
the Abstract field".

-- 
Mark H. Wood
Lead Technology Analyst

University Library
Indiana University Indianapolis
755 W. Michigan Street
Indianapolis, IN 46202
317-274-0749
library.indianapolis.iu.edu

**Comment by kshepherd** [comment]
@mwoodiupui i'm guessing you intended your comment for the issue rather than this pull request? (we're happy enough using whatever field is decided and making it configurable, for this PR)

**Comment by quasipoint** [comment]
Ready to review!

**Comment by pnbecker** [comment]
@pilasou If I remember correctly, you were quite interested in getting this solved, right? Do you think you can test and review it?

**Comment by pilasou** [comment]
Hi @pnbecker, sure, I will give it a try. I understand this is the script to update existing items. The DOI generation by DSpace has not been changed yet (storing DOI in dc.identifier.doi rather than dc.identifier.uri). Thanks!

**Comment by pnbecker** [comment]
Thank you @pilasou.
This PR introduces the migrate script and makes it configurable where DOIs are stored. For example here: 
https://github.com/DSpace/DSpace/pull/11545/files#diff-a33fc950c2c8a6e2e7f89872a1c9b40f516ae91bd06a8d8da3d1c639dc0b70f8R173-R177 in combination with https://github.com/DSpace/DSpace/pull/11545/files#diff-a33fc950c2c8a6e2e7f89872a1c9b40f516ae91bd06a8d8da3d1c639dc0b70f8R1081-R1086

**Comment by quasipoint** [comment]
Yes, this is (or should be) a complete implementation of the resolution of the DSpace developer meeting of 2024-10-17 about future DOI storage. It includes the migrate script, but also changes the default place that minted DOIs from DataCite and EZID are stored to `dc.identifier.doi`, and the place that DOIs from import crosswalks are stored to `dc.relation.hasversion`. However, both of these are customizable (which wasn’t the case for minted DOIs previously)

**Comment by pilasou** [comment]
Hi @quasipoint hi @pnbecker, I have tested the script using DSpace Docker environnement. I was only able to use the script to change the DOI storage metadata of existing items and to import from external source (I have not tested all source, only: DOI, Pubmed, OpenAIRE, OpenAlex and ArXiv).

I have not tested DOI registration.

I confirm that bothe DOI storage metadata changes and Import from external sources works as describe (see details below, thought the DOI was imported in dc.relation.hasversion, I noticed a few little problems).

**1) Changing DOI metadata storage for existing items**
For each test, I first used the -n option to deplay a report of what would be change. I also test the rehydrate option for one of the test (c) and it worked.

_a) An Item with DOI ID stored in dc.identifier.doi_
Command line used : ./dspace doi-migrate -f dc.identifier.doi -t dc.relation.hasversion --only-prefix 10.1177
Results: SUCCESS. DOI is stored in its URL form (https://doi.org/10.1177/304948262513933909) and as been moved to dc.relation.hasversion. Metadata dc.identifier.doi has been deleted.

_b) An item with DOI URL (HTTPS) in dc.identifier_
Command line: ./dspace doi-migrate -f dc.identifier -t dc.relation.hasversion --only-prefix 10.1525
Results: SUCCESS
DOI stored in its URL form (https://doi.org/10.1177/304948262513933909) in dc.relation.hasversion. dc.identifier metadata has been removed.

_c) An item with DOI former URL (http://dx.doi.org/) in dc.identifier.uri_
Command line: ./dspace doi-migrate -f dc.identifier.uri -t dc.identifier.doi --only-prefix 10.1016 -n > tmp/101016.csv
Results:
"ItemUUID","FromFieldName","FromValue","ToFieldName","ToValue"
"0136fe00-43ca-439e-ae6c-b2b08c2b8f5e","dc.identifier.uri","http://dx.doi.org/10.1016/j.jacc.2023.09.339","dc.identifier.doi","https://doi.org/10.1016/j.jacc.2023.09.339"
"0136fe00-43ca-439e-ae6c-b2b08c2b8f5e","dc.identifier.uri","http://dx.doi.org/10.1016/j.jacc.2023.09.339","dc.identifier.doi","https://doi.org/10.1016/j.jacc.2023.09.339"
"d5dad1b3-3013-4d98-b091-568c90a4f124","dc.identifier.uri","https://doi.org/10.1016/j.chom.2018.05.012","dc.identifier.doi","https://doi.org/10.1016/j.chom.2018.05.012"
"d5dad1b3-3013-4d98-b091-568c90a4f124","dc.identifier.uri","https://doi.org/10.1016/j.chom.2018.05.012","dc.identifier.doi","https://doi.org/10.1016/j.chom.2018.05.012"

I then used the rehydrate command to apply the change. 
cat /tmp/101016.csv | ./dspace doi-migrate --rehydrate

_d) Prefix exlusion test_
./dspace doi-migrate -f dc.identifier.doi -t dc.relation.hasversion --except-prefix 10.1016 -n
Results: SUCCESS. Only dc.identifier.doi not using 10.1016 were returned.

_e) Use URL that are not DOI in dc.identifier.doi (ex: https://essd.copernicus.org/articles/13/1561/2021/)_
Results: SUCCESS. The item is not processed. 

**2) Metadata Import**

_a) From ArXiv (ID used 1808.04773)_
Results: SUCCESS. DOI stored in dc.relation.hasversion

_b) From OpenAlex_
By title : I was not able to recieved results. I searched for complete title, not workds in the title (ex: Structure and Expression of the Mouse Gene Encoding the Orphan Nuclear Receptor TEC)
By Author ID : ID used a5055032546. DOI was added to dc.relation.hasversion
By DOI: ID used 10.1056/nejmoa1514616. DOI was added to dc.relation.hasversion but also in dc.identifier.other.

_c) From OpenAIRE_
By Title: DOI not part of the metadata imported. Title used: Fast(er) Robust Point Cloud Alignment Using Lie Algebra https://explore.openaire.eu/search/publication?pid=10.1109%2Firos60139.2025.11247419
By Author: DOI not part of the metadata imported. Author used: Ollevier, Thierry. (Title: CsF/clinoptilolite: an efficient solid base in S<sub>N</sub>Ar and copper-catalyzed Ullmann reactions)

_d) From DOI_
Crossref (ID used 10.1002/9780470015902.a0023273): SUCCESS. DOI stored in dc.relation.hasversion
Datacite (ID used 10.60918/17362): SUCCESS. DOI stored in dc.relation.hasversion
DOI (ID used 10.1517/17460441.2013.798296): SUCCESS. DOI stored in dc.relation.hasversion


_e) From Pubmed and Pubmed Europe (ID used 15043867 - https://pubmed.ncbi.nlm.nih.gov/15043867/)_
When Using Pubmed, the DOI is not part of the metadata imported.
When Using Pubmed Europe, the DOI is imported in dc.relation.hasversion

**Comment by quasipoint** [comment]
> _c) An item with DOI former URL (http://dx.doi.org/) in dc.identifier.uri_ Command line: ./dspace doi-migrate -f dc.identifier.uri -t dc.identifier.doi --only-prefix 10.1016 -n > tmp/101016.csv Results: "ItemUUID","FromFieldName","FromValue","ToFieldName","ToValue" "0136fe00-43ca-439e-ae6c-b2b08c2b8f5e","dc.identifier.uri","[http://dx.doi.org/10.1016/j.jacc.2023.09.339","dc.identifier.doi","https://doi.org/10.1016/j.jacc.2023.09.339](http://dx.doi.org/10.1016/j.jacc.2023.09.339%22,%22dc.identifier.doi%22,%22https://doi.org/10.1016/j.jacc.2023.09.339)" "0136fe00-43ca-439e-ae6c-b2b08c2b8f5e","dc.identifier.uri","[http://dx.doi.org/10.1016/j.jacc.2023.09.339","dc.identifier.doi","https://doi.org/10.1016/j.jacc.2023.09.339](http://dx.doi.org/10.1016/j.jacc.2023.09.339%22,%22dc.identifier.doi%22,%22https://doi.org/10.1016/j.jacc.2023.09.339)" "d5dad1b3-3013-4d98-b091-568c90a4f124","dc.identifier.uri","[https://doi.org/10.1016/j.chom.2018.05.012","dc.identifier.doi","https://doi.org/10.1016/j.chom.2018.05.012](https://doi.org/10.1016/j.chom.2018.05.012%22,%22dc.identifier.doi%22,%22https://doi.org/10.1016/j.chom.2018.05.012)" "d5dad1b3-3013-4d98-b091-568c90a4f124","dc.identifier.uri","[https://doi.org/10.1016/j.chom.2018.05.012","dc.identifier.doi","https://doi.org/10.1016/j.chom.2018.05.012](https://doi.org/10.1016/j.chom.2018.05.012%22,%22dc.identifier.doi%22,%22https://doi.org/10.1016/j.chom.2018.05.012)"

Were there two copies of the metadata on each item? I’m not understanding why it’s showing each migration twice. This might be a bug in the migrator?

> _b) From OpenAlex_ By title : I was not able to recieved results. I searched for complete title, not workds in the title (ex: Structure and Expression of the Mouse Gene Encoding the Orphan Nuclear Receptor TEC)

This is probably a different bug.

> By DOI: ID used 10.1056/nejmoa1514616. DOI was added to dc.relation.hasversion but also in dc.identifier.other.

This appears to be a quirk of OpenAlex and the existing integration. I’m not sure what to do about it.

> _c) From OpenAIRE_ By Title: DOI not part of the metadata imported. Title used: Fast(er) Robust Point Cloud Alignment Using Lie Algebra https://explore.openaire.eu/search/publication?pid=10.1109%2Firos60139.2025.11247419 By Author: DOI not part of the metadata imported. Author used: Ollevier, Thierry. (Title: CsF/clinoptilolite: an efficient solid base in SNAr and copper-catalyzed Ullmann reactions)
>
> [snip]
>
> _e) From Pubmed and Pubmed Europe (ID used 15043867 - https://pubmed.ncbi.nlm.nih.gov/15043867/)_ When Using Pubmed, the DOI is not part of the metadata imported.

If the DOI is not imported at all, this appears to be a separate, pre-existing bug, at least for Pubmed. There is no code to import the DOI here: https://github.com/DSpace/DSpace/blob/main/dspace/config/spring/api/pubmed-integration.xml

I’m less sure about OpenAIRE. That might genuinely have been introduced by this patch. The OpenAIRE, ArXiv, and VuFind importers were harder to test because they have no integration tests; when I tried to write some for them, I found that these use a different HTTP class which is harder to mock, so I decided not to add new tests for them in this PR.

I’ll try to reproduce the OpenAIRE bug and fix it.

**Comment by quasipoint** [comment]
I can reproduce the OpenAIRE bug on some items, but not others. Still investigating.

**Comment by quasipoint** [comment]
Fixed in 65af37c

**Comment by quasipoint** [comment]
The OpenAlex search by title query you mentioned is also broken for me on DSpace `main` (ac53150aaaa6f3184ca282289b81bbbef478f525). Others work though (e.g. try [chemical basis of morphogenesis])

**Comment by quasipoint** [comment]
Okay, but [chemical basis of morphogenesis] does not return any results either on my branch. So there is something wrong. Looking into it

**Comment by quasipoint** [comment]
Err, but just [chemical] on its own does work (also worked on `main`), and returns papers including Turing’s morphogenesis paper. So this appears to be nondeterministic, hooray

**Comment by quasipoint** [comment]
And now when I logged out and back in again, [chemical basis of morphogenesis] *did* work (on my branch). Aaaaa

**Comment by pnbecker** [comment]
@pilasou @quasipoint adjusted this PR. Besides pre-existing problems in OpenAlex this should be ready for a re-review.

@tdonohue I cannot put it @pilasou as a reviewer. Do you have to add him first somewhere?

**Comment by tdonohue** [comment]
@pnbecker : Yes, it's a GitHub limitation that we can only assign reviewers if they are added first to the "DSpace" GitHub project with basic developer permissions.  @pilasou , I've sent you an invitation to be added to the "DSpace" GitHub project.

That all said, as always, *anyone* can perform a review without being assigned.  In that scenario, if you add a review, your name will appear in the "Reviewers" column *after* you submit your review.

**Comment by pilasou** [comment]
HI @quasipoint hi @pnbecker, I have re-run all the test I first done (as described in comment: https://github.com/DSpace/DSpace/pull/11545#issuecomment-3791709320). I am happy to report that all my test were successfull except the one with Pubmed which still do not import the DOI. 

Following are also the test that previously failed but passed now: 

- OpenAlex - By title : doi imported in dc.relation.ispartof (Title used: Structure and Expression of the Mouse Gene Encoding the Orphan Nuclear Receptor TEC)
- OpenAIRE - By Title : doi imported in dc.relation.ispartof (Title used: Fast(er) Robust Point Cloud Alignment Using Lie Algebra)
- OpenAIRE - By Author : doi imported in dc.relation.isaprtof (Author used: Ollevier, Thierry. (Title: CsF/clinoptilolite: an efficient solid base in SNAr and copper-catalyzed Ullmann reactions))

When using Pubmed, the DOI is still not part of the metadata imported. (ID used 15043867 - https://pubmed.ncbi.nlm.nih.gov/15043867/).

**Comment by quasipoint** [comment]
> Following are also the test that previously failed but passed now:
> 
>     * OpenAlex - By title : doi imported in dc.relation.ispartof (Title used: Structure and Expression of the Mouse Gene Encoding the Orphan Nuclear Receptor TEC)
> 
>     * OpenAIRE - By Title : doi imported in dc.relation.ispartof (Title used: Fast(er) Robust Point Cloud Alignment Using Lie Algebra)
> 
>     * OpenAIRE - By Author : doi imported in dc.relation.isaprtof (Author used: Ollevier, Thierry. (Title: CsF/clinoptilolite: an efficient solid base in SNAr and copper-catalyzed Ullmann reactions))

Can you double check this? It’s supposed to be in `dc.relation.hasversion`, not `dc.relation.ispartof`. If this is a bug, I can’t reproduce it being put in `ispartof`.

> When using Pubmed, the DOI is still not part of the metadata imported. (ID used 15043867 - https://pubmed.ncbi.nlm.nih.gov/15043867/).

I will create an issue for this problem

**Comment by pnbecker** [comment]
the failing integration tests are coming from a rebase this morning. We are working on that.

**Comment by pilasou** [comment]
@quasipoint Hi, to answer you comment (https://github.com/DSpace/DSpace/pull/11545#issuecomment-3926408394) following my test, sorry, this was my mistake, all doi were sent correctly in dc.relation.hasversion metadata and not dc.relation.ispartof.

**Comment by quasipoint** [comment]
`git bisect` identifies b6212a9aad36a2ad99ec206280cfe2dac9810ce9 as the culprit

File: dspace-api/src/main/java/org/dspace/identifier/doi/DOIMigrator.java [hunk 1]
```diff
@@ -0,0 +1,310 @@
...
+            String toValue) {
+    }
+
+    public DOIMigrator(Context context) {
+        this.context = context;
+        this.itemService = ContentServiceFactory.getInstance().getItemService();
+        this.metadataFieldService = ContentServiceFactory.getInstance().getMetadataFieldService();
+    }
+
+    public static void main(String[] args) {
```
Comment (steph-ieffam) [inline dspace-api/src/main/java/org/dspace/identifier/doi/DOIMigrator.java:70]: @quasipoint, is there a specific reason you’re still using the legacy approach to implement the scripts?

I really think this approach should no longer be used. My suggestion would be to switch to the `DSpaceRunnable` framework and use `scripts.xml` instead of `launcher.xml` and the legacy style.

The `isAllowedToExecute` method in the configuration class that extends `ScriptConfiguration` should work well for restricting the script to specific users.

**Review by steph-ieffam — CHANGES_REQUESTED** [review]
@quasipoint I've done a review and the code looks good. Just the DOIMigrator script approach is not fully correct to me

File: dspace-api/src/main/java/org/dspace/identifier/doi/DOIMigrator.java (hunk 1 above)
Comment (pnbecker) [reply dspace-api/src/main/java/org/dspace/identifier/doi/DOIMigrator.java:70]: @steph-ieffam Thank you very much for the review!

We didn't see this as legacy approach. While we see benefits in `DSpaceRunnable` in general, this is a script thought to be run only once, only during a data migration or upgrade and only by administrators with full system access. We wanted to avoid that this script requires a valid `eperson` as it will be used as a data transformation.

So this is not a normal script, that should ever be started via webui. We think, it should run as part of a migration/upgrade to a new major version of DSpace only, when you also have time to adopt the `submission-forms.xml` and the configuration of the `DOIIdentifierProvider` to reflect the change of metadata fields. And to limit it to this case (upgrade/migration), we thought it's good to keep it simple and runnable via CLI only without the need of a valid eperson.

Comment (pnbecker) [reply dspace-api/src/main/java/org/dspace/identifier/doi/DOIMigrator.java:70]: @steph-ieffam Do you want us to change it to a DSpaceRunnable or do you agree with our reasoning why we did this differently?

Comment (steph-ieffam) [reply dspace-api/src/main/java/org/dspace/identifier/doi/DOIMigrator.java:70]: @pnbecker if the changes are time consuming I don't want to force on this matter. But I think we should discuss it in one of our developer's meeting so that we all agree if this approach should be avoided at all or is just fine in cases like this.
We could bring this at the next developer meeting if it's ok

Comment (pnbecker) [reply dspace-api/src/main/java/org/dspace/identifier/doi/DOIMigrator.java:70]: Good idea. @tdonohue  please add this to the agenda for the meeting next week, when you’re back.

**Comment by quasipoint** [comment]
Note the review of this branch by @aprilherron in https://github.com/DSpace/DSpace/pull/11962#issuecomment-4093593055

**Comment by kshepherd** [comment]
@tdonohue fyi this PR is required, and is included, by the Crossref DOI PR which has a positive review by @benbosman (see https://github.com/DSpace/DSpace/pull/11962#issuecomment-4120057744) - so the changes contained in this PR are effectively already reviewed

**Review by steph-ieffam — APPROVED** [review]
as discussed with the comunity everyone is fine with the script approach so I'm approving the PR since everything else looks fine to me

File: dspace-api/src/main/java/org/dspace/identifier/doi/DOIMigrator.java (hunk 1 above)
Comment (tdonohue) [reply dspace-api/src/main/java/org/dspace/identifier/doi/DOIMigrator.java:70]: We discussed in today's dev meeting and agreed that this script can be command-line only because it's a migration script.  It's not meant to be run from the UI.

**Comment by tdonohue** [comment]
Merging as this is at +2 (from 4Science and Atmire team members).  

@quasipoint, @kshepherd and @pnbecker :  I'm adding the "needs documentation" label here because this PR will require documentation updates to the DSpace 10 documentation (especially to the DOI pages). https://wiki.lyrasis.org/display/DSDOC10x/

Once those updates have been made, we can review the flag

**Comment by pilasou** [comment]
Hi @quasipoint @tdonohue Just throwing ideas for the documentation of this major improvment, 

3 aspects should be added to the DOI page (https://wiki.lyrasis.org/display/DSDOC10x/DOI+Digital+Object+Identifier) : 

1. The new storage as describe on the Expected / Improved behavior section of the related Issue :  https://github.com/DSpace/DSpace/issues/9901
2. Mention the script which must be used ONLY to change DOI storage of already archived items (before 10).
3. The CrossRef DOI registration update.

The last component of this PR, the import from external sources should be added to the Live import from external sources Page (https://wiki.lyrasis.org/display/DSDOC10x/Live+Import+from+external+sources).

I am ready to help on this if needed!

**Comment by pnbecker** [comment]
@pilasou thank you. I agree about adding it to that page with one exception. I think we should mention the script only as part of the upgrade procedure (https://wiki.lyrasis.org/display/DSDOC10x/Upgrading+DSpace#UpgradingDSpace-UpgradingtheBackendSteps). We can link it from the DOI page in addition to explaining it there. I want people to be clear that this is thought as a one time upgrade script.

We will work on that as soon as we can. Any help in the meantime is highly appreciated.

**Comment by tdonohue** [comment]
@quasipoint , @pnbecker , @pilasou : Friendly reminder that these improvements to DOIs still require documentation (unless I'm overlooking it?)

There's good discussion around what pages require updating above.  Namely these ones:
* https://wiki.lyrasis.org/display/DSDOC10x/DOI+Digital+Object+Identifier
* https://wiki.lyrasis.org/display/DSDOC10x/Live+Import+from+external+sources
* https://wiki.lyrasis.org/display/DSDOC10x/Upgrading+DSpace#UpgradingDSpace-UpgradingtheBackendSteps

**Comment by quasipoint** [comment]
Documentation for this one is done. I did not edit https://wiki.lyrasis.org/display/DSDOC10x/Live+Import+from+external+sources as I could not see anything relevant that needed changing

**Comment by tdonohue** [comment]
Thanks @quasipoint !  The docs look good to me.  Removing the `needs documentation` label.
