### PR TITLE
Restoring sherpa and orcid support as authorities

### LINKED ISSUE #2891: Support for ORCID and other external providers in the authority framework is needed
**Describe the bug**
It was noted in https://github.com/DSpace/DSpace/pull/2792 that support for the ORCIDAuthority but also for Library of Congress and Sherpa related authorities were dropped here https://github.com/DSpace/DSpace/commit/9bb2e7e526348bb87661d59959271ccda2879c9c#diff-c4bcce032ec14858759cf4cef1a2d627

Not all the institutions would like to immediately use the Configurable Entities and in any case there are always the chance that some of this authorities are intended to be used only to improve the quality of the metadata without dealing with local record for them.

### PR DESCRIPTION
**Pull request by abollini**
## References
* Fixes #2891
During manual testing I have found also some bugs in the SherpaService that have been fixed in this PR and also affect the import of publisher or journal as external entities
1. the sherpa parser used only the first result to populate all the results. This mean that if a query return 3 matches only the first item was reported three times (you can try to search for nature as journal or public as publisher)
2. the SHERPAv2PublisherDataProvider was querying for journal instead than publisher

Please note that both issues are not covered by the current unit or integration test but as this implementation already go over the original budget (2 hours) - we spent 5 hours on that - and it is out of scope for this PR I suggest to open a low priority ticket to improve the test (it should cost around 4 hours)

## Description
The code has been rebased to make easier the review using subsequent commits to reach the goal 
- the first commit re-introduces the classes that were removed accidentally as noted in the issue
- the second comment is about the changes required to adapt the code with the recent changes in the codebase including the switch to orcid v3
- the third commit is about renaming and cleaning a bit the configuration
- fortth and fifth are about the 2 extra issues found in the SherpaService

## Instructions for Reviewers
You need to enable the sherpa and orcid integration to test the features from the UI (otherwise you can review the tests added in the `VocabularyRestRepositoryIT`

In your local.cfg file add
```
solr.authority.server=${solr.server}/authority
plugin.named.org.dspace.content.authority.ChoiceAuthority = \
    org.dspace.content.authority.SolrAuthority = SolrAuthorAuthority,\
        org.dspace.content.authority.SHERPARoMEOPublisher = SRPublisher,\
        org.dspace.content.authority.SHERPARoMEOJournalTitle = SRJournalTitle

choices.plugin.dc.contributor.author = SolrAuthorAuthority
choices.presentation.dc.contributor.author = authorLookup
authority.controlled.dc.contributor.author = true
authority.author.indexer.field.1 = dc.contributor.author

choices.plugin.dc.publisher = SRPublisher
choices.presentation.dc.publisher = lookup
authority.controlled.dc.publisher = true

choices.plugin.dc.relation.ispartof = SRJournalTitle
choices.presentation.dc.relation.ispartof = lookup
authority.controlled.dc.relation.ispartof = true

sherpa.romeo.apikey = YOUR-API-KEY-HERE
```
edit your `config/spring/api/orcid-authority-services.xml` uncommenting the orcid part
If you want to test the sherpa journal authority add a dc.relation.ispartof metadata to your `submission-forms.xml`

Once done make a new submission trying to use the autocomplete feature on the author (the orcid search is quite slow), on the publisher metadata and on a journal metadata

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 

## Checklist
- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [X] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [N/A] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [X] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [N/A] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [N/A] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

File: dspace-api/src/main/java/org/dspace/authority/orcid/Orcidv3.java [hunk 1]
```diff
@@ -0,0 +1,214 @@
...
+import org.orcid.jaxb.model.v3.release.common.OrcidIdentifier;
+import org.orcid.jaxb.model.v3.release.record.Person;
+import org.orcid.jaxb.model.v3.release.search.Result;
+
+/**
+ * @author Jonas Van Goolen (jonas at atmire dot com)
+ * This class contains all methods for retrieving "Person" objects calling the ORCID (version 2) endpoints.
+ * Additionally, this can also create AuthorityValues based on these returned Person objects
+ */
+public class Orcidv3 implements SolrAuthorityInterface {
```
Comment (KevinVdV) [inline dspace-api/src/main/java/org/dspace/authority/orcid/Orcidv3.java:39]: Could we not rename this class to have a better name instead of Orcidv3, something like Orcidv3SolrAuthorityInterface should make it a bit more clear what this class does.

File: dspace-api/src/main/java/org/dspace/content/authority/SolrAuthority.java [hunk 2]
```diff
@@ -135,14 +130,16 @@ public Choices getMatches(String text, int start, int limit, String locale,
...
 
-                if (externalResults && StringUtils.isNotBlank(text)) {
+                if (StringUtils.isNotBlank(text)) {
                     int sizeFromSolr = alreadyPresent.size();
-                    int maxExternalResults = limit <= 10 ? Math.max(limit - sizeFromSolr, 2) : Math
-                        .max(limit - 10 - sizeFromSolr, 2) + limit - 10;
+                    int maxExternalResults = sizeFromSolr < limit ? limit + 1 : sizeFromSolr + 1;
+                    // force an upper limit for external results
+                    if (maxExternalResults > 100) {
+                        maxExternalResults = 100;
```
Comment (KevinVdV) [inline dspace-api/src/main/java/org/dspace/content/authority/SolrAuthority.java:138]: Setting the results to 100 might make requests quite slow. Because ORCID works like this:

* You do a query to retrieve a list of ORCID identifiers
* We send a single query for each ORCID identifier that we have to retrieve the details of that orcid

So in order to retrieve 100 records we need to send 101 requests to ORCID. I would recommend lowering this to 10.

File: dspace-api/src/main/java/org/dspace/authority/orcid/Orcidv3.java [hunk 3]
```diff
@@ -0,0 +1,214 @@
...
+        }
+        return result;
+    }
+
+    /**
+     * Create an AuthorityValue from a Person retrieved using the given orcid identifier.
+     * @param id orcid identifier
+     * @return AuthorityValue
+     */
+    public AuthorityValue queryAuthorityID(String id) {
```
Comment (KevinVdV) [inline dspace-api/src/main/java/org/dspace/authority/orcid/Orcidv3.java:133]: Missing an @override annotiation.

**Review by KevinVdV — CHANGES_REQUESTED** [review]
I made an initial review of the code, there is one bigger issue with the way the that ORCID is implemented. The Orcidv3 class was reinstated, but this duplicates a lot of code from the OrcidV3AuthorDataProvider. If we ever move to version 4 of ORCID we would have to update 2 classes. What I would suggest:

* Refactor the authority class to CONTAIN the OrcidV3AuthorDataProvider
* Any queries coming through queryAuthorityID() / queryAuthorities are redirected to the OrcidV3AuthorDataProvider
* the above will return ExternalDataObject objects, these can be translated into the AuthorityValue objects

I also found an issue when testing using postman, when testing the following call:

> {{url}}/api/submission/vocabularies/SolrAuthorAuthority/entries?filter=Einstein&size=10

I got the following exception:

> Error from server at http://localhost:8983/solr/authority: no field name specified in query and no default specified via ‘df’ param

File: dspace-api/src/main/java/org/dspace/authority/orcid/Orcidv3.java (hunk 3 above)
Comment (abollini) [reply dspace-api/src/main/java/org/dspace/authority/orcid/Orcidv3.java:136]: done https://github.com/DSpace/DSpace/pull/3186/commits/3b61bb1ed5c96144585cd792d266b74274981efd#diff-21202b044326794f262a491f799050d643eb10fe0219487be1b8901a613a0d21R135

File: dspace-api/src/main/java/org/dspace/content/authority/SolrAuthority.java (hunk 2 above)
Comment (abollini) [reply dspace-api/src/main/java/org/dspace/content/authority/SolrAuthority.java]: done

File: dspace-api/src/main/java/org/dspace/authority/orcid/Orcidv3.java (hunk 1 above)
Comment (abollini) [reply dspace-api/src/main/java/org/dspace/authority/orcid/Orcidv3.java:41]: this is aligned with the previous name that was Orcidv2, that said I agree that we can use a better name but please review my general comment about your refactoring suggestion

**Comment by abollini** [comment]
hi @KevinVdV  thanks for your review, I have applied all the not controversial feedback to this PR.
The issue with the SolrAuthority is not related to this PR and most probably is due to a not updated configuration in your solr installation as it seems to be related to this old fix https://github.com/DSpace/DSpace/commit/1d08e15254971b996be803f3b4b1011f24a03140#diff-9bc5d9a4836e3567a3331d3b53db4bc36348a38895cff8b25c6bb175b603ec49R109

About the refactoring I agree with you that could be a nice improvements but it is IMHO out-of-scope of the original plan for this PR. Moreover, I would prefer to introduce an OrcidService layer shared among the Authority and OrcidV3AuthorDataProvider implementations instead than having one to rely on the other. This because the OrcidV3AuthorDataProvider could be also not configured in some instance (if they not use entity) or could have custom mapping that should indeed be remapped in the Authority part (the metadata used to store the name, orcid, etc).
I suggest to put this refactoring in a separate ticket, it should took 4 hours and we can eventually look to it @tdonohue

**Review by tdonohue — CHANGES_REQUESTED** [review]
@abollini : Overall this looks good.  I agree with both your points & @KevinVdV's....this code could eventually use some cleaning up / refactoring to avoid duplication, but it's **good enough** for now, and we can create a followup issue for the refactoring.

I tested this and it works well overall.  However, in testing the SRJournalTitle, I noticed the dspace.log has errors because there are 3 old `jsp.*` labels in `SHERPAResponse` class here: https://github.com/DSpace/DSpace/blob/80c3f98447dfe1ca6977faebb774ac406532a29e/dspace-api/src/main/java/org/dspace/app/sherpa/v2/SHERPAResponse.java#L420-L425

While your PR didn't cause that error, would you mind renaming those labels to no longer have `jsp` and adding them back to Messages.properties?  If you'd rather we do this in a separate PR that's ok.

I added a few other comments inline, but mostly this looks good to me.

File: dspace/config/spring/api/orcid-authority-services.xml [hunk 4]
```diff
@@ -15,9 +15,20 @@
...
     <bean id="dspace.DSpaceAuthorityIndexer" class="org.dspace.authority.indexer.DSpaceAuthorityIndexer"/>
 
+<!--
+    <alias name="OrcidSource" alias="AuthoritySource"/>
+    <bean name="OrcidSource" class="org.dspace.authority.orcid.Orcidv3">
+        <property name="clientId" value="${orcid.clientid}" />
+        <property name="clientSecret" value="${orcid.clientsecret}" />
+        <property name="OAUTHUrl" value="${orcid.oauth.url}" />
+        <property name="orcidRestConnector" ref="orcidRestConnector"/>
+    </bean>
```
[the remark this answers is not in the document]
Comment (abollini) [reply dspace/config/spring/api/orcid-authority-services.xml:25]: I don't like this ORCID lookup implementation that is based on the SolrAuthority and indeed we don't use it in dspace-cris for instance. That said, this is what we had in DSpace and the reason why the orcid integration needs to uncomment the spring is to allow the use of the SolrAuthority without it.
I'm going to apply the other minor cleanup requested in the feedback but I would suggest to postpone any major refactoring that would also have an impact on existing documentation and experience to followup PRs

File: dspace-api/src/main/java/org/dspace/authority/orcid/Orcidv3.java (hunk 1 above)
Comment (abollini) [reply dspace-api/src/main/java/org/dspace/authority/orcid/Orcidv3.java]: done, named Orcidv3SolrAuthority**Impl** as it is an implementation

File: dspace-api/src/main/java/org/dspace/content/authority/SHERPARoMEOJournalTitle.java [hunk 5]
```diff
@@ -0,0 +1,91 @@
...
+import org.dspace.app.sherpa.SHERPAService;
+import org.dspace.app.sherpa.v2.SHERPAResponse;
+import org.dspace.utils.DSpace;
+
+/**
+ * Sample Journal-name authority based on SHERPA/RoMEO v2
+ *
+ * WARNING: This is a very crude and incomplete implementation, done mainly
+ * as a proof-of-concept.  Any site that actually wants to use it will
+ * probably have to refine it (and give patches back to dspace.org).
```
[the remark this answers is not in the document]
Comment (abollini) [reply dspace-api/src/main/java/org/dspace/content/authority/SHERPARoMEOJournalTitle.java]: removed, the implementation now is sufficiently robust and good

File: dspace-api/src/main/java/org/dspace/content/authority/SHERPARoMEOPublisher.java [hunk 6]
```diff
@@ -0,0 +1,92 @@
...
+import org.dspace.app.sherpa.v2.SHERPAPublisherResponse;
+import org.dspace.utils.DSpace;
+
+/**
+ * Sample Publisher name authority based on SHERPA/RoMEO v2
+ *
+ *
+ * WARNING: This is a very crude and incomplete implementation, done mainly
+ * as a proof-of-concept.  Any site that actually wants to use it will
+ * probably have to refine it (and give patches back to dspace.org).
```
[the remark this answers is not in the document]
Comment (abollini) [reply dspace-api/src/main/java/org/dspace/content/authority/SHERPARoMEOPublisher.java]: removed, the implementation now is sufficiently robust and good

**Comment by abollini** [comment]
@tdonohue I have applied the feedback, the i18n messages have been removed completely as they are not used and the articleVersion is already available in the response. It will be a responsability of the REST part or better of the Angular Client to provide a translation for these labels.

File: dspace/config/spring/api/orcid-authority-services.xml (hunk 4 above)
[the remark this answers is not in the document]
Comment (tdonohue) [reply dspace/config/spring/api/orcid-authority-services.xml:25]: @abollini : Thanks for the explanation. It makes sense to me to delay any other major refactoring, so we can leave this as-is for now.

**Review by tdonohue — APPROVED** [review]
👍 @abollini : I gave this another test today, and it seems to be working. I was able to easily test Sherpa via Publisher (I didn't have a Journal field at the time, but I had tested that previously successfully). I also was able to successfully test the ORCID authority on the Author field 

(As a sidenote, for other testers, remember that after enabling the author authority, you may need to run `./dspace index-authority` to index the authors into your Solr.)

So, this looks good to me. Thanks again!

**Review by KevinVdV — APPROVED** [review]
I re-reviewed this PR & am able to verify that:
* The lookup for sherpa journals works & when selecting one the authority is properly stored
* The lookup for sherpa publishers works & when selecting on the authority is properly stored
* The lookup for ORCID records both from ORCID & from the solr authority cache
