### PR TITLE
Bug Fix: Remove RequestItems referencing deleted Bitstreams (main)

### LINKED ISSUE #9674: Cleanup fails with exception if any deleted bitstream is linked to any request
## Describe the bug
If any bitstream in the _ORIGINAL_ bundle is deleted using the REST API (v7.6.1), the cleanup command fails with exception if there is any pending request to that bitstream.

## To Reproduce
1. Add an item with a bitstream (preferably PDF files) with embargo/restrictions.
2. Add a new request for that bitstream.
3. Delete the bitstream using the REST API:
    `DELETE /api/core/bitstreams/:bitstreamId`
4. Run `bin/dspace cleanup`, which should show errors like this:
```
Caused by: org.postgresql.util.PSQLException: ERROR: update or delete on table "bitstream" violates foreign key constraint "requestitem_bitstream_id_fkey" on table "requestitem"
  Detail: Key (uuid)=(fe62eeb6-afb5-4648-86ef-6229aed22796) is still referenced from table "requestitem".
```

## Expected behavior
There should be a force mode in cleanup to handle cases like this:
`bin/dspace cleanup -f`
or more specifically
`bin/dspace cleanup --unlink-requests`

This should set the _bitstream_id_ to _null_ in the corresponding request records (which should mean _"this request referenced a single bitstream which is now deleted"_).

## Related work
Currently, I run this SQL before running `cleanup` to mark the deleted _bitstream_id_ in the _requestitem_ as null:
```
UPDATE requestitem SET bitstream_id = null
WHERE bitstream_id IN (SELECT uuid FROM bitstream WHERE deleted = true);
```

### PR DESCRIPTION
**Pull request by ZahraaChreim-Atmire**
## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #9674 
* DSpace 7.x version: https://github.com/DSpace/DSpace/pull/11468
* DSpace 8.x version: https://github.com/DSpace/DSpace/pull/11470
* DSpace 9.x version: https://github.com/DSpace/DSpace/pull/11471
* Related to https://github.com/DSpace/DSpace/pull/9106

## Description
Ensures that when a `Bitstream` is deleted, any associated `RequestItem` entities referencing it are also removed, preventing orphaned request records and issues with `cleanup` script.

## Instructions for Reviewers
List of changes in this PR:
* First, added logic in `BitstreamServiceImpl.delete()` to remove any `RequestItem` entities referencing the deleted `bitstream`.
* Second, introduced a SQL migration script to clean up existing database records with deleted bitstreams.
* Third, added new test method to `RequestItemRepositoryIT` to verify that deleting a bitstream automatically removes its associated request items.

How to Test / Review:
- Create a new `item` and attach a **restricted** `bitstream`.
- Submit a **request a copy** for that `bitstream` and verify that a corresponding entry is created in the `requestitem` table.
- Delete the `bitstream`.
- Confirm that the related `RequestItem` entry is automatically removed from the `requestitem` table.
- Run the `dspace cleanup` script and verify that it executes successfully and that no database integrity errors occur, such as: `ERROR: update or delete on table "bitstream" violates foreign key constraint "requestitem_bitstream_id_fkey" on table "requestitem"`.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome).
However, reviewers may request that you complete any actions in this list if you have not done so. If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR **passes Checkstyle** validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR **includes Javadoc** for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR **passes all tests and includes new/updated Unit or Integration Tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [ ] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [ ] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by nwoodward — APPROVED** [review]
👍 Thanks @ZahraaChreim-Atmire! This PR fixes a bug that **many** repositories have dealt with over the years. I tested it locally, and it works well.

**Review by tdonohue — CHANGES_REQUESTED** [review]
@ZahraaChreim-Atmire : I tested this today, and ran into what seems to be a bug.  I'm not able to get the new code in `BitstreamServiceImpl` to work correctly.

Here's what I did:
1. Login as an Admin, and submit a new Item with a single Bitstream.  Embargo that Bitstream until a future date
2. Logout, and make a request for that embargoed Bitstream as an anonymous user.
3. Verify that the request is in the `requestitem` database table.
4. Now, login as an Admin and attempt to *delete the entire Item*.  The deletion fails, and I see this error in the logs:
```
2025-11-10 17:29:08,325 INFO  295655b9-510a-4da9-a384-f485495973fb a99a2985-4a24-4d17-9d30-49be53a52b6c org.dspace.app.rest.utils.DSpaceAPIRequestLoggingFilter @ Before request [DELETE /server/api/core/items/4b4b98e5-1a16-4d33-ae06-d4652e215925] originated from /items/4b4b98e5-1a16-4d33-ae06-d4652e215925/edit/delete
2025-11-10 17:29:08,345 INFO  295655b9-510a-4da9-a384-f485495973fb a99a2985-4a24-4d17-9d30-49be53a52b6c org.dspace.content.ItemServiceImpl @ dspacedemo+admin@gmail.com::delete_item:item_id=4b4b98e5-1a16-4d33-ae06-d4652e215925
2025-11-10 17:29:08,362 INFO  295655b9-510a-4da9-a384-f485495973fb a99a2985-4a24-4d17-9d30-49be53a52b6c org.dspace.content.Bundle @ dspacedemo+admin@gmail.com::delete_bundle:bundle_id=835aa04a-bd4d-4936-a337-0f233e519825
2025-11-10 17:29:08,374 INFO  295655b9-510a-4da9-a384-f485495973fb a99a2985-4a24-4d17-9d30-49be53a52b6c org.dspace.content.Bundle @ dspacedemo+admin@gmail.com::remove_bitstream:bundle_id=835aa04a-bd4d-4936-a337-0f233e519825,bitstream_id=3cf27147-2ded-4ba3-80b5-5450f5d41b2b
2025-11-10 17:29:08,397 INFO  295655b9-510a-4da9-a384-f485495973fb a99a2985-4a24-4d17-9d30-49be53a52b6c org.dspace.content.ItemServiceImpl @ dspacedemo+admin@gmail.com::update_item:item_id=4b4b98e5-1a16-4d33-ae06-d4652e215925
2025-11-10 17:29:08,416 INFO  295655b9-510a-4da9-a384-f485495973fb a99a2985-4a24-4d17-9d30-49be53a52b6c org.dspace.content.ItemServiceImpl @ dspacedemo+admin@gmail.com::update_item:item_id=4b4b98e5-1a16-4d33-ae06-d4652e215925
2025-11-10 17:29:08,423 INFO  295655b9-510a-4da9-a384-f485495973fb a99a2985-4a24-4d17-9d30-49be53a52b6c org.dspace.content.BitstreamServiceImpl @ dspacedemo+admin@gmail.com::delete_bitstream:bitstream_id=3cf27147-2ded-4ba3-80b5-5450f5d41b2b
2025-11-10 17:29:08,434 INFO  295655b9-510a-4da9-a384-f485495973fb a99a2985-4a24-4d17-9d30-49be53a52b6c org.dspace.content.BitstreamServiceImpl @ dspacedemo+admin@gmail.com::update_bitstream:bitstream_id=3cf27147-2ded-4ba3-80b5-5450f5d41b2b
2025-11-10 17:29:08,455 ERROR 295655b9-510a-4da9-a384-f485495973fb a99a2985-4a24-4d17-9d30-49be53a52b6c org.dspace.app.rest.exception.DSpaceApiExceptionControllerAdvice @ An exception has occurred (status:500)
java.lang.NullPointerException: Cannot invoke "org.dspace.content.Bitstream.equals(Object)" because the return value of "org.dspace.app.requestitem.RequestItem.getBitstream()" is null
  at org.dspace.content.BitstreamServiceImpl.delete(BitstreamServiceImpl.java:305)
  at org.dspace.content.BitstreamServiceImpl.delete(BitstreamServiceImpl.java:49)
  at org.dspace.content.BundleServiceImpl.removeBitstream(BundleServiceImpl.java:252)
  at org.dspace.content.BundleServiceImpl.delete(BundleServiceImpl.java:548)
  at org.dspace.content.BundleServiceImpl.delete(BundleServiceImpl.java:50)
  at org.dspace.content.ItemServiceImpl.deleteBundle(ItemServiceImpl.java:924)
  at org.dspace.content.ItemServiceImpl.removeAllBundles(ItemServiceImpl.java:915)
  at org.dspace.content.ItemServiceImpl.rawDelete(ItemServiceImpl.java:853)
  at org.dspace.content.ItemServiceImpl.delete(ItemServiceImpl.java:829)
  at org.dspace.content.ItemServiceImpl.delete(ItemServiceImpl.java:102)
  at org.dspace.app.rest.repository.ItemRestRepository.delete(ItemRestRepository.java:181)
```

I believe the newly added code is flawed because it assumes that `requestItem.getBitstream()` will always return a non-null value.  Beyond that, the rest of the code looks good.

**Comment by nwoodward** [comment]
@tdonohue Ah. I only deleted the bitstream on the item. I'll try again with the entire item, but I imagine I'll get the same error.

**Comment by nwoodward** [comment]
Strange. I've tried a few times today, and I'm not able to replicate that error message when I delete the entire item. I think a null check on `requestItem.getBitstream()` in `BitstreamServiceImpl` is necessary, but I don't see why _not_ having that would cause an error when deleting an item. I'm not sure it matters, but I'm testing everything locally.

File: dspace-api/src/main/java/org/dspace/content/BitstreamServiceImpl.java [hunk 1]
```diff
@@ -293,6 +297,15 @@ public void delete(Context context, Bitstream bitstream) throws SQLException, Au
         //Remove all bundles from the bitstream object, clearing the connection in 2 ways
         bundles.clear();
 
+        // Remove any RequestItem entities associated with this bitstream ensuring there are no requests referencing
+        // a deleted bitstream
+        List<RequestItem> requestItems = requestItemService.findAll(context);
+        for (RequestItem requestItem : requestItems) {
+            if (requestItem.getBitstream().equals(bitstream)) {
```
Comment (tdonohue) [inline dspace-api/src/main/java/org/dspace/content/BitstreamServiceImpl.java]: @ZahraaChreim-Atmire and @nwoodward : I tested this again and I'm still getting the same error as before.  I think the flaw is on this line of code.  I *think* this `if` should be:
```
if (bitstream.equals(requestItem.getBitstream())
```

The reason why is that `requestItem.getBistream()` **can be null**.  If it ever is null, then you end up with a NullPointerException.  So, you either need to swap this `if` around (because `bitstream` should never be `null` here) or add a separate check for null.

**Comment by ZahraaChreim-Atmire** [comment]
@tdonohue Thank you for the detailed feedback, I was finally able to reproduce the issue, and you are absolutely correct about it. It occurs when a `RequestItem` is created at **item-level** rather than **bitstream-level**, which results in `bitstream_id = null` in the `requestitem` table.

Here are the corrected steps to reproduce the problem:
1. Login as an Admin and submit a new Item that contains at least one embargoed bitstream.
2. Logout, attempt to download the embargoed bitstream from the item view page as an anonymous user. You will be redirected to the “Request a Copy” form: submit a request for **all restricted files of this item**.
3. In the database, verify that the `requestitem` table now contains an entry with:
    - `bitstream_id = NULL`
    - `item_id = <UUID of the item>`
    - This is the item-level request scenario that triggers the problem.
4. Login as an Admin again and attempt to delete the entire Item. The deletion fails, and the logs show a `NullPointerException` at `BitstreamServiceImpl.delete()` because `requestItem.getBitstream()` is null.

Regarding the fix: your suggestion to reverse the comparison was exactly right. Changing the condition to `if (bitstream.equals(requestItem.getBitstream()))` prevents the `NullPointerException` and correctly handles both item-level and bitstream-level requests. I verified the fix across all scenarios: deleting entire items, deleting individual bitstreams, and running the cleanup script.. everything now works without issues!

**Review by tdonohue — APPROVED** [review]
👍 Thanks @ZahraaChreim-Atmire !  Your recent change works for me as well.  I'm now able to successfully delete the Item that was previously failing with a NullPointerException.

**Comment by misilot** [comment]
@tdonohue I can't tell, was this back ported to 7x? Whoops, I can't read. Looks like it is in 7.6.6! Excited to test this out!

**Comment by tdonohue** [comment]
@misilot : yes, see the description of the PR.  It has a link to the 7.x version: https://github.com/DSpace/DSpace/pull/11468 which looks to have been released in 7.6.6
