### PR TITLE
fix bug: reset password from Admin Panel when Captcha enabled

### LINKED ISSUE #8765: Reset Password does not work from the Admin Panel when Captcha verification enabled
**Describe the bug**
When I am logged in as admin and try to reset a password for another eperson, it will throw an error: 
Error when trying to reset password
An error occured when attempting to reset the password for the account associated with the following email address: 213523@ids.upchiapas.edu.mx. The same behavior encountered also in the DSpace 7.5 DEMO website.

**To Reproduce**
1. MUST have [Google Recaptcha](https://wiki.lyrasis.org/display/DSDOC7x/CAPTCHA+Verification) enabled to reproduce this bug.
2. Log in as Admin
3. Go to Access Control -> People -> Edit a Person -> Reset Password

Related:
The Bug was first described in #https://github.com/DSpace/DSpace/issues/8670
However, the angular fix (#2107) did not resolve the problem. In the Network Tab, I see how the request is sent properly (with the correct parameter =forgot), but the Backend responds with 403 Forbidden.
Maybe is something in the backend that should be changed as well?

### PR DESCRIPTION
**Pull request by Ma-Tador**
## References
* Fixes #8765

## Description
Changed the method responsible to handle register and reset password.

## Instructions for Reviewers
Disable reCaptcha check if the request is to reset password (because the user was already checked at registration).

List of changes in this PR:
Refactoring the createAndReturn method.

**Include guidance for how to test or review your PR.** 
    Log in as Admin
    Go to Access Control -> People -> Edit a Person -> Reset Password

### CODE REVIEW

**Comment by tdonohue** [comment]
@Ma-Tador : I just realized this PR is failing our Checkstyle checks (it appears your IDE may have reformatted some of the code slightly and it fails checks). To see these failures locally you can run our checker from the commandline: https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide#CodeStyleGuide-Checkingcodestylefromcommandline

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/RegistrationRestRepository.java [hunk 1]
```diff
@@ -87,17 +87,22 @@ public RegistrationRest findOne(Context context, Integer integer) {
     public Page<RegistrationRest> findAll(Context context, Pageable pageable) {
         throw new RepositoryMethodNotImplementedException("No implementation found; Method not allowed!", "");
     }
-
+
```
Comment (tdonohue) [inline dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/RegistrationRestRepository.java:90]: Remove trailing spaces.

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/RegistrationRestRepository.java [hunk 2]
```diff
@@ -130,14 +129,14 @@ public RegistrationRest createAndReturn(Context context) {
...
+                                                            + eperson.getEmail());
                 }
                 accountService.sendForgotPasswordInfo(context, registrationRest.getEmail());
             } catch (SQLException | IOException | MessagingException | AuthorizeException e) {
                 log.error("Something went wrong with sending forgot password info email: "
-                    + registrationRest.getEmail(), e);
+                              + registrationRest.getEmail(), e);
             }
-        } else if (accountType.equalsIgnoreCase(TYPE_REGISTER)) {
+           } else if (accountType.equalsIgnoreCase(TYPE_REGISTER)) {
```
Comment (tdonohue) [inline dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/RegistrationRestRepository.java:139]: Please remove the indentation here before the `else if`. This can go back to how it was

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/RegistrationRestRepository.java [hunk 3]
```diff
@@ -152,12 +151,13 @@ public RegistrationRest createAndReturn(Context context) {
...
             } catch (SQLException | IOException | MessagingException | AuthorizeException e) {
                 log.error("Something went wrong with sending registration info email: "
-                    + registrationRest.getEmail(), e);
+                              + registrationRest.getEmail(), e);
             }
         }
         return null;
     }
 
+
```
Comment (tdonohue) [inline dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/RegistrationRestRepository.java:160]: This extra line can be removed

**Review by tdonohue — CHANGES_REQUESTED** [review]
@Ma-Tador :  Overall this looks good & I verified that your fixes **work**.  I also verified this bug does exist on `main` (but only when Captcha is enabled).

However, it looks like your editor / IDE has accidentally reformatted some of the code so that it no longer aligns with our [Code Style requirements](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).  This means that running a checkstyle is failing on this new code: `mvn -U checkstyle:check`   I've highlighted below where the main problems are.

If you can cleanup the code so that it passes Checkstyle, then I think this will be ready (presuming that all automated tests pass/succeed).  If you have any issues with getting this updated, please let me know...as I'd like to include this fix in 7.6 (which is due in June).

**Comment by Ma-Tador** [comment]
Hi Tim, I am using NetBeans as IDE and I can not load the checkstyle into it to proper align with the DSpace checkstyle. Should I change to IntelliJ in order to have my code properly formatted as per DSpace checkstyle? Will the Intellij Community Edition work properly with the complexity of DSpace? (Spring Boot, JPA etc)
However, I removed the white space as you pointed, so I hopefully will pass the DSpace checkstyle.

**Comment by tdonohue** [comment]
@Ma-Tador : You can use our Checkstyle checks in the NetBeans IDE.  See the instructions on the Code Style Guide page I linked to above: https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide#CodeStyleGuide-NetBeans

You can also run the checkstyle checks from commandline via Maven, if you don't want to run them in your IDE. https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide#CodeStyleGuide-Checkingcodestylefromcommandline

I can verify too that IntelliJ Community Edition (which is free) works perfectly well with DSpace 7.  However, you can continue to use Netbeans if you wish (At this time I think most core developers are using IntelliJ but there are a few who I know use Netbeans.)

In any case, it appears the Checkstyle issues are fixed (those tests passed).  However, now there is a test failure in  `RegistrationRestRepositoryIT`: 
```
Error:  Failures: 
Error:  org.dspace.app.rest.RegistrationRestRepositoryIT.registrationFlowWithNoHeaderCaptchaTokenTest(org.dspace.app.rest.RegistrationRestRepositoryIT)
Error:    Run 1: RegistrationRestRepositoryIT.registrationFlowWithNoHeaderCaptchaTokenTest:303 Status expected:<403> but was:<400>
Error:    Run 2: RegistrationRestRepositoryIT.registrationFlowWithNoHeaderCaptchaTokenTest:303 Status expected:<403> but was:<400>
Error:    Run 3: RegistrationRestRepositoryIT.registrationFlowWithNoHeaderCaptchaTokenTest:303 Status expected:<403> but was:<400>
```
Again, this can be reproduced locally (on your machine) by running the Integration tests locally via the instructions at: https://github.com/DSpace/DSpace/#running-tests

The good news is that I think the problem may be that the test itself is wrong.  It appears to be missing the required `accountTestType` param.  So, I think you can correct it by adding this:
```
.param(TYPE_QUERY_PARAM, TYPE_REGISTER)
```
To around line 301 (see how other nearby tests all include this same code): https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/test/java/org/dspace/app/rest/RegistrationRestRepositoryIT.java#L301

Once the Integration tests are passing, this can be merged.  Hopefully this simple change will fix things... but if not, then we may need to look closer at why the changed code isn't returning what that test expects.

**Comment by mwoodiupui** [comment]
On Tue, May 02, 2023 at 07:25:28AM -0700, Tim Donohue wrote:
> @Ma-Tador : You can use our Checkstyle checks in the NetBeans IDE.  See the instructions on the Code Style Guide page I linked to above: https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide#CodeStyleGuide-NetBeans
> 
> You can also run the checkstyle checks from commandline via Maven, if you don't want to run them in your IDE. https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide#CodeStyleGuide-Checkingcodestylefromcommandline
> 
> I can verify too that IntelliJ Community Edition (which is free) works perfectly well with DSpace 7.  However, you can continue to use Netbeans if you wish (At this time I think most core developers are using IntelliJ but there are a few who I know use Netbeans.)

Didn't we have a file in some common format that encodes our style
rules and can be imported into most IDEs?  I recall loading one into
NetBeans years ago.  This is separate from Checkstyle; it configures
the IDE to follow our rules in its own auto-formatting, so you don't
make Checkstyle unhappy in the first place.

-- 
Mark H. Wood
Lead Technology Analyst

University Library
Indiana University - Purdue University Indianapolis
755 W. Michigan Street
Indianapolis, IN 46202
317-274-0749
www.ulib.iupui.edu

**Comment by tdonohue** [comment]
@mwoodiupui : Yes, our `checkstyle.xml` config file is what can be imported into every IDE, provided that you have the IDE-specific "checkstyle plugin".  I believe every Java IDE supports checkstyle, but some may require you to install a plugin. Again, though, the instructions for most IDEs are in our Code Style Guide:  https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide#CodeStyleGuide-IDESupport

**Comment by Ma-Tador** [comment]
Thank you @tdonohue and @mwoodiupui. I will migrate to IntelliJ since so many developers here use it and I will set the checkstyle as instructed. Thank you for sharing.
I changed the <code>RegistrationRestRepositoryIT</code> as instructed.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @Ma-Tador !  This looks correct now.  Already tested the code and found it to be working.
