### PR TITLE
test(#9611): Fix AccessConditionOptionMatcher validation logic

### LINKED ISSUE #9611: Access condition option matchers don't take arguments into account properly
**Describe the bug**
Accidentally noticed that the `maxStartDate` and `maxEndDate` assertions don't take into account the actual value [here](https://github.com/DSpace/DSpace/blob/b02a7f9dbc0a99661331dc30e166157fcf1f37dd/dspace-server-webapp/src/test/java/org/dspace/app/rest/matcher/AccessConditionOptionMatcher.java#L38-L41).

**To reproduce**
Change the `maxStartDate` and `maxEndDate` of the `embargo` and `lease` ACOs to e.g. `+7YEARS`
→ `BulkAccessConditionRestRepositoryIT` will still pass, even though the date limits do not match anymore.

**Expected behavior**
The ITs should cover properties from the Spring layer through to the REST layer where reasonable.
We should also look around to see if there are similar issues elsewhere and fix those too.
Note that this will be yet another test that would start failing when the default configuration is changed -- to work around this we can either
- Override `access-conditions.xml` in `dspace-server-webapp/src/test/data/dspaceFolder`
- Refactor the test to be more configuration-agnostic

### PR DESCRIPTION
**Pull request by JohnnyMendesC**
## References
* Fixes #9611 

## Description
Updates AccessConditionOptionMatcher to correctly validate date limits using DateMathParser instead of ignoring the arguments. Refactors BulkAccessConditionRestRepositoryIT to use dynamic configuration values instead of hardcoded strings.

### List of changes in this PR:

* Refactored `AccessConditionOptionMatcher` to use `DateMathParser` and `LocalDate`. It now parses the math expression (e.g., +36MONTHS) and validates strictly against the JSON response date.
* Updated `BulkAccessConditionRestRepositoryIT` to inject `BulkAccessConditionConfigurationService`.
* The test now fetches the actual configured limits (`embargoLimit`, `leaseLimit`) dynamically instead of using hardcoded strings like "+36MONTHS".

### Guidance for testing:
1. Run the integration test: `mvn -pl dspace-server-webapp -Dtest=org.dspace.app.rest.BulkAccessConditionRestRepositoryIT -DskipUnitTests=false -DtrimStackTrace=false -e test`
2. To verify robustness, you can temporarily change the embargo limit in access-conditions.xml (e.g., to +1YEAR) and verify that the test still passes without modification.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome).
However, reviewers may request that you complete any actions in this list if you have not done so. If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [ ] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [ ] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [ ] My PR **passes Checkstyle** validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [ ] My PR **includes Javadoc** for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [ ] My PR **passes all tests and includes new/updated Unit or Integration Tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [ ] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [ ] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [ ] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

File: dspace-server-webapp/src/test/java/org/dspace/app/rest/matcher/AccessConditionOptionMatcher.java [hunk 1]
```diff
@@ -35,11 +41,54 @@ public static Matcher<? super Object> matchAccessConditionOption(String name,
...
-                StringUtils.isNotBlank(maxEndDate) ? hasJsonPath("$.maxEndDate", notNullValue())
+                StringUtils.isNotBlank(maxEndDate) ? hasJsonPath("$.maxEndDate", new DateMathMatcher(maxEndDate))
                                                      : hasNoJsonPath("$.maxEndDate")
                 );
     }
 
+    /**
+     * Internal matcher to compare an ISO date from JSON with a DateMath expression.
+     */
+    private static class DateMathMatcher extends BaseMatcher<String> {
```
Comment (ybnd) [inline dspace-server-webapp/src/test/java/org/dspace/app/rest/matcher/AccessConditionOptionMatcher.java:55]: Is there any case where this matcher is used to compate `Date`s to date expressions like `+6MONTHS`?
I didn't find one; we can probably get away with just a simple `is()` comparison on the date expressions.

**Review by ybnd — CHANGES_REQUESTED** [review]
Just now noticed that I'd written the comment below but didn't publish the review 🤦 

Overall I'm +1, just not sure why the matcher needs to be so complex.

File: dspace-server-webapp/src/test/java/org/dspace/app/rest/matcher/AccessConditionOptionMatcher.java (hunk 1 above)
Comment (JohnnyMendesC) [reply dspace-server-webapp/src/test/java/org/dspace/app/rest/matcher/AccessConditionOptionMatcher.java:55]: Hi @ybnd! Thanks for the review.

When I wrote this, I've mistakenly assumed the REST layer would evaluate and return these values as computed ISO dates, which is why I over-engineered the `DateMathMatcher` to parse and compare them.
Since the endpoint simply exposes the string expressions (like `+6MONTHS`), you are absolutely right, the custom matcher is completely unnecessary and a simple `is()` comparison is much better.

I'll simplify the Matcher to use `is()` and push the updates. 

Thanks for catching this!

**Comment by JohnnyMendesC** [comment]
Hi @ybnd!

The CI integration tests just failed, and looking at the logs, it shows that the `REST` layer does evaluate the expressions and returns computed ISO dates in the JSON response, rather than the literal strings.

Here is a snippet from the CI failure:
```
Expected: ... json path "$['maxStartDate']" evaluated to is "+36MONTHS"
but: not matched: <{name=embargo, hasStartDate=true, hasEndDate=false, maxStartDate=2029-03-04}>
```

Because of this behavior, we really do need that custom `DateMathMatcher` to parse the `+36MONTHS` string and compare it against the computed 2029-03-04 date. I will revert the simplification commit so the tests can pass again. Let me know if you'd prefer to handle this differently!

**Comment by ybnd** [comment]
@JohnnyMendesC oh sorry for the misdirection 🤦

In that case +1 from me, if that last `main` merge wasn't too tricky it may be good to rebase https://github.com/DSpace/DSpace/pull/11719/changes/3a6350c5c80591e041d5acf01c4c5f34f297410a and https://github.com/DSpace/DSpace/pull/11719/changes/82851757ea89e966c65a11d39cad83ba651affba away since they cancel each other out

**Review by ybnd — APPROVED** [review]

**Comment by JohnnyMendesC** [comment]
@ybnd, no worries at all! I completely agree about the commit history. I've just performed an interactive rebase to drop those two extra commits, keeping the history clean and straightforward.
Thanks again for your time, the review, and the approval!

**Review by tdonohue — APPROVED** [review]
👍 Thanks @JohnnyMendesC !  This looks good to me & only changes our automated tests.
