### PR TITLE
Importing new csv with relationships

### LINKED ISSUE #3008: Importing new CSV with relationships
**Describe the bug**
When trying to import new items with relationships to existing items, the relationships can no longer be created

**To Reproduce**
1. Create a few archived Publication items
2. Create a CSV file with new Person items (using the `+`) and relation.isPublicationOfAuthor containing UUIDs of the Publication items
3. The validation now fails

**Expected behavior**
The validation should still succeed (it blocks a correct setup)

**Related work**
https://github.com/DSpace/DSpace/pull/2522

### PR DESCRIPTION
**Pull request by Raf-atmire**
## References
* Fixes https://github.com/DSpace/DSpace/issues/3008

## Description
This PR ensures that Relationships can be created through the importing of CSVs to create Items and alter existing Items.

## Instructions for Reviewers

List of changes in this PR:
* Creation of Relationships is possible through the import CSV
* Added tests for this

How to test this PR:
* Create a CSV for a new Item, add a Relationship.type metadatafield and a relationship.<RelationshipType> metadatafield in the headers. Fill them in with proper values
* Verify that an Item is created with a Relationship to the specified item in the CSV
* Repeat but for an existing Item, verify that a new Relationship is made

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Comment by paulo-graca** [comment]
Using: `/dspace/bin/dspace -h` the old `metadata-import` isn't displayed
https://wiki.lyrasis.org/display/DSDOC7x/Batch+Metadata+Editing

**Comment by paulo-graca** [comment]
There is still the issue when trying to import data that belongs to a schema "person" (like `person.giveName`):

```
# /dspace/bin/dspace metadata-import -e paulo.graca@fccn.pt -f /tmp/0519b1e8-3774-4822-b1c8-694dc5296c31-pub.csv
The script has started
org.dspace.app.bulkedit.MetadataImportInvalidHeadingException: Bad metadata declaration in column3: givenName
        at org.dspace.app.bulkedit.DSpaceCSV.<init>(DSpaceCSV.java:190)
        at org.dspace.app.bulkedit.MetadataImport.internalRun(MetadataImport.java:195)
        at org.dspace.scripts.DSpaceRunnable.run(DSpaceRunnable.java:104)
        at org.dspace.app.launcher.ScriptLauncher.executeScript(ScriptLauncher.java:144)
        at org.dspace.app.launcher.ScriptLauncher.handleScript(ScriptLauncher.java:126)
        at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:93)
```

**Review by paulo-graca — APPROVED** [review]
Despite the issues I referred, I managed to import the records into the system:
```
# /dspace/bin/dspace metadata-import -e myEperson@mail.com -f /tmp/0519b1e8-3774-4822-b1c8-694dc5296c31-pub.csv
The script has started
-----------------------------------------------------------
New item:
 + New owning collection (123456789/3):
Persons
 + Add    (dc.contributor.author):
Delete3, John3
 + Add    (organization.legalName):
legalName
 + Add    (relationship.type):
Person
-----------------------------------------------------------



Do you want to make these changes? [y/n]
y
-----------------------------------------------------------
New item:
981a864e-eb03-402d-9c3e-9eae71e578ec (123456789/26)
 + New owning collection  (123456789/3):
Persons
 + Added   (dc.contributor.author):
Delete, John
 + Added   (relationship.type):
Person
-----------------------------------------------------------
New item:
c7958bd2-2eea-48f5-8a19-063f5e6b3b5f (123456789/27)
 + New owning collection  (123456789/2):
Main collection
 + Added   (dc.contributor.author):
Kolmakov, Nikolai N.
 + Added   (dc.date.issued):
2008-09-20
 + Added   (dc.description.abstract[por]):
To delete 2 - The goldfish
 + Added   (dc.identifier):
http://dx.doi.org/10.1186/1471-2164-9-429
 + Added   (dc.identifier.citation[por]):
BMC Genomics, 9, 1, 429-429, 2008.
 + Added   (dc.identifier.issn):
1471-2164
 + Added   (dc.identifier.other):
AUT: ACA00258
 + Added   (dc.identifier.uri):
http://dev5.rcaap.pt/handle/10400.1/232
 + Added   (dc.language.iso[por]):
eng
 + Added   (dc.publisher[por]):
BioMed Central
 + Added   (dc.rights[por]):
openAccess
 + Added   (dc.title[por]):
To delete
 + Added   (dc.type[por]):
article
 + Added   (relation.isAuthorOfPublication):
981a864e-eb03-402d-9c3e-9eae71e578ec
 + Added   (relationship.type):
Publication
log4j:WARN No appenders could be found for logger (org.dspace.discovery.SolrSearchCore).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
The script has completed

```

File: dspace-api/src/test/java/org/dspace/app/bulkedit/MetadataImportTest.java [hunk 1]
```diff
@@ -10,63 +10,75 @@
...
 import org.dspace.scripts.configuration.ScriptConfiguration;
 import org.dspace.scripts.factory.ScriptServiceFactory;
 import org.dspace.scripts.service.ScriptService;
-import org.junit.Rule;
+import org.junit.Before;
 import org.junit.Test;
-import org.junit.rules.ExpectedException;
 
-public class MetadataImportTest extends AbstractIntegrationTest {
+public class MetadataImportTest extends AbstractIntegrationTestWithDatabase {
```
Comment (tdonohue) [inline dspace-api/src/test/java/org/dspace/app/bulkedit/MetadataImportTest.java:48]: Small thing...this is an Integration Test, so it should be renamed `MetadataImportIT`.

**Review by tdonohue — CHANGES_REQUESTED** [review]
@Raf-atmire : Very small comment below. It looks like we have a misnamed Test file (it should end in "IT" since it's an integration test).  I realize you didn't create this file, but I think we should use this PR as an opportunity to correct the name of that test (so that it no longer runs with Unit Tests).

Beyond that, the code changes here are rather small and reasonable.

**Comment by Raf-atmire** [comment]
@paulo-graca The issue with the "person" schema is being fixed in a different pr: https://github.com/DSpace/DSpace/pull/3036
@tdonohue Good catch, I've renamed the class as requested

**Review by tdonohue — APPROVED** [review]
👍 Looks good to me now.  Code and tests make sense here. I didn't test it, but I trust the tests of @paulo-graca (and the issue he found is fixed in a separate PR #3036 ).  Thanks @Raf-atmire !
