### PR TITLE
Fix #3330: Retain UUIDs on packager restore

### LINKED ISSUE #3330: Packager does not retain UUIDs on restore
**Describe the bug**
As has historically been the case with handles, the `-r` packager option should also re-used the UUID of the original item.  Item UUIDs are intended to be immutable references to items that exist in DSpace. For example, people's bookmarks and spiders will have those old UUIDs in their URLs.  Therefore, when an item is being restored into DSpace (e.g. due to disaster recovery), it is important to have the ability to retain the original UUID and thus URL references.

**To Reproduce**
1. Do a packager export
2. Run a packager import
3. Notice how the UUID is difference

**Expected behavior**
The UUID should be retained.

**Related work**
Addressed by this PR: https://github.com/DSpace/DSpace/pull/3329

### PR DESCRIPTION
**Pull request by ConfusionOrb221**
## References

* Fixes #3330

## Description

Updates core DSpace services to optionally accept a UUID at item creation time. This is now used by packager at the appropriate time to ensure the original UUID is used for the "new" item.

## Testing

Includes new unit tests to verify packager will retain UUIDs. These steps can be run manually as well (export, then restore the same item with -r)

### CODE REVIEW

**Comment by tdonohue** [comment]
@ConfusionOrb221 or @cwilper  : Please add a description to this PR, as it looks like it replaces another.  Keep in mind our PR template: https://github.com/DSpace/DSpace/blob/main/.github/pull_request_template.md
 
 This also applies to #3328.  Neither can be reviewed publicly without a more detailed description.  Thanks!

**Comment by cwilper** [comment]
Thanks Tim, we're getting these PRs in shape currently; I'm keeping the "work in progress" tag on these until they're ready for review by others.

**Comment by cwilper** [comment]
> ..I'm keeping the "work in progress" tag on these until they're ready for review by others.

@tdonohue This one is smaller and is now ready, so I took the tag off. The other one I'm keeping in WIP state while some initial items are addressed (but the description now gives some background and info about the approach, so folks can start looking).

File: dspace-api/src/main/java/org/dspace/content/Community.java [hunk 1]
```diff
@@ -96,6 +97,10 @@ protected Community() {
 
     }
 
+    protected Community(UUID uuid) {
```
Comment (tdonohue) [inline dspace-api/src/main/java/org/dspace/content/Community.java:100]: Please add JavaDocs here to describe this constructor

File: dspace-api/src/main/java/org/dspace/content/DSpaceObject.java [hunk 2]
```diff
@@ -76,6 +76,12 @@
     @Transient
     private boolean modified = false;
 
+    @Transient
+    protected UUID predefinedUUID;
+    public UUID getPredefinedUUID() {
```
Comment (tdonohue) [inline dspace-api/src/main/java/org/dspace/content/DSpaceObject.java:81]: This should be described in JavaDocs/comments... as it's not entirely clear when looking at DSpaceObject what this property *does*.  We should describe that this is read by our UUID generator to assign a predefined UUID (if specified).

File: dspace-api/src/main/java/org/dspace/content/CheckExistingUUIDGenerator.java [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+
+import org.hibernate.engine.spi.SharedSessionContractImplementor;
+import org.hibernate.id.UUIDGenerator;
+
+/**
+ * Allows DSpaceObjects to provide a pre-determined UUID
+ *
+ * @author April Herron
+ */
+public class CheckExistingUUIDGenerator extends UUIDGenerator {
```
Comment (tdonohue) [inline dspace-api/src/main/java/org/dspace/content/CheckExistingUUIDGenerator.java:21]: I notice here there's no check to see if the UUID *is unique*.  Is the plan here that we are depending on the database layer to throw an error if someone attempts to create, e.g. two Items with the same UUID?   If so, I'd recommend we add tests to verify this will result in an error.  We obviously need UUIDs to be unique.

As a sidenote, we might want to consider renaming this to be `PredefinedUUIDGenerator`, so that it better aligns with `getPredefinedUUID()` method....the current name implies to me that is "checks" whether a UUID exists or not.

File: dspace-api/src/main/java/org/dspace/content/service/ItemService.java [hunk 4]
```diff
@@ -55,6 +55,20 @@
...
+     * responsibility of the caller.
+     *
+     * @param context DSpace context object
+     * @param workspaceItem in progress workspace item
+     * @param uuid the pre-determined UUID to assign to the new item
+     * @return the newly created item
+     * @throws SQLException if database error
+     * @throws AuthorizeException if authorization error
+     */
+    public Item create(Context context, WorkspaceItem workspaceItem, UUID uuid) throws SQLException, AuthorizeException;
```
Comment (tdonohue) [inline dspace-api/src/main/java/org/dspace/content/service/ItemService.java:70]: This method is public despite claiming to not be public in the JavaDocs.  One or the other should be corrected.

Considering this create() method does NOT check authorization properly, it probably shouldn't be public -- otherwise we are potentially creating security issues if this is used inappropriately.

File: dspace-api/src/test/java/org/dspace/app/packager/PackagerIT.java [hunk 5]
```diff
@@ -0,0 +1,123 @@
...
+            assertTrue(tempFile.length() > 0);
+            String idStr = getID();
+            assertEquals(idStr, article.getID().toString());
+        } finally {
+            tempFile.delete();
+        }
+    }
+
+    @Test
+    public void packagerImportUUIDTest() throws Exception {
```
Comment (tdonohue) [inline dspace-api/src/test/java/org/dspace/app/packager/PackagerIT.java:58]: This method appears to only test if Item UUIDs are restored.  We should have similar tests for Community & Collection to verify they work similarly.

As a sidenote...you may have seen it, but we already have a `ITDSpaceAIP` class which does a very thorough export/import of a hierarchy of AIPs.  If you find it easier, you could simply update that IT to also verify that UUIDs are restored for various object types.  It's up to you though, as having a separate IT class is reasonable as well.

**Review by tdonohue — CHANGES_REQUESTED** [review]
@ConfusionOrb221 : Thanks for the PR here. This is a necessary feature and the code overall looks good.  I do however have some inline comments/suggestions for improvements (I think they should be minor overall, but let me know if not).  

I've not yet had a chance to give this a thorough test, but the ITs do look reasonable overall (for Items at least).  I'll find time to test this more thoroughly as well.

File: dspace-api/src/main/java/org/dspace/content/service/ItemService.java (hunk 4 above)
Comment (ConfusionOrb221) [reply dspace-api/src/main/java/org/dspace/content/service/ItemService.java:68]: So for this I had just copied the above javadocs and edited it slightly so I figured if this was the case both methods would need to be changed so in the commit I just pushed I put the check for auth in both of these methods and then changed the javadoc to reflect that aswell as the fact that they are public.

File: dspace-api/src/main/java/org/dspace/content/CheckExistingUUIDGenerator.java (hunk 3 above)
Comment (ConfusionOrb221) [reply dspace-api/src/main/java/org/dspace/content/CheckExistingUUIDGenerator.java]: Currently what will happen is it will just overwrite the other item with that UUID I added a test to reflect this process.

File: dspace-api/src/test/java/org/dspace/app/packager/PackagerIT.java (hunk 5 above)
Comment (ConfusionOrb221) [reply dspace-api/src/test/java/org/dspace/app/packager/PackagerIT.java:67]: Left my changed in its own class because I extend AbstractIntegrationTestWithDatabase which allows me to call the runDspaceScript()

File: dspace-api/src/test/java/org/dspace/app/packager/PackagerIT.java [hunk 6]
```diff
@@ -0,0 +1,186 @@
...
+    }
+
+
+    private void performExportScript(String handle, File outputFile) throws Exception {
+        runDSpaceScript("packager", "-d", "-e", "admin@email.com", "-i", handle, "-t",
+                "AIP", outputFile.getPath());
+    }
+
+    private void performImportScript(File outputFile) throws Exception {
+        runDSpaceScript("packager", "-r", "-f", "-u", "-e", "admin@email.com", "-t",
```
Comment (tdonohue) [inline dspace-api/src/test/java/org/dspace/app/packager/PackagerIT.java:183]: This looks to always run in "force replace mode" (`-r -f`).  We should have a test which also runs simple in restore more (`-r`).  That test should NOT overwrite an existing object with the same UUID, as "restore" mode means it will throw an error if the object already exists in the system. See docs at https://wiki.lyrasis.org/display/DSDOC7x/AIP+Backup+and+Restore#AIPBackupandRestore-DefaultRestoreMode

**Review by tdonohue — CHANGES_REQUESTED** [review]
@ConfusionOrb221 : Thanks for the quick updates.  Based on your answers, I think we still have one more problem here.  There's two types of "restore" supported by the packager...there's "force" mode (which you use) which should overwrite existing content.  But, there's also a default restore which should **never** overwrite existing content (i.e. if an object with that UUID already exists, a default restore should fail).

So, if you could add a test to prove that a "default restore" will not replace the object, that would help verify that this is working as expected.  See comments inline below for more..

File: dspace-api/src/main/java/org/dspace/content/CommunityServiceImpl.java [hunk 7]
```diff
@@ -379,17 +390,29 @@ public void addCollection(Context context, Community community, Collection colle
...
         // Check authorisation
         authorizeService.authorizeAction(context, parentCommunity, Constants.ADD);
 
-        Community c = create(parentCommunity, context, handle);
+        Community c;
+        if (uuid != null) {
+            c = create(parentCommunity, context, handle, uuid);
+        } else {
+            c = create(parentCommunity, context, handle);
+        }
```
Comment (abollini) [inline dspace-api/src/main/java/org/dspace/content/CommunityServiceImpl.java:415]: minon thing, this can be eventually simplified as the 4-params method always work

File: dspace-api/src/main/java/org/dspace/content/ItemServiceImpl.java [hunk 8]
```diff
@@ -176,6 +176,7 @@ public Item find(Context context, UUID id) throws SQLException {
 
     @Override
     public Item create(Context context, WorkspaceItem workspaceItem) throws SQLException, AuthorizeException {
+        authorizeService.authorizeAction(context, workspaceItem.getCollection(), Constants.ADD);
```
Comment (abollini) [inline dspace-api/src/main/java/org/dspace/content/ItemServiceImpl.java:179]: the whole method can be replaced by an internal call to the 3-params version

**Review by abollini — COMMENTED** [review]
I like the proposed functionality and apart from minor inline feedback I would ask two questions to be sure that these changes will not create issues to existing users:
- is it still possible to restore AIPs created with the previous version? are handles preserved?
- should we deal with inconsistency like an AIP where a new uuid is associated with an already used handle?

File: dspace-api/src/test/java/org/dspace/app/packager/PackagerIT.java (hunk 6 above)
Comment (ConfusionOrb221) [reply dspace-api/src/test/java/org/dspace/app/packager/PackagerIT.java:219]: I created another test to make sure that if the uuid already exists that it will not replace the item when not in force mode and that the item already there isn't merged over. I also fixed an issue with the WorkspaceItemTest because of the new auths the spy wasn't listening for them so thats where the change in that file came from.

**Comment by ConfusionOrb221** [comment]
> I like the proposed functionality and apart from minor inline feedback I would ask two questions to be sure that these changes will not create issues to existing users:
> 
> * is it still possible to restore AIPs created with the previous version? are handles preserved?
> * should we deal with inconsistency like an AIP where a new uuid is associated with an already used handle?

@abollini I believe if the handle already exists it will just mint a new one for the item I can look into confirming this thou either through an IT or through just testing locally and get back to you on that one. Im also not sure how this handle already existing would happen unless the export is coming from another dspace the handles go in order so if we were restoring a previous object that was deleted it should never have its handle consumed?

On your second question I'm testing that now locally will try to get back to you by the end of the day today if you can restore using a AIP created with a previous version.

**Comment by tdonohue** [comment]
@ConfusionOrb221 : This appears to be failing an Integration Test with a `NullPointerException`.  Here's the error from our CI process:
```
Error:  Tests run: 23, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 8.919 s <<< FAILURE! - in org.dspace.app.csv.CSVMetadataImportReferenceIT
Error:  testCSVImportInvalidRelationship(org.dspace.app.csv.CSVMetadataImportReferenceIT)  Time elapsed: 0.099 s  <<< ERROR!
java.lang.NullPointerException
	at org.dspace.app.csv.CSVMetadataImportReferenceIT.setup(CSVMetadataImportReferenceIT.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

I'm not sure exactly what's going on here, but it appears that the `CollectionBuilder` isn't working properly, as that's what's on line 75 of that IT class.  Could you look into this?  This error doesn't appear on our `main` branch, but seems new in your PR.

**Comment by ConfusionOrb221** [comment]
@tdonohue  Not really sure what happened with that I didn't touch that class at all and in the previous commit it appears to have passed and the only thing I changed was deleting a comment from that commit so trying to push just a menial change to run the tests again to see if they pass. They are all passing locally so im not sure.

**Comment by tdonohue** [comment]
@ConfusionOrb221 : Apologies, but it looks like this now has some code conflicts.  If you could resolve those, I can see if I can replicate the test failures in this PR on my end.  I agree, they look very odd, but they are also consistent...it makes me wonder if something changed on the `main` branch which is impacting the changes in your PR.  So, resolving the code conflicts & ensuring you are rebased on the latest `main` may help us figure out what is going on.

File: dspace-api/src/test/java/org/dspace/app/packager/PackagerIT.java [hunk 9]
```diff
@@ -0,0 +1,226 @@
...
+    protected ConfigurationService configService = DSpaceServicesFactory.getInstance().getConfigurationService();
+    protected Community child1;
+    protected Collection col1;
+    protected Item article;
+    File tempFile;
+
+    @Test
+    public void packagerExportUUIDTest() throws Exception {
+        context.turnOffAuthorisationSystem();
+        createTemplate();
```
Comment (tdonohue) [inline dspace-api/src/test/java/org/dspace/app/packager/PackagerIT.java:66]: @ConfusionOrb221 : I *think* your random failures are being caused by not cleaning up the content you've created in your tests.  Several of your tests call `createTemplate()` to create several objects in the database...but, it appears to me those created objects are NEVER removed.  

Allowing objects to stay in the test database after tests complete is bad practice, as it can result in later ITs failing over unexpected content in the test database.

So, I think you may need want to refactor this set of tests to have a method like this:
```
@Before
public void setup() {
   // You could also just move the content of createTemplate() and createFiles() into this method
   createTemplate();  
   createFiles();
}
```

Then, have a corresponding `@After` method:
```
@After
public void destroy() {
    deleteTemplate(); //doesn't exist yet
    deleteFiles();  // doesn't exist yet
}
```

That'd ensure the same content is created before each `@Test` and then deleted after each test completes.

Comment (ConfusionOrb221) [reply dspace-api/src/test/java/org/dspace/app/packager/PackagerIT.java]: Did the above changed and it did fix that test case that we were running into seemed to be that the handle was running into something I had created previously.

**Review by tdonohue — COMMENTED** [review]
@ConfusionOrb221 : Code is looking better overall.  I just have a minor comment in the ITs.

I tested this out by exporting a small hierarchy (starting with a Community), deleting that hierarchy & then restoring.  **It all worked!**

(I did initially run into an unfortunate bug that Entities cannot be restored at all...even as simple Items, but that's unrelated to this PR. But, hopefully that'll be fixed in your other PR #3328, once that's ready for review.) 

All in all, I'm basically a +1 on this PR once the final small fix to the ITs is complete.  Thanks for your hard work on this!

**Review by tdonohue — APPROVED** [review]
👍 Looks good to me now. Thanks @ConfusionOrb221 !  I think this is ready to merge, but will wait on any final feedback from @abollini
